#    Copyright (C) 2021 by Kevin D. Woerner
##-# =KDW= ################# BUILDER $KWROOT/0lib/vkkcp.sh ##################
##-# =KDW= ######### SOURCE $KWROOT/codekdw/kw-lib/Kwelements.fwipp #########
##-# =KDW= #### THIS FILE CAN BE OVERWRITTEN BY KEVIN D. WOERNER OR HIS #####
##-# =KDW= ############ MINIONS AT *ANY* TIME. Caveat utilitor. #############
# 2021-05-14 kdw  For Changelog, See File varylog
import sys
import math
import time
import Kw
HYDROGEN_Z = 1
HYDROGEN = 1.008
H_Z = HYDROGEN_Z
H_WEIGHT = 1.008
H_MASS = 1.008 * Kw.MOLARMASS
HMASS = H_MASS / Kw.AVOGADRO
H_DENSITY = 0.08988 * Kw.DENSITY
H_MELT = 14.01 * Kw.KELVIN
H_BOIL = 20.28 * Kw.KELVIN
H_Cp = 14304 * Kw.SPECIFICHEAT
H_En = 2.20
HELIUM_Z = 2
HELIUM = 4.002602
He_Z = HELIUM_Z
He_WEIGHT = 4.002602
He_MASS = 4.002602 * Kw.MOLARMASS
HeMASS = He_MASS / Kw.AVOGADRO
He_DENSITY = 0.1785 * Kw.DENSITY
He_MELT = -1 * Kw.KELVIN
He_BOIL = 4.22 * Kw.KELVIN
He_Cp = 5193 * Kw.SPECIFICHEAT
He_En = -1
LITHIUM_Z = 3
LITHIUM = 6.94
Li_Z = LITHIUM_Z
Li_WEIGHT = 6.94
Li_MASS = 6.94 * Kw.MOLARMASS
LiMASS = Li_MASS / Kw.AVOGADRO
Li_DENSITY = 534 * Kw.DENSITY
Li_MELT = 453.69 * Kw.KELVIN
Li_BOIL = 1560 * Kw.KELVIN
Li_Cp = 3582 * Kw.SPECIFICHEAT
Li_En = 0.98
BERYLLIUM_Z = 4
BERYLLIUM = 9.0121831
Be_Z = BERYLLIUM_Z
Be_WEIGHT = 9.0121831
Be_MASS = 9.0121831 * Kw.MOLARMASS
BeMASS = Be_MASS / Kw.AVOGADRO
Be_DENSITY = 1850 * Kw.DENSITY
Be_MELT = 1560 * Kw.KELVIN
Be_BOIL = 2742 * Kw.KELVIN
Be_Cp = 1825 * Kw.SPECIFICHEAT
Be_En = 1.57
BORON_Z = 5
BORON = 10.81
B_Z = BORON_Z
B_WEIGHT = 10.81
B_MASS = 10.81 * Kw.MOLARMASS
BMASS = B_MASS / Kw.AVOGADRO
B_DENSITY = 2340 * Kw.DENSITY
B_MELT = 2349 * Kw.KELVIN
B_BOIL = 4200 * Kw.KELVIN
B_Cp = 1026 * Kw.SPECIFICHEAT
B_En = 2.04
CARBON_Z = 6
CARBON = 12.011
C_Z = CARBON_Z
C_WEIGHT = 12.011
C_MASS = 12.011 * Kw.MOLARMASS
CMASS = C_MASS / Kw.AVOGADRO
C_DENSITY = 2267 * Kw.DENSITY
C_MELT = 3800 * Kw.KELVIN
C_BOIL = 4300 * Kw.KELVIN
C_Cp = 709 * Kw.SPECIFICHEAT
C_En = 2.55
NITROGEN_Z = 7
NITROGEN = 14.007
N_Z = NITROGEN_Z
N_WEIGHT = 14.007
N_MASS = 14.007 * Kw.MOLARMASS
NMASS = N_MASS / Kw.AVOGADRO
N_DENSITY = 1.2506 * Kw.DENSITY
N_MELT = 63.15 * Kw.KELVIN
N_BOIL = 77.36 * Kw.KELVIN
N_Cp = 1040 * Kw.SPECIFICHEAT
N_En = 3.04
OXYGEN_Z = 8
OXYGEN = 15.999
O_Z = OXYGEN_Z
O_WEIGHT = 15.999
O_MASS = 15.999 * Kw.MOLARMASS
OMASS = O_MASS / Kw.AVOGADRO
O_DENSITY = 1.429 * Kw.DENSITY
O_MELT = 54.36 * Kw.KELVIN
O_BOIL = 90.20 * Kw.KELVIN
O_Cp = 918 * Kw.SPECIFICHEAT
O_En = 3.44
FLUORINE_Z = 9
FLUORINE = 18.998403163
F_Z = FLUORINE_Z
F_WEIGHT = 18.998403163
F_MASS = 18.998403163 * Kw.MOLARMASS
FMASS = F_MASS / Kw.AVOGADRO
F_DENSITY = 1.696 * Kw.DENSITY
F_MELT = 53.53 * Kw.KELVIN
F_BOIL = 85.03 * Kw.KELVIN
F_Cp = 824 * Kw.SPECIFICHEAT
F_En = 3.98
NEON_Z = 10
NEON = 20.1797
Ne_Z = NEON_Z
Ne_WEIGHT = 20.1797
Ne_MASS = 20.1797 * Kw.MOLARMASS
NeMASS = Ne_MASS / Kw.AVOGADRO
Ne_DENSITY = 0.8999 * Kw.DENSITY
Ne_MELT = 24.56 * Kw.KELVIN
Ne_BOIL = 27.07 * Kw.KELVIN
Ne_Cp = 1030 * Kw.SPECIFICHEAT
Ne_En = -1
SODIUM_Z = 11
SODIUM = 22.98976928
Na_Z = SODIUM_Z
Na_WEIGHT = 22.98976928
Na_MASS = 22.98976928 * Kw.MOLARMASS
NaMASS = Na_MASS / Kw.AVOGADRO
Na_DENSITY = 971 * Kw.DENSITY
Na_MELT = 370.87 * Kw.KELVIN
Na_BOIL = 1156 * Kw.KELVIN
Na_Cp = 1228 * Kw.SPECIFICHEAT
Na_En = 0.93
MAGNESIUM_Z = 12
MAGNESIUM = 24.305
Mg_Z = MAGNESIUM_Z
Mg_WEIGHT = 24.305
Mg_MASS = 24.305 * Kw.MOLARMASS
MgMASS = Mg_MASS / Kw.AVOGADRO
Mg_DENSITY = 1738 * Kw.DENSITY
Mg_MELT = 923 * Kw.KELVIN
Mg_BOIL = 1363 * Kw.KELVIN
Mg_Cp = 1023 * Kw.SPECIFICHEAT
Mg_En = 1.31
ALUMINIUM_Z = 13
ALUMINIUM = 26.9815384
Al_Z = ALUMINIUM_Z
Al_WEIGHT = 26.9815384
Al_MASS = 26.9815384 * Kw.MOLARMASS
AlMASS = Al_MASS / Kw.AVOGADRO
Al_DENSITY = 2698 * Kw.DENSITY
Al_MELT = 933.47 * Kw.KELVIN
Al_BOIL = 2792 * Kw.KELVIN
Al_Cp = 897 * Kw.SPECIFICHEAT
Al_En = 1.61
SILICON_Z = 14
SILICON = 28.085
Si_Z = SILICON_Z
Si_WEIGHT = 28.085
Si_MASS = 28.085 * Kw.MOLARMASS
SiMASS = Si_MASS / Kw.AVOGADRO
Si_DENSITY = 2329.6 * Kw.DENSITY
Si_MELT = 1687 * Kw.KELVIN
Si_BOIL = 3538 * Kw.KELVIN
Si_Cp = 705 * Kw.SPECIFICHEAT
Si_En = 1.90
PHOSPHORUS_Z = 15
PHOSPHORUS = 30.973761998
P_Z = PHOSPHORUS_Z
P_WEIGHT = 30.973761998
P_MASS = 30.973761998 * Kw.MOLARMASS
PMASS = P_MASS / Kw.AVOGADRO
P_DENSITY = 1820 * Kw.DENSITY
P_MELT = 317.30 * Kw.KELVIN
P_BOIL = 550 * Kw.KELVIN
P_Cp = 769 * Kw.SPECIFICHEAT
P_En = 2.19
SULFUR_Z = 16
SULFUR = 32.06
S_Z = SULFUR_Z
S_WEIGHT = 32.06
S_MASS = 32.06 * Kw.MOLARMASS
SMASS = S_MASS / Kw.AVOGADRO
S_DENSITY = 2067 * Kw.DENSITY
S_MELT = 388.36 * Kw.KELVIN
S_BOIL = 717.87 * Kw.KELVIN
S_Cp = 710 * Kw.SPECIFICHEAT
S_En = 2.58
CHLORINE_Z = 17
CHLORINE = 35.45
Cl_Z = CHLORINE_Z
Cl_WEIGHT = 35.45
Cl_MASS = 35.45 * Kw.MOLARMASS
ClMASS = Cl_MASS / Kw.AVOGADRO
Cl_DENSITY = 3.214 * Kw.DENSITY
Cl_MELT = 171.6 * Kw.KELVIN
Cl_BOIL = 239.11 * Kw.KELVIN
Cl_Cp = 479 * Kw.SPECIFICHEAT
Cl_En = 3.16
ARGON_Z = 18
ARGON = 39.948
Ar_Z = ARGON_Z
Ar_WEIGHT = 39.948
Ar_MASS = 39.948 * Kw.MOLARMASS
ArMASS = Ar_MASS / Kw.AVOGADRO
Ar_DENSITY = 1.7837 * Kw.DENSITY
Ar_MELT = 83.80 * Kw.KELVIN
Ar_BOIL = 87.30 * Kw.KELVIN
Ar_Cp = 520 * Kw.SPECIFICHEAT
Ar_En = -1
POTASSIUM_Z = 19
POTASSIUM = 39.0983
K_Z = POTASSIUM_Z
K_WEIGHT = 39.0983
K_MASS = 39.0983 * Kw.MOLARMASS
KMASS = K_MASS / Kw.AVOGADRO
K_DENSITY = 862 * Kw.DENSITY
K_MELT = 336.53 * Kw.KELVIN
K_BOIL = 1032 * Kw.KELVIN
K_Cp = 757 * Kw.SPECIFICHEAT
K_En = 0.82
CALCIUM_Z = 20
CALCIUM = 40.078
Ca_Z = CALCIUM_Z
Ca_WEIGHT = 40.078
Ca_MASS = 40.078 * Kw.MOLARMASS
CaMASS = Ca_MASS / Kw.AVOGADRO
Ca_DENSITY = 1540 * Kw.DENSITY
Ca_MELT = 1115 * Kw.KELVIN
Ca_BOIL = 1757 * Kw.KELVIN
Ca_Cp = 647 * Kw.SPECIFICHEAT
Ca_En = 1.00
SCANDIUM_Z = 21
SCANDIUM = 44.955908
Sc_Z = SCANDIUM_Z
Sc_WEIGHT = 44.955908
Sc_MASS = 44.955908 * Kw.MOLARMASS
ScMASS = Sc_MASS / Kw.AVOGADRO
Sc_DENSITY = 2989 * Kw.DENSITY
Sc_MELT = 1814 * Kw.KELVIN
Sc_BOIL = 3109 * Kw.KELVIN
Sc_Cp = 568 * Kw.SPECIFICHEAT
Sc_En = 1.36
TITANIUM_Z = 22
TITANIUM = 47.867
Ti_Z = TITANIUM_Z
Ti_WEIGHT = 47.867
Ti_MASS = 47.867 * Kw.MOLARMASS
TiMASS = Ti_MASS / Kw.AVOGADRO
Ti_DENSITY = 4540 * Kw.DENSITY
Ti_MELT = 1941 * Kw.KELVIN
Ti_BOIL = 3560 * Kw.KELVIN
Ti_Cp = 523 * Kw.SPECIFICHEAT
Ti_En = 1.54
VANADIUM_Z = 23
VANADIUM = 50.9415
V_Z = VANADIUM_Z
V_WEIGHT = 50.9415
V_MASS = 50.9415 * Kw.MOLARMASS
VMASS = V_MASS / Kw.AVOGADRO
V_DENSITY = 6110 * Kw.DENSITY
V_MELT = 2183 * Kw.KELVIN
V_BOIL = 3680 * Kw.KELVIN
V_Cp = 489 * Kw.SPECIFICHEAT
V_En = 1.63
CHROMIUM_Z = 24
CHROMIUM = 51.9961
Cr_Z = CHROMIUM_Z
Cr_WEIGHT = 51.9961
Cr_MASS = 51.9961 * Kw.MOLARMASS
CrMASS = Cr_MASS / Kw.AVOGADRO
Cr_DENSITY = 7150 * Kw.DENSITY
Cr_MELT = 2180 * Kw.KELVIN
Cr_BOIL = 2944 * Kw.KELVIN
Cr_Cp = 449 * Kw.SPECIFICHEAT
Cr_En = 1.66
MANGANESE_Z = 25
MANGANESE = 54.938043
Mn_Z = MANGANESE_Z
Mn_WEIGHT = 54.938043
Mn_MASS = 54.938043 * Kw.MOLARMASS
MnMASS = Mn_MASS / Kw.AVOGADRO
Mn_DENSITY = 7440 * Kw.DENSITY
Mn_MELT = 1519 * Kw.KELVIN
Mn_BOIL = 2334 * Kw.KELVIN
Mn_Cp = 479 * Kw.SPECIFICHEAT
Mn_En = 1.55
IRON_Z = 26
IRON = 55.845
Fe_Z = IRON_Z
Fe_WEIGHT = 55.845
Fe_MASS = 55.845 * Kw.MOLARMASS
FeMASS = Fe_MASS / Kw.AVOGADRO
Fe_DENSITY = 7874 * Kw.DENSITY
Fe_MELT = 1811 * Kw.KELVIN
Fe_BOIL = 3134 * Kw.KELVIN
Fe_Cp = 449 * Kw.SPECIFICHEAT
Fe_En = 1.83
COBALT_Z = 27
COBALT = 58.933194
Co_Z = COBALT_Z
Co_WEIGHT = 58.933194
Co_MASS = 58.933194 * Kw.MOLARMASS
CoMASS = Co_MASS / Kw.AVOGADRO
Co_DENSITY = 8860 * Kw.DENSITY
Co_MELT = 1768 * Kw.KELVIN
Co_BOIL = 3200 * Kw.KELVIN
Co_Cp = 421 * Kw.SPECIFICHEAT
Co_En = 1.88
NICKEL_Z = 28
NICKEL = 58.6934
Ni_Z = NICKEL_Z
Ni_WEIGHT = 58.6934
Ni_MASS = 58.6934 * Kw.MOLARMASS
NiMASS = Ni_MASS / Kw.AVOGADRO
Ni_DENSITY = 8912 * Kw.DENSITY
Ni_MELT = 1728 * Kw.KELVIN
Ni_BOIL = 3186 * Kw.KELVIN
Ni_Cp = 444 * Kw.SPECIFICHEAT
Ni_En = 1.91
COPPER_Z = 29
COPPER = 63.546
Cu_Z = COPPER_Z
Cu_WEIGHT = 63.546
Cu_MASS = 63.546 * Kw.MOLARMASS
CuMASS = Cu_MASS / Kw.AVOGADRO
Cu_DENSITY = 8960 * Kw.DENSITY
Cu_MELT = 1357.77 * Kw.KELVIN
Cu_BOIL = 2835 * Kw.KELVIN
Cu_Cp = 385 * Kw.SPECIFICHEAT
Cu_En = 1.90
ZINC_Z = 30
ZINC = 65.38
Zn_Z = ZINC_Z
Zn_WEIGHT = 65.38
Zn_MASS = 65.38 * Kw.MOLARMASS
ZnMASS = Zn_MASS / Kw.AVOGADRO
Zn_DENSITY = 7134 * Kw.DENSITY
Zn_MELT = 692.88 * Kw.KELVIN
Zn_BOIL = 1180 * Kw.KELVIN
Zn_Cp = 388 * Kw.SPECIFICHEAT
Zn_En = 1.65
GALLIUM_Z = 31
GALLIUM = 69.723
Ga_Z = GALLIUM_Z
Ga_WEIGHT = 69.723
Ga_MASS = 69.723 * Kw.MOLARMASS
GaMASS = Ga_MASS / Kw.AVOGADRO
Ga_DENSITY = 5907 * Kw.DENSITY
Ga_MELT = 302.9146 * Kw.KELVIN
Ga_BOIL = 2673 * Kw.KELVIN
Ga_Cp = 371 * Kw.SPECIFICHEAT
Ga_En = 1.81
GERMANIUM_Z = 32
GERMANIUM = 72.630
Ge_Z = GERMANIUM_Z
Ge_WEIGHT = 72.630
Ge_MASS = 72.630 * Kw.MOLARMASS
GeMASS = Ge_MASS / Kw.AVOGADRO
Ge_DENSITY = 5323 * Kw.DENSITY
Ge_MELT = 1211.40 * Kw.KELVIN
Ge_BOIL = 3106 * Kw.KELVIN
Ge_Cp = 320 * Kw.SPECIFICHEAT
Ge_En = 2.01
ARSENIC_Z = 33
ARSENIC = 74.921595
As_Z = ARSENIC_Z
As_WEIGHT = 74.921595
As_MASS = 74.921595 * Kw.MOLARMASS
AsMASS = As_MASS / Kw.AVOGADRO
As_DENSITY = 5776 * Kw.DENSITY
As_MELT = 1090 * Kw.KELVIN
As_BOIL = 887 * Kw.KELVIN
As_Cp = 329 * Kw.SPECIFICHEAT
As_En = 2.18
SELENIUM_Z = 34
SELENIUM = 78.971
Se_Z = SELENIUM_Z
Se_WEIGHT = 78.971
Se_MASS = 78.971 * Kw.MOLARMASS
SeMASS = Se_MASS / Kw.AVOGADRO
Se_DENSITY = 4809 * Kw.DENSITY
Se_MELT = 453 * Kw.KELVIN
Se_BOIL = 958 * Kw.KELVIN
Se_Cp = 321 * Kw.SPECIFICHEAT
Se_En = 2.55
BROMINE_Z = 35
BROMINE = 79.904
Br_Z = BROMINE_Z
Br_WEIGHT = 79.904
Br_MASS = 79.904 * Kw.MOLARMASS
BrMASS = Br_MASS / Kw.AVOGADRO
Br_DENSITY = 3122 * Kw.DENSITY
Br_MELT = 265.8 * Kw.KELVIN
Br_BOIL = 332.0 * Kw.KELVIN
Br_Cp = 474 * Kw.SPECIFICHEAT
Br_En = 2.96
KRYPTON_Z = 36
KRYPTON = 83.798
Kr_Z = KRYPTON_Z
Kr_WEIGHT = 83.798
Kr_MASS = 83.798 * Kw.MOLARMASS
KrMASS = Kr_MASS / Kw.AVOGADRO
Kr_DENSITY = 3.733 * Kw.DENSITY
Kr_MELT = 115.79 * Kw.KELVIN
Kr_BOIL = 119.93 * Kw.KELVIN
Kr_Cp = 248 * Kw.SPECIFICHEAT
Kr_En = 3.00
RUBIDIUM_Z = 37
RUBIDIUM = 85.4678
Rb_Z = RUBIDIUM_Z
Rb_WEIGHT = 85.4678
Rb_MASS = 85.4678 * Kw.MOLARMASS
RbMASS = Rb_MASS / Kw.AVOGADRO
Rb_DENSITY = 1532 * Kw.DENSITY
Rb_MELT = 312.46 * Kw.KELVIN
Rb_BOIL = 961 * Kw.KELVIN
Rb_Cp = 363 * Kw.SPECIFICHEAT
Rb_En = 0.82
STRONTIUM_Z = 38
STRONTIUM = 87.62
Sr_Z = STRONTIUM_Z
Sr_WEIGHT = 87.62
Sr_MASS = 87.62 * Kw.MOLARMASS
SrMASS = Sr_MASS / Kw.AVOGADRO
Sr_DENSITY = 2640 * Kw.DENSITY
Sr_MELT = 1050 * Kw.KELVIN
Sr_BOIL = 1655 * Kw.KELVIN
Sr_Cp = 301 * Kw.SPECIFICHEAT
Sr_En = 0.95
YTTRIUM_Z = 39
YTTRIUM = 88.90584
Y_Z = YTTRIUM_Z
Y_WEIGHT = 88.90584
Y_MASS = 88.90584 * Kw.MOLARMASS
YMASS = Y_MASS / Kw.AVOGADRO
Y_DENSITY = 4469 * Kw.DENSITY
Y_MELT = 1799 * Kw.KELVIN
Y_BOIL = 3609 * Kw.KELVIN
Y_Cp = 298 * Kw.SPECIFICHEAT
Y_En = 1.22
ZIRCONIUM_Z = 40
ZIRCONIUM = 91.224
Zr_Z = ZIRCONIUM_Z
Zr_WEIGHT = 91.224
Zr_MASS = 91.224 * Kw.MOLARMASS
ZrMASS = Zr_MASS / Kw.AVOGADRO
Zr_DENSITY = 6506 * Kw.DENSITY
Zr_MELT = 2128 * Kw.KELVIN
Zr_BOIL = 4682 * Kw.KELVIN
Zr_Cp = 278 * Kw.SPECIFICHEAT
Zr_En = 1.33
NIOBIUM_Z = 41
NIOBIUM = 92.90637
Nb_Z = NIOBIUM_Z
Nb_WEIGHT = 92.90637
Nb_MASS = 92.90637 * Kw.MOLARMASS
NbMASS = Nb_MASS / Kw.AVOGADRO
Nb_DENSITY = 8570 * Kw.DENSITY
Nb_MELT = 2750 * Kw.KELVIN
Nb_BOIL = 5017 * Kw.KELVIN
Nb_Cp = 265 * Kw.SPECIFICHEAT
Nb_En = 1.6
MOLYBDENUM_Z = 42
MOLYBDENUM = 95.95
Mo_Z = MOLYBDENUM_Z
Mo_WEIGHT = 95.95
Mo_MASS = 95.95 * Kw.MOLARMASS
MoMASS = Mo_MASS / Kw.AVOGADRO
Mo_DENSITY = 10220 * Kw.DENSITY
Mo_MELT = 2896 * Kw.KELVIN
Mo_BOIL = 4912 * Kw.KELVIN
Mo_Cp = 251 * Kw.SPECIFICHEAT
Mo_En = 2.16
TECHNETIUM_Z = 43
TECHNETIUM = 98
Tc_Z = TECHNETIUM_Z
Tc_WEIGHT = 98
Tc_MASS = 98 * Kw.MOLARMASS
TcMASS = Tc_MASS / Kw.AVOGADRO
Tc_DENSITY = 11500 * Kw.DENSITY
Tc_MELT = 2430 * Kw.KELVIN
Tc_BOIL = 4538 * Kw.KELVIN
Tc_Cp = -1 * Kw.SPECIFICHEAT
Tc_En = 1.9
RUTHENIUM_Z = 44
RUTHENIUM = 101.07
Ru_Z = RUTHENIUM_Z
Ru_WEIGHT = 101.07
Ru_MASS = 101.07 * Kw.MOLARMASS
RuMASS = Ru_MASS / Kw.AVOGADRO
Ru_DENSITY = 12370 * Kw.DENSITY
Ru_MELT = 2607 * Kw.KELVIN
Ru_BOIL = 4423 * Kw.KELVIN
Ru_Cp = 238 * Kw.SPECIFICHEAT
Ru_En = 2.2
RHODIUM_Z = 45
RHODIUM = 102.90549
Rh_Z = RHODIUM_Z
Rh_WEIGHT = 102.90549
Rh_MASS = 102.90549 * Kw.MOLARMASS
RhMASS = Rh_MASS / Kw.AVOGADRO
Rh_DENSITY = 12410 * Kw.DENSITY
Rh_MELT = 2237 * Kw.KELVIN
Rh_BOIL = 3968 * Kw.KELVIN
Rh_Cp = 243 * Kw.SPECIFICHEAT
Rh_En = 2.28
PALLADIUM_Z = 46
PALLADIUM = 106.42
Pd_Z = PALLADIUM_Z
Pd_WEIGHT = 106.42
Pd_MASS = 106.42 * Kw.MOLARMASS
PdMASS = Pd_MASS / Kw.AVOGADRO
Pd_DENSITY = 12020 * Kw.DENSITY
Pd_MELT = 1828.05 * Kw.KELVIN
Pd_BOIL = 3236 * Kw.KELVIN
Pd_Cp = 244 * Kw.SPECIFICHEAT
Pd_En = 2.20
SILVER_Z = 47
SILVER = 107.8682
Ag_Z = SILVER_Z
Ag_WEIGHT = 107.8682
Ag_MASS = 107.8682 * Kw.MOLARMASS
AgMASS = Ag_MASS / Kw.AVOGADRO
Ag_DENSITY = 10501 * Kw.DENSITY
Ag_MELT = 1234.93 * Kw.KELVIN
Ag_BOIL = 2435 * Kw.KELVIN
Ag_Cp = 235 * Kw.SPECIFICHEAT
Ag_En = 1.93
CADMIUM_Z = 48
CADMIUM = 112.414
Cd_Z = CADMIUM_Z
Cd_WEIGHT = 112.414
Cd_MASS = 112.414 * Kw.MOLARMASS
CdMASS = Cd_MASS / Kw.AVOGADRO
Cd_DENSITY = 8690 * Kw.DENSITY
Cd_MELT = 594.22 * Kw.KELVIN
Cd_BOIL = 1040 * Kw.KELVIN
Cd_Cp = 232 * Kw.SPECIFICHEAT
Cd_En = 1.69
INDIUM_Z = 49
INDIUM = 114.818
In_Z = INDIUM_Z
In_WEIGHT = 114.818
In_MASS = 114.818 * Kw.MOLARMASS
InMASS = In_MASS / Kw.AVOGADRO
In_DENSITY = 7310 * Kw.DENSITY
In_MELT = 429.75 * Kw.KELVIN
In_BOIL = 2345 * Kw.KELVIN
In_Cp = 233 * Kw.SPECIFICHEAT
In_En = 1.78
TIN_Z = 50
TIN = 118.710
Sn_Z = TIN_Z
Sn_WEIGHT = 118.710
Sn_MASS = 118.710 * Kw.MOLARMASS
SnMASS = Sn_MASS / Kw.AVOGADRO
Sn_DENSITY = 7287 * Kw.DENSITY
Sn_MELT = 505.08 * Kw.KELVIN
Sn_BOIL = 2875 * Kw.KELVIN
Sn_Cp = 228 * Kw.SPECIFICHEAT
Sn_En = 1.96
ANTIMONY_Z = 51
ANTIMONY = 121.760
Sb_Z = ANTIMONY_Z
Sb_WEIGHT = 121.760
Sb_MASS = 121.760 * Kw.MOLARMASS
SbMASS = Sb_MASS / Kw.AVOGADRO
Sb_DENSITY = 6685 * Kw.DENSITY
Sb_MELT = 903.78 * Kw.KELVIN
Sb_BOIL = 1860 * Kw.KELVIN
Sb_Cp = 207 * Kw.SPECIFICHEAT
Sb_En = 2.05
TELLURIUM_Z = 52
TELLURIUM = 127.60
Te_Z = TELLURIUM_Z
Te_WEIGHT = 127.60
Te_MASS = 127.60 * Kw.MOLARMASS
TeMASS = Te_MASS / Kw.AVOGADRO
Te_DENSITY = 6232 * Kw.DENSITY
Te_MELT = 722.66 * Kw.KELVIN
Te_BOIL = 1261 * Kw.KELVIN
Te_Cp = 202 * Kw.SPECIFICHEAT
Te_En = 2.1
IODINE_Z = 53
IODINE = 126.90447
I_Z = IODINE_Z
I_WEIGHT = 126.90447
I_MASS = 126.90447 * Kw.MOLARMASS
IMASS = I_MASS / Kw.AVOGADRO
I_DENSITY = 4930 * Kw.DENSITY
I_MELT = 386.85 * Kw.KELVIN
I_BOIL = 457.4 * Kw.KELVIN
I_Cp = 214 * Kw.SPECIFICHEAT
I_En = 2.66
XENON_Z = 54
XENON = 131.293
Xe_Z = XENON_Z
Xe_WEIGHT = 131.293
Xe_MASS = 131.293 * Kw.MOLARMASS
XeMASS = Xe_MASS / Kw.AVOGADRO
Xe_DENSITY = 5.887 * Kw.DENSITY
Xe_MELT = 161.4 * Kw.KELVIN
Xe_BOIL = 165.03 * Kw.KELVIN
Xe_Cp = 158 * Kw.SPECIFICHEAT
Xe_En = 2.60
CAESIUM_Z = 55
CAESIUM = 132.90545196
Cs_Z = CAESIUM_Z
Cs_WEIGHT = 132.90545196
Cs_MASS = 132.90545196 * Kw.MOLARMASS
CsMASS = Cs_MASS / Kw.AVOGADRO
Cs_DENSITY = 1873 * Kw.DENSITY
Cs_MELT = 301.59 * Kw.KELVIN
Cs_BOIL = 944 * Kw.KELVIN
Cs_Cp = 242 * Kw.SPECIFICHEAT
Cs_En = 0.79
BARIUM_Z = 56
BARIUM = 137.327
Ba_Z = BARIUM_Z
Ba_WEIGHT = 137.327
Ba_MASS = 137.327 * Kw.MOLARMASS
BaMASS = Ba_MASS / Kw.AVOGADRO
Ba_DENSITY = 3594 * Kw.DENSITY
Ba_MELT = 1000 * Kw.KELVIN
Ba_BOIL = 2170 * Kw.KELVIN
Ba_Cp = 204 * Kw.SPECIFICHEAT
Ba_En = 0.89
LANTHANUM_Z = 57
LANTHANUM = 138.90547
La_Z = LANTHANUM_Z
La_WEIGHT = 138.90547
La_MASS = 138.90547 * Kw.MOLARMASS
LaMASS = La_MASS / Kw.AVOGADRO
La_DENSITY = 6145 * Kw.DENSITY
La_MELT = 1193 * Kw.KELVIN
La_BOIL = 3737 * Kw.KELVIN
La_Cp = 195 * Kw.SPECIFICHEAT
La_En = 1.1
CERIUM_Z = 58
CERIUM = 140.116
Ce_Z = CERIUM_Z
Ce_WEIGHT = 140.116
Ce_MASS = 140.116 * Kw.MOLARMASS
CeMASS = Ce_MASS / Kw.AVOGADRO
Ce_DENSITY = 6770 * Kw.DENSITY
Ce_MELT = 1068 * Kw.KELVIN
Ce_BOIL = 3716 * Kw.KELVIN
Ce_Cp = 192 * Kw.SPECIFICHEAT
Ce_En = 1.12
PRASEODYMIUM_Z = 59
PRASEODYMIUM = 140.90766
Pr_Z = PRASEODYMIUM_Z
Pr_WEIGHT = 140.90766
Pr_MASS = 140.90766 * Kw.MOLARMASS
PrMASS = Pr_MASS / Kw.AVOGADRO
Pr_DENSITY = 6773 * Kw.DENSITY
Pr_MELT = 1208 * Kw.KELVIN
Pr_BOIL = 3793 * Kw.KELVIN
Pr_Cp = 193 * Kw.SPECIFICHEAT
Pr_En = 1.13
NEODYMIUM_Z = 60
NEODYMIUM = 144.242
Nd_Z = NEODYMIUM_Z
Nd_WEIGHT = 144.242
Nd_MASS = 144.242 * Kw.MOLARMASS
NdMASS = Nd_MASS / Kw.AVOGADRO
Nd_DENSITY = 7007 * Kw.DENSITY
Nd_MELT = 1297 * Kw.KELVIN
Nd_BOIL = 3347 * Kw.KELVIN
Nd_Cp = 190 * Kw.SPECIFICHEAT
Nd_En = 1.14
PROMETHIUM_Z = 61
PROMETHIUM = 145
Pm_Z = PROMETHIUM_Z
Pm_WEIGHT = 145
Pm_MASS = 145 * Kw.MOLARMASS
PmMASS = Pm_MASS / Kw.AVOGADRO
Pm_DENSITY = 7260 * Kw.DENSITY
Pm_MELT = 1315 * Kw.KELVIN
Pm_BOIL = 3273 * Kw.KELVIN
Pm_Cp = -1 * Kw.SPECIFICHEAT
Pm_En = 1.13
SAMARIUM_Z = 62
SAMARIUM = 150.36
Sm_Z = SAMARIUM_Z
Sm_WEIGHT = 150.36
Sm_MASS = 150.36 * Kw.MOLARMASS
SmMASS = Sm_MASS / Kw.AVOGADRO
Sm_DENSITY = 7520 * Kw.DENSITY
Sm_MELT = 1345 * Kw.KELVIN
Sm_BOIL = 2067 * Kw.KELVIN
Sm_Cp = 197 * Kw.SPECIFICHEAT
Sm_En = 1.17
EUROPIUM_Z = 63
EUROPIUM = 151.964
Eu_Z = EUROPIUM_Z
Eu_WEIGHT = 151.964
Eu_MASS = 151.964 * Kw.MOLARMASS
EuMASS = Eu_MASS / Kw.AVOGADRO
Eu_DENSITY = 5243 * Kw.DENSITY
Eu_MELT = 1099 * Kw.KELVIN
Eu_BOIL = 1802 * Kw.KELVIN
Eu_Cp = 182 * Kw.SPECIFICHEAT
Eu_En = 1.2
GADOLINIUM_Z = 64
GADOLINIUM = 157.25
Gd_Z = GADOLINIUM_Z
Gd_WEIGHT = 157.25
Gd_MASS = 157.25 * Kw.MOLARMASS
GdMASS = Gd_MASS / Kw.AVOGADRO
Gd_DENSITY = 7895 * Kw.DENSITY
Gd_MELT = 1585 * Kw.KELVIN
Gd_BOIL = 3546 * Kw.KELVIN
Gd_Cp = 236 * Kw.SPECIFICHEAT
Gd_En = 1.2
TERBIUM_Z = 65
TERBIUM = 158.925354
Tb_Z = TERBIUM_Z
Tb_WEIGHT = 158.925354
Tb_MASS = 158.925354 * Kw.MOLARMASS
TbMASS = Tb_MASS / Kw.AVOGADRO
Tb_DENSITY = 8229 * Kw.DENSITY
Tb_MELT = 1629 * Kw.KELVIN
Tb_BOIL = 3503 * Kw.KELVIN
Tb_Cp = 182 * Kw.SPECIFICHEAT
Tb_En = 1.2
DYSPROSIUM_Z = 66
DYSPROSIUM = 162.500
Dy_Z = DYSPROSIUM_Z
Dy_WEIGHT = 162.500
Dy_MASS = 162.500 * Kw.MOLARMASS
DyMASS = Dy_MASS / Kw.AVOGADRO
Dy_DENSITY = 8550 * Kw.DENSITY
Dy_MELT = 1680 * Kw.KELVIN
Dy_BOIL = 2840 * Kw.KELVIN
Dy_Cp = 170 * Kw.SPECIFICHEAT
Dy_En = 1.22
HOLMIUM_Z = 67
HOLMIUM = 164.930328
Ho_Z = HOLMIUM_Z
Ho_WEIGHT = 164.930328
Ho_MASS = 164.930328 * Kw.MOLARMASS
HoMASS = Ho_MASS / Kw.AVOGADRO
Ho_DENSITY = 8795 * Kw.DENSITY
Ho_MELT = 1734 * Kw.KELVIN
Ho_BOIL = 2993 * Kw.KELVIN
Ho_Cp = 165 * Kw.SPECIFICHEAT
Ho_En = 1.23
ERBIUM_Z = 68
ERBIUM = 167.259
Er_Z = ERBIUM_Z
Er_WEIGHT = 167.259
Er_MASS = 167.259 * Kw.MOLARMASS
ErMASS = Er_MASS / Kw.AVOGADRO
Er_DENSITY = 9066 * Kw.DENSITY
Er_MELT = 1802 * Kw.KELVIN
Er_BOIL = 3141 * Kw.KELVIN
Er_Cp = 168 * Kw.SPECIFICHEAT
Er_En = 1.24
THULIUM_Z = 69
THULIUM = 168.934218
Tm_Z = THULIUM_Z
Tm_WEIGHT = 168.934218
Tm_MASS = 168.934218 * Kw.MOLARMASS
TmMASS = Tm_MASS / Kw.AVOGADRO
Tm_DENSITY = 9321 * Kw.DENSITY
Tm_MELT = 1818 * Kw.KELVIN
Tm_BOIL = 2223 * Kw.KELVIN
Tm_Cp = 160 * Kw.SPECIFICHEAT
Tm_En = 1.25
YTTERBIUM_Z = 70
YTTERBIUM = 173.045
Yb_Z = YTTERBIUM_Z
Yb_WEIGHT = 173.045
Yb_MASS = 173.045 * Kw.MOLARMASS
YbMASS = Yb_MASS / Kw.AVOGADRO
Yb_DENSITY = 6965 * Kw.DENSITY
Yb_MELT = 1097 * Kw.KELVIN
Yb_BOIL = 1469 * Kw.KELVIN
Yb_Cp = 155 * Kw.SPECIFICHEAT
Yb_En = 1.1
LUTETIUM_Z = 71
LUTETIUM = 174.9668
Lu_Z = LUTETIUM_Z
Lu_WEIGHT = 174.9668
Lu_MASS = 174.9668 * Kw.MOLARMASS
LuMASS = Lu_MASS / Kw.AVOGADRO
Lu_DENSITY = 9840 * Kw.DENSITY
Lu_MELT = 1925 * Kw.KELVIN
Lu_BOIL = 3675 * Kw.KELVIN
Lu_Cp = 154 * Kw.SPECIFICHEAT
Lu_En = 1.27
HAFNIUM_Z = 72
HAFNIUM = 178.49
Hf_Z = HAFNIUM_Z
Hf_WEIGHT = 178.49
Hf_MASS = 178.49 * Kw.MOLARMASS
HfMASS = Hf_MASS / Kw.AVOGADRO
Hf_DENSITY = 13310 * Kw.DENSITY
Hf_MELT = 2506 * Kw.KELVIN
Hf_BOIL = 4876 * Kw.KELVIN
Hf_Cp = 144 * Kw.SPECIFICHEAT
Hf_En = 1.3
TANTALUM_Z = 73
TANTALUM = 180.94788
Ta_Z = TANTALUM_Z
Ta_WEIGHT = 180.94788
Ta_MASS = 180.94788 * Kw.MOLARMASS
TaMASS = Ta_MASS / Kw.AVOGADRO
Ta_DENSITY = 16654 * Kw.DENSITY
Ta_MELT = 3290 * Kw.KELVIN
Ta_BOIL = 5731 * Kw.KELVIN
Ta_Cp = 140 * Kw.SPECIFICHEAT
Ta_En = 1.5
TUNGSTEN_Z = 74
TUNGSTEN = 183.84
W_Z = TUNGSTEN_Z
W_WEIGHT = 183.84
W_MASS = 183.84 * Kw.MOLARMASS
WMASS = W_MASS / Kw.AVOGADRO
W_DENSITY = 19250 * Kw.DENSITY
W_MELT = 3695 * Kw.KELVIN
W_BOIL = 5828 * Kw.KELVIN
W_Cp = 132 * Kw.SPECIFICHEAT
W_En = 2.36
RHENIUM_Z = 75
RHENIUM = 186.207
Re_Z = RHENIUM_Z
Re_WEIGHT = 186.207
Re_MASS = 186.207 * Kw.MOLARMASS
ReMASS = Re_MASS / Kw.AVOGADRO
Re_DENSITY = 21020 * Kw.DENSITY
Re_MELT = 3459 * Kw.KELVIN
Re_BOIL = 5869 * Kw.KELVIN
Re_Cp = 137 * Kw.SPECIFICHEAT
Re_En = 1.9
OSMIUM_Z = 76
OSMIUM = 190.23
Os_Z = OSMIUM_Z
Os_WEIGHT = 190.23
Os_MASS = 190.23 * Kw.MOLARMASS
OsMASS = Os_MASS / Kw.AVOGADRO
Os_DENSITY = 22610 * Kw.DENSITY
Os_MELT = 3306 * Kw.KELVIN
Os_BOIL = 5285 * Kw.KELVIN
Os_Cp = 130 * Kw.SPECIFICHEAT
Os_En = 2.2
IRIDIUM_Z = 77
IRIDIUM = 192.217
Ir_Z = IRIDIUM_Z
Ir_WEIGHT = 192.217
Ir_MASS = 192.217 * Kw.MOLARMASS
IrMASS = Ir_MASS / Kw.AVOGADRO
Ir_DENSITY = 22560 * Kw.DENSITY
Ir_MELT = 2719 * Kw.KELVIN
Ir_BOIL = 4701 * Kw.KELVIN
Ir_Cp = 131 * Kw.SPECIFICHEAT
Ir_En = 2.2
PLATINUM_Z = 78
PLATINUM = 195.084
Pt_Z = PLATINUM_Z
Pt_WEIGHT = 195.084
Pt_MASS = 195.084 * Kw.MOLARMASS
PtMASS = Pt_MASS / Kw.AVOGADRO
Pt_DENSITY = 21460 * Kw.DENSITY
Pt_MELT = 2041.4 * Kw.KELVIN
Pt_BOIL = 4098 * Kw.KELVIN
Pt_Cp = 133 * Kw.SPECIFICHEAT
Pt_En = 2.28
GOLD_Z = 79
GOLD = 196.966570
Au_Z = GOLD_Z
Au_WEIGHT = 196.966570
Au_MASS = 196.966570 * Kw.MOLARMASS
AuMASS = Au_MASS / Kw.AVOGADRO
Au_DENSITY = 19282 * Kw.DENSITY
Au_MELT = 1337.33 * Kw.KELVIN
Au_BOIL = 3129 * Kw.KELVIN
Au_Cp = 129 * Kw.SPECIFICHEAT
Au_En = 2.54
MERCURY_Z = 80
MERCURY = 200.592
Hg_Z = MERCURY_Z
Hg_WEIGHT = 200.592
Hg_MASS = 200.592 * Kw.MOLARMASS
HgMASS = Hg_MASS / Kw.AVOGADRO
Hg_DENSITY = 13533.6 * Kw.DENSITY
Hg_MELT = 234.43 * Kw.KELVIN
Hg_BOIL = 629.88 * Kw.KELVIN
Hg_Cp = 140 * Kw.SPECIFICHEAT
Hg_En = 2.00
THALLIUM_Z = 81
THALLIUM = 204.38
Tl_Z = THALLIUM_Z
Tl_WEIGHT = 204.38
Tl_MASS = 204.38 * Kw.MOLARMASS
TlMASS = Tl_MASS / Kw.AVOGADRO
Tl_DENSITY = 11850 * Kw.DENSITY
Tl_MELT = 577 * Kw.KELVIN
Tl_BOIL = 1746 * Kw.KELVIN
Tl_Cp = 129 * Kw.SPECIFICHEAT
Tl_En = 1.62
LEAD_Z = 82
LEAD = 207.2
Pb_Z = LEAD_Z
Pb_WEIGHT = 207.2
Pb_MASS = 207.2 * Kw.MOLARMASS
PbMASS = Pb_MASS / Kw.AVOGADRO
Pb_DENSITY = 11342 * Kw.DENSITY
Pb_MELT = 600.61 * Kw.KELVIN
Pb_BOIL = 2022 * Kw.KELVIN
Pb_Cp = 129 * Kw.SPECIFICHEAT
Pb_En = 1.87
BISMUTH_Z = 83
BISMUTH = 208.98040
Bi_Z = BISMUTH_Z
Bi_WEIGHT = 208.98040
Bi_MASS = 208.98040 * Kw.MOLARMASS
BiMASS = Bi_MASS / Kw.AVOGADRO
Bi_DENSITY = 9807 * Kw.DENSITY
Bi_MELT = 544.7 * Kw.KELVIN
Bi_BOIL = 1837 * Kw.KELVIN
Bi_Cp = 122 * Kw.SPECIFICHEAT
Bi_En = 2.02
POLONIUM_Z = 84
POLONIUM = 209
Po_Z = POLONIUM_Z
Po_WEIGHT = 209
Po_MASS = 209 * Kw.MOLARMASS
PoMASS = Po_MASS / Kw.AVOGADRO
Po_DENSITY = 9320 * Kw.DENSITY
Po_MELT = 527 * Kw.KELVIN
Po_BOIL = 1235 * Kw.KELVIN
Po_Cp = -1 * Kw.SPECIFICHEAT
Po_En = 2.0
ASTATINE_Z = 85
ASTATINE = 210
At_Z = ASTATINE_Z
At_WEIGHT = 210
At_MASS = 210 * Kw.MOLARMASS
AtMASS = At_MASS / Kw.AVOGADRO
At_DENSITY = 7000 * Kw.DENSITY
At_MELT = 575 * Kw.KELVIN
At_BOIL = 610 * Kw.KELVIN
At_Cp = -1 * Kw.SPECIFICHEAT
At_En = 2.2
RADON_Z = 86
RADON = 222
Rn_Z = RADON_Z
Rn_WEIGHT = 222
Rn_MASS = 222 * Kw.MOLARMASS
RnMASS = Rn_MASS / Kw.AVOGADRO
Rn_DENSITY = 9.73 * Kw.DENSITY
Rn_MELT = 202 * Kw.KELVIN
Rn_BOIL = 211.3 * Kw.KELVIN
Rn_Cp = 94 * Kw.SPECIFICHEAT
Rn_En = 2.2
FRANCIUM_Z = 87
FRANCIUM = 223
Fr_Z = FRANCIUM_Z
Fr_WEIGHT = 223
Fr_MASS = 223 * Kw.MOLARMASS
FrMASS = Fr_MASS / Kw.AVOGADRO
Fr_DENSITY = 1870 * Kw.DENSITY
Fr_MELT = 300 * Kw.KELVIN
Fr_BOIL = 950 * Kw.KELVIN
Fr_Cp = -1 * Kw.SPECIFICHEAT
Fr_En = 0.7
RADIUM_Z = 88
RADIUM = 226
Ra_Z = RADIUM_Z
Ra_WEIGHT = 226
Ra_MASS = 226 * Kw.MOLARMASS
RaMASS = Ra_MASS / Kw.AVOGADRO
Ra_DENSITY = 5500 * Kw.DENSITY
Ra_MELT = 973 * Kw.KELVIN
Ra_BOIL = 2010 * Kw.KELVIN
Ra_Cp = 94 * Kw.SPECIFICHEAT
Ra_En = 0.9
ACTINIUM_Z = 89
ACTINIUM = 227
Ac_Z = ACTINIUM_Z
Ac_WEIGHT = 227
Ac_MASS = 227 * Kw.MOLARMASS
AcMASS = Ac_MASS / Kw.AVOGADRO
Ac_DENSITY = 10070 * Kw.DENSITY
Ac_MELT = 1323 * Kw.KELVIN
Ac_BOIL = 3471 * Kw.KELVIN
Ac_Cp = 120 * Kw.SPECIFICHEAT
Ac_En = 1.1
THORIUM_Z = 90
THORIUM = 232.0377
Th_Z = THORIUM_Z
Th_WEIGHT = 232.0377
Th_MASS = 232.0377 * Kw.MOLARMASS
ThMASS = Th_MASS / Kw.AVOGADRO
Th_DENSITY = 11720 * Kw.DENSITY
Th_MELT = 2115 * Kw.KELVIN
Th_BOIL = 5061 * Kw.KELVIN
Th_Cp = 113 * Kw.SPECIFICHEAT
Th_En = 1.3
PROTACTINIUM_Z = 91
PROTACTINIUM = 231.03588
Pa_Z = PROTACTINIUM_Z
Pa_WEIGHT = 231.03588
Pa_MASS = 231.03588 * Kw.MOLARMASS
PaMASS = Pa_MASS / Kw.AVOGADRO
Pa_DENSITY = 15370 * Kw.DENSITY
Pa_MELT = 1841 * Kw.KELVIN
Pa_BOIL = 4300 * Kw.KELVIN
Pa_Cp = -1 * Kw.SPECIFICHEAT
Pa_En = 1.5
URANIUM_Z = 92
URANIUM = 238.02891
U_Z = URANIUM_Z
U_WEIGHT = 238.02891
U_MASS = 238.02891 * Kw.MOLARMASS
UMASS = U_MASS / Kw.AVOGADRO
U_DENSITY = 18950 * Kw.DENSITY
U_MELT = 1405.3 * Kw.KELVIN
U_BOIL = 4404 * Kw.KELVIN
U_Cp = 116 * Kw.SPECIFICHEAT
U_En = 1.38
NEPTUNIUM_Z = 93
NEPTUNIUM = 237
Np_Z = NEPTUNIUM_Z
Np_WEIGHT = 237
Np_MASS = 237 * Kw.MOLARMASS
NpMASS = Np_MASS / Kw.AVOGADRO
Np_DENSITY = 20450 * Kw.DENSITY
Np_MELT = 917 * Kw.KELVIN
Np_BOIL = 4273 * Kw.KELVIN
Np_Cp = -1 * Kw.SPECIFICHEAT
Np_En = 1.36
PLUTONIUM_Z = 94
PLUTONIUM = 244
Pu_Z = PLUTONIUM_Z
Pu_WEIGHT = 244
Pu_MASS = 244 * Kw.MOLARMASS
PuMASS = Pu_MASS / Kw.AVOGADRO
Pu_DENSITY = 19840 * Kw.DENSITY
Pu_MELT = 912.5 * Kw.KELVIN
Pu_BOIL = 3501 * Kw.KELVIN
Pu_Cp = -1 * Kw.SPECIFICHEAT
Pu_En = 1.28
AMERICIUM_Z = 95
AMERICIUM = 243
Am_Z = AMERICIUM_Z
Am_WEIGHT = 243
Am_MASS = 243 * Kw.MOLARMASS
AmMASS = Am_MASS / Kw.AVOGADRO
Am_DENSITY = 13690 * Kw.DENSITY
Am_MELT = 1449 * Kw.KELVIN
Am_BOIL = 2880 * Kw.KELVIN
Am_Cp = -1 * Kw.SPECIFICHEAT
Am_En = 1.13
CURIUM_Z = 96
CURIUM = 247
Cm_Z = CURIUM_Z
Cm_WEIGHT = 247
Cm_MASS = 247 * Kw.MOLARMASS
CmMASS = Cm_MASS / Kw.AVOGADRO
Cm_DENSITY = 13510 * Kw.DENSITY
Cm_MELT = 1613 * Kw.KELVIN
Cm_BOIL = 3383 * Kw.KELVIN
Cm_Cp = -1 * Kw.SPECIFICHEAT
Cm_En = 1.28
BERKELIUM_Z = 97
BERKELIUM = 247
Bk_Z = BERKELIUM_Z
Bk_WEIGHT = 247
Bk_MASS = 247 * Kw.MOLARMASS
BkMASS = Bk_MASS / Kw.AVOGADRO
Bk_DENSITY = 14790 * Kw.DENSITY
Bk_MELT = 1259 * Kw.KELVIN
Bk_BOIL = 2900 * Kw.KELVIN
Bk_Cp = -1 * Kw.SPECIFICHEAT
Bk_En = 1.3
CALIFORNIUM_Z = 98
CALIFORNIUM = 251
Cf_Z = CALIFORNIUM_Z
Cf_WEIGHT = 251
Cf_MASS = 251 * Kw.MOLARMASS
CfMASS = Cf_MASS / Kw.AVOGADRO
Cf_DENSITY = 15100 * Kw.DENSITY
Cf_MELT = 1173 * Kw.KELVIN
Cf_BOIL = -1 * Kw.KELVIN
Cf_Cp = -1 * Kw.SPECIFICHEAT
Cf_En = 1.3
EINSTEINIUM_Z = 99
EINSTEINIUM = 252
Es_Z = EINSTEINIUM_Z
Es_WEIGHT = 252
Es_MASS = 252 * Kw.MOLARMASS
EsMASS = Es_MASS / Kw.AVOGADRO
Es_DENSITY = 8840 * Kw.DENSITY
Es_MELT = 1133 * Kw.KELVIN
Es_BOIL = -1 * Kw.KELVIN
Es_Cp = -1 * Kw.SPECIFICHEAT
Es_En = 1.3
FERMIUM_Z = 100
FERMIUM = 257
Fm_Z = FERMIUM_Z
Fm_WEIGHT = 257
Fm_MASS = 257 * Kw.MOLARMASS
FmMASS = Fm_MASS / Kw.AVOGADRO
Fm_DENSITY = -1 * Kw.DENSITY
Fm_MELT = -1 * Kw.KELVIN
Fm_BOIL = -1 * Kw.KELVIN
Fm_Cp = -1 * Kw.SPECIFICHEAT
Fm_En = 1.3
MENDELEVIUM_Z = 101
MENDELEVIUM = 258
Md_Z = MENDELEVIUM_Z
Md_WEIGHT = 258
Md_MASS = 258 * Kw.MOLARMASS
MdMASS = Md_MASS / Kw.AVOGADRO
Md_DENSITY = -1 * Kw.DENSITY
Md_MELT = -1 * Kw.KELVIN
Md_BOIL = -1 * Kw.KELVIN
Md_Cp = -1 * Kw.SPECIFICHEAT
Md_En = 1.3
NOBELIUM_Z = 102
NOBELIUM = 259
No_Z = NOBELIUM_Z
No_WEIGHT = 259
No_MASS = 259 * Kw.MOLARMASS
NoMASS = No_MASS / Kw.AVOGADRO
No_DENSITY = -1 * Kw.DENSITY
No_MELT = -1 * Kw.KELVIN
No_BOIL = -1 * Kw.KELVIN
No_Cp = -1 * Kw.SPECIFICHEAT
No_En = 1.3
LAWRENCIUM_Z = 103
LAWRENCIUM = 266
Lr_Z = LAWRENCIUM_Z
Lr_WEIGHT = 266
Lr_MASS = 266 * Kw.MOLARMASS
LrMASS = Lr_MASS / Kw.AVOGADRO
Lr_DENSITY = -1 * Kw.DENSITY
Lr_MELT = -1 * Kw.KELVIN
Lr_BOIL = -1 * Kw.KELVIN
Lr_Cp = -1 * Kw.SPECIFICHEAT
Lr_En = 1.3
RUTHERFORDIUM_Z = 104
RUTHERFORDIUM = 267
Rf_Z = RUTHERFORDIUM_Z
Rf_WEIGHT = 267
Rf_MASS = 267 * Kw.MOLARMASS
RfMASS = Rf_MASS / Kw.AVOGADRO
Rf_DENSITY = -1 * Kw.DENSITY
Rf_MELT = -1 * Kw.KELVIN
Rf_BOIL = -1 * Kw.KELVIN
Rf_Cp = -1 * Kw.SPECIFICHEAT
Rf_En = -1
DUBNIUM_Z = 105
DUBNIUM = 268
Db_Z = DUBNIUM_Z
Db_WEIGHT = 268
Db_MASS = 268 * Kw.MOLARMASS
DbMASS = Db_MASS / Kw.AVOGADRO
Db_DENSITY = -1 * Kw.DENSITY
Db_MELT = -1 * Kw.KELVIN
Db_BOIL = -1 * Kw.KELVIN
Db_Cp = -1 * Kw.SPECIFICHEAT
Db_En = -1
SEABORGIUM_Z = 106
SEABORGIUM = 269
Sg_Z = SEABORGIUM_Z
Sg_WEIGHT = 269
Sg_MASS = 269 * Kw.MOLARMASS
SgMASS = Sg_MASS / Kw.AVOGADRO
Sg_DENSITY = -1 * Kw.DENSITY
Sg_MELT = -1 * Kw.KELVIN
Sg_BOIL = -1 * Kw.KELVIN
Sg_Cp = -1 * Kw.SPECIFICHEAT
Sg_En = -1
BOHRIUM_Z = 107
BOHRIUM = 270
Bh_Z = BOHRIUM_Z
Bh_WEIGHT = 270
Bh_MASS = 270 * Kw.MOLARMASS
BhMASS = Bh_MASS / Kw.AVOGADRO
Bh_DENSITY = -1 * Kw.DENSITY
Bh_MELT = -1 * Kw.KELVIN
Bh_BOIL = -1 * Kw.KELVIN
Bh_Cp = -1 * Kw.SPECIFICHEAT
Bh_En = -1
HASSIUM_Z = 108
HASSIUM = 270
Hs_Z = HASSIUM_Z
Hs_WEIGHT = 270
Hs_MASS = 270 * Kw.MOLARMASS
HsMASS = Hs_MASS / Kw.AVOGADRO
Hs_DENSITY = -1 * Kw.DENSITY
Hs_MELT = -1 * Kw.KELVIN
Hs_BOIL = -1 * Kw.KELVIN
Hs_Cp = -1 * Kw.SPECIFICHEAT
Hs_En = -1
MEITNERIUM_Z = 109
MEITNERIUM = 278
Mt_Z = MEITNERIUM_Z
Mt_WEIGHT = 278
Mt_MASS = 278 * Kw.MOLARMASS
MtMASS = Mt_MASS / Kw.AVOGADRO
Mt_DENSITY = -1 * Kw.DENSITY
Mt_MELT = -1 * Kw.KELVIN
Mt_BOIL = -1 * Kw.KELVIN
Mt_Cp = -1 * Kw.SPECIFICHEAT
Mt_En = -1
DARMSTADTIUM_Z = 110
DARMSTADTIUM = 281
Ds_Z = DARMSTADTIUM_Z
Ds_WEIGHT = 281
Ds_MASS = 281 * Kw.MOLARMASS
DsMASS = Ds_MASS / Kw.AVOGADRO
Ds_DENSITY = -1 * Kw.DENSITY
Ds_MELT = -1 * Kw.KELVIN
Ds_BOIL = -1 * Kw.KELVIN
Ds_Cp = -1 * Kw.SPECIFICHEAT
Ds_En = -1
ROENTGENIUM_Z = 111
ROENTGENIUM = 282
Rg_Z = ROENTGENIUM_Z
Rg_WEIGHT = 282
Rg_MASS = 282 * Kw.MOLARMASS
RgMASS = Rg_MASS / Kw.AVOGADRO
Rg_DENSITY = -1 * Kw.DENSITY
Rg_MELT = -1 * Kw.KELVIN
Rg_BOIL = -1 * Kw.KELVIN
Rg_Cp = -1 * Kw.SPECIFICHEAT
Rg_En = -1
COPERNICIUM_Z = 112
COPERNICIUM = 285
Cn_Z = COPERNICIUM_Z
Cn_WEIGHT = 285
Cn_MASS = 285 * Kw.MOLARMASS
CnMASS = Cn_MASS / Kw.AVOGADRO
Cn_DENSITY = -1 * Kw.DENSITY
Cn_MELT = -1 * Kw.KELVIN
Cn_BOIL = 357 * Kw.KELVIN
Cn_Cp = -1 * Kw.SPECIFICHEAT
Cn_En = -1
NIHONIUM_Z = 113
NIHONIUM = 286
Nh_Z = NIHONIUM_Z
Nh_WEIGHT = 286
Nh_MASS = 286 * Kw.MOLARMASS
NhMASS = Nh_MASS / Kw.AVOGADRO
Nh_DENSITY = -1 * Kw.DENSITY
Nh_MELT = -1 * Kw.KELVIN
Nh_BOIL = -1 * Kw.KELVIN
Nh_Cp = -1 * Kw.SPECIFICHEAT
Nh_En = -1
FLEROVIUM_Z = 114
FLEROVIUM = 289
Fl_Z = FLEROVIUM_Z
Fl_WEIGHT = 289
Fl_MASS = 289 * Kw.MOLARMASS
FlMASS = Fl_MASS / Kw.AVOGADRO
Fl_DENSITY = -1 * Kw.DENSITY
Fl_MELT = -1 * Kw.KELVIN
Fl_BOIL = 210 * Kw.KELVIN
Fl_Cp = -1 * Kw.SPECIFICHEAT
Fl_En = -1
MOSCOVIUM_Z = 115
MOSCOVIUM = 290
Mc_Z = MOSCOVIUM_Z
Mc_WEIGHT = 290
Mc_MASS = 290 * Kw.MOLARMASS
McMASS = Mc_MASS / Kw.AVOGADRO
Mc_DENSITY = -1 * Kw.DENSITY
Mc_MELT = -1 * Kw.KELVIN
Mc_BOIL = -1 * Kw.KELVIN
Mc_Cp = -1 * Kw.SPECIFICHEAT
Mc_En = -1
LIVERMORIUM_Z = 116
LIVERMORIUM = 293
Lv_Z = LIVERMORIUM_Z
Lv_WEIGHT = 293
Lv_MASS = 293 * Kw.MOLARMASS
LvMASS = Lv_MASS / Kw.AVOGADRO
Lv_DENSITY = -1 * Kw.DENSITY
Lv_MELT = -1 * Kw.KELVIN
Lv_BOIL = -1 * Kw.KELVIN
Lv_Cp = -1 * Kw.SPECIFICHEAT
Lv_En = -1
TENNESSINE_Z = 117
TENNESSINE = 294
Ts_Z = TENNESSINE_Z
Ts_WEIGHT = 294
Ts_MASS = 294 * Kw.MOLARMASS
TsMASS = Ts_MASS / Kw.AVOGADRO
Ts_DENSITY = -1 * Kw.DENSITY
Ts_MELT = -1 * Kw.KELVIN
Ts_BOIL = -1 * Kw.KELVIN
Ts_Cp = -1 * Kw.SPECIFICHEAT
Ts_En = -1
OGANESSON_Z = 118
OGANESSON = 294
Og_Z = OGANESSON_Z
Og_WEIGHT = 294
Og_MASS = 294 * Kw.MOLARMASS
OgMASS = Og_MASS / Kw.AVOGADRO
Og_DENSITY = -1 * Kw.DENSITY
Og_MELT = -1 * Kw.KELVIN
Og_BOIL = -1 * Kw.KELVIN
Og_Cp = -1 * Kw.SPECIFICHEAT
Og_En = -1
H1_WEIGHT = 1.007825032241
H1_MASS = 1.007825032241 * Kw.MOLARMASS
H1MASS = H1_MASS / Kw.AVOGADRO
DEUTERIUM_Z = 1
DEUTERIUM = 2.01410177811
D_Z = DEUTERIUM_Z
D_WEIGHT = 2.01410177811
D_MASS = 2.01410177811 * Kw.MOLARMASS
DMASS = D_MASS / Kw.AVOGADRO
TRITIUM_Z = 1
TRITIUM = 3.01604928199
T_Z = TRITIUM_Z
T_WEIGHT = 3.01604928199
T_MASS = 3.01604928199 * Kw.MOLARMASS
TMASS = T_MASS / Kw.AVOGADRO
H2_WEIGHT = D_WEIGHT
H2_MASS = D_WEIGHT * Kw.MOLARMASS
H2MASS = H2_MASS / Kw.AVOGADRO
H3_WEIGHT = T_WEIGHT
H3_MASS = T_WEIGHT * Kw.MOLARMASS
H3MASS = H3_MASS / Kw.AVOGADRO
He3_WEIGHT = 3.01602932265
He3_MASS = 3.01602932265 * Kw.MOLARMASS
He3MASS = He3_MASS / Kw.AVOGADRO
He4_WEIGHT = 4.002603254130
He4_MASS = 4.002603254130 * Kw.MOLARMASS
He4MASS = He4_MASS / Kw.AVOGADRO
C12_WEIGHT = 12.0
C12_MASS = 12.0 * Kw.MOLARMASS
C12MASS = C12_MASS / Kw.AVOGADRO
C13_WEIGHT = 13.00335483521
C13_MASS = 13.00335483521 * Kw.MOLARMASS
C13MASS = C13_MASS / Kw.AVOGADRO
C14_WEIGHT = 14.003241988
C14_MASS = 14.003241988 * Kw.MOLARMASS
C14MASS = C14_MASS / Kw.AVOGADRO
O16_WEIGHT = 15.99491461960
O16_MASS = 15.99491461960 * Kw.MOLARMASS
O16MASS = O16_MASS / Kw.AVOGADRO
O17_WEIGHT = 16.9991317566
O17_MASS = 16.9991317566 * Kw.MOLARMASS
O17MASS = O17_MASS / Kw.AVOGADRO
O18_WEIGHT = 17.9991596128
O18_MASS = 17.9991596128 * Kw.MOLARMASS
O18MASS = O18_MASS / Kw.AVOGADRO
DEUTERON_WEIGHT = 2.013553212745
DEUTERON_MASS = 2.013553212745 * Kw.MOLARMASS
DEUTERONMASS = DEUTERON_MASS / Kw.AVOGADRO
DEUTERONMASS_ERR = 2.0E-11
DEUTERONENERGY = DEUTERONMASS * (Kw.LIGHT * Kw.LIGHT)
HELION_WEIGHT = 3.0149322467175
HELION_MASS = 3.0149322467175 * Kw.MOLARMASS
HELIONMASS = HELION_MASS / Kw.AVOGADRO
HELIONMASS_ERR = 3.2E-11
HELIONENERGY = HELIONMASS * (Kw.LIGHT * Kw.LIGHT)
TRITON_WEIGHT = 3.01550071621
TRITON_MASS = 3.01550071621 * Kw.MOLARMASS
TRITONMASS = TRITON_MASS / Kw.AVOGADRO
TRITONMASS_ERR = 4.0E-11
TRITONENERGY = TRITONMASS * (Kw.LIGHT * Kw.LIGHT)
ALPHA_WEIGHT = 4.001506179127
ALPHA_MASS = 4.001506179127 * Kw.MOLARMASS
ALPHAMASS = ALPHA_MASS / Kw.AVOGADRO
ALPHAMASS_ERR = 1.6E-11
ALPHAENERGY = ALPHAMASS * (Kw.LIGHT * Kw.LIGHT)
UPQUARK_ENERGY = 2.3E+6 * Kw.eV
UPQUARKMASS = UPQUARK_ENERGY / (Kw.LIGHT * Kw.LIGHT)
UPQUARK_MASS = UPQUARKMASS * Kw.AVOGADRO
UPQUARKMASS_ERR = 0.7E+6 / 2.3E+6
UPQUARK_Hz = UPQUARK_ENERGY / Kw.PLANCK
UPQUARK_WAVELENGTH = Kw.LIGHT / UPQUARK_Hz
UPQUARK_CHARGE = 2.0 / 3.0 * Kw.ELEMENTARYCHARGE
DOWNQUARK_ENERGY = 4.8E+6 * Kw.eV
DOWNQUARKMASS = DOWNQUARK_ENERGY / (Kw.LIGHT * Kw.LIGHT)
DOWNQUARK_MASS = DOWNQUARKMASS * Kw.AVOGADRO
DOWNQUARKMASS_ERR = 0.5E+6 / 4.8E+6
DOWNQUARK_Hz = DOWNQUARK_ENERGY / Kw.PLANCK
DOWNQUARK_WAVELENGTH = Kw.LIGHT / DOWNQUARK_Hz
DOWNQUARK_CHARGE = -1.0 / 3.0 * Kw.ELEMENTARYCHARGE
CHARMQUARK_ENERGY = 1275E+6 * Kw.eV
CHARMQUARKMASS = CHARMQUARK_ENERGY / (Kw.LIGHT * Kw.LIGHT)
CHARMQUARK_MASS = CHARMQUARKMASS * Kw.AVOGADRO
CHARMQUARKMASS_ERR = 25E+6 / 1275E+6
CHARMQUARK_Hz = CHARMQUARK_ENERGY / Kw.PLANCK
CHARMQUARK_WAVELENGTH = Kw.LIGHT / CHARMQUARK_Hz
CHARMQUARK_CHARGE = 2.0 / 3.0 * Kw.ELEMENTARYCHARGE
STRANGEQUARK_ENERGY = 95E+6 * Kw.eV
STRANGEQUARKMASS = STRANGEQUARK_ENERGY / (Kw.LIGHT * Kw.LIGHT)
STRANGEQUARK_MASS = STRANGEQUARKMASS * Kw.AVOGADRO
STRANGEQUARKMASS_ERR = 5E+6 / 95E+6
STRANGEQUARK_Hz = STRANGEQUARK_ENERGY / Kw.PLANCK
STRANGEQUARK_WAVELENGTH = Kw.LIGHT / STRANGEQUARK_Hz
STRANGEQUARK_CHARGE = -1.0 / 3.0 * Kw.ELEMENTARYCHARGE
TOPQUARK_ENERGY = 173210E+6 * Kw.eV
TOPQUARKMASS = TOPQUARK_ENERGY / (Kw.LIGHT * Kw.LIGHT)
TOPQUARK_MASS = TOPQUARKMASS * Kw.AVOGADRO
TOPQUARKMASS_ERR = 710E+6 / 173210E+6
TOPQUARK_Hz = TOPQUARK_ENERGY / Kw.PLANCK
TOPQUARK_WAVELENGTH = Kw.LIGHT / TOPQUARK_Hz
TOPQUARK_CHARGE = 2.0 / 3.0 * Kw.ELEMENTARYCHARGE
BOTTOMQUARK_ENERGY = 4180E+6 * Kw.eV
BOTTOMQUARKMASS = BOTTOMQUARK_ENERGY / (Kw.LIGHT * Kw.LIGHT)
BOTTOMQUARK_MASS = BOTTOMQUARKMASS * Kw.AVOGADRO
BOTTOMQUARKMASS_ERR = 30E+6 / 4180E+6
BOTTOMQUARK_Hz = BOTTOMQUARK_ENERGY / Kw.PLANCK
BOTTOMQUARK_WAVELENGTH = Kw.LIGHT / BOTTOMQUARK_Hz
BOTTOMQUARK_CHARGE = -1.0 / 3.0 * Kw.ELEMENTARYCHARGE
HIGGSBOSON_ENERGY = 125.1E+9 * Kw.eV
HIGGSBOSONMASS = HIGGSBOSON_ENERGY / (Kw.LIGHT * Kw.LIGHT)
HIGGSBOSON_MASS = HIGGSBOSONMASS * Kw.AVOGADRO
HIGGSBOSONMASS_ERR = 0.14E+9 / 125.1E+9
HIGGSBOSON_Hz = HIGGSBOSON_ENERGY / Kw.PLANCK
HIGGSBOSON_WAVELENGTH = Kw.LIGHT / HIGGSBOSON_Hz
WBOSON_ENERGY = 80.379E+9 * Kw.eV
WBOSONMASS = WBOSON_ENERGY / (Kw.LIGHT * Kw.LIGHT)
WBOSON_MASS = WBOSONMASS * Kw.AVOGADRO
WBOSONMASS_ERR = 0.012E+9 / 80.379E+9
WBOSON_Hz = WBOSON_ENERGY / Kw.PLANCK
WBOSON_WAVELENGTH = Kw.LIGHT / WBOSON_Hz
ZBOSON_ENERGY = 91.1876E+9 * Kw.eV
ZBOSONMASS = ZBOSON_ENERGY / (Kw.LIGHT * Kw.LIGHT)
ZBOSON_MASS = ZBOSONMASS * Kw.AVOGADRO
ZBOSONMASS_ERR = 0.0023E+9 / 91.1876E+9
ZBOSON_Hz = ZBOSON_ENERGY / Kw.PLANCK
ZBOSON_WAVELENGTH = Kw.LIGHT / ZBOSON_Hz
TAU_ENERGY = 1776.86E+6 * Kw.eV
TAUMASS = TAU_ENERGY / (Kw.LIGHT * Kw.LIGHT)
TAU_MASS = TAUMASS * Kw.AVOGADRO
TAUMASS_ERR = 0.12E+6 / 1776.86E+6
TAU_Hz = TAU_ENERGY / Kw.PLANCK
TAU_WAVELENGTH = Kw.LIGHT / TAU_Hz
MUON_ENERGY = 105.6583755E+6 * Kw.eV
MUONMASS = MUON_ENERGY / (Kw.LIGHT * Kw.LIGHT)
MUON_MASS = MUONMASS * Kw.AVOGADRO
MUONMASS_ERR = 0.0000023E+6 / 105.6583755E+6
MUON_Hz = MUON_ENERGY / Kw.PLANCK
MUON_WAVELENGTH = Kw.LIGHT / MUON_Hz
ELECTRON_ENERGY = 0.51099895000E+6 * Kw.eV
ELECTRONMASS = ELECTRON_ENERGY / (Kw.LIGHT * Kw.LIGHT)
ELECTRON_MASS = ELECTRONMASS * Kw.AVOGADRO
ELECTRONMASS_ERR = 0.00000000015E+6 / 0.51099895000E+6
ELECTRON_Hz = ELECTRON_ENERGY / Kw.PLANCK
ELECTRON_WAVELENGTH = Kw.LIGHT / ELECTRON_Hz
PROTON_ENERGY = 938.27208816E+6 * Kw.eV
PROTONMASS = PROTON_ENERGY / (Kw.LIGHT * Kw.LIGHT)
PROTON_MASS = PROTONMASS * Kw.AVOGADRO
PROTONMASS_ERR = 0.00000029E+6 / 938.27208816E+6
PROTON_Hz = PROTON_ENERGY / Kw.PLANCK
PROTON_WAVELENGTH = Kw.LIGHT / PROTON_Hz
NEUTRON_ENERGY = 939.56542052E+6 * Kw.eV
NEUTRONMASS = NEUTRON_ENERGY / (Kw.LIGHT * Kw.LIGHT)
NEUTRON_MASS = NEUTRONMASS * Kw.AVOGADRO
NEUTRONMASS_ERR = 0.00000054E+6 / 939.56542052E+6
NEUTRON_Hz = NEUTRON_ENERGY / Kw.PLANCK
NEUTRON_WAVELENGTH = Kw.LIGHT / NEUTRON_Hz
HYDROGEN_RADIUS = (Kw.HBAR / (ELECTRON_MASS * Kw.LIGHT * Kw.ALPHA))
HYDROGEN_RADIUS_ERR = Kw.ALPHA_ERR
BOHRRADIUS = HYDROGEN_RADIUS
BOHRRADIUS_ERR = HYDROGEN_RADIUS_ERR
AIR_MASS = Kw.PPM * (7.80781E+5 * (2.0 * N_MASS) + 2.09444E+5 * (2.0 *\
         O_MASS) + 9.339E+3 * (Ar_MASS) + 4.1E+2 * (C_MASS + 2.0 *\
         O_MASS) + 1.818E+1 * (Ne_MASS) + 5.24 * (He_MASS) + 1.79 *\
         (C_MASS + 4.0 * H_MASS) + 1.14 * (Kr_MASS) + 0.55 * (2.0 * H_MASS))
AIRMASS = AIR_MASS / Kw.AVOGADRO
STEAM_MASS = 2 * H_MASS + 0 * C_MASS + 1 * O_MASS
STEAMMASS = STEAM_MASS / Kw.AVOGADRO
STEAM_HF = -241826 * Kw.JOULE / Kw.MOLE
STEAM_HC = 0.0 * Kw.JOULE / Kw.MOLE
STEAM_JPKG = - STEAM_HC / STEAM_MASS
STEAM_DENSITY = 0.7363 * Kw.DENSITY
STEAM_JPL = STEAM_JPKG * STEAM_DENSITY * Kw.LITER
H2O_MASS = 2 * H_MASS + 0 * C_MASS + 1 * O_MASS
H2OMASS = H2O_MASS / Kw.AVOGADRO
H2O_HF = -285830 * Kw.JOULE / Kw.MOLE
H2O_HC = 0.0 * Kw.JOULE / Kw.MOLE
H2O_JPKG = - H2O_HC / H2O_MASS
H2O_DENSITY = 999 * Kw.DENSITY
H2O_JPL = H2O_JPKG * H2O_DENSITY * Kw.LITER
WATER_MASS = 2 * H_MASS + 0 * C_MASS + 1 * O_MASS
WATERMASS = WATER_MASS / Kw.AVOGADRO
WATER_HF = -285830 * Kw.JOULE / Kw.MOLE
WATER_HC = 0.0 * Kw.JOULE / Kw.MOLE
WATER_JPKG = - WATER_HC / WATER_MASS
WATER_DENSITY = 999 * Kw.DENSITY
WATER_JPL = WATER_JPKG * WATER_DENSITY * Kw.LITER
CO2_MASS = 0 * H_MASS + 1 * C_MASS + 2 * O_MASS
CO2MASS = CO2_MASS / Kw.AVOGADRO
CO2_HF = -393510 * Kw.JOULE / Kw.MOLE
CO2_HC = 0.0 * Kw.JOULE / Kw.MOLE
CO2_JPKG = - CO2_HC / CO2_MASS
CO2_DENSITY = 1.7988 * Kw.DENSITY
CO2_JPL = CO2_JPKG * CO2_DENSITY * Kw.LITER
CARBONDIOXIDE_MASS = 0 * H_MASS + 1 * C_MASS + 2 * O_MASS
CARBONDIOXIDEMASS = CARBONDIOXIDE_MASS / Kw.AVOGADRO
CARBONDIOXIDE_HF = -393510 * Kw.JOULE / Kw.MOLE
CARBONDIOXIDE_HC = 0.0 * Kw.JOULE / Kw.MOLE
CARBONDIOXIDE_JPKG = - CARBONDIOXIDE_HC / CARBONDIOXIDE_MASS
CARBONDIOXIDE_DENSITY = 1.7988 * Kw.DENSITY
CARBONDIOXIDE_JPL = CARBONDIOXIDE_JPKG * CARBONDIOXIDE_DENSITY * Kw.LITER
O2_MASS = 0 * H_MASS + 0 * C_MASS + 2 * O_MASS
O2MASS = O2_MASS / Kw.AVOGADRO
O2_HF = 0 * Kw.JOULE / Kw.MOLE
O2_HC = 0.0 * Kw.JOULE / Kw.MOLE
O2_JPKG = - O2_HC / O2_MASS
O2_DENSITY = 1.3079 * Kw.DENSITY
O2_JPL = O2_JPKG * O2_DENSITY * Kw.LITER
HYDROGEN_MASS = 2 * H_MASS + 0 * C_MASS + 0 * O_MASS
HYDROGENMASS = HYDROGEN_MASS / Kw.AVOGADRO
HYDROGEN_HF = 0 * Kw.JOULE / Kw.MOLE
HYDROGEN_HC = (CO2_HF * 0 + H2O_HF * (2 / 2.0) + HYDROGEN_HF)
HYDROGEN_HCC = -2.86E+5 * Kw.JOULE / Kw.MOLE
HYDROGEN_JPKG = - HYDROGEN_HC / HYDROGEN_MASS
HYDROGEN_DENSITY = 0.08240 * Kw.DENSITY
HYDROGEN_JPL = HYDROGEN_JPKG * HYDROGEN_DENSITY * Kw.LITER
METHANE_MASS = 4 * H_MASS + 1 * C_MASS + 0 * O_MASS
METHANEMASS = METHANE_MASS / Kw.AVOGADRO
METHANE_HF = -74870 * Kw.JOULE / Kw.MOLE
METHANE_HC = (CO2_HF * 1 + H2O_HF * (4 / 2.0) + METHANE_HF)
METHANE_HCC = -8.907E+5 * Kw.JOULE / Kw.MOLE
METHANE_JPKG = - METHANE_HC / METHANE_MASS
METHANE_DENSITY = 0.6557 * Kw.DENSITY
METHANE_JPL = METHANE_JPKG * METHANE_DENSITY * Kw.LITER
ETHANE_MASS = 6 * H_MASS + 2 * C_MASS + 0 * O_MASS
ETHANEMASS = ETHANE_MASS / Kw.AVOGADRO
ETHANE_HF = -84000 * Kw.JOULE / Kw.MOLE
ETHANE_HC = (CO2_HF * 2 + H2O_HF * (6 / 2.0) + ETHANE_HF)
ETHANE_HCC = -1.5607E+6 * Kw.JOULE / Kw.MOLE
ETHANE_JPKG = - ETHANE_HC / ETHANE_MASS
ETHANE_DENSITY = 1.229 * Kw.DENSITY
ETHANE_JPL = ETHANE_JPKG * ETHANE_DENSITY * Kw.LITER
PROPANE_MASS = 8 * H_MASS + 3 * C_MASS + 0 * O_MASS
PROPANEMASS = PROPANE_MASS / Kw.AVOGADRO
PROPANE_HF = -104700 * Kw.JOULE / Kw.MOLE
PROPANE_HC = (CO2_HF * 3 + H2O_HF * (8 / 2.0) + PROPANE_HF)
PROPANE_HCC = -2.2192E+6 * Kw.JOULE / Kw.MOLE
PROPANE_JPKG = - PROPANE_HC / PROPANE_MASS
PROPANE_DENSITY = 1.8028 * Kw.DENSITY
PROPANE_JPL = PROPANE_JPKG * PROPANE_DENSITY * Kw.LITER
BUTANE_MASS = 10 * H_MASS + 4 * C_MASS + 0 * O_MASS
BUTANEMASS = BUTANE_MASS / Kw.AVOGADRO
BUTANE_HF = -125600 * Kw.JOULE / Kw.MOLE
BUTANE_HC = (CO2_HF * 4 + H2O_HF * (10 / 2.0) + BUTANE_HF)
BUTANE_HCC = -2.8775E+6 * Kw.JOULE / Kw.MOLE
BUTANE_JPKG = - BUTANE_HC / BUTANE_MASS
BUTANE_DENSITY = 2.3757 * Kw.DENSITY
BUTANE_JPL = BUTANE_JPKG * BUTANE_DENSITY * Kw.LITER
PENTANE_MASS = 12 * H_MASS + 5 * C_MASS + 0 * O_MASS
PENTANEMASS = PENTANE_MASS / Kw.AVOGADRO
PENTANE_HF = -173500 * Kw.JOULE / Kw.MOLE
PENTANE_HC = (CO2_HF * 5 + H2O_HF * (12 / 2.0) + PENTANE_HF)
PENTANE_HCC = -3.509E+6 * Kw.JOULE / Kw.MOLE
PENTANE_JPKG = - PENTANE_HC / PENTANE_MASS
PENTANE_DENSITY = 626 * Kw.DENSITY
PENTANE_JPL = PENTANE_JPKG * PENTANE_DENSITY * Kw.LITER
HEXANE_MASS = 14 * H_MASS + 6 * C_MASS + 0 * O_MASS
HEXANEMASS = HEXANE_MASS / Kw.AVOGADRO
HEXANE_HF = -198700 * Kw.JOULE / Kw.MOLE
HEXANE_HC = (CO2_HF * 6 + H2O_HF * (14 / 2.0) + HEXANE_HF)
HEXANE_HCC = -4.163E+6 * Kw.JOULE / Kw.MOLE
HEXANE_JPKG = - HEXANE_HC / HEXANE_MASS
HEXANE_DENSITY = 655 * Kw.DENSITY
HEXANE_JPL = HEXANE_JPKG * HEXANE_DENSITY * Kw.LITER
ETHANOL_MASS = 6 * H_MASS + 2 * C_MASS + 1 * O_MASS
ETHANOLMASS = ETHANOL_MASS / Kw.AVOGADRO
ETHANOL_HF = -276000 * Kw.JOULE / Kw.MOLE
ETHANOL_HC = (CO2_HF * 2 + H2O_HF * (6 / 2.0) + ETHANOL_HF)
ETHANOL_HCC = -1.3676E+6 * Kw.JOULE / Kw.MOLE
ETHANOL_JPKG = - ETHANOL_HC / ETHANOL_MASS
ETHANOL_DENSITY = 789.45 * Kw.DENSITY
ETHANOL_JPL = ETHANOL_JPKG * ETHANOL_DENSITY * Kw.LITER
ETHANOL_G_MASS = 6 * H_MASS + 2 * C_MASS + 1 * O_MASS
ETHANOL_GMASS = ETHANOL_G_MASS / Kw.AVOGADRO
ETHANOL_G_HF = -234000 * Kw.JOULE / Kw.MOLE
ETHANOL_G_HC = (CO2_HF * 2 + H2O_HF * (6 / 2.0) + ETHANOL_G_HF)
ETHANOL_G_HCC = -1.3663E+6 * Kw.JOULE / Kw.MOLE
ETHANOL_G_JPKG = - ETHANOL_G_HC / ETHANOL_G_MASS
ETHANOL_G_DENSITY = 789.45 * Kw.DENSITY
ETHANOL_G_JPL = ETHANOL_G_JPKG * ETHANOL_G_DENSITY * Kw.LITER
SUCROSE_MASS = 22 * H_MASS + 12 * C_MASS + 11 * O_MASS
SUCROSEMASS = SUCROSE_MASS / Kw.AVOGADRO
SUCROSE_HF = -2221200 * Kw.JOULE / Kw.MOLE
SUCROSE_HC = (CO2_HF * 12 + H2O_HF * (22 / 2.0) + SUCROSE_HF)
SUCROSE_HCC = -5.6434E+6 * Kw.JOULE / Kw.MOLE
SUCROSE_JPKG = - SUCROSE_HC / SUCROSE_MASS
SUCROSE_DENSITY = 1587 * Kw.DENSITY
SUCROSE_JPL = SUCROSE_JPKG * SUCROSE_DENSITY * Kw.LITER
SUGAR_MASS = 22 * H_MASS + 12 * C_MASS + 11 * O_MASS
SUGARMASS = SUGAR_MASS / Kw.AVOGADRO
SUGAR_HF = -2221200 * Kw.JOULE / Kw.MOLE
SUGAR_HC = (CO2_HF * 12 + H2O_HF * (22 / 2.0) + SUGAR_HF)
SUGAR_HCC = -5.6434E+6 * Kw.JOULE / Kw.MOLE
SUGAR_JPKG = - SUGAR_HC / SUGAR_MASS
SUGAR_DENSITY = 845 * Kw.DENSITY
SUGAR_JPL = SUGAR_JPKG * SUGAR_DENSITY * Kw.LITER
COAL_MASS = 0 * H_MASS + 1 * C_MASS + 0 * O_MASS
COALMASS = COAL_MASS / Kw.AVOGADRO
COAL_JPKG = 2.9307E+7 * (Kw.JOULE / Kw.KG)
COAL_DENSITY = 1300 * Kw.DENSITY
COAL_JPL = COAL_JPKG * COAL_DENSITY * Kw.LITER
PARAFFIN_MASS = 62 * H_MASS + 30 * C_MASS + 0 * O_MASS
PARAFFINMASS = PARAFFIN_MASS / Kw.AVOGADRO
PARAFFIN_JPKG = 4.6E+7 * (Kw.JOULE / Kw.KG)
PARAFFIN_DENSITY = 900 * Kw.DENSITY
PARAFFIN_JPL = PARAFFIN_JPKG * PARAFFIN_DENSITY * Kw.LITER
FAT_MASS = 104 * H_MASS + 55 * C_MASS + 6 * O_MASS
FATMASS = FAT_MASS / Kw.AVOGADRO
FAT_JPKG = 3.7E+7 * (Kw.JOULE / Kw.KG)
FAT_DENSITY = 900 * Kw.DENSITY
FAT_JPL = FAT_JPKG * FAT_DENSITY * Kw.LITER
DIESEL_MASS = 26 * H_MASS + 12 * C_MASS + 0 * O_MASS
DIESELMASS = DIESEL_MASS / Kw.AVOGADRO
DIESEL_JPKG = 4.48E+7 * (Kw.JOULE / Kw.KG)
DIESEL_DENSITY = 832 * Kw.DENSITY
DIESEL_JPL = DIESEL_JPKG * DIESEL_DENSITY * Kw.LITER
GASOLINE_MASS = 18 * H_MASS + 8 * C_MASS + 0 * O_MASS
GASOLINEMASS = GASOLINE_MASS / Kw.AVOGADRO
GASOLINE_JPKG = 4.64E+7 * (Kw.JOULE / Kw.KG)
GASOLINE_DENSITY = 748.9 * Kw.DENSITY
GASOLINE_JPL = GASOLINE_JPKG * GASOLINE_DENSITY * Kw.LITER
KEROSENE_MASS = 28 * H_MASS + 13 * C_MASS + 0 * O_MASS
KEROSENEMASS = KEROSENE_MASS / Kw.AVOGADRO
KEROSENE_JPKG = 4.62E+7 * (Kw.JOULE / Kw.KG)
KEROSENE_DENSITY = 800 * Kw.DENSITY
KEROSENE_JPL = KEROSENE_JPKG * KEROSENE_DENSITY * Kw.LITER
C13_RATIO = 1.07E-2
C14_RATIO = 1.0E-12
C12_RATIO = 1.0 - C13_RATIO - C14_RATIO
C_MEAN_MASS = C12_MASS * C12_RATIO + C13_MASS * C13_RATIO + C14_MASS *\
         C14_RATIO
WATER_Cp = 4184.0 * Kw.SPECIFICHEAT
ICE_Cp = 2108.0 * Kw.SPECIFICHEAT
STEAM_Cp = 1996.0 * Kw.SPECIFICHEAT
WATER_FUSION_JPMOLE = 6.0089E+3 * Kw.JOULE / Kw.MOLE
WATER_FUSION_JPKG = WATER_FUSION_JPMOLE / WATER_MASS
WATER_VAPORIZATION_JPMOLE = 4.0660E+4 * Kw.JOULE / Kw.MOLE
WATER_VAPORIZATION_JPKG = WATER_VAPORIZATION_JPMOLE / WATER_MASS
WATER_CRITICAL = 647.096 * Kw.KELVIN
VSMOW_H3_RATIO = 1.85E-17
VSMOW_H2_RATIO = 1.5576E-4
VSMOW_H1_RATIO = 1.0 - VSMOW_H2_RATIO - VSMOW_H3_RATIO
VSMOW_H_MASS = (H1_MASS * VSMOW_H1_RATIO + H2_MASS * VSMOW_H2_RATIO +\
         H3_MASS * VSMOW_H3_RATIO)
VSMOW_O18_RATIO = 2.00520E-3
VSMOW_O17_RATIO = 3.799E-4
VSMOW_O16_RATIO = 1.0 - VSMOW_O17_RATIO - VSMOW_O18_RATIO
VSMOW_O_MASS = O16_MASS * VSMOW_O16_RATIO + O17_MASS * VSMOW_O17_RATIO +\
         O18_MASS * VSMOW_O18_RATIO
VSMOW_MASS = 2.0 * VSMOW_H_MASS + VSMOW_O_MASS
TNTJPKG = 4.184E+6 * Kw.JOULE / Kw.KILOGRAM
def watervapor_pressure(temp_k):
   if (temp_k <= 16.1 or WATER_CRITICAL <= temp_k):
      retvalu = 0.0
   else:
      temp_c = Kw.k2tempc(temp_k)
      if (0.0 <= temp_c):
         retvalu = 611.21 * math.exp((18.678 - temp_c / 234.5) * (temp_c\
                  / (257.14 + temp_c)))
      else:
         retvalu = 611.15 * math.exp((23.036 - temp_c / 333.7) * (temp_c\
                  / (279.82 + temp_c)))
   return (retvalu)
def watervaporization(temp_k):
   if (WATER_CRITICAL <= temp_k):
      retvalu = 0.0
   else:
      retvalu = math.pow((WATER_CRITICAL - temp_k) / (WATER_CRITICAL -\
               373.15), 0.37) * WATER_VAPORIZATION_JPMOLE
   return (retvalu)
def waterboiling(pressure_pa):
   if (pressure_pa <= 0.0):
      retvalu = 0.0
   else:
      retvalu = 1.0 / (1.0 / 373.15 - math.log(pressure_pa / Kw.ATM) *\
               Kw.GAS / WATER_VAPORIZATION_JPMOLE)
   return (retvalu)
def waterdensity_airfree(temp_k):
   temp_c = Kw.k2tempc(temp_k)
   if (temp_c < 5.0 or 40.0 < temp_c):
      retvalu = ((((((-2.8054253E-10) * temp_c + 1.0556302E-7) * temp_c -\
               4.6170461E-5) * temp_c - 7.9870401E-3) * temp_c +\
               1.6945176E+1) * temp_c + 9.9983952E+2)
      retvalu /= (1.6897850E-2 * temp_c + 1.0)
   else:
      retvalu = (((((-3.821216E-7) * temp_c + 6.943248E-5) * temp_c -\
               8.523829E-3) * temp_c + 6.32693E-2) * temp_c + 9.9985308E+2)
   return (retvalu)
def waterdensity(temp_k):
   temp_c = Kw.k2tempc(temp_k)
   if (temp_c < 0.0):
      retvalu = 917 - 0.13 * temp_c
   elif (temp_c <= 5.0):
      retvalu = (((8.7191684845109E-5) * temp_c - 9.0329747829960E-3) *\
               temp_c + 6.7771627919989E-2) * temp_c + 9.9984281840963E+2
   elif (temp_c <= 40.0):
      retvalu = ((((-3.821216E-7) * temp_c + 6.943248E-5) * temp_c -\
               8.523829E-3) * temp_c + 6.337563E-2) * temp_c +\
               9.9984847E+2 + 0.0059
   else:
      retvalu = ((((-6.5202248732325E-8) * temp_c + 2.5745673934090E-5) *\
               temp_c - 6.1868849581972E-3) * temp_c +\
               6.0164627537211E-3) * temp_c + 1.0003918667215E+3
   return (retvalu)
def waterdensity_airfree__1(temp_k):
   temp_c = Kw.k2tempc(temp_k)
   if (temp_c <= 5.0):
      retvalu = ((((9.6308327803439E-5) * temp_c - 9.0973473048107E-3) *\
               temp_c + 6.7877518213033E-2) * temp_c + 9.9984280358288E+2)
   elif (temp_c <= 40.0):
      retvalu = (((((((-4.6205682267935E-11) * temp_c +\
               1.0474115539454E-8) * temp_c - 1.1933226216922E-6) *\
               temp_c + 9.8476793645150E-5) * temp_c -\
               9.0387372512241E-3) * temp_c + 6.7575261493264E-2) *\
               temp_c + 9.9984328159055E+2)
   elif (temp_c <= 100):
      retvalu = (((((-6.5202248732325E-8) * temp_c + 2.5745673934090E-5)\
               * temp_c - 6.1868849581972E-3) * temp_c +\
               6.0164627537211E-3) * temp_c + 1.0003918667215E+3)
   else:
      retvalu = ((((((((((-5.4752717629528E-17) * temp_c +\
               1.1052954300641E-13) * temp_c - 9.7190466446857E-11) *\
               temp_c + 4.8801821861028E-8) * temp_c -\
               1.5403658215495E-5) * temp_c + 3.1660515368531E-3) *\
               temp_c - 4.2335200290825E-1) * temp_c +\
               3.5482000718216E+1) * temp_c - 1.6909944548890E+3) *\
               temp_c + 3.5888296998420E+4)
   return (retvalu)
#   DDDDDDDDDDescription ########################### kwelements_description #
def kwelements_description():
   return( \
   "   Kwelements Constants: Ac_BOIL Ac_Cp Ac_DENSITY Ac_En Ac_MASS Ac_M" + \
   "ELT Ac_WEIGHT Ac_Z AcMASS ACTINIUM ACTINIUM_Z Ag_BOIL Ag_Cp Ag_DENSI" + \
   "TY Ag_En Ag_MASS Ag_MELT Ag_WEIGHT Ag_Z AgMASS AIR_MASS AIRMASS Al_B" + \
   "OIL Al_Cp Al_DENSITY Al_En Al_MASS Al_MELT Al_WEIGHT Al_Z AlMASS ALP" + \
   "HA_MASS ALPHA_WEIGHT ALPHAENERGY ALPHAMASS ALPHAMASS_ERR ALUMINIUM A" + \
   "LUMINIUM_Z Am_BOIL Am_Cp Am_DENSITY Am_En Am_MASS Am_MELT Am_WEIGHT " + \
   "Am_Z AMERICIUM AMERICIUM_Z AmMASS ANTIMONY ANTIMONY_Z Ar_BOIL Ar_Cp " + \
   "Ar_DENSITY Ar_En Ar_MASS Ar_MELT Ar_WEIGHT Ar_Z ARGON ARGON_Z ArMASS" + \
   " ARSENIC ARSENIC_Z As_BOIL As_Cp As_DENSITY As_En As_MASS As_MELT As" + \
   "_WEIGHT As_Z AsMASS ASTATINE ASTATINE_Z At_BOIL At_Cp At_DENSITY At_" + \
   "En At_MASS At_MELT At_WEIGHT At_Z AtMASS Au_BOIL Au_Cp Au_DENSITY Au" + \
   "_En Au_MASS Au_MELT Au_WEIGHT Au_Z AuMASS B_BOIL B_Cp B_DENSITY B_En" + \
   " B_MASS B_MELT B_WEIGHT B_Z Ba_BOIL Ba_Cp Ba_DENSITY Ba_En Ba_MASS B" + \
   "a_MELT Ba_WEIGHT Ba_Z BaMASS BARIUM BARIUM_Z Be_BOIL Be_Cp Be_DENSIT" + \
   "Y Be_En Be_MASS Be_MELT Be_WEIGHT Be_Z BeMASS BERKELIUM BERKELIUM_Z " + \
   "BERYLLIUM BERYLLIUM_Z Bh_BOIL Bh_Cp Bh_DENSITY Bh_En Bh_MASS Bh_MELT" + \
   " Bh_WEIGHT Bh_Z BhMASS Bi_BOIL Bi_Cp Bi_DENSITY Bi_En Bi_MASS Bi_MEL" + \
   "T Bi_WEIGHT Bi_Z BiMASS BISMUTH BISMUTH_Z Bk_BOIL Bk_Cp Bk_DENSITY B" + \
   "k_En Bk_MASS Bk_MELT Bk_WEIGHT Bk_Z BkMASS BMASS BOHRIUM BOHRIUM_Z B" + \
   "OHRRADIUS BOHRRADIUS_ERR BORON BORON_Z BOTTOMQUARK_CHARGE BOTTOMQUAR" + \
   "K_ENERGY BOTTOMQUARK_Hz BOTTOMQUARK_MASS BOTTOMQUARK_WAVELENGTH BOTT" + \
   "OMQUARKMASS BOTTOMQUARKMASS_ERR Br_BOIL Br_Cp Br_DENSITY Br_En Br_MA" + \
   "SS Br_MELT Br_WEIGHT Br_Z BrMASS BROMINE BROMINE_Z BUTANE_DENSITY BU" + \
   "TANE_HC BUTANE_HCC BUTANE_HF BUTANE_JPKG BUTANE_JPL BUTANE_MASS BUTA" + \
   "NEMASS C12_MASS C12_RATIO C12_WEIGHT C12MASS C13_MASS C13_RATIO C13_" + \
   "WEIGHT C13MASS C14_MASS C14_RATIO C14_WEIGHT C14MASS C_BOIL C_Cp C_D" + \
   "ENSITY C_En C_MASS C_MEAN_MASS C_MELT C_WEIGHT C_Z Ca_BOIL Ca_Cp Ca_" + \
   "DENSITY Ca_En Ca_MASS Ca_MELT Ca_WEIGHT Ca_Z CADMIUM CADMIUM_Z CAESI" + \
   "UM CAESIUM_Z CALCIUM CALCIUM_Z CALIFORNIUM CALIFORNIUM_Z CaMASS CARB" + \
   "ON CARBON_Z CARBONDIOXIDE_DENSITY CARBONDIOXIDE_HC CARBONDIOXIDE_HF " + \
   "CARBONDIOXIDE_JPKG CARBONDIOXIDE_JPL CARBONDIOXIDE_MASS CARBONDIOXID" + \
   "EMASS Cd_BOIL Cd_Cp Cd_DENSITY Cd_En Cd_MASS Cd_MELT Cd_WEIGHT Cd_Z " + \
   "CdMASS Ce_BOIL Ce_Cp Ce_DENSITY Ce_En Ce_MASS Ce_MELT Ce_WEIGHT Ce_Z" + \
   " CeMASS CERIUM CERIUM_Z Cf_BOIL Cf_Cp Cf_DENSITY Cf_En Cf_MASS Cf_ME" + \
   "LT Cf_WEIGHT Cf_Z CfMASS CHARMQUARK_CHARGE CHARMQUARK_ENERGY CHARMQU" + \
   "ARK_Hz CHARMQUARK_MASS CHARMQUARK_WAVELENGTH CHARMQUARKMASS CHARMQUA" + \
   "RKMASS_ERR CHLORINE CHLORINE_Z CHROMIUM CHROMIUM_Z Cl_BOIL Cl_Cp Cl_" + \
   "DENSITY Cl_En Cl_MASS Cl_MELT Cl_WEIGHT Cl_Z ClMASS Cm_BOIL Cm_Cp Cm" + \
   "_DENSITY Cm_En Cm_MASS Cm_MELT Cm_WEIGHT Cm_Z CMASS CmMASS Cn_BOIL C" + \
   "n_Cp Cn_DENSITY Cn_En Cn_MASS Cn_MELT Cn_WEIGHT Cn_Z CnMASS CO2_DENS" + \
   "ITY CO2_HC CO2_HF CO2_JPKG CO2_JPL CO2_MASS CO2MASS Co_BOIL Co_Cp Co" + \
   "_DENSITY Co_En Co_MASS Co_MELT Co_WEIGHT Co_Z COAL_DENSITY COAL_JPKG" + \
   " COAL_JPL COAL_MASS COALMASS COBALT COBALT_Z CoMASS COPERNICIUM COPE" + \
   "RNICIUM_Z COPPER COPPER_Z Cr_BOIL Cr_Cp Cr_DENSITY Cr_En Cr_MASS Cr_" + \
   "MELT Cr_WEIGHT Cr_Z CrMASS Cs_BOIL Cs_Cp Cs_DENSITY Cs_En Cs_MASS Cs" + \
   "_MELT Cs_WEIGHT Cs_Z CsMASS Cu_BOIL Cu_Cp Cu_DENSITY Cu_En Cu_MASS C" + \
   "u_MELT Cu_WEIGHT Cu_Z CuMASS CURIUM CURIUM_Z D_MASS D_WEIGHT D_Z DAR" + \
   "MSTADTIUM DARMSTADTIUM_Z Db_BOIL Db_Cp Db_DENSITY Db_En Db_MASS Db_M" + \
   "ELT Db_WEIGHT Db_Z DbMASS DEUTERIUM DEUTERIUM_Z DEUTERON_MASS DEUTER" + \
   "ON_WEIGHT DEUTERONENERGY DEUTERONMASS DEUTERONMASS_ERR DIESEL_DENSIT" + \
   "Y DIESEL_JPKG DIESEL_JPL DIESEL_MASS DIESELMASS DMASS DOWNQUARK_CHAR" + \
   "GE DOWNQUARK_ENERGY DOWNQUARK_Hz DOWNQUARK_MASS DOWNQUARK_WAVELENGTH" + \
   " DOWNQUARKMASS DOWNQUARKMASS_ERR Ds_BOIL Ds_Cp Ds_DENSITY Ds_En Ds_M" + \
   "ASS Ds_MELT Ds_WEIGHT Ds_Z DsMASS DUBNIUM DUBNIUM_Z Dy_BOIL Dy_Cp Dy" + \
   "_DENSITY Dy_En Dy_MASS Dy_MELT Dy_WEIGHT Dy_Z DyMASS DYSPROSIUM DYSP" + \
   "ROSIUM_Z EINSTEINIUM EINSTEINIUM_Z ELECTRON_ENERGY ELECTRON_Hz ELECT" + \
   "RON_MASS ELECTRON_WAVELENGTH ELECTRONMASS ELECTRONMASS_ERR Er_BOIL E" + \
   "r_Cp Er_DENSITY Er_En Er_MASS Er_MELT Er_WEIGHT Er_Z ERBIUM ERBIUM_Z" + \
   " ErMASS Es_BOIL Es_Cp Es_DENSITY Es_En Es_MASS Es_MELT Es_WEIGHT Es_" + \
   "Z EsMASS ETHANE_DENSITY ETHANE_HC ETHANE_HCC ETHANE_HF ETHANE_JPKG E" + \
   "THANE_JPL ETHANE_MASS ETHANEMASS ETHANOL_DENSITY ETHANOL_G_DENSITY E" + \
   "THANOL_G_HC ETHANOL_G_HCC ETHANOL_G_HF ETHANOL_G_JPKG ETHANOL_G_JPL " + \
   "ETHANOL_G_MASS ETHANOL_GMASS ETHANOL_HC ETHANOL_HCC ETHANOL_HF ETHAN" + \
   "OL_JPKG ETHANOL_JPL ETHANOL_MASS ETHANOLMASS Eu_BOIL Eu_Cp Eu_DENSIT" + \
   "Y Eu_En Eu_MASS Eu_MELT Eu_WEIGHT Eu_Z EuMASS EUROPIUM EUROPIUM_Z F_" + \
   "BOIL F_Cp F_DENSITY F_En F_MASS F_MELT F_WEIGHT F_Z FAT_DENSITY FAT_" + \
   "JPKG FAT_JPL FAT_MASS FATMASS Fe_BOIL Fe_Cp Fe_DENSITY Fe_En Fe_MASS" + \
   " Fe_MELT Fe_WEIGHT Fe_Z FeMASS FERMIUM FERMIUM_Z Fl_BOIL Fl_Cp Fl_DE" + \
   "NSITY Fl_En Fl_MASS Fl_MELT Fl_WEIGHT Fl_Z FLEROVIUM FLEROVIUM_Z FlM" + \
   "ASS FLUORINE FLUORINE_Z Fm_BOIL Fm_Cp Fm_DENSITY Fm_En Fm_MASS Fm_ME" + \
   "LT Fm_WEIGHT Fm_Z FMASS FmMASS Fr_BOIL Fr_Cp Fr_DENSITY Fr_En Fr_MAS" + \
   "S Fr_MELT Fr_WEIGHT Fr_Z FRANCIUM FRANCIUM_Z FrMASS Ga_BOIL Ga_Cp Ga" + \
   "_DENSITY Ga_En Ga_MASS Ga_MELT Ga_WEIGHT Ga_Z GADOLINIUM GADOLINIUM_" + \
   "Z GALLIUM GALLIUM_Z GaMASS GASOLINE_DENSITY GASOLINE_JPKG GASOLINE_J" + \
   "PL GASOLINE_MASS GASOLINEMASS Gd_BOIL Gd_Cp Gd_DENSITY Gd_En Gd_MASS" + \
   " Gd_MELT Gd_WEIGHT Gd_Z GdMASS Ge_BOIL Ge_Cp Ge_DENSITY Ge_En Ge_MAS" + \
   "S Ge_MELT Ge_WEIGHT Ge_Z GeMASS GERMANIUM GERMANIUM_Z GOLD GOLD_Z H1" + \
   "_MASS H1_WEIGHT H1MASS H2_MASS H2_WEIGHT H2MASS H2O_DENSITY H2O_HC H" + \
   "2O_HF H2O_JPKG H2O_JPL H2O_MASS H2OMASS H3_MASS H3_WEIGHT H3MASS H_B" + \
   "OIL H_Cp H_DENSITY H_En H_MASS H_MELT H_WEIGHT H_Z HAFNIUM HAFNIUM_Z" + \
   " HASSIUM HASSIUM_Z He3_MASS He3_WEIGHT He3MASS He4_MASS He4_WEIGHT H" + \
   "e4MASS He_BOIL He_Cp He_DENSITY He_En He_MASS He_MELT He_WEIGHT He_Z" + \
   " HELION_MASS HELION_WEIGHT HELIONENERGY HELIONMASS HELIONMASS_ERR HE" + \
   "LIUM HELIUM_Z HeMASS HEXANE_DENSITY HEXANE_HC HEXANE_HCC HEXANE_HF H" + \
   "EXANE_JPKG HEXANE_JPL HEXANE_MASS HEXANEMASS Hf_BOIL Hf_Cp Hf_DENSIT" + \
   "Y Hf_En Hf_MASS Hf_MELT Hf_WEIGHT Hf_Z HfMASS Hg_BOIL Hg_Cp Hg_DENSI" + \
   "TY Hg_En Hg_MASS Hg_MELT Hg_WEIGHT Hg_Z HgMASS HIGGSBOSON_ENERGY HIG" + \
   "GSBOSON_Hz HIGGSBOSON_MASS HIGGSBOSON_WAVELENGTH HIGGSBOSONMASS HIGG" + \
   "SBOSONMASS_ERR HMASS Ho_BOIL Ho_Cp Ho_DENSITY Ho_En Ho_MASS Ho_MELT " + \
   "Ho_WEIGHT Ho_Z HOLMIUM HOLMIUM_Z HoMASS Hs_BOIL Hs_Cp Hs_DENSITY Hs_" + \
   "En Hs_MASS Hs_MELT Hs_WEIGHT Hs_Z HsMASS HYDROGEN HYDROGEN_DENSITY H" + \
   "YDROGEN_HC HYDROGEN_HCC HYDROGEN_HF HYDROGEN_JPKG HYDROGEN_JPL HYDRO" + \
   "GEN_MASS HYDROGEN_RADIUS HYDROGEN_RADIUS_ERR HYDROGEN_Z HYDROGENMASS" + \
   " I_BOIL I_Cp I_DENSITY I_En I_MASS I_MELT I_WEIGHT I_Z ICE_Cp IMASS " + \
   "In_BOIL In_Cp In_DENSITY In_En In_MASS In_MELT In_WEIGHT In_Z INDIUM" + \
   " INDIUM_Z InMASS IODINE IODINE_Z Ir_BOIL Ir_Cp Ir_DENSITY Ir_En Ir_M" + \
   "ASS Ir_MELT Ir_WEIGHT Ir_Z IRIDIUM IRIDIUM_Z IrMASS IRON IRON_Z K_BO" + \
   "IL K_Cp K_DENSITY K_En K_MASS K_MELT K_WEIGHT K_Z KEROSENE_DENSITY K" + \
   "EROSENE_JPKG KEROSENE_JPL KEROSENE_MASS KEROSENEMASS KMASS Kr_BOIL K" + \
   "r_Cp Kr_DENSITY Kr_En Kr_MASS Kr_MELT Kr_WEIGHT Kr_Z KrMASS KRYPTON " + \
   "KRYPTON_Z La_BOIL La_Cp La_DENSITY La_En La_MASS La_MELT La_WEIGHT L" + \
   "a_Z LaMASS LANTHANUM LANTHANUM_Z LAWRENCIUM LAWRENCIUM_Z LEAD LEAD_Z" + \
   " Li_BOIL Li_Cp Li_DENSITY Li_En Li_MASS Li_MELT Li_WEIGHT Li_Z LiMAS" + \
   "S LITHIUM LITHIUM_Z LIVERMORIUM LIVERMORIUM_Z Lr_BOIL Lr_Cp Lr_DENSI" + \
   "TY Lr_En Lr_MASS Lr_MELT Lr_WEIGHT Lr_Z LrMASS Lu_BOIL Lu_Cp Lu_DENS" + \
   "ITY Lu_En Lu_MASS Lu_MELT Lu_WEIGHT Lu_Z LuMASS LUTETIUM LUTETIUM_Z " + \
   "Lv_BOIL Lv_Cp Lv_DENSITY Lv_En Lv_MASS Lv_MELT Lv_WEIGHT Lv_Z LvMASS" + \
   " MAGNESIUM MAGNESIUM_Z MANGANESE MANGANESE_Z Mc_BOIL Mc_Cp Mc_DENSIT" + \
   "Y Mc_En Mc_MASS Mc_MELT Mc_WEIGHT Mc_Z McMASS Md_BOIL Md_Cp Md_DENSI" + \
   "TY Md_En Md_MASS Md_MELT Md_WEIGHT Md_Z MdMASS MEITNERIUM MEITNERIUM" + \
   "_Z MENDELEVIUM MENDELEVIUM_Z MERCURY MERCURY_Z METHANE_DENSITY METHA" + \
   "NE_HC METHANE_HCC METHANE_HF METHANE_JPKG METHANE_JPL METHANE_MASS M" + \
   "ETHANEMASS Mg_BOIL Mg_Cp Mg_DENSITY Mg_En Mg_MASS Mg_MELT Mg_WEIGHT " + \
   "Mg_Z MgMASS Mn_BOIL Mn_Cp Mn_DENSITY Mn_En Mn_MASS Mn_MELT Mn_WEIGHT" + \
   " Mn_Z MnMASS Mo_BOIL Mo_Cp Mo_DENSITY Mo_En Mo_MASS Mo_MELT Mo_WEIGH" + \
   "T Mo_Z MOLYBDENUM MOLYBDENUM_Z MoMASS MOSCOVIUM MOSCOVIUM_Z Mt_BOIL " + \
   "Mt_Cp Mt_DENSITY Mt_En Mt_MASS Mt_MELT Mt_WEIGHT Mt_Z MtMASS MUON_EN" + \
   "ERGY MUON_Hz MUON_MASS MUON_WAVELENGTH MUONMASS MUONMASS_ERR N_BOIL " + \
   "N_Cp N_DENSITY N_En N_MASS N_MELT N_WEIGHT N_Z Na_BOIL Na_Cp Na_DENS" + \
   "ITY Na_En Na_MASS Na_MELT Na_WEIGHT Na_Z NaMASS Nb_BOIL Nb_Cp Nb_DEN" + \
   "SITY Nb_En Nb_MASS Nb_MELT Nb_WEIGHT Nb_Z NbMASS Nd_BOIL Nd_Cp Nd_DE" + \
   "NSITY Nd_En Nd_MASS Nd_MELT Nd_WEIGHT Nd_Z NdMASS Ne_BOIL Ne_Cp Ne_D" + \
   "ENSITY Ne_En Ne_MASS Ne_MELT Ne_WEIGHT Ne_Z NeMASS NEODYMIUM NEODYMI" + \
   "UM_Z NEON NEON_Z NEPTUNIUM NEPTUNIUM_Z NEUTRON_ENERGY NEUTRON_Hz NEU" + \
   "TRON_MASS NEUTRON_WAVELENGTH NEUTRONMASS NEUTRONMASS_ERR Nh_BOIL Nh_" + \
   "Cp Nh_DENSITY Nh_En Nh_MASS Nh_MELT Nh_WEIGHT Nh_Z NhMASS Ni_BOIL Ni" + \
   "_Cp Ni_DENSITY Ni_En Ni_MASS Ni_MELT Ni_WEIGHT Ni_Z NICKEL NICKEL_Z " + \
   "NIHONIUM NIHONIUM_Z NiMASS NIOBIUM NIOBIUM_Z NITROGEN NITROGEN_Z NMA" + \
   "SS No_BOIL No_Cp No_DENSITY No_En No_MASS No_MELT No_WEIGHT No_Z NOB" + \
   "ELIUM NOBELIUM_Z NoMASS Np_BOIL Np_Cp Np_DENSITY Np_En Np_MASS Np_ME" + \
   "LT Np_WEIGHT Np_Z NpMASS O16_MASS O16_WEIGHT O16MASS O17_MASS O17_WE" + \
   "IGHT O17MASS O18_MASS O18_WEIGHT O18MASS O2_DENSITY O2_HC O2_HF O2_J" + \
   "PKG O2_JPL O2_MASS O2MASS O_BOIL O_Cp O_DENSITY O_En O_MASS O_MELT O" + \
   "_WEIGHT O_Z Og_BOIL Og_Cp Og_DENSITY Og_En Og_MASS Og_MELT Og_WEIGHT" + \
   " Og_Z OGANESSON OGANESSON_Z OgMASS OMASS Os_BOIL Os_Cp Os_DENSITY Os" + \
   "_En Os_MASS Os_MELT Os_WEIGHT Os_Z OsMASS OSMIUM OSMIUM_Z OXYGEN OXY" + \
   "GEN_Z P_BOIL P_Cp P_DENSITY P_En P_MASS P_MELT P_WEIGHT P_Z Pa_BOIL " + \
   "Pa_Cp Pa_DENSITY Pa_En Pa_MASS Pa_MELT Pa_WEIGHT Pa_Z PALLADIUM PALL" + \
   "ADIUM_Z PaMASS PARAFFIN_DENSITY PARAFFIN_JPKG PARAFFIN_JPL PARAFFIN_" + \
   "MASS PARAFFINMASS Pb_BOIL Pb_Cp Pb_DENSITY Pb_En Pb_MASS Pb_MELT Pb_" + \
   "WEIGHT Pb_Z PbMASS Pd_BOIL Pd_Cp Pd_DENSITY Pd_En Pd_MASS Pd_MELT Pd" + \
   "_WEIGHT Pd_Z PdMASS PENTANE_DENSITY PENTANE_HC PENTANE_HCC PENTANE_H" + \
   "F PENTANE_JPKG PENTANE_JPL PENTANE_MASS PENTANEMASS PHOSPHORUS PHOSP" + \
   "HORUS_Z PLATINUM PLATINUM_Z PLUTONIUM PLUTONIUM_Z Pm_BOIL Pm_Cp Pm_D" + \
   "ENSITY Pm_En Pm_MASS Pm_MELT Pm_WEIGHT Pm_Z PMASS PmMASS Po_BOIL Po_" + \
   "Cp Po_DENSITY Po_En Po_MASS Po_MELT Po_WEIGHT Po_Z POLONIUM POLONIUM" + \
   "_Z PoMASS POTASSIUM POTASSIUM_Z Pr_BOIL Pr_Cp Pr_DENSITY Pr_En Pr_MA" + \
   "SS Pr_MELT Pr_WEIGHT Pr_Z PRASEODYMIUM PRASEODYMIUM_Z PrMASS PROMETH" + \
   "IUM PROMETHIUM_Z PROPANE_DENSITY PROPANE_HC PROPANE_HCC PROPANE_HF P" + \
   "ROPANE_JPKG PROPANE_JPL PROPANE_MASS PROPANEMASS PROTACTINIUM PROTAC" + \
   "TINIUM_Z PROTON_ENERGY PROTON_Hz PROTON_MASS PROTON_WAVELENGTH PROTO" + \
   "NMASS PROTONMASS_ERR Pt_BOIL Pt_Cp Pt_DENSITY Pt_En Pt_MASS Pt_MELT " + \
   "Pt_WEIGHT Pt_Z PtMASS Pu_BOIL Pu_Cp Pu_DENSITY Pu_En Pu_MASS Pu_MELT" + \
   " Pu_WEIGHT Pu_Z PuMASS Ra_BOIL Ra_Cp Ra_DENSITY Ra_En Ra_MASS Ra_MEL" + \
   "T Ra_WEIGHT Ra_Z RADIUM RADIUM_Z RADON RADON_Z RaMASS Rb_BOIL Rb_Cp " + \
   "Rb_DENSITY Rb_En Rb_MASS Rb_MELT Rb_WEIGHT Rb_Z RbMASS Re_BOIL Re_Cp" + \
   " Re_DENSITY Re_En Re_MASS Re_MELT Re_WEIGHT Re_Z ReMASS Rf_BOIL Rf_C" + \
   "p Rf_DENSITY Rf_En Rf_MASS Rf_MELT Rf_WEIGHT Rf_Z RfMASS Rg_BOIL Rg_" + \
   "Cp Rg_DENSITY Rg_En Rg_MASS Rg_MELT Rg_WEIGHT Rg_Z RgMASS Rh_BOIL Rh" + \
   "_Cp Rh_DENSITY Rh_En Rh_MASS Rh_MELT Rh_WEIGHT Rh_Z RHENIUM RHENIUM_" + \
   "Z RhMASS RHODIUM RHODIUM_Z Rn_BOIL Rn_Cp Rn_DENSITY Rn_En Rn_MASS Rn" + \
   "_MELT Rn_WEIGHT Rn_Z RnMASS ROENTGENIUM ROENTGENIUM_Z Ru_BOIL Ru_Cp " + \
   "Ru_DENSITY Ru_En Ru_MASS Ru_MELT Ru_WEIGHT Ru_Z RUBIDIUM RUBIDIUM_Z " + \
   "RuMASS RUTHENIUM RUTHENIUM_Z RUTHERFORDIUM RUTHERFORDIUM_Z S_BOIL S_" + \
   "Cp S_DENSITY S_En S_MASS S_MELT S_WEIGHT S_Z SAMARIUM SAMARIUM_Z Sb_" + \
   "BOIL Sb_Cp Sb_DENSITY Sb_En Sb_MASS Sb_MELT Sb_WEIGHT Sb_Z SbMASS Sc" + \
   "_BOIL Sc_Cp Sc_DENSITY Sc_En Sc_MASS Sc_MELT Sc_WEIGHT Sc_Z SCANDIUM" + \
   " SCANDIUM_Z ScMASS Se_BOIL Se_Cp Se_DENSITY Se_En Se_MASS Se_MELT Se" + \
   "_WEIGHT Se_Z SEABORGIUM SEABORGIUM_Z SELENIUM SELENIUM_Z SeMASS Sg_B" + \
   "OIL Sg_Cp Sg_DENSITY Sg_En Sg_MASS Sg_MELT Sg_WEIGHT Sg_Z SgMASS Si_" + \
   "BOIL Si_Cp Si_DENSITY Si_En Si_MASS Si_MELT Si_WEIGHT Si_Z SILICON S" + \
   "ILICON_Z SILVER SILVER_Z SiMASS Sm_BOIL Sm_Cp Sm_DENSITY Sm_En Sm_MA" + \
   "SS Sm_MELT Sm_WEIGHT Sm_Z SMASS SmMASS Sn_BOIL Sn_Cp Sn_DENSITY Sn_E" + \
   "n Sn_MASS Sn_MELT Sn_WEIGHT Sn_Z SnMASS SODIUM SODIUM_Z Sr_BOIL Sr_C" + \
   "p Sr_DENSITY Sr_En Sr_MASS Sr_MELT Sr_WEIGHT Sr_Z SrMASS STEAM_Cp ST" + \
   "EAM_DENSITY STEAM_HC STEAM_HF STEAM_JPKG STEAM_JPL STEAM_MASS STEAMM" + \
   "ASS STRANGEQUARK_CHARGE STRANGEQUARK_ENERGY STRANGEQUARK_Hz STRANGEQ" + \
   "UARK_MASS STRANGEQUARK_WAVELENGTH STRANGEQUARKMASS STRANGEQUARKMASS_" + \
   "ERR STRONTIUM STRONTIUM_Z SUCROSE_DENSITY SUCROSE_HC SUCROSE_HCC SUC" + \
   "ROSE_HF SUCROSE_JPKG SUCROSE_JPL SUCROSE_MASS SUCROSEMASS SUGAR_DENS" + \
   "ITY SUGAR_HC SUGAR_HCC SUGAR_HF SUGAR_JPKG SUGAR_JPL SUGAR_MASS SUGA" + \
   "RMASS SULFUR SULFUR_Z T_MASS T_WEIGHT T_Z Ta_BOIL Ta_Cp Ta_DENSITY T" + \
   "a_En Ta_MASS Ta_MELT Ta_WEIGHT Ta_Z TaMASS TANTALUM TANTALUM_Z TAU_E" + \
   "NERGY TAU_Hz TAU_MASS TAU_WAVELENGTH TAUMASS TAUMASS_ERR Tb_BOIL Tb_" + \
   "Cp Tb_DENSITY Tb_En Tb_MASS Tb_MELT Tb_WEIGHT Tb_Z TbMASS Tc_BOIL Tc" + \
   "_Cp Tc_DENSITY Tc_En Tc_MASS Tc_MELT Tc_WEIGHT Tc_Z TcMASS Te_BOIL T" + \
   "e_Cp Te_DENSITY Te_En Te_MASS Te_MELT Te_WEIGHT Te_Z TECHNETIUM TECH" + \
   "NETIUM_Z TELLURIUM TELLURIUM_Z TeMASS TENNESSINE TENNESSINE_Z TERBIU" + \
   "M TERBIUM_Z Th_BOIL Th_Cp Th_DENSITY Th_En Th_MASS Th_MELT Th_WEIGHT" + \
   " Th_Z THALLIUM THALLIUM_Z ThMASS THORIUM THORIUM_Z THULIUM THULIUM_Z" + \
   " Ti_BOIL Ti_Cp Ti_DENSITY Ti_En Ti_MASS Ti_MELT Ti_WEIGHT Ti_Z TiMAS" + \
   "S TIN TIN_Z TITANIUM TITANIUM_Z Tl_BOIL Tl_Cp Tl_DENSITY Tl_En Tl_MA" + \
   "SS Tl_MELT Tl_WEIGHT Tl_Z TlMASS Tm_BOIL Tm_Cp Tm_DENSITY Tm_En Tm_M" + \
   "ASS Tm_MELT Tm_WEIGHT Tm_Z TMASS TmMASS TNTJPKG TOPQUARK_CHARGE TOPQ" + \
   "UARK_ENERGY TOPQUARK_Hz TOPQUARK_MASS TOPQUARK_WAVELENGTH TOPQUARKMA" + \
   "SS TOPQUARKMASS_ERR TRITIUM TRITIUM_Z TRITON_MASS TRITON_WEIGHT TRIT" + \
   "ONENERGY TRITONMASS TRITONMASS_ERR Ts_BOIL Ts_Cp Ts_DENSITY Ts_En Ts" + \
   "_MASS Ts_MELT Ts_WEIGHT Ts_Z TsMASS TUNGSTEN TUNGSTEN_Z U_BOIL U_Cp " + \
   "U_DENSITY U_En U_MASS U_MELT U_WEIGHT U_Z UMASS UPQUARK_CHARGE UPQUA" + \
   "RK_ENERGY UPQUARK_Hz UPQUARK_MASS UPQUARK_WAVELENGTH UPQUARKMASS UPQ" + \
   "UARKMASS_ERR URANIUM URANIUM_Z V_BOIL V_Cp V_DENSITY V_En V_MASS V_M" + \
   "ELT V_WEIGHT V_Z VANADIUM VANADIUM_Z VMASS VSMOW_H1_RATIO VSMOW_H2_R" + \
   "ATIO VSMOW_H3_RATIO VSMOW_H_MASS VSMOW_MASS VSMOW_O16_RATIO VSMOW_O1" + \
   "7_RATIO VSMOW_O18_RATIO VSMOW_O_MASS W_BOIL W_Cp W_DENSITY W_En W_MA" + \
   "SS W_MELT W_WEIGHT W_Z WATER_Cp WATER_CRITICAL WATER_DENSITY WATER_F" + \
   "USION_JPKG WATER_FUSION_JPMOLE WATER_HC WATER_HF WATER_JPKG WATER_JP" + \
   "L WATER_MASS WATER_VAPORIZATION_JPKG WATER_VAPORIZATION_JPMOLE WATER" + \
   "MASS WBOSON_ENERGY WBOSON_Hz WBOSON_MASS WBOSON_WAVELENGTH WBOSONMAS" + \
   "S WBOSONMASS_ERR WMASS Xe_BOIL Xe_Cp Xe_DENSITY Xe_En Xe_MASS Xe_MEL" + \
   "T Xe_WEIGHT Xe_Z XeMASS XENON XENON_Z Y_BOIL Y_Cp Y_DENSITY Y_En Y_M" + \
   "ASS Y_MELT Y_WEIGHT Y_Z Yb_BOIL Yb_Cp Yb_DENSITY Yb_En Yb_MASS Yb_ME" + \
   "LT Yb_WEIGHT Yb_Z YbMASS YMASS YTTERBIUM YTTERBIUM_Z YTTRIUM YTTRIUM" + \
   "_Z ZBOSON_ENERGY ZBOSON_Hz ZBOSON_MASS ZBOSON_WAVELENGTH ZBOSONMASS " + \
   "ZBOSONMASS_ERR ZINC ZINC_Z ZIRCONIUM ZIRCONIUM_Z Zn_BOIL Zn_Cp Zn_DE" + \
   "NSITY Zn_En Zn_MASS Zn_MELT Zn_WEIGHT Zn_Z ZnMASS Zr_BOIL Zr_Cp Zr_D" + \
   "ENSITY Zr_En Zr_MASS Zr_MELT Zr_WEIGHT Zr_Z ZrMASS" + \
   "\n" + \
   "   Kwelements 1-ary Functions: waterboiling waterdensity waterdensit" + \
   "y_airfree waterdensity_airfree__1 watervapor_pressure watervaporizat" + \
   "ion" + \
   "\n"
)
def kwelements_desc():
   return( \
   "   Kwelements Constants: Ac_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z)" + \
   " AcMASS ACTINIUM(_Z)? Ag_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) Ag" + \
   "MASS AIR(_MASS|MASS) Al_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) AlM" + \
   "ASS ALPHA(_(MASS|WEIGHT)|ENERGY|MASS(_ERR)?) ALUMINIUM(_Z)? Am_(BOIL" + \
   "|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) AMERICIUM(_Z)? AmMASS ANTIMONY(_" + \
   "Z)? Ar_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) ARGON(_Z)? ArMASS AR" + \
   "SENIC(_Z)? As_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) AsMASS ASTATI" + \
   "NE(_Z)? At_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) AtMASS Au_(BOIL|" + \
   "Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) AuMASS B_BOIL B_Cp B_DENSITY B_En" + \
   " B_M(ASS|ELT) B_WEIGHT B_Z Ba_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|" + \
   "Z) BaMASS BARIUM(_Z)? Be_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) Be" + \
   "MASS BER(KELIUM(_Z)?|YLLIUM(_Z)?) Bh_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|" + \
   "WEIGHT|Z) BhMASS Bi_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) BiMASS " + \
   "BISMUTH(_Z)? Bk_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) BkMASS BMAS" + \
   "S BOHR(IUM(_Z)?|RADIUS(_ERR)?) BORON(_Z)? BOTTOMQUARK(_(CHARGE|ENERG" + \
   "Y|Hz|MASS|WAVELENGTH)|MASS(_ERR)?) Br_(BOIL|Cp|DENSITY|En|M(ASS|ELT)" + \
   "|WEIGHT|Z) BrMASS BROMINE(_Z)? BUTANE(_(DENSITY|H(CC?|F)|JP(KG|L)|MA" + \
   "SS)|MASS) C12(_(MASS|RATIO|WEIGHT)|MASS) C13(_(MASS|RATIO|WEIGHT)|MA" + \
   "SS) C14(_(MASS|RATIO|WEIGHT)|MASS) C_BOIL C_Cp C_DENSITY C_En C_M(AS" + \
   "S|E(AN_MASS|LT)) C_WEIGHT C_Z Ca_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIG" + \
   "HT|Z) CADMIUM(_Z)? CAESIUM(_Z)? CAL(CIUM(_Z)?|IFORNIUM(_Z)?) CaMASS " + \
   "CARBON(|_Z|DIOXIDE(_(DENSITY|H[CF]|JP(KG|L)|MASS)|MASS)) Cd_(BOIL|Cp" + \
   "|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) CdMASS Ce_(BOIL|Cp|DENSITY|En|M(ASS" + \
   "|ELT)|WEIGHT|Z) CeMASS CERIUM(_Z)? Cf_(BOIL|Cp|DENSITY|En|M(ASS|ELT)" + \
   "|WEIGHT|Z) CfMASS CHARMQUARK(_(CHARGE|ENERGY|Hz|MASS|WAVELENGTH)|MAS" + \
   "S(_ERR)?) CHLORINE(_Z)? CHROMIUM(_Z)? Cl_(BOIL|Cp|DENSITY|En|M(ASS|E" + \
   "LT)|WEIGHT|Z) ClMASS Cm_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) CMA" + \
   "SS CmMASS Cn_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) CnMASS CO2(_(D" + \
   "ENSITY|H[CF]|JP(KG|L)|MASS)|MASS) Co_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|" + \
   "WEIGHT|Z) COAL(_(DENSITY|JP(KG|L)|MASS)|MASS) COBALT(_Z)? CoMASS COP" + \
   "(ERNICIUM(_Z)?|PER(_Z)?) Cr_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z)" + \
   " CrMASS Cs_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) CsMASS Cu_(BOIL|" + \
   "Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) CuMASS CURIUM(_Z)? D_MASS D_WEIGH" + \
   "T D_Z DARMSTADTIUM(_Z)? Db_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) " + \
   "DbMASS DEUTER(IUM(_Z)?|ON(_(MASS|WEIGHT)|ENERGY|MASS(_ERR)?)) DIESEL" + \
   "(_(DENSITY|JP(KG|L)|MASS)|MASS) DMASS DOWNQUARK(_(CHARGE|ENERGY|Hz|M" + \
   "ASS|WAVELENGTH)|MASS(_ERR)?) Ds_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGH" + \
   "T|Z) DsMASS DUBNIUM(_Z)? Dy_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z)" + \
   " DyMASS DYSPROSIUM(_Z)? EINSTEINIUM(_Z)? ELECTRON(_(ENERGY|Hz|MASS|W" + \
   "AVELENGTH)|MASS(_ERR)?) Er_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) " + \
   "ERBIUM(_Z)? ErMASS Es_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) EsMAS" + \
   "S ETHAN(E(_(DENSITY|H(CC?|F)|JP(KG|L)|MASS)|MASS)|OL(_(DENSITY|G(_(D" + \
   "ENSITY|H(CC?|F)|JP(KG|L)|MASS)|MASS)|H(CC?|F)|JP(KG|L)|MASS)|MASS)) " + \
   "Eu_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) EuMASS EUROPIUM(_Z)? F_B" + \
   "OIL F_Cp F_DENSITY F_En F_M(ASS|ELT) F_WEIGHT F_Z FAT(_(DENSITY|JP(K" + \
   "G|L)|MASS)|MASS) Fe_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) FeMASS " + \
   "FERMIUM(_Z)? Fl_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) FLEROVIUM(_" + \
   "Z)? FlMASS FLUORINE(_Z)? Fm_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z)" + \
   " FMASS FmMASS Fr_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) FRANCIUM(_" + \
   "Z)? FrMASS Ga_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) GADOLINIUM(_Z" + \
   ")? GALLIUM(_Z)? GaMASS GASOLINE(_(DENSITY|JP(KG|L)|MASS)|MASS) Gd_(B" + \
   "OIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) GdMASS Ge_(BOIL|Cp|DENSITY|En" + \
   "|M(ASS|ELT)|WEIGHT|Z) GeMASS GERMANIUM(_Z)? GOLD(_Z)? H1_(MASS|WEIGH" + \
   "T) H1MASS H2_(MASS|WEIGHT) H2MASS H2O(_(DENSITY|H[CF]|JP(KG|L)|MASS)" + \
   "|MASS) H3_(MASS|WEIGHT) H3MASS H_BOIL H_Cp H_DENSITY H_En H_M(ASS|EL" + \
   "T) H_WEIGHT H_Z HAFNIUM(_Z)? HASSIUM(_Z)? He3(_(MASS|WEIGHT)|MASS) H" + \
   "e4(_(MASS|WEIGHT)|MASS) He_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) " + \
   "HELI(ON(_(MASS|WEIGHT)|ENERGY|MASS(_ERR)?)|UM(_Z)?) HeMASS HEXANE(_(" + \
   "DENSITY|H(CC?|F)|JP(KG|L)|MASS)|MASS) Hf_(BOIL|Cp|DENSITY|En|M(ASS|E" + \
   "LT)|WEIGHT|Z) HfMASS Hg_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) HgM" + \
   "ASS HIGGSBOSON(_(ENERGY|Hz|MASS|WAVELENGTH)|MASS(_ERR)?) HMASS Ho_(B" + \
   "OIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) HOLMIUM(_Z)? HoMASS Hs_(BOIL|" + \
   "Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) HsMASS HYDROGEN(|_(DENSITY|H(CC?|" + \
   "F)|JP(KG|L)|MASS|RADIUS(_ERR)?|Z)|MASS) I_BOIL I_Cp I_DENSITY I_En I" + \
   "_M(ASS|ELT) I_WEIGHT I_Z ICE_Cp IMASS In_(BOIL|Cp|DENSITY|En|M(ASS|E" + \
   "LT)|WEIGHT|Z) INDIUM(_Z)? InMASS IODINE(_Z)? Ir_(BOIL|Cp|DENSITY|En|" + \
   "M(ASS|ELT)|WEIGHT|Z) IRIDIUM(_Z)? IrMASS IRON(_Z)? K_BOIL K_Cp K_DEN" + \
   "SITY K_En K_M(ASS|ELT) K_WEIGHT K_Z KEROSENE(_(DENSITY|JP(KG|L)|MASS" + \
   ")|MASS) KMASS Kr_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) KrMASS KRY" + \
   "PTON(_Z)? La_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) LaMASS LANTHAN" + \
   "UM(_Z)? LAWRENCIUM(_Z)? LEAD(_Z)? Li_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|" + \
   "WEIGHT|Z) LiMASS LITHIUM(_Z)? LIVERMORIUM(_Z)? Lr_(BOIL|Cp|DENSITY|E" + \
   "n|M(ASS|ELT)|WEIGHT|Z) LrMASS Lu_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIG" + \
   "HT|Z) LuMASS LUTETIUM(_Z)? Lv_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|" + \
   "Z) LvMASS MAGNESIUM(_Z)? MANGANESE(_Z)? Mc_(BOIL|Cp|DENSITY|En|M(ASS" + \
   "|ELT)|WEIGHT|Z) McMASS Md_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) M" + \
   "dMASS MEITNERIUM(_Z)? MENDELEVIUM(_Z)? MERCURY(_Z)? METHANE(_(DENSIT" + \
   "Y|H(CC?|F)|JP(KG|L)|MASS)|MASS) Mg_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WE" + \
   "IGHT|Z) MgMASS Mn_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) MnMASS Mo" + \
   "_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) MOLYBDENUM(_Z)? MoMASS MOS" + \
   "COVIUM(_Z)? Mt_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) MtMASS MUON(" + \
   "_(ENERGY|Hz|MASS|WAVELENGTH)|MASS(_ERR)?) N_BOIL N_Cp N_DENSITY N_En" + \
   " N_M(ASS|ELT) N_WEIGHT N_Z Na_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|" + \
   "Z) NaMASS Nb_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) NbMASS Nd_(BOI" + \
   "L|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) NdMASS Ne_(BOIL|Cp|DENSITY|En|M" + \
   "(ASS|ELT)|WEIGHT|Z) NeMASS NEO(DYMIUM(_Z)?|N(_Z)?) NEPTUNIUM(_Z)? NE" + \
   "UTRON(_(ENERGY|Hz|MASS|WAVELENGTH)|MASS(_ERR)?) Nh_(BOIL|Cp|DENSITY|" + \
   "En|M(ASS|ELT)|WEIGHT|Z) NhMASS Ni_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEI" + \
   "GHT|Z) NICKEL(_Z)? NIHONIUM(_Z)? NiMASS NIOBIUM(_Z)? NITROGEN(_Z)? N" + \
   "MASS No_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) NOBELIUM(_Z)? NoMAS" + \
   "S Np_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) NpMASS O16(_(MASS|WEIG" + \
   "HT)|MASS) O17(_(MASS|WEIGHT)|MASS) O18(_(MASS|WEIGHT)|MASS) O2_(DENS" + \
   "ITY|H[CF]|JP(KG|L)|MASS) O2MASS O_BOIL O_Cp O_DENSITY O_En O_M(ASS|E" + \
   "LT) O_WEIGHT O_Z Og_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) OGANESS" + \
   "ON(_Z)? OgMASS OMASS Os_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) OsM" + \
   "ASS OSMIUM(_Z)? OXYGEN(_Z)? P_BOIL P_Cp P_DENSITY P_En P_M(ASS|ELT) " + \
   "P_WEIGHT P_Z Pa_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) PALLADIUM(_" + \
   "Z)? PaMASS PARAFFIN(_(DENSITY|JP(KG|L)|MASS)|MASS) Pb_(BOIL|Cp|DENSI" + \
   "TY|En|M(ASS|ELT)|WEIGHT|Z) PbMASS Pd_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|" + \
   "WEIGHT|Z) PdMASS PENTANE(_(DENSITY|H(CC?|F)|JP(KG|L)|MASS)|MASS) PHO" + \
   "SPHORUS(_Z)? PLATINUM(_Z)? PLUTONIUM(_Z)? Pm_(BOIL|Cp|DENSITY|En|M(A" + \
   "SS|ELT)|WEIGHT|Z) PMASS PmMASS Po_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEI" + \
   "GHT|Z) POLONIUM(_Z)? PoMASS POTASSIUM(_Z)? Pr_(BOIL|Cp|DENSITY|En|M(" + \
   "ASS|ELT)|WEIGHT|Z) PRASEODYMIUM(_Z)? PrMASS PRO(METHIUM(_Z)?|PANE(_(" + \
   "DENSITY|H(CC?|F)|JP(KG|L)|MASS)|MASS)|T(ACTINIUM(_Z)?|ON(_(ENERGY|Hz" + \
   "|MASS|WAVELENGTH)|MASS(_ERR)?))) Pt_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|W" + \
   "EIGHT|Z) PtMASS Pu_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) PuMASS R" + \
   "a_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) RAD(IUM(_Z)?|ON(_Z)?) RaM" + \
   "ASS Rb_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) RbMASS Re_(BOIL|Cp|D" + \
   "ENSITY|En|M(ASS|ELT)|WEIGHT|Z) ReMASS Rf_(BOIL|Cp|DENSITY|En|M(ASS|E" + \
   "LT)|WEIGHT|Z) RfMASS Rg_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) RgM" + \
   "ASS Rh_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) RHENIUM(_Z)? RhMASS " + \
   "RHODIUM(_Z)? Rn_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) RnMASS ROEN" + \
   "TGENIUM(_Z)? Ru_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) RUBIDIUM(_Z" + \
   ")? RuMASS RUTHE(NIUM(_Z)?|RFORDIUM(_Z)?) S_BOIL S_Cp S_DENSITY S_En " + \
   "S_M(ASS|ELT) S_WEIGHT S_Z SAMARIUM(_Z)? Sb_(BOIL|Cp|DENSITY|En|M(ASS" + \
   "|ELT)|WEIGHT|Z) SbMASS Sc_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) S" + \
   "CANDIUM(_Z)? ScMASS Se_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) SEAB" + \
   "ORGIUM(_Z)? SELENIUM(_Z)? SeMASS Sg_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|W" + \
   "EIGHT|Z) SgMASS Si_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) SIL(ICON" + \
   "(_Z)?|VER(_Z)?) SiMASS Sm_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) S" + \
   "MASS SmMASS Sn_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) SnMASS SODIU" + \
   "M(_Z)? Sr_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) SrMASS STEAM(_(Cp" + \
   "|DENSITY|H[CF]|JP(KG|L)|MASS)|MASS) STR(ANGEQUARK(_(CHARGE|ENERGY|Hz" + \
   "|MASS|WAVELENGTH)|MASS(_ERR)?)|ONTIUM(_Z)?) SUCROSE(_(DENSITY|H(CC?|" + \
   "F)|JP(KG|L)|MASS)|MASS) SUGAR(_(DENSITY|H(CC?|F)|JP(KG|L)|MASS)|MASS" + \
   ") SULFUR(_Z)? T_MASS T_WEIGHT T_Z Ta_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|" + \
   "WEIGHT|Z) TaMASS TANTALUM(_Z)? TAU(_(ENERGY|Hz|MASS|WAVELENGTH)|MASS" + \
   "(_ERR)?) Tb_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) TbMASS Tc_(BOIL" + \
   "|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) TcMASS Te_(BOIL|Cp|DENSITY|En|M(" + \
   "ASS|ELT)|WEIGHT|Z) TECHNETIUM(_Z)? TELLURIUM(_Z)? TeMASS TENNESSINE(" + \
   "_Z)? TERBIUM(_Z)? Th_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) THALLI" + \
   "UM(_Z)? ThMASS THORIUM(_Z)? THULIUM(_Z)? Ti_(BOIL|Cp|DENSITY|En|M(AS" + \
   "S|ELT)|WEIGHT|Z) TiMASS TIN(_Z)? TITANIUM(_Z)? Tl_(BOIL|Cp|DENSITY|E" + \
   "n|M(ASS|ELT)|WEIGHT|Z) TlMASS Tm_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIG" + \
   "HT|Z) TMASS TmMASS TNTJPKG TOPQUARK(_(CHARGE|ENERGY|Hz|MASS|WAVELENG" + \
   "TH)|MASS(_ERR)?) TRIT(IUM(_Z)?|ON(_(MASS|WEIGHT)|ENERGY|MASS(_ERR)?)" + \
   ") Ts_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) TsMASS TUNGSTEN(_Z)? U" + \
   "_BOIL U_Cp U_DENSITY U_En U_M(ASS|ELT) U_WEIGHT U_Z UMASS UPQUARK(_(" + \
   "CHARGE|ENERGY|Hz|MASS|WAVELENGTH)|MASS(_ERR)?) URANIUM(_Z)? V_BOIL V" + \
   "_Cp V_DENSITY V_En V_M(ASS|ELT) V_WEIGHT V_Z VANADIUM(_Z)? VMASS VSM" + \
   "OW_(H(1_RATIO|2_RATIO|3_RATIO|_MASS)|MASS|O(1[678]_RATIO|_MASS)) W_B" + \
   "OIL W_Cp W_DENSITY W_En W_M(ASS|ELT) W_WEIGHT W_Z WATER(_(C(p|RITICA" + \
   "L)|DENSITY|FUSION_JP(KG|MOLE)|H[CF]|JP(KG|L)|MASS|VAPORIZATION_JP(KG" + \
   "|MOLE))|MASS) WBOSON(_(ENERGY|Hz|MASS|WAVELENGTH)|MASS(_ERR)?) WMASS" + \
   " Xe_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) XeMASS XENON(_Z)? Y_BOI" + \
   "L Y_Cp Y_DENSITY Y_En Y_M(ASS|ELT) Y_WEIGHT Y_Z Yb_(BOIL|Cp|DENSITY|" + \
   "En|M(ASS|ELT)|WEIGHT|Z) YbMASS YMASS YTT(ERBIUM(_Z)?|RIUM(_Z)?) ZBOS" + \
   "ON(_(ENERGY|Hz|MASS|WAVELENGTH)|MASS(_ERR)?) ZINC(_Z)? ZIRCONIUM(_Z)" + \
   "? Zn_(BOIL|Cp|DENSITY|En|M(ASS|ELT)|WEIGHT|Z) ZnMASS Zr_(BOIL|Cp|DEN" + \
   "SITY|En|M(ASS|ELT)|WEIGHT|Z) ZrMASS" + \
   "\n" + \
   "   Kwelements 1-ary Functions: water(boiling|density(_airfree(__1)?)" + \
   "?|vapor(_pressure|ization))" + \
   "\n"
)
