//   Copyright (C) 2020 by Kevin D. Woerner
//-/ =KDW= ########## DO NOT EDIT -- AUTOGENERATED CODE #########
//-/ =KDW= ############ BUILDER $KWROOT/0lib/vkkcp.sh ###########
//-/ =KDW= ##### SRC $KWROOT/codekdw/kw-lib/Kwelements.fwipp ####
// 2020-10-12 kdw  For Changelog, See File Kwelements.varylog
#ifndef INCLUDED_Kwelements_h
#define INCLUDED_Kwelements_h
double cxhydrogenz(void);
double cxhydrogen(void);
double cxhz(void);
double cxh_mass(void);
double cxhmass(void);
double cxh_density(void);
double cxh_melt(void);
double cxh_boil(void);
double cxh_cp(void);
double cxh_en(void);
double cxheliumz(void);
double cxhelium(void);
double cxhez(void);
double cxhe_mass(void);
double cxhemass(void);
double cxhe_density(void);
double cxhe_melt(void);
double cxhe_boil(void);
double cxhe_cp(void);
double cxhe_en(void);
double cxlithiumz(void);
double cxlithium(void);
double cxliz(void);
double cxli_mass(void);
double cxlimass(void);
double cxli_density(void);
double cxli_melt(void);
double cxli_boil(void);
double cxli_cp(void);
double cxli_en(void);
double cxberylliumz(void);
double cxberyllium(void);
double cxbez(void);
double cxbe_mass(void);
double cxbemass(void);
double cxbe_density(void);
double cxbe_melt(void);
double cxbe_boil(void);
double cxbe_cp(void);
double cxbe_en(void);
double cxboronz(void);
double cxboron(void);
double cxbz(void);
double cxb_mass(void);
double cxbmass(void);
double cxb_density(void);
double cxb_melt(void);
double cxb_boil(void);
double cxb_cp(void);
double cxb_en(void);
double cxcarbonz(void);
double cxcarbon(void);
double cxcz(void);
double cxc_mass(void);
double cxcmass(void);
double cxc_density(void);
double cxc_melt(void);
double cxc_boil(void);
double cxc_cp(void);
double cxc_en(void);
double cxnitrogenz(void);
double cxnitrogen(void);
double cxnz(void);
double cxn_mass(void);
double cxnmass(void);
double cxn_density(void);
double cxn_melt(void);
double cxn_boil(void);
double cxn_cp(void);
double cxn_en(void);
double cxoxygenz(void);
double cxoxygen(void);
double cxoz(void);
double cxo_mass(void);
double cxomass(void);
double cxo_density(void);
double cxo_melt(void);
double cxo_boil(void);
double cxo_cp(void);
double cxo_en(void);
double cxfluorinez(void);
double cxfluorine(void);
double cxfz(void);
double cxf_mass(void);
double cxfmass(void);
double cxf_density(void);
double cxf_melt(void);
double cxf_boil(void);
double cxf_cp(void);
double cxf_en(void);
double cxneonz(void);
double cxneon(void);
double cxnez(void);
double cxne_mass(void);
double cxnemass(void);
double cxne_density(void);
double cxne_melt(void);
double cxne_boil(void);
double cxne_cp(void);
double cxne_en(void);
double cxsodiumz(void);
double cxsodium(void);
double cxnaz(void);
double cxna_mass(void);
double cxnamass(void);
double cxna_density(void);
double cxna_melt(void);
double cxna_boil(void);
double cxna_cp(void);
double cxna_en(void);
double cxmagnesiumz(void);
double cxmagnesium(void);
double cxmgz(void);
double cxmg_mass(void);
double cxmgmass(void);
double cxmg_density(void);
double cxmg_melt(void);
double cxmg_boil(void);
double cxmg_cp(void);
double cxmg_en(void);
double cxaluminiumz(void);
double cxaluminium(void);
double cxalz(void);
double cxal_mass(void);
double cxalmass(void);
double cxal_density(void);
double cxal_melt(void);
double cxal_boil(void);
double cxal_cp(void);
double cxal_en(void);
double cxsiliconz(void);
double cxsilicon(void);
double cxsiz(void);
double cxsi_mass(void);
double cxsimass(void);
double cxsi_density(void);
double cxsi_melt(void);
double cxsi_boil(void);
double cxsi_cp(void);
double cxsi_en(void);
double cxphosphorusz(void);
double cxphosphorus(void);
double cxpz(void);
double cxp_mass(void);
double cxpmass(void);
double cxp_density(void);
double cxp_melt(void);
double cxp_boil(void);
double cxp_cp(void);
double cxp_en(void);
double cxsulfurz(void);
double cxsulfur(void);
double cxsz(void);
double cxs_mass(void);
double cxsmass(void);
double cxs_density(void);
double cxs_melt(void);
double cxs_boil(void);
double cxs_cp(void);
double cxs_en(void);
double cxchlorinez(void);
double cxchlorine(void);
double cxclz(void);
double cxcl_mass(void);
double cxclmass(void);
double cxcl_density(void);
double cxcl_melt(void);
double cxcl_boil(void);
double cxcl_cp(void);
double cxcl_en(void);
double cxargonz(void);
double cxargon(void);
double cxarz(void);
double cxar_mass(void);
double cxarmass(void);
double cxar_density(void);
double cxar_melt(void);
double cxar_boil(void);
double cxar_cp(void);
double cxar_en(void);
double cxpotassiumz(void);
double cxpotassium(void);
double cxkz(void);
double cxk_mass(void);
double cxkmass(void);
double cxk_density(void);
double cxk_melt(void);
double cxk_boil(void);
double cxk_cp(void);
double cxk_en(void);
double cxcalciumz(void);
double cxcalcium(void);
double cxcaz(void);
double cxca_mass(void);
double cxcamass(void);
double cxca_density(void);
double cxca_melt(void);
double cxca_boil(void);
double cxca_cp(void);
double cxca_en(void);
double cxscandiumz(void);
double cxscandium(void);
double cxscz(void);
double cxsc_mass(void);
double cxscmass(void);
double cxsc_density(void);
double cxsc_melt(void);
double cxsc_boil(void);
double cxsc_cp(void);
double cxsc_en(void);
double cxtitaniumz(void);
double cxtitanium(void);
double cxtiz(void);
double cxti_mass(void);
double cxtimass(void);
double cxti_density(void);
double cxti_melt(void);
double cxti_boil(void);
double cxti_cp(void);
double cxti_en(void);
double cxvanadiumz(void);
double cxvanadium(void);
double cxvz(void);
double cxv_mass(void);
double cxvmass(void);
double cxv_density(void);
double cxv_melt(void);
double cxv_boil(void);
double cxv_cp(void);
double cxv_en(void);
double cxchromiumz(void);
double cxchromium(void);
double cxcrz(void);
double cxcr_mass(void);
double cxcrmass(void);
double cxcr_density(void);
double cxcr_melt(void);
double cxcr_boil(void);
double cxcr_cp(void);
double cxcr_en(void);
double cxmanganesez(void);
double cxmanganese(void);
double cxmnz(void);
double cxmn_mass(void);
double cxmnmass(void);
double cxmn_density(void);
double cxmn_melt(void);
double cxmn_boil(void);
double cxmn_cp(void);
double cxmn_en(void);
double cxironz(void);
double cxiron(void);
double cxfez(void);
double cxfe_mass(void);
double cxfemass(void);
double cxfe_density(void);
double cxfe_melt(void);
double cxfe_boil(void);
double cxfe_cp(void);
double cxfe_en(void);
double cxcobaltz(void);
double cxcobalt(void);
double cxcoz(void);
double cxco_mass(void);
double cxcomass(void);
double cxco_density(void);
double cxco_melt(void);
double cxco_boil(void);
double cxco_cp(void);
double cxco_en(void);
double cxnickelz(void);
double cxnickel(void);
double cxniz(void);
double cxni_mass(void);
double cxnimass(void);
double cxni_density(void);
double cxni_melt(void);
double cxni_boil(void);
double cxni_cp(void);
double cxni_en(void);
double cxcopperz(void);
double cxcopper(void);
double cxcuz(void);
double cxcu_mass(void);
double cxcumass(void);
double cxcu_density(void);
double cxcu_melt(void);
double cxcu_boil(void);
double cxcu_cp(void);
double cxcu_en(void);
double cxzincz(void);
double cxzinc(void);
double cxznz(void);
double cxzn_mass(void);
double cxznmass(void);
double cxzn_density(void);
double cxzn_melt(void);
double cxzn_boil(void);
double cxzn_cp(void);
double cxzn_en(void);
double cxgalliumz(void);
double cxgallium(void);
double cxgaz(void);
double cxga_mass(void);
double cxgamass(void);
double cxga_density(void);
double cxga_melt(void);
double cxga_boil(void);
double cxga_cp(void);
double cxga_en(void);
double cxgermaniumz(void);
double cxgermanium(void);
double cxgez(void);
double cxge_mass(void);
double cxgemass(void);
double cxge_density(void);
double cxge_melt(void);
double cxge_boil(void);
double cxge_cp(void);
double cxge_en(void);
double cxarsenicz(void);
double cxarsenic(void);
double cxasz(void);
double cxas_mass(void);
double cxasmass(void);
double cxas_density(void);
double cxas_melt(void);
double cxas_boil(void);
double cxas_cp(void);
double cxas_en(void);
double cxseleniumz(void);
double cxselenium(void);
double cxsez(void);
double cxse_mass(void);
double cxsemass(void);
double cxse_density(void);
double cxse_melt(void);
double cxse_boil(void);
double cxse_cp(void);
double cxse_en(void);
double cxbrominez(void);
double cxbromine(void);
double cxbrz(void);
double cxbr_mass(void);
double cxbrmass(void);
double cxbr_density(void);
double cxbr_melt(void);
double cxbr_boil(void);
double cxbr_cp(void);
double cxbr_en(void);
double cxkryptonz(void);
double cxkrypton(void);
double cxkrz(void);
double cxkr_mass(void);
double cxkrmass(void);
double cxkr_density(void);
double cxkr_melt(void);
double cxkr_boil(void);
double cxkr_cp(void);
double cxkr_en(void);
double cxrubidiumz(void);
double cxrubidium(void);
double cxrbz(void);
double cxrb_mass(void);
double cxrbmass(void);
double cxrb_density(void);
double cxrb_melt(void);
double cxrb_boil(void);
double cxrb_cp(void);
double cxrb_en(void);
double cxstrontiumz(void);
double cxstrontium(void);
double cxsrz(void);
double cxsr_mass(void);
double cxsrmass(void);
double cxsr_density(void);
double cxsr_melt(void);
double cxsr_boil(void);
double cxsr_cp(void);
double cxsr_en(void);
double cxyttriumz(void);
double cxyttrium(void);
double cxyz(void);
double cxy_mass(void);
double cxymass(void);
double cxy_density(void);
double cxy_melt(void);
double cxy_boil(void);
double cxy_cp(void);
double cxy_en(void);
double cxzirconiumz(void);
double cxzirconium(void);
double cxzrz(void);
double cxzr_mass(void);
double cxzrmass(void);
double cxzr_density(void);
double cxzr_melt(void);
double cxzr_boil(void);
double cxzr_cp(void);
double cxzr_en(void);
double cxniobiumz(void);
double cxniobium(void);
double cxnbz(void);
double cxnb_mass(void);
double cxnbmass(void);
double cxnb_density(void);
double cxnb_melt(void);
double cxnb_boil(void);
double cxnb_cp(void);
double cxnb_en(void);
double cxmolybdenumz(void);
double cxmolybdenum(void);
double cxmoz(void);
double cxmo_mass(void);
double cxmomass(void);
double cxmo_density(void);
double cxmo_melt(void);
double cxmo_boil(void);
double cxmo_cp(void);
double cxmo_en(void);
double cxtechnetiumz(void);
double cxtechnetium(void);
double cxtcz(void);
double cxtc_mass(void);
double cxtcmass(void);
double cxtc_density(void);
double cxtc_melt(void);
double cxtc_boil(void);
double cxtc_cp(void);
double cxtc_en(void);
double cxrutheniumz(void);
double cxruthenium(void);
double cxruz(void);
double cxru_mass(void);
double cxrumass(void);
double cxru_density(void);
double cxru_melt(void);
double cxru_boil(void);
double cxru_cp(void);
double cxru_en(void);
double cxrhodiumz(void);
double cxrhodium(void);
double cxrhz(void);
double cxrh_mass(void);
double cxrhmass(void);
double cxrh_density(void);
double cxrh_melt(void);
double cxrh_boil(void);
double cxrh_cp(void);
double cxrh_en(void);
double cxpalladiumz(void);
double cxpalladium(void);
double cxpdz(void);
double cxpd_mass(void);
double cxpdmass(void);
double cxpd_density(void);
double cxpd_melt(void);
double cxpd_boil(void);
double cxpd_cp(void);
double cxpd_en(void);
double cxsilverz(void);
double cxsilver(void);
double cxagz(void);
double cxag_mass(void);
double cxagmass(void);
double cxag_density(void);
double cxag_melt(void);
double cxag_boil(void);
double cxag_cp(void);
double cxag_en(void);
double cxcadmiumz(void);
double cxcadmium(void);
double cxcdz(void);
double cxcd_mass(void);
double cxcdmass(void);
double cxcd_density(void);
double cxcd_melt(void);
double cxcd_boil(void);
double cxcd_cp(void);
double cxcd_en(void);
double cxindiumz(void);
double cxindium(void);
double cxinz(void);
double cxin_mass(void);
double cxinmass(void);
double cxin_density(void);
double cxin_melt(void);
double cxin_boil(void);
double cxin_cp(void);
double cxin_en(void);
double cxtinz(void);
double cxtin(void);
double cxsnz(void);
double cxsn_mass(void);
double cxsnmass(void);
double cxsn_density(void);
double cxsn_melt(void);
double cxsn_boil(void);
double cxsn_cp(void);
double cxsn_en(void);
double cxantimonyz(void);
double cxantimony(void);
double cxsbz(void);
double cxsb_mass(void);
double cxsbmass(void);
double cxsb_density(void);
double cxsb_melt(void);
double cxsb_boil(void);
double cxsb_cp(void);
double cxsb_en(void);
double cxtelluriumz(void);
double cxtellurium(void);
double cxtez(void);
double cxte_mass(void);
double cxtemass(void);
double cxte_density(void);
double cxte_melt(void);
double cxte_boil(void);
double cxte_cp(void);
double cxte_en(void);
double cxiodinez(void);
double cxiodine(void);
double cxiz(void);
double cxi_mass(void);
double cximass(void);
double cxi_density(void);
double cxi_melt(void);
double cxi_boil(void);
double cxi_cp(void);
double cxi_en(void);
double cxxenonz(void);
double cxxenon(void);
double cxxez(void);
double cxxe_mass(void);
double cxxemass(void);
double cxxe_density(void);
double cxxe_melt(void);
double cxxe_boil(void);
double cxxe_cp(void);
double cxxe_en(void);
double cxcaesiumz(void);
double cxcaesium(void);
double cxcsz(void);
double cxcs_mass(void);
double cxcsmass(void);
double cxcs_density(void);
double cxcs_melt(void);
double cxcs_boil(void);
double cxcs_cp(void);
double cxcs_en(void);
double cxbariumz(void);
double cxbarium(void);
double cxbaz(void);
double cxba_mass(void);
double cxbamass(void);
double cxba_density(void);
double cxba_melt(void);
double cxba_boil(void);
double cxba_cp(void);
double cxba_en(void);
double cxlanthanumz(void);
double cxlanthanum(void);
double cxlaz(void);
double cxla_mass(void);
double cxlamass(void);
double cxla_density(void);
double cxla_melt(void);
double cxla_boil(void);
double cxla_cp(void);
double cxla_en(void);
double cxceriumz(void);
double cxcerium(void);
double cxcez(void);
double cxce_mass(void);
double cxcemass(void);
double cxce_density(void);
double cxce_melt(void);
double cxce_boil(void);
double cxce_cp(void);
double cxce_en(void);
double cxpraseodymiumz(void);
double cxpraseodymium(void);
double cxprz(void);
double cxpr_mass(void);
double cxprmass(void);
double cxpr_density(void);
double cxpr_melt(void);
double cxpr_boil(void);
double cxpr_cp(void);
double cxpr_en(void);
double cxneodymiumz(void);
double cxneodymium(void);
double cxndz(void);
double cxnd_mass(void);
double cxndmass(void);
double cxnd_density(void);
double cxnd_melt(void);
double cxnd_boil(void);
double cxnd_cp(void);
double cxnd_en(void);
double cxpromethiumz(void);
double cxpromethium(void);
double cxpmz(void);
double cxpm_mass(void);
double cxpmmass(void);
double cxpm_density(void);
double cxpm_melt(void);
double cxpm_boil(void);
double cxpm_cp(void);
double cxpm_en(void);
double cxsamariumz(void);
double cxsamarium(void);
double cxsmz(void);
double cxsm_mass(void);
double cxsmmass(void);
double cxsm_density(void);
double cxsm_melt(void);
double cxsm_boil(void);
double cxsm_cp(void);
double cxsm_en(void);
double cxeuropiumz(void);
double cxeuropium(void);
double cxeuz(void);
double cxeu_mass(void);
double cxeumass(void);
double cxeu_density(void);
double cxeu_melt(void);
double cxeu_boil(void);
double cxeu_cp(void);
double cxeu_en(void);
double cxgadoliniumz(void);
double cxgadolinium(void);
double cxgdz(void);
double cxgd_mass(void);
double cxgdmass(void);
double cxgd_density(void);
double cxgd_melt(void);
double cxgd_boil(void);
double cxgd_cp(void);
double cxgd_en(void);
double cxterbiumz(void);
double cxterbium(void);
double cxtbz(void);
double cxtb_mass(void);
double cxtbmass(void);
double cxtb_density(void);
double cxtb_melt(void);
double cxtb_boil(void);
double cxtb_cp(void);
double cxtb_en(void);
double cxdysprosiumz(void);
double cxdysprosium(void);
double cxdyz(void);
double cxdy_mass(void);
double cxdymass(void);
double cxdy_density(void);
double cxdy_melt(void);
double cxdy_boil(void);
double cxdy_cp(void);
double cxdy_en(void);
double cxholmiumz(void);
double cxholmium(void);
double cxhoz(void);
double cxho_mass(void);
double cxhomass(void);
double cxho_density(void);
double cxho_melt(void);
double cxho_boil(void);
double cxho_cp(void);
double cxho_en(void);
double cxerbiumz(void);
double cxerbium(void);
double cxerz(void);
double cxer_mass(void);
double cxermass(void);
double cxer_density(void);
double cxer_melt(void);
double cxer_boil(void);
double cxer_cp(void);
double cxer_en(void);
double cxthuliumz(void);
double cxthulium(void);
double cxtmz(void);
double cxtm_mass(void);
double cxtmmass(void);
double cxtm_density(void);
double cxtm_melt(void);
double cxtm_boil(void);
double cxtm_cp(void);
double cxtm_en(void);
double cxytterbiumz(void);
double cxytterbium(void);
double cxybz(void);
double cxyb_mass(void);
double cxybmass(void);
double cxyb_density(void);
double cxyb_melt(void);
double cxyb_boil(void);
double cxyb_cp(void);
double cxyb_en(void);
double cxlutetiumz(void);
double cxlutetium(void);
double cxluz(void);
double cxlu_mass(void);
double cxlumass(void);
double cxlu_density(void);
double cxlu_melt(void);
double cxlu_boil(void);
double cxlu_cp(void);
double cxlu_en(void);
double cxhafniumz(void);
double cxhafnium(void);
double cxhfz(void);
double cxhf_mass(void);
double cxhfmass(void);
double cxhf_density(void);
double cxhf_melt(void);
double cxhf_boil(void);
double cxhf_cp(void);
double cxhf_en(void);
double cxtantalumz(void);
double cxtantalum(void);
double cxtaz(void);
double cxta_mass(void);
double cxtamass(void);
double cxta_density(void);
double cxta_melt(void);
double cxta_boil(void);
double cxta_cp(void);
double cxta_en(void);
double cxtungstenz(void);
double cxtungsten(void);
double cxwz(void);
double cxw_mass(void);
double cxwmass(void);
double cxw_density(void);
double cxw_melt(void);
double cxw_boil(void);
double cxw_cp(void);
double cxw_en(void);
double cxrheniumz(void);
double cxrhenium(void);
double cxrez(void);
double cxre_mass(void);
double cxremass(void);
double cxre_density(void);
double cxre_melt(void);
double cxre_boil(void);
double cxre_cp(void);
double cxre_en(void);
double cxosmiumz(void);
double cxosmium(void);
double cxosz(void);
double cxos_mass(void);
double cxosmass(void);
double cxos_density(void);
double cxos_melt(void);
double cxos_boil(void);
double cxos_cp(void);
double cxos_en(void);
double cxiridiumz(void);
double cxiridium(void);
double cxirz(void);
double cxir_mass(void);
double cxirmass(void);
double cxir_density(void);
double cxir_melt(void);
double cxir_boil(void);
double cxir_cp(void);
double cxir_en(void);
double cxplatinumz(void);
double cxplatinum(void);
double cxptz(void);
double cxpt_mass(void);
double cxptmass(void);
double cxpt_density(void);
double cxpt_melt(void);
double cxpt_boil(void);
double cxpt_cp(void);
double cxpt_en(void);
double cxgoldz(void);
double cxgold(void);
double cxauz(void);
double cxau_mass(void);
double cxaumass(void);
double cxau_density(void);
double cxau_melt(void);
double cxau_boil(void);
double cxau_cp(void);
double cxau_en(void);
double cxmercuryz(void);
double cxmercury(void);
double cxhgz(void);
double cxhg_mass(void);
double cxhgmass(void);
double cxhg_density(void);
double cxhg_melt(void);
double cxhg_boil(void);
double cxhg_cp(void);
double cxhg_en(void);
double cxthalliumz(void);
double cxthallium(void);
double cxtlz(void);
double cxtl_mass(void);
double cxtlmass(void);
double cxtl_density(void);
double cxtl_melt(void);
double cxtl_boil(void);
double cxtl_cp(void);
double cxtl_en(void);
double cxleadz(void);
double cxlead(void);
double cxpbz(void);
double cxpb_mass(void);
double cxpbmass(void);
double cxpb_density(void);
double cxpb_melt(void);
double cxpb_boil(void);
double cxpb_cp(void);
double cxpb_en(void);
double cxbismuthz(void);
double cxbismuth(void);
double cxbiz(void);
double cxbi_mass(void);
double cxbimass(void);
double cxbi_density(void);
double cxbi_melt(void);
double cxbi_boil(void);
double cxbi_cp(void);
double cxbi_en(void);
double cxpoloniumz(void);
double cxpolonium(void);
double cxpoz(void);
double cxpo_mass(void);
double cxpomass(void);
double cxpo_density(void);
double cxpo_melt(void);
double cxpo_boil(void);
double cxpo_cp(void);
double cxpo_en(void);
double cxastatinez(void);
double cxastatine(void);
double cxatz(void);
double cxat_mass(void);
double cxatmass(void);
double cxat_density(void);
double cxat_melt(void);
double cxat_boil(void);
double cxat_cp(void);
double cxat_en(void);
double cxradonz(void);
double cxradon(void);
double cxrnz(void);
double cxrn_mass(void);
double cxrnmass(void);
double cxrn_density(void);
double cxrn_melt(void);
double cxrn_boil(void);
double cxrn_cp(void);
double cxrn_en(void);
double cxfranciumz(void);
double cxfrancium(void);
double cxfrz(void);
double cxfr_mass(void);
double cxfrmass(void);
double cxfr_density(void);
double cxfr_melt(void);
double cxfr_boil(void);
double cxfr_cp(void);
double cxfr_en(void);
double cxradiumz(void);
double cxradium(void);
double cxraz(void);
double cxra_mass(void);
double cxramass(void);
double cxra_density(void);
double cxra_melt(void);
double cxra_boil(void);
double cxra_cp(void);
double cxra_en(void);
double cxactiniumz(void);
double cxactinium(void);
double cxacz(void);
double cxac_mass(void);
double cxacmass(void);
double cxac_density(void);
double cxac_melt(void);
double cxac_boil(void);
double cxac_cp(void);
double cxac_en(void);
double cxthoriumz(void);
double cxthorium(void);
double cxthz(void);
double cxth_mass(void);
double cxthmass(void);
double cxth_density(void);
double cxth_melt(void);
double cxth_boil(void);
double cxth_cp(void);
double cxth_en(void);
double cxprotactiniumz(void);
double cxprotactinium(void);
double cxpaz(void);
double cxpa_mass(void);
double cxpamass(void);
double cxpa_density(void);
double cxpa_melt(void);
double cxpa_boil(void);
double cxpa_cp(void);
double cxpa_en(void);
double cxuraniumz(void);
double cxuranium(void);
double cxuz(void);
double cxu_mass(void);
double cxumass(void);
double cxu_density(void);
double cxu_melt(void);
double cxu_boil(void);
double cxu_cp(void);
double cxu_en(void);
double cxneptuniumz(void);
double cxneptunium(void);
double cxnpz(void);
double cxnp_mass(void);
double cxnpmass(void);
double cxnp_density(void);
double cxnp_melt(void);
double cxnp_boil(void);
double cxnp_cp(void);
double cxnp_en(void);
double cxplutoniumz(void);
double cxplutonium(void);
double cxpuz(void);
double cxpu_mass(void);
double cxpumass(void);
double cxpu_density(void);
double cxpu_melt(void);
double cxpu_boil(void);
double cxpu_cp(void);
double cxpu_en(void);
double cxamericiumz(void);
double cxamericium(void);
double cxamz(void);
double cxam_mass(void);
double cxammass(void);
double cxam_density(void);
double cxam_melt(void);
double cxam_boil(void);
double cxam_cp(void);
double cxam_en(void);
double cxcuriumz(void);
double cxcurium(void);
double cxcmz(void);
double cxcm_mass(void);
double cxcmmass(void);
double cxcm_density(void);
double cxcm_melt(void);
double cxcm_boil(void);
double cxcm_cp(void);
double cxcm_en(void);
double cxberkeliumz(void);
double cxberkelium(void);
double cxbkz(void);
double cxbk_mass(void);
double cxbkmass(void);
double cxbk_density(void);
double cxbk_melt(void);
double cxbk_boil(void);
double cxbk_cp(void);
double cxbk_en(void);
double cxcaliforniumz(void);
double cxcalifornium(void);
double cxcfz(void);
double cxcf_mass(void);
double cxcfmass(void);
double cxcf_density(void);
double cxcf_melt(void);
double cxcf_boil(void);
double cxcf_cp(void);
double cxcf_en(void);
double cxeinsteiniumz(void);
double cxeinsteinium(void);
double cxesz(void);
double cxes_mass(void);
double cxesmass(void);
double cxes_density(void);
double cxes_melt(void);
double cxes_boil(void);
double cxes_cp(void);
double cxes_en(void);
double cxfermiumz(void);
double cxfermium(void);
double cxfmz(void);
double cxfm_mass(void);
double cxfmmass(void);
double cxfm_density(void);
double cxfm_melt(void);
double cxfm_boil(void);
double cxfm_cp(void);
double cxfm_en(void);
double cxmendeleviumz(void);
double cxmendelevium(void);
double cxmdz(void);
double cxmd_mass(void);
double cxmdmass(void);
double cxmd_density(void);
double cxmd_melt(void);
double cxmd_boil(void);
double cxmd_cp(void);
double cxmd_en(void);
double cxnobeliumz(void);
double cxnobelium(void);
double cxnoz(void);
double cxno_mass(void);
double cxnomass(void);
double cxno_density(void);
double cxno_melt(void);
double cxno_boil(void);
double cxno_cp(void);
double cxno_en(void);
double cxlawrenciumz(void);
double cxlawrencium(void);
double cxlrz(void);
double cxlr_mass(void);
double cxlrmass(void);
double cxlr_density(void);
double cxlr_melt(void);
double cxlr_boil(void);
double cxlr_cp(void);
double cxlr_en(void);
double cxrutherfordiumz(void);
double cxrutherfordium(void);
double cxrfz(void);
double cxrf_mass(void);
double cxrfmass(void);
double cxrf_density(void);
double cxrf_melt(void);
double cxrf_boil(void);
double cxrf_cp(void);
double cxrf_en(void);
double cxdubniumz(void);
double cxdubnium(void);
double cxdbz(void);
double cxdb_mass(void);
double cxdbmass(void);
double cxdb_density(void);
double cxdb_melt(void);
double cxdb_boil(void);
double cxdb_cp(void);
double cxdb_en(void);
double cxseaborgiumz(void);
double cxseaborgium(void);
double cxsgz(void);
double cxsg_mass(void);
double cxsgmass(void);
double cxsg_density(void);
double cxsg_melt(void);
double cxsg_boil(void);
double cxsg_cp(void);
double cxsg_en(void);
double cxbohriumz(void);
double cxbohrium(void);
double cxbhz(void);
double cxbh_mass(void);
double cxbhmass(void);
double cxbh_density(void);
double cxbh_melt(void);
double cxbh_boil(void);
double cxbh_cp(void);
double cxbh_en(void);
double cxhassiumz(void);
double cxhassium(void);
double cxhsz(void);
double cxhs_mass(void);
double cxhsmass(void);
double cxhs_density(void);
double cxhs_melt(void);
double cxhs_boil(void);
double cxhs_cp(void);
double cxhs_en(void);
double cxmeitneriumz(void);
double cxmeitnerium(void);
double cxmtz(void);
double cxmt_mass(void);
double cxmtmass(void);
double cxmt_density(void);
double cxmt_melt(void);
double cxmt_boil(void);
double cxmt_cp(void);
double cxmt_en(void);
double cxdarmstadtiumz(void);
double cxdarmstadtium(void);
double cxdsz(void);
double cxds_mass(void);
double cxdsmass(void);
double cxds_density(void);
double cxds_melt(void);
double cxds_boil(void);
double cxds_cp(void);
double cxds_en(void);
double cxroentgeniumz(void);
double cxroentgenium(void);
double cxrgz(void);
double cxrg_mass(void);
double cxrgmass(void);
double cxrg_density(void);
double cxrg_melt(void);
double cxrg_boil(void);
double cxrg_cp(void);
double cxrg_en(void);
double cxcoperniciumz(void);
double cxcopernicium(void);
double cxcnz(void);
double cxcn_mass(void);
double cxcnmass(void);
double cxcn_density(void);
double cxcn_melt(void);
double cxcn_boil(void);
double cxcn_cp(void);
double cxcn_en(void);
double cxnihoniumz(void);
double cxnihonium(void);
double cxnhz(void);
double cxnh_mass(void);
double cxnhmass(void);
double cxnh_density(void);
double cxnh_melt(void);
double cxnh_boil(void);
double cxnh_cp(void);
double cxnh_en(void);
double cxfleroviumz(void);
double cxflerovium(void);
double cxflz(void);
double cxfl_mass(void);
double cxflmass(void);
double cxfl_density(void);
double cxfl_melt(void);
double cxfl_boil(void);
double cxfl_cp(void);
double cxfl_en(void);
double cxmoscoviumz(void);
double cxmoscovium(void);
double cxmcz(void);
double cxmc_mass(void);
double cxmcmass(void);
double cxmc_density(void);
double cxmc_melt(void);
double cxmc_boil(void);
double cxmc_cp(void);
double cxmc_en(void);
double cxlivermoriumz(void);
double cxlivermorium(void);
double cxlvz(void);
double cxlv_mass(void);
double cxlvmass(void);
double cxlv_density(void);
double cxlv_melt(void);
double cxlv_boil(void);
double cxlv_cp(void);
double cxlv_en(void);
double cxtennessinez(void);
double cxtennessine(void);
double cxtsz(void);
double cxts_mass(void);
double cxtsmass(void);
double cxts_density(void);
double cxts_melt(void);
double cxts_boil(void);
double cxts_cp(void);
double cxts_en(void);
double cxoganessonz(void);
double cxoganesson(void);
double cxogz(void);
double cxog_mass(void);
double cxogmass(void);
double cxog_density(void);
double cxog_melt(void);
double cxog_boil(void);
double cxog_cp(void);
double cxog_en(void);
double cxair_mass(void);
double cxairmass(void);
double cxwater_mass(void);
double cxwatermass(void);
double cxwater_cp(void);
double cxice_cp(void);
double cxsteam_cp(void);
double cxh1_mass(void);
double cxh1mass(void);
double cxh2_mass(void);
double cxh2mass(void);
double cxh3_mass(void);
double cxh3mass(void);
double cxhe3_mass(void);
double cxhe3mass(void);
double cxhe4_mass(void);
double cxhe4mass(void);
double cxc12_mass(void);
double cxc12mass(void);
double cxc13_mass(void);
double cxc13mass(void);
double cxc14_mass(void);
double cxc14mass(void);
double cxo16_mass(void);
double cxo16mass(void);
double cxo17_mass(void);
double cxo17mass(void);
double cxo18_mass(void);
double cxo18mass(void);
double cxc13_ratio(void);
double cxc14_ratio(void);
double cxc12_ratio(void);
double cxc_mean_mass(void);
double cxvsmow_h3_ratio(void);
double cxvsmow_h2_ratio(void);
double cxvsmow_h1_ratio(void);
double cxvsmow_h_mass(void);
double cxvsmow_o18_ratio(void);
double cxvsmow_o17_ratio(void);
double cxvsmow_o16_ratio(void);
double cxvsmow_o_mass(void);
double cxvsmow_mass(void);
double cxwater_fusion_jpmole(void);
double cxwater_fusion_jpkg(void);
double cxwater_vaporization_jpmole(void);
double cxwater_vaporization_jpkg(void);
double cxch4_mass(void);
double cxch4mass(void);
double cxc2h6_mass(void);
double cxc2h6mass(void);
double cxc3h8_mass(void);
double cxc3h8mass(void);
double cxc4h10_mass(void);
double cxc4h10mass(void);
double cxc2h60_mass(void);
double cxc2h60mass(void);
double cxch3ch2oh_mass(void);
double cxch3ch2ohmass(void);
double cxc12h22o11_mass(void);
double cxc12h22o11mass(void);
double cxsugar_mass(void);
double cxsugarmass(void);
double cxsugar_jpmole(void);
double cxsugar_jpkg(void);
double cxsugar_jpkgtotal(void);
double cxsugardensity(void);
double cxsugar_jpl(void);
double cxcoal_mass(void);
double cxcoalmass(void);
double cxcoal_jpmole(void);
double cxcoal_jpkg(void);
double cxcoal_jpkgtotal(void);
double cxcoaldensity(void);
double cxcoal_jpl(void);
double cxparaffin_mass(void);
double cxparaffinmass(void);
double cxparaffin_jpmole(void);
double cxparaffin_jpkg(void);
double cxparaffin_jpkgtotal(void);
double cxparaffindensity(void);
double cxparaffin_jpl(void);
double cxfat_mass(void);
double cxfatmass(void);
double cxfat_jpmole(void);
double cxfat_jpkg(void);
double cxfat_jpkgtotal(void);
double cxfatdensity(void);
double cxfat_jpl(void);
double cxdiesel_mass(void);
double cxdieselmass(void);
double cxdiesel_jpmole(void);
double cxdiesel_jpkg(void);
double cxdiesel_jpkgtotal(void);
double cxdieseldensity(void);
double cxdiesel_jpl(void);
double cxgasoline_mass(void);
double cxgasolinemass(void);
double cxgasoline_jpmole(void);
double cxgasoline_jpkg(void);
double cxgasoline_jpkgtotal(void);
double cxgasolinedensity(void);
double cxgasoline_jpl(void);
double cxkerosene_mass(void);
double cxkerosenemass(void);
double cxkerosene_jpmole(void);
double cxkerosene_jpkg(void);
double cxkerosene_jpkgtotal(void);
double cxkerosenedensity(void);
double cxkerosene_jpl(void);
double cxhydrogen_mass(void);
double cxhydrogenmass(void);
double cxhydrogen_jpmole(void);
double cxhydrogen_jpkg(void);
double cxhydrogen_jpkgtotal(void);
double cxmethane_mass(void);
double cxmethanemass(void);
double cxmethane_jpmole(void);
double cxmethane_jpkg(void);
double cxmethane_jpkgtotal(void);
double cxethane_mass(void);
double cxethanemass(void);
double cxethane_jpmole(void);
double cxethane_jpkg(void);
double cxethane_jpkgtotal(void);
double cxpropane_mass(void);
double cxpropanemass(void);
double cxpropane_jpmole(void);
double cxpropane_jpkg(void);
double cxpropane_jpkgtotal(void);
double cxbutane_mass(void);
double cxbutanemass(void);
double cxbutane_jpmole(void);
double cxbutane_jpkg(void);
double cxbutane_jpkgtotal(void);
double cxpentane_mass(void);
double cxpentanemass(void);
double cxpentane_jpmole(void);
double cxpentane_jpkg(void);
double cxpentane_jpkgtotal(void);
double cxhexane_mass(void);
double cxhexanemass(void);
double cxhexane_jpmole(void);
double cxhexane_jpkg(void);
double cxhexane_jpkgtotal(void);
double cxethanol_mass(void);
double cxethanolmass(void);
double cxethanol_jpmole(void);
double cxethanol_jpkg(void);
double cxethanol_jpkgtotal(void);
double cxsucrose_mass(void);
double cxsucrosemass(void);
double cxsucrose_jpmole(void);
double cxsucrose_jpkg(void);
double cxsucrose_jpkgtotal(void);
double cxtntjpkg(void);
#include "Kw.h"
#define HYDROGENZ 1
#define HYDROGEN (1.008)
#define HZ 1
#define H_MASS (1.008 * MOLARMASS)
#define HMASS (H_MASS / AVOGADRO)
#define H_DENSITY (0.08988 * DENSITY)
#define H_MELT (14.01 * KELVIN)
#define H_BOIL (20.28 * KELVIN)
#define H_Cp (14304 * SPECIFICHEAT)
#define H_En (2.20)
#define HELIUMZ 2
#define HELIUM (4.002602)
#define HeZ 2
#define He_MASS (4.002602 * MOLARMASS)
#define HeMASS (He_MASS / AVOGADRO)
#define He_DENSITY (0.1785 * DENSITY)
#define He_MELT (- 1 * KELVIN)
#define He_BOIL (4.22 * KELVIN)
#define He_Cp (5193 * SPECIFICHEAT)
#define He_En (- 1)
#define LITHIUMZ 3
#define LITHIUM (6.94)
#define LiZ 3
#define Li_MASS (6.94 * MOLARMASS)
#define LiMASS (Li_MASS / AVOGADRO)
#define Li_DENSITY (534 * DENSITY)
#define Li_MELT (453.69 * KELVIN)
#define Li_BOIL (1560 * KELVIN)
#define Li_Cp (3582 * SPECIFICHEAT)
#define Li_En (0.98)
#define BERYLLIUMZ 4
#define BERYLLIUM (9.0121831)
#define BeZ 4
#define Be_MASS (9.0121831 * MOLARMASS)
#define BeMASS (Be_MASS / AVOGADRO)
#define Be_DENSITY (1850 * DENSITY)
#define Be_MELT (1560 * KELVIN)
#define Be_BOIL (2742 * KELVIN)
#define Be_Cp (1825 * SPECIFICHEAT)
#define Be_En (1.57)
#define BORONZ 5
#define BORON (10.81)
#define BZ 5
#define B_MASS (10.81 * MOLARMASS)
#define BMASS (B_MASS / AVOGADRO)
#define B_DENSITY (2340 * DENSITY)
#define B_MELT (2349 * KELVIN)
#define B_BOIL (4200 * KELVIN)
#define B_Cp (1026 * SPECIFICHEAT)
#define B_En (2.04)
#define CARBONZ 6
#define CARBON (12.011)
#define CZ 6
#define C_MASS (12.011 * MOLARMASS)
#define CMASS (C_MASS / AVOGADRO)
#define C_DENSITY (2267 * DENSITY)
#define C_MELT (3800 * KELVIN)
#define C_BOIL (4300 * KELVIN)
#define C_Cp (709 * SPECIFICHEAT)
#define C_En (2.55)
#define NITROGENZ 7
#define NITROGEN (14.007)
#define NZ 7
#define N_MASS (14.007 * MOLARMASS)
#define NMASS (N_MASS / AVOGADRO)
#define N_DENSITY (1.2506 * DENSITY)
#define N_MELT (63.15 * KELVIN)
#define N_BOIL (77.36 * KELVIN)
#define N_Cp (1040 * SPECIFICHEAT)
#define N_En (3.04)
#define OXYGENZ 8
#define OXYGEN (15.999)
#define OZ 8
#define O_MASS (15.999 * MOLARMASS)
#define OMASS (O_MASS / AVOGADRO)
#define O_DENSITY (1.429 * DENSITY)
#define O_MELT (54.36 * KELVIN)
#define O_BOIL (90.20 * KELVIN)
#define O_Cp (918 * SPECIFICHEAT)
#define O_En (3.44)
#define FLUORINEZ 9
#define FLUORINE (18.998403163)
#define FZ 9
#define F_MASS (18.998403163 * MOLARMASS)
#define FMASS (F_MASS / AVOGADRO)
#define F_DENSITY (1.696 * DENSITY)
#define F_MELT (53.53 * KELVIN)
#define F_BOIL (85.03 * KELVIN)
#define F_Cp (824 * SPECIFICHEAT)
#define F_En (3.98)
#define NEONZ 10
#define NEON (20.1797)
#define NeZ 10
#define Ne_MASS (20.1797 * MOLARMASS)
#define NeMASS (Ne_MASS / AVOGADRO)
#define Ne_DENSITY (0.8999 * DENSITY)
#define Ne_MELT (24.56 * KELVIN)
#define Ne_BOIL (27.07 * KELVIN)
#define Ne_Cp (1030 * SPECIFICHEAT)
#define Ne_En (- 1)
#define SODIUMZ 11
#define SODIUM (22.98976928)
#define NaZ 11
#define Na_MASS (22.98976928 * MOLARMASS)
#define NaMASS (Na_MASS / AVOGADRO)
#define Na_DENSITY (971 * DENSITY)
#define Na_MELT (370.87 * KELVIN)
#define Na_BOIL (1156 * KELVIN)
#define Na_Cp (1228 * SPECIFICHEAT)
#define Na_En (0.93)
#define MAGNESIUMZ 12
#define MAGNESIUM (24.305)
#define MgZ 12
#define Mg_MASS (24.305 * MOLARMASS)
#define MgMASS (Mg_MASS / AVOGADRO)
#define Mg_DENSITY (1738 * DENSITY)
#define Mg_MELT (923 * KELVIN)
#define Mg_BOIL (1363 * KELVIN)
#define Mg_Cp (1023 * SPECIFICHEAT)
#define Mg_En (1.31)
#define ALUMINIUMZ 13
#define ALUMINIUM (26.9815384)
#define AlZ 13
#define Al_MASS (26.9815384 * MOLARMASS)
#define AlMASS (Al_MASS / AVOGADRO)
#define Al_DENSITY (2698 * DENSITY)
#define Al_MELT (933.47 * KELVIN)
#define Al_BOIL (2792 * KELVIN)
#define Al_Cp (897 * SPECIFICHEAT)
#define Al_En (1.61)
#define SILICONZ 14
#define SILICON (28.085)
#define SiZ 14
#define Si_MASS (28.085 * MOLARMASS)
#define SiMASS (Si_MASS / AVOGADRO)
#define Si_DENSITY (2329.6 * DENSITY)
#define Si_MELT (1687 * KELVIN)
#define Si_BOIL (3538 * KELVIN)
#define Si_Cp (705 * SPECIFICHEAT)
#define Si_En (1.9)
#define PHOSPHORUSZ 15
#define PHOSPHORUS (30.973761998)
#define PZ 15
#define P_MASS (30.973761998 * MOLARMASS)
#define PMASS (P_MASS / AVOGADRO)
#define P_DENSITY (1820 * DENSITY)
#define P_MELT (317.30 * KELVIN)
#define P_BOIL (550 * KELVIN)
#define P_Cp (769 * SPECIFICHEAT)
#define P_En (2.19)
#define SULFURZ 16
#define SULFUR (32.06)
#define SZ 16
#define S_MASS (32.06 * MOLARMASS)
#define SMASS (S_MASS / AVOGADRO)
#define S_DENSITY (2067 * DENSITY)
#define S_MELT (388.36 * KELVIN)
#define S_BOIL (717.87 * KELVIN)
#define S_Cp (710 * SPECIFICHEAT)
#define S_En (2.58)
#define CHLORINEZ 17
#define CHLORINE (35.45)
#define ClZ 17
#define Cl_MASS (35.45 * MOLARMASS)
#define ClMASS (Cl_MASS / AVOGADRO)
#define Cl_DENSITY (3.214 * DENSITY)
#define Cl_MELT (171.6 * KELVIN)
#define Cl_BOIL (239.11 * KELVIN)
#define Cl_Cp (479 * SPECIFICHEAT)
#define Cl_En (3.16)
#define ARGONZ 18
#define ARGON (39.948)
#define ArZ 18
#define Ar_MASS (39.948 * MOLARMASS)
#define ArMASS (Ar_MASS / AVOGADRO)
#define Ar_DENSITY (1.7837 * DENSITY)
#define Ar_MELT (83.80 * KELVIN)
#define Ar_BOIL (87.30 * KELVIN)
#define Ar_Cp (520 * SPECIFICHEAT)
#define Ar_En (- 1)
#define POTASSIUMZ 19
#define POTASSIUM (39.0983)
#define KZ 19
#define K_MASS (39.0983 * MOLARMASS)
#define KMASS (K_MASS / AVOGADRO)
#define K_DENSITY (862 * DENSITY)
#define K_MELT (336.53 * KELVIN)
#define K_BOIL (1032 * KELVIN)
#define K_Cp (757 * SPECIFICHEAT)
#define K_En (0.82)
#define CALCIUMZ 20
#define CALCIUM (40.078)
#define CaZ 20
#define Ca_MASS (40.078 * MOLARMASS)
#define CaMASS (Ca_MASS / AVOGADRO)
#define Ca_DENSITY (1540 * DENSITY)
#define Ca_MELT (1115 * KELVIN)
#define Ca_BOIL (1757 * KELVIN)
#define Ca_Cp (647 * SPECIFICHEAT)
#define Ca_En 1
#define SCANDIUMZ 21
#define SCANDIUM (44.955908)
#define ScZ 21
#define Sc_MASS (44.955908 * MOLARMASS)
#define ScMASS (Sc_MASS / AVOGADRO)
#define Sc_DENSITY (2989 * DENSITY)
#define Sc_MELT (1814 * KELVIN)
#define Sc_BOIL (3109 * KELVIN)
#define Sc_Cp (568 * SPECIFICHEAT)
#define Sc_En (1.36)
#define TITANIUMZ 22
#define TITANIUM (47.867)
#define TiZ 22
#define Ti_MASS (47.867 * MOLARMASS)
#define TiMASS (Ti_MASS / AVOGADRO)
#define Ti_DENSITY (4540 * DENSITY)
#define Ti_MELT (1941 * KELVIN)
#define Ti_BOIL (3560 * KELVIN)
#define Ti_Cp (523 * SPECIFICHEAT)
#define Ti_En (1.54)
#define VANADIUMZ 23
#define VANADIUM (50.9415)
#define VZ 23
#define V_MASS (50.9415 * MOLARMASS)
#define VMASS (V_MASS / AVOGADRO)
#define V_DENSITY (6110 * DENSITY)
#define V_MELT (2183 * KELVIN)
#define V_BOIL (3680 * KELVIN)
#define V_Cp (489 * SPECIFICHEAT)
#define V_En (1.63)
#define CHROMIUMZ 24
#define CHROMIUM (51.9961)
#define CrZ 24
#define Cr_MASS (51.9961 * MOLARMASS)
#define CrMASS (Cr_MASS / AVOGADRO)
#define Cr_DENSITY (7150 * DENSITY)
#define Cr_MELT (2180 * KELVIN)
#define Cr_BOIL (2944 * KELVIN)
#define Cr_Cp (449 * SPECIFICHEAT)
#define Cr_En (1.66)
#define MANGANESEZ 25
#define MANGANESE (54.938043)
#define MnZ 25
#define Mn_MASS (54.938043 * MOLARMASS)
#define MnMASS (Mn_MASS / AVOGADRO)
#define Mn_DENSITY (7440 * DENSITY)
#define Mn_MELT (1519 * KELVIN)
#define Mn_BOIL (2334 * KELVIN)
#define Mn_Cp (479 * SPECIFICHEAT)
#define Mn_En (1.55)
#define IRONZ 26
#define IRON (55.845)
#define FeZ 26
#define Fe_MASS (55.845 * MOLARMASS)
#define FeMASS (Fe_MASS / AVOGADRO)
#define Fe_DENSITY (7874 * DENSITY)
#define Fe_MELT (1811 * KELVIN)
#define Fe_BOIL (3134 * KELVIN)
#define Fe_Cp (449 * SPECIFICHEAT)
#define Fe_En (1.83)
#define COBALTZ 27
#define COBALT (58.933194)
#define CoZ 27
#define Co_MASS (58.933194 * MOLARMASS)
#define CoMASS (Co_MASS / AVOGADRO)
#define Co_DENSITY (8860 * DENSITY)
#define Co_MELT (1768 * KELVIN)
#define Co_BOIL (3200 * KELVIN)
#define Co_Cp (421 * SPECIFICHEAT)
#define Co_En (1.88)
#define NICKELZ 28
#define NICKEL (58.6934)
#define NiZ 28
#define Ni_MASS (58.6934 * MOLARMASS)
#define NiMASS (Ni_MASS / AVOGADRO)
#define Ni_DENSITY (8912 * DENSITY)
#define Ni_MELT (1728 * KELVIN)
#define Ni_BOIL (3186 * KELVIN)
#define Ni_Cp (444 * SPECIFICHEAT)
#define Ni_En (1.91)
#define COPPERZ 29
#define COPPER (63.546)
#define CuZ 29
#define Cu_MASS (63.546 * MOLARMASS)
#define CuMASS (Cu_MASS / AVOGADRO)
#define Cu_DENSITY (8960 * DENSITY)
#define Cu_MELT (1357.77 * KELVIN)
#define Cu_BOIL (2835 * KELVIN)
#define Cu_Cp (385 * SPECIFICHEAT)
#define Cu_En (1.9)
#define ZINCZ 30
#define ZINC (65.38)
#define ZnZ 30
#define Zn_MASS (65.38 * MOLARMASS)
#define ZnMASS (Zn_MASS / AVOGADRO)
#define Zn_DENSITY (7134 * DENSITY)
#define Zn_MELT (692.88 * KELVIN)
#define Zn_BOIL (1180 * KELVIN)
#define Zn_Cp (388 * SPECIFICHEAT)
#define Zn_En (1.65)
#define GALLIUMZ 31
#define GALLIUM (69.723)
#define GaZ 31
#define Ga_MASS (69.723 * MOLARMASS)
#define GaMASS (Ga_MASS / AVOGADRO)
#define Ga_DENSITY (5907 * DENSITY)
#define Ga_MELT (302.9146 * KELVIN)
#define Ga_BOIL (2673 * KELVIN)
#define Ga_Cp (371 * SPECIFICHEAT)
#define Ga_En (1.81)
#define GERMANIUMZ 32
#define GERMANIUM (72.630)
#define GeZ 32
#define Ge_MASS (72.630 * MOLARMASS)
#define GeMASS (Ge_MASS / AVOGADRO)
#define Ge_DENSITY (5323 * DENSITY)
#define Ge_MELT (1211.40 * KELVIN)
#define Ge_BOIL (3106 * KELVIN)
#define Ge_Cp (320 * SPECIFICHEAT)
#define Ge_En (2.01)
#define ARSENICZ 33
#define ARSENIC (74.921595)
#define AsZ 33
#define As_MASS (74.921595 * MOLARMASS)
#define AsMASS (As_MASS / AVOGADRO)
#define As_DENSITY (5776 * DENSITY)
#define As_MELT (1090 * KELVIN)
#define As_BOIL (887 * KELVIN)
#define As_Cp (329 * SPECIFICHEAT)
#define As_En (2.18)
#define SELENIUMZ 34
#define SELENIUM (78.971)
#define SeZ 34
#define Se_MASS (78.971 * MOLARMASS)
#define SeMASS (Se_MASS / AVOGADRO)
#define Se_DENSITY (4809 * DENSITY)
#define Se_MELT (453 * KELVIN)
#define Se_BOIL (958 * KELVIN)
#define Se_Cp (321 * SPECIFICHEAT)
#define Se_En (2.55)
#define BROMINEZ 35
#define BROMINE (79.904)
#define BrZ 35
#define Br_MASS (79.904 * MOLARMASS)
#define BrMASS (Br_MASS / AVOGADRO)
#define Br_DENSITY (3122 * DENSITY)
#define Br_MELT (265.8 * KELVIN)
#define Br_BOIL (332.0 * KELVIN)
#define Br_Cp (474 * SPECIFICHEAT)
#define Br_En (2.96)
#define KRYPTONZ 36
#define KRYPTON (83.798)
#define KrZ 36
#define Kr_MASS (83.798 * MOLARMASS)
#define KrMASS (Kr_MASS / AVOGADRO)
#define Kr_DENSITY (3.733 * DENSITY)
#define Kr_MELT (115.79 * KELVIN)
#define Kr_BOIL (119.93 * KELVIN)
#define Kr_Cp (248 * SPECIFICHEAT)
#define Kr_En 3
#define RUBIDIUMZ 37
#define RUBIDIUM (85.4678)
#define RbZ 37
#define Rb_MASS (85.4678 * MOLARMASS)
#define RbMASS (Rb_MASS / AVOGADRO)
#define Rb_DENSITY (1532 * DENSITY)
#define Rb_MELT (312.46 * KELVIN)
#define Rb_BOIL (961 * KELVIN)
#define Rb_Cp (363 * SPECIFICHEAT)
#define Rb_En (0.82)
#define STRONTIUMZ 38
#define STRONTIUM (87.62)
#define SrZ 38
#define Sr_MASS (87.62 * MOLARMASS)
#define SrMASS (Sr_MASS / AVOGADRO)
#define Sr_DENSITY (2640 * DENSITY)
#define Sr_MELT (1050 * KELVIN)
#define Sr_BOIL (1655 * KELVIN)
#define Sr_Cp (301 * SPECIFICHEAT)
#define Sr_En (0.95)
#define YTTRIUMZ 39
#define YTTRIUM (88.90584)
#define YZ 39
#define Y_MASS (88.90584 * MOLARMASS)
#define YMASS (Y_MASS / AVOGADRO)
#define Y_DENSITY (4469 * DENSITY)
#define Y_MELT (1799 * KELVIN)
#define Y_BOIL (3609 * KELVIN)
#define Y_Cp (298 * SPECIFICHEAT)
#define Y_En (1.22)
#define ZIRCONIUMZ 40
#define ZIRCONIUM (91.224)
#define ZrZ 40
#define Zr_MASS (91.224 * MOLARMASS)
#define ZrMASS (Zr_MASS / AVOGADRO)
#define Zr_DENSITY (6506 * DENSITY)
#define Zr_MELT (2128 * KELVIN)
#define Zr_BOIL (4682 * KELVIN)
#define Zr_Cp (278 * SPECIFICHEAT)
#define Zr_En (1.33)
#define NIOBIUMZ 41
#define NIOBIUM (92.90637)
#define NbZ 41
#define Nb_MASS (92.90637 * MOLARMASS)
#define NbMASS (Nb_MASS / AVOGADRO)
#define Nb_DENSITY (8570 * DENSITY)
#define Nb_MELT (2750 * KELVIN)
#define Nb_BOIL (5017 * KELVIN)
#define Nb_Cp (265 * SPECIFICHEAT)
#define Nb_En (1.6)
#define MOLYBDENUMZ 42
#define MOLYBDENUM (95.95)
#define MoZ 42
#define Mo_MASS (95.95 * MOLARMASS)
#define MoMASS (Mo_MASS / AVOGADRO)
#define Mo_DENSITY (10220 * DENSITY)
#define Mo_MELT (2896 * KELVIN)
#define Mo_BOIL (4912 * KELVIN)
#define Mo_Cp (251 * SPECIFICHEAT)
#define Mo_En (2.16)
#define TECHNETIUMZ 43
#define TECHNETIUM 98
#define TcZ 43
#define Tc_MASS (98 * MOLARMASS)
#define TcMASS (Tc_MASS / AVOGADRO)
#define Tc_DENSITY (11500 * DENSITY)
#define Tc_MELT (2430 * KELVIN)
#define Tc_BOIL (4538 * KELVIN)
#define Tc_Cp (- 1 * SPECIFICHEAT)
#define Tc_En (1.9)
#define RUTHENIUMZ 44
#define RUTHENIUM (101.07)
#define RuZ 44
#define Ru_MASS (101.07 * MOLARMASS)
#define RuMASS (Ru_MASS / AVOGADRO)
#define Ru_DENSITY (12370 * DENSITY)
#define Ru_MELT (2607 * KELVIN)
#define Ru_BOIL (4423 * KELVIN)
#define Ru_Cp (238 * SPECIFICHEAT)
#define Ru_En (2.2)
#define RHODIUMZ 45
#define RHODIUM (102.90549)
#define RhZ 45
#define Rh_MASS (102.90549 * MOLARMASS)
#define RhMASS (Rh_MASS / AVOGADRO)
#define Rh_DENSITY (12410 * DENSITY)
#define Rh_MELT (2237 * KELVIN)
#define Rh_BOIL (3968 * KELVIN)
#define Rh_Cp (243 * SPECIFICHEAT)
#define Rh_En (2.28)
#define PALLADIUMZ 46
#define PALLADIUM (106.42)
#define PdZ 46
#define Pd_MASS (106.42 * MOLARMASS)
#define PdMASS (Pd_MASS / AVOGADRO)
#define Pd_DENSITY (12020 * DENSITY)
#define Pd_MELT (1828.05 * KELVIN)
#define Pd_BOIL (3236 * KELVIN)
#define Pd_Cp (244 * SPECIFICHEAT)
#define Pd_En (2.2)
#define SILVERZ 47
#define SILVER (107.8682)
#define AgZ 47
#define Ag_MASS (107.8682 * MOLARMASS)
#define AgMASS (Ag_MASS / AVOGADRO)
#define Ag_DENSITY (10501 * DENSITY)
#define Ag_MELT (1234.93 * KELVIN)
#define Ag_BOIL (2435 * KELVIN)
#define Ag_Cp (235 * SPECIFICHEAT)
#define Ag_En (1.93)
#define CADMIUMZ 48
#define CADMIUM (112.414)
#define CdZ 48
#define Cd_MASS (112.414 * MOLARMASS)
#define CdMASS (Cd_MASS / AVOGADRO)
#define Cd_DENSITY (8690 * DENSITY)
#define Cd_MELT (594.22 * KELVIN)
#define Cd_BOIL (1040 * KELVIN)
#define Cd_Cp (232 * SPECIFICHEAT)
#define Cd_En (1.69)
#define INDIUMZ 49
#define INDIUM (114.818)
#define InZ 49
#define In_MASS (114.818 * MOLARMASS)
#define InMASS (In_MASS / AVOGADRO)
#define In_DENSITY (7310 * DENSITY)
#define In_MELT (429.75 * KELVIN)
#define In_BOIL (2345 * KELVIN)
#define In_Cp (233 * SPECIFICHEAT)
#define In_En (1.78)
#define TINZ 50
#define TIN (118.710)
#define SnZ 50
#define Sn_MASS (118.710 * MOLARMASS)
#define SnMASS (Sn_MASS / AVOGADRO)
#define Sn_DENSITY (7287 * DENSITY)
#define Sn_MELT (505.08 * KELVIN)
#define Sn_BOIL (2875 * KELVIN)
#define Sn_Cp (228 * SPECIFICHEAT)
#define Sn_En (1.96)
#define ANTIMONYZ 51
#define ANTIMONY (121.760)
#define SbZ 51
#define Sb_MASS (121.760 * MOLARMASS)
#define SbMASS (Sb_MASS / AVOGADRO)
#define Sb_DENSITY (6685 * DENSITY)
#define Sb_MELT (903.78 * KELVIN)
#define Sb_BOIL (1860 * KELVIN)
#define Sb_Cp (207 * SPECIFICHEAT)
#define Sb_En (2.05)
#define TELLURIUMZ 52
#define TELLURIUM (127.60)
#define TeZ 52
#define Te_MASS (127.60 * MOLARMASS)
#define TeMASS (Te_MASS / AVOGADRO)
#define Te_DENSITY (6232 * DENSITY)
#define Te_MELT (722.66 * KELVIN)
#define Te_BOIL (1261 * KELVIN)
#define Te_Cp (202 * SPECIFICHEAT)
#define Te_En (2.1)
#define IODINEZ 53
#define IODINE (126.90447)
#define IZ 53
#define I_MASS (126.90447 * MOLARMASS)
#define IMASS (I_MASS / AVOGADRO)
#define I_DENSITY (4930 * DENSITY)
#define I_MELT (386.85 * KELVIN)
#define I_BOIL (457.4 * KELVIN)
#define I_Cp (214 * SPECIFICHEAT)
#define I_En (2.66)
#define XENONZ 54
#define XENON (131.293)
#define XeZ 54
#define Xe_MASS (131.293 * MOLARMASS)
#define XeMASS (Xe_MASS / AVOGADRO)
#define Xe_DENSITY (5.887 * DENSITY)
#define Xe_MELT (161.4 * KELVIN)
#define Xe_BOIL (165.03 * KELVIN)
#define Xe_Cp (158 * SPECIFICHEAT)
#define Xe_En (2.6)
#define CAESIUMZ 55
#define CAESIUM (132.90545196)
#define CsZ 55
#define Cs_MASS (132.90545196 * MOLARMASS)
#define CsMASS (Cs_MASS / AVOGADRO)
#define Cs_DENSITY (1873 * DENSITY)
#define Cs_MELT (301.59 * KELVIN)
#define Cs_BOIL (944 * KELVIN)
#define Cs_Cp (242 * SPECIFICHEAT)
#define Cs_En (0.79)
#define BARIUMZ 56
#define BARIUM (137.327)
#define BaZ 56
#define Ba_MASS (137.327 * MOLARMASS)
#define BaMASS (Ba_MASS / AVOGADRO)
#define Ba_DENSITY (3594 * DENSITY)
#define Ba_MELT (1000 * KELVIN)
#define Ba_BOIL (2170 * KELVIN)
#define Ba_Cp (204 * SPECIFICHEAT)
#define Ba_En (0.89)
#define LANTHANUMZ 57
#define LANTHANUM (138.90547)
#define LaZ 57
#define La_MASS (138.90547 * MOLARMASS)
#define LaMASS (La_MASS / AVOGADRO)
#define La_DENSITY (6145 * DENSITY)
#define La_MELT (1193 * KELVIN)
#define La_BOIL (3737 * KELVIN)
#define La_Cp (195 * SPECIFICHEAT)
#define La_En (1.1)
#define CERIUMZ 58
#define CERIUM (140.116)
#define CeZ 58
#define Ce_MASS (140.116 * MOLARMASS)
#define CeMASS (Ce_MASS / AVOGADRO)
#define Ce_DENSITY (6770 * DENSITY)
#define Ce_MELT (1068 * KELVIN)
#define Ce_BOIL (3716 * KELVIN)
#define Ce_Cp (192 * SPECIFICHEAT)
#define Ce_En (1.12)
#define PRASEODYMIUMZ 59
#define PRASEODYMIUM (140.90766)
#define PrZ 59
#define Pr_MASS (140.90766 * MOLARMASS)
#define PrMASS (Pr_MASS / AVOGADRO)
#define Pr_DENSITY (6773 * DENSITY)
#define Pr_MELT (1208 * KELVIN)
#define Pr_BOIL (3793 * KELVIN)
#define Pr_Cp (193 * SPECIFICHEAT)
#define Pr_En (1.13)
#define NEODYMIUMZ 60
#define NEODYMIUM (144.242)
#define NdZ 60
#define Nd_MASS (144.242 * MOLARMASS)
#define NdMASS (Nd_MASS / AVOGADRO)
#define Nd_DENSITY (7007 * DENSITY)
#define Nd_MELT (1297 * KELVIN)
#define Nd_BOIL (3347 * KELVIN)
#define Nd_Cp (190 * SPECIFICHEAT)
#define Nd_En (1.14)
#define PROMETHIUMZ 61
#define PROMETHIUM 145
#define PmZ 61
#define Pm_MASS (145 * MOLARMASS)
#define PmMASS (Pm_MASS / AVOGADRO)
#define Pm_DENSITY (7260 * DENSITY)
#define Pm_MELT (1315 * KELVIN)
#define Pm_BOIL (3273 * KELVIN)
#define Pm_Cp (- 1 * SPECIFICHEAT)
#define Pm_En (1.13)
#define SAMARIUMZ 62
#define SAMARIUM (150.36)
#define SmZ 62
#define Sm_MASS (150.36 * MOLARMASS)
#define SmMASS (Sm_MASS / AVOGADRO)
#define Sm_DENSITY (7520 * DENSITY)
#define Sm_MELT (1345 * KELVIN)
#define Sm_BOIL (2067 * KELVIN)
#define Sm_Cp (197 * SPECIFICHEAT)
#define Sm_En (1.17)
#define EUROPIUMZ 63
#define EUROPIUM (151.964)
#define EuZ 63
#define Eu_MASS (151.964 * MOLARMASS)
#define EuMASS (Eu_MASS / AVOGADRO)
#define Eu_DENSITY (5243 * DENSITY)
#define Eu_MELT (1099 * KELVIN)
#define Eu_BOIL (1802 * KELVIN)
#define Eu_Cp (182 * SPECIFICHEAT)
#define Eu_En (1.2)
#define GADOLINIUMZ 64
#define GADOLINIUM (157.25)
#define GdZ 64
#define Gd_MASS (157.25 * MOLARMASS)
#define GdMASS (Gd_MASS / AVOGADRO)
#define Gd_DENSITY (7895 * DENSITY)
#define Gd_MELT (1585 * KELVIN)
#define Gd_BOIL (3546 * KELVIN)
#define Gd_Cp (236 * SPECIFICHEAT)
#define Gd_En (1.2)
#define TERBIUMZ 65
#define TERBIUM (158.925354)
#define TbZ 65
#define Tb_MASS (158.925354 * MOLARMASS)
#define TbMASS (Tb_MASS / AVOGADRO)
#define Tb_DENSITY (8229 * DENSITY)
#define Tb_MELT (1629 * KELVIN)
#define Tb_BOIL (3503 * KELVIN)
#define Tb_Cp (182 * SPECIFICHEAT)
#define Tb_En (1.2)
#define DYSPROSIUMZ 66
#define DYSPROSIUM (162.500)
#define DyZ 66
#define Dy_MASS (162.500 * MOLARMASS)
#define DyMASS (Dy_MASS / AVOGADRO)
#define Dy_DENSITY (8550 * DENSITY)
#define Dy_MELT (1680 * KELVIN)
#define Dy_BOIL (2840 * KELVIN)
#define Dy_Cp (170 * SPECIFICHEAT)
#define Dy_En (1.22)
#define HOLMIUMZ 67
#define HOLMIUM (164.930328)
#define HoZ 67
#define Ho_MASS (164.930328 * MOLARMASS)
#define HoMASS (Ho_MASS / AVOGADRO)
#define Ho_DENSITY (8795 * DENSITY)
#define Ho_MELT (1734 * KELVIN)
#define Ho_BOIL (2993 * KELVIN)
#define Ho_Cp (165 * SPECIFICHEAT)
#define Ho_En (1.23)
#define ERBIUMZ 68
#define ERBIUM (167.259)
#define ErZ 68
#define Er_MASS (167.259 * MOLARMASS)
#define ErMASS (Er_MASS / AVOGADRO)
#define Er_DENSITY (9066 * DENSITY)
#define Er_MELT (1802 * KELVIN)
#define Er_BOIL (3141 * KELVIN)
#define Er_Cp (168 * SPECIFICHEAT)
#define Er_En (1.24)
#define THULIUMZ 69
#define THULIUM (168.934218)
#define TmZ 69
#define Tm_MASS (168.934218 * MOLARMASS)
#define TmMASS (Tm_MASS / AVOGADRO)
#define Tm_DENSITY (9321 * DENSITY)
#define Tm_MELT (1818 * KELVIN)
#define Tm_BOIL (2223 * KELVIN)
#define Tm_Cp (160 * SPECIFICHEAT)
#define Tm_En (1.25)
#define YTTERBIUMZ 70
#define YTTERBIUM (173.045)
#define YbZ 70
#define Yb_MASS (173.045 * MOLARMASS)
#define YbMASS (Yb_MASS / AVOGADRO)
#define Yb_DENSITY (6965 * DENSITY)
#define Yb_MELT (1097 * KELVIN)
#define Yb_BOIL (1469 * KELVIN)
#define Yb_Cp (155 * SPECIFICHEAT)
#define Yb_En (1.1)
#define LUTETIUMZ 71
#define LUTETIUM (174.9668)
#define LuZ 71
#define Lu_MASS (174.9668 * MOLARMASS)
#define LuMASS (Lu_MASS / AVOGADRO)
#define Lu_DENSITY (9840 * DENSITY)
#define Lu_MELT (1925 * KELVIN)
#define Lu_BOIL (3675 * KELVIN)
#define Lu_Cp (154 * SPECIFICHEAT)
#define Lu_En (1.27)
#define HAFNIUMZ 72
#define HAFNIUM (178.49)
#define HfZ 72
#define Hf_MASS (178.49 * MOLARMASS)
#define HfMASS (Hf_MASS / AVOGADRO)
#define Hf_DENSITY (13310 * DENSITY)
#define Hf_MELT (2506 * KELVIN)
#define Hf_BOIL (4876 * KELVIN)
#define Hf_Cp (144 * SPECIFICHEAT)
#define Hf_En (1.3)
#define TANTALUMZ 73
#define TANTALUM (180.94788)
#define TaZ 73
#define Ta_MASS (180.94788 * MOLARMASS)
#define TaMASS (Ta_MASS / AVOGADRO)
#define Ta_DENSITY (16654 * DENSITY)
#define Ta_MELT (3290 * KELVIN)
#define Ta_BOIL (5731 * KELVIN)
#define Ta_Cp (140 * SPECIFICHEAT)
#define Ta_En (1.5)
#define TUNGSTENZ 74
#define TUNGSTEN (183.84)
#define WZ 74
#define W_MASS (183.84 * MOLARMASS)
#define WMASS (W_MASS / AVOGADRO)
#define W_DENSITY (19250 * DENSITY)
#define W_MELT (3695 * KELVIN)
#define W_BOIL (5828 * KELVIN)
#define W_Cp (132 * SPECIFICHEAT)
#define W_En (2.36)
#define RHENIUMZ 75
#define RHENIUM (186.207)
#define ReZ 75
#define Re_MASS (186.207 * MOLARMASS)
#define ReMASS (Re_MASS / AVOGADRO)
#define Re_DENSITY (21020 * DENSITY)
#define Re_MELT (3459 * KELVIN)
#define Re_BOIL (5869 * KELVIN)
#define Re_Cp (137 * SPECIFICHEAT)
#define Re_En (1.9)
#define OSMIUMZ 76
#define OSMIUM (190.23)
#define OsZ 76
#define Os_MASS (190.23 * MOLARMASS)
#define OsMASS (Os_MASS / AVOGADRO)
#define Os_DENSITY (22610 * DENSITY)
#define Os_MELT (3306 * KELVIN)
#define Os_BOIL (5285 * KELVIN)
#define Os_Cp (130 * SPECIFICHEAT)
#define Os_En (2.2)
#define IRIDIUMZ 77
#define IRIDIUM (192.217)
#define IrZ 77
#define Ir_MASS (192.217 * MOLARMASS)
#define IrMASS (Ir_MASS / AVOGADRO)
#define Ir_DENSITY (22560 * DENSITY)
#define Ir_MELT (2719 * KELVIN)
#define Ir_BOIL (4701 * KELVIN)
#define Ir_Cp (131 * SPECIFICHEAT)
#define Ir_En (2.2)
#define PLATINUMZ 78
#define PLATINUM (195.084)
#define PtZ 78
#define Pt_MASS (195.084 * MOLARMASS)
#define PtMASS (Pt_MASS / AVOGADRO)
#define Pt_DENSITY (21460 * DENSITY)
#define Pt_MELT (2041.4 * KELVIN)
#define Pt_BOIL (4098 * KELVIN)
#define Pt_Cp (133 * SPECIFICHEAT)
#define Pt_En (2.28)
#define GOLDZ 79
#define GOLD (196.966570)
#define AuZ 79
#define Au_MASS (196.966570 * MOLARMASS)
#define AuMASS (Au_MASS / AVOGADRO)
#define Au_DENSITY (19282 * DENSITY)
#define Au_MELT (1337.33 * KELVIN)
#define Au_BOIL (3129 * KELVIN)
#define Au_Cp (129 * SPECIFICHEAT)
#define Au_En (2.54)
#define MERCURYZ 80
#define MERCURY (200.592)
#define HgZ 80
#define Hg_MASS (200.592 * MOLARMASS)
#define HgMASS (Hg_MASS / AVOGADRO)
#define Hg_DENSITY (13533.6 * DENSITY)
#define Hg_MELT (234.43 * KELVIN)
#define Hg_BOIL (629.88 * KELVIN)
#define Hg_Cp (140 * SPECIFICHEAT)
#define Hg_En 2
#define THALLIUMZ 81
#define THALLIUM (204.38)
#define TlZ 81
#define Tl_MASS (204.38 * MOLARMASS)
#define TlMASS (Tl_MASS / AVOGADRO)
#define Tl_DENSITY (11850 * DENSITY)
#define Tl_MELT (577 * KELVIN)
#define Tl_BOIL (1746 * KELVIN)
#define Tl_Cp (129 * SPECIFICHEAT)
#define Tl_En (1.62)
#define LEADZ 82
#define LEAD (207.2)
#define PbZ 82
#define Pb_MASS (207.2 * MOLARMASS)
#define PbMASS (Pb_MASS / AVOGADRO)
#define Pb_DENSITY (11342 * DENSITY)
#define Pb_MELT (600.61 * KELVIN)
#define Pb_BOIL (2022 * KELVIN)
#define Pb_Cp (129 * SPECIFICHEAT)
#define Pb_En (1.87)
#define BISMUTHZ 83
#define BISMUTH (208.98040)
#define BiZ 83
#define Bi_MASS (208.98040 * MOLARMASS)
#define BiMASS (Bi_MASS / AVOGADRO)
#define Bi_DENSITY (9807 * DENSITY)
#define Bi_MELT (544.7 * KELVIN)
#define Bi_BOIL (1837 * KELVIN)
#define Bi_Cp (122 * SPECIFICHEAT)
#define Bi_En (2.02)
#define POLONIUMZ 84
#define POLONIUM 209
#define PoZ 84
#define Po_MASS (209 * MOLARMASS)
#define PoMASS (Po_MASS / AVOGADRO)
#define Po_DENSITY (9320 * DENSITY)
#define Po_MELT (527 * KELVIN)
#define Po_BOIL (1235 * KELVIN)
#define Po_Cp (- 1 * SPECIFICHEAT)
#define Po_En (2.0)
#define ASTATINEZ 85
#define ASTATINE 210
#define AtZ 85
#define At_MASS (210 * MOLARMASS)
#define AtMASS (At_MASS / AVOGADRO)
#define At_DENSITY (7000 * DENSITY)
#define At_MELT (575 * KELVIN)
#define At_BOIL (610 * KELVIN)
#define At_Cp (- 1 * SPECIFICHEAT)
#define At_En (2.2)
#define RADONZ 86
#define RADON 222
#define RnZ 86
#define Rn_MASS (222 * MOLARMASS)
#define RnMASS (Rn_MASS / AVOGADRO)
#define Rn_DENSITY (9.73 * DENSITY)
#define Rn_MELT (202 * KELVIN)
#define Rn_BOIL (211.3 * KELVIN)
#define Rn_Cp (94 * SPECIFICHEAT)
#define Rn_En (2.2)
#define FRANCIUMZ 87
#define FRANCIUM 223
#define FrZ 87
#define Fr_MASS (223 * MOLARMASS)
#define FrMASS (Fr_MASS / AVOGADRO)
#define Fr_DENSITY (1870 * DENSITY)
#define Fr_MELT (300 * KELVIN)
#define Fr_BOIL (950 * KELVIN)
#define Fr_Cp (- 1 * SPECIFICHEAT)
#define Fr_En (0.7)
#define RADIUMZ 88
#define RADIUM 226
#define RaZ 88
#define Ra_MASS (226 * MOLARMASS)
#define RaMASS (Ra_MASS / AVOGADRO)
#define Ra_DENSITY (5500 * DENSITY)
#define Ra_MELT (973 * KELVIN)
#define Ra_BOIL (2010 * KELVIN)
#define Ra_Cp (94 * SPECIFICHEAT)
#define Ra_En (0.9)
#define ACTINIUMZ 89
#define ACTINIUM 227
#define AcZ 89
#define Ac_MASS (227 * MOLARMASS)
#define AcMASS (Ac_MASS / AVOGADRO)
#define Ac_DENSITY (10070 * DENSITY)
#define Ac_MELT (1323 * KELVIN)
#define Ac_BOIL (3471 * KELVIN)
#define Ac_Cp (120 * SPECIFICHEAT)
#define Ac_En (1.1)
#define THORIUMZ 90
#define THORIUM (232.0377)
#define ThZ 90
#define Th_MASS (232.0377 * MOLARMASS)
#define ThMASS (Th_MASS / AVOGADRO)
#define Th_DENSITY (11720 * DENSITY)
#define Th_MELT (2115 * KELVIN)
#define Th_BOIL (5061 * KELVIN)
#define Th_Cp (113 * SPECIFICHEAT)
#define Th_En (1.3)
#define PROTACTINIUMZ 91
#define PROTACTINIUM (231.03588)
#define PaZ 91
#define Pa_MASS (231.03588 * MOLARMASS)
#define PaMASS (Pa_MASS / AVOGADRO)
#define Pa_DENSITY (15370 * DENSITY)
#define Pa_MELT (1841 * KELVIN)
#define Pa_BOIL (4300 * KELVIN)
#define Pa_Cp (- 1 * SPECIFICHEAT)
#define Pa_En (1.5)
#define URANIUMZ 92
#define URANIUM (238.02891)
#define UZ 92
#define U_MASS (238.02891 * MOLARMASS)
#define UMASS (U_MASS / AVOGADRO)
#define U_DENSITY (18950 * DENSITY)
#define U_MELT (1405.3 * KELVIN)
#define U_BOIL (4404 * KELVIN)
#define U_Cp (116 * SPECIFICHEAT)
#define U_En (1.38)
#define NEPTUNIUMZ 93
#define NEPTUNIUM 237
#define NpZ 93
#define Np_MASS (237 * MOLARMASS)
#define NpMASS (Np_MASS / AVOGADRO)
#define Np_DENSITY (20450 * DENSITY)
#define Np_MELT (917 * KELVIN)
#define Np_BOIL (4273 * KELVIN)
#define Np_Cp (- 1 * SPECIFICHEAT)
#define Np_En (1.36)
#define PLUTONIUMZ 94
#define PLUTONIUM 244
#define PuZ 94
#define Pu_MASS (244 * MOLARMASS)
#define PuMASS (Pu_MASS / AVOGADRO)
#define Pu_DENSITY (19840 * DENSITY)
#define Pu_MELT (912.5 * KELVIN)
#define Pu_BOIL (3501 * KELVIN)
#define Pu_Cp (- 1 * SPECIFICHEAT)
#define Pu_En (1.28)
#define AMERICIUMZ 95
#define AMERICIUM 243
#define AmZ 95
#define Am_MASS (243 * MOLARMASS)
#define AmMASS (Am_MASS / AVOGADRO)
#define Am_DENSITY (13690 * DENSITY)
#define Am_MELT (1449 * KELVIN)
#define Am_BOIL (2880 * KELVIN)
#define Am_Cp (- 1 * SPECIFICHEAT)
#define Am_En (1.13)
#define CURIUMZ 96
#define CURIUM 247
#define CmZ 96
#define Cm_MASS (247 * MOLARMASS)
#define CmMASS (Cm_MASS / AVOGADRO)
#define Cm_DENSITY (13510 * DENSITY)
#define Cm_MELT (1613 * KELVIN)
#define Cm_BOIL (3383 * KELVIN)
#define Cm_Cp (- 1 * SPECIFICHEAT)
#define Cm_En (1.28)
#define BERKELIUMZ 97
#define BERKELIUM 247
#define BkZ 97
#define Bk_MASS (247 * MOLARMASS)
#define BkMASS (Bk_MASS / AVOGADRO)
#define Bk_DENSITY (14790 * DENSITY)
#define Bk_MELT (1259 * KELVIN)
#define Bk_BOIL (2900 * KELVIN)
#define Bk_Cp (- 1 * SPECIFICHEAT)
#define Bk_En (1.3)
#define CALIFORNIUMZ 98
#define CALIFORNIUM 251
#define CfZ 98
#define Cf_MASS (251 * MOLARMASS)
#define CfMASS (Cf_MASS / AVOGADRO)
#define Cf_DENSITY (15100 * DENSITY)
#define Cf_MELT (1173 * KELVIN)
#define Cf_BOIL (- 1 * KELVIN)
#define Cf_Cp (- 1 * SPECIFICHEAT)
#define Cf_En (1.3)
#define EINSTEINIUMZ 99
#define EINSTEINIUM 252
#define EsZ 99
#define Es_MASS (252 * MOLARMASS)
#define EsMASS (Es_MASS / AVOGADRO)
#define Es_DENSITY (8840 * DENSITY)
#define Es_MELT (1133 * KELVIN)
#define Es_BOIL (- 1 * KELVIN)
#define Es_Cp (- 1 * SPECIFICHEAT)
#define Es_En (1.3)
#define FERMIUMZ 100
#define FERMIUM 257
#define FmZ 100
#define Fm_MASS (257 * MOLARMASS)
#define FmMASS (Fm_MASS / AVOGADRO)
#define Fm_DENSITY (- 1 * DENSITY)
#define Fm_MELT (- 1 * KELVIN)
#define Fm_BOIL (- 1 * KELVIN)
#define Fm_Cp (- 1 * SPECIFICHEAT)
#define Fm_En (1.3)
#define MENDELEVIUMZ 101
#define MENDELEVIUM 258
#define MdZ 101
#define Md_MASS (258 * MOLARMASS)
#define MdMASS (Md_MASS / AVOGADRO)
#define Md_DENSITY (- 1 * DENSITY)
#define Md_MELT (- 1 * KELVIN)
#define Md_BOIL (- 1 * KELVIN)
#define Md_Cp (- 1 * SPECIFICHEAT)
#define Md_En (1.3)
#define NOBELIUMZ 102
#define NOBELIUM 259
#define NoZ 102
#define No_MASS (259 * MOLARMASS)
#define NoMASS (No_MASS / AVOGADRO)
#define No_DENSITY (- 1 * DENSITY)
#define No_MELT (- 1 * KELVIN)
#define No_BOIL (- 1 * KELVIN)
#define No_Cp (- 1 * SPECIFICHEAT)
#define No_En (1.3)
#define LAWRENCIUMZ 103
#define LAWRENCIUM 266
#define LrZ 103
#define Lr_MASS (266 * MOLARMASS)
#define LrMASS (Lr_MASS / AVOGADRO)
#define Lr_DENSITY (- 1 * DENSITY)
#define Lr_MELT (- 1 * KELVIN)
#define Lr_BOIL (- 1 * KELVIN)
#define Lr_Cp (- 1 * SPECIFICHEAT)
#define Lr_En (1.3)
#define RUTHERFORDIUMZ 104
#define RUTHERFORDIUM 267
#define RfZ 104
#define Rf_MASS (267 * MOLARMASS)
#define RfMASS (Rf_MASS / AVOGADRO)
#define Rf_DENSITY (- 1 * DENSITY)
#define Rf_MELT (- 1 * KELVIN)
#define Rf_BOIL (- 1 * KELVIN)
#define Rf_Cp (- 1 * SPECIFICHEAT)
#define Rf_En (- 1)
#define DUBNIUMZ 105
#define DUBNIUM 268
#define DbZ 105
#define Db_MASS (268 * MOLARMASS)
#define DbMASS (Db_MASS / AVOGADRO)
#define Db_DENSITY (- 1 * DENSITY)
#define Db_MELT (- 1 * KELVIN)
#define Db_BOIL (- 1 * KELVIN)
#define Db_Cp (- 1 * SPECIFICHEAT)
#define Db_En (- 1)
#define SEABORGIUMZ 106
#define SEABORGIUM 269
#define SgZ 106
#define Sg_MASS (269 * MOLARMASS)
#define SgMASS (Sg_MASS / AVOGADRO)
#define Sg_DENSITY (- 1 * DENSITY)
#define Sg_MELT (- 1 * KELVIN)
#define Sg_BOIL (- 1 * KELVIN)
#define Sg_Cp (- 1 * SPECIFICHEAT)
#define Sg_En (- 1)
#define BOHRIUMZ 107
#define BOHRIUM 270
#define BhZ 107
#define Bh_MASS (270 * MOLARMASS)
#define BhMASS (Bh_MASS / AVOGADRO)
#define Bh_DENSITY (- 1 * DENSITY)
#define Bh_MELT (- 1 * KELVIN)
#define Bh_BOIL (- 1 * KELVIN)
#define Bh_Cp (- 1 * SPECIFICHEAT)
#define Bh_En (- 1)
#define HASSIUMZ 108
#define HASSIUM 270
#define HsZ 108
#define Hs_MASS (270 * MOLARMASS)
#define HsMASS (Hs_MASS / AVOGADRO)
#define Hs_DENSITY (- 1 * DENSITY)
#define Hs_MELT (- 1 * KELVIN)
#define Hs_BOIL (- 1 * KELVIN)
#define Hs_Cp (- 1 * SPECIFICHEAT)
#define Hs_En (- 1)
#define MEITNERIUMZ 109
#define MEITNERIUM 278
#define MtZ 109
#define Mt_MASS (278 * MOLARMASS)
#define MtMASS (Mt_MASS / AVOGADRO)
#define Mt_DENSITY (- 1 * DENSITY)
#define Mt_MELT (- 1 * KELVIN)
#define Mt_BOIL (- 1 * KELVIN)
#define Mt_Cp (- 1 * SPECIFICHEAT)
#define Mt_En (- 1)
#define DARMSTADTIUMZ 110
#define DARMSTADTIUM 281
#define DsZ 110
#define Ds_MASS (281 * MOLARMASS)
#define DsMASS (Ds_MASS / AVOGADRO)
#define Ds_DENSITY (- 1 * DENSITY)
#define Ds_MELT (- 1 * KELVIN)
#define Ds_BOIL (- 1 * KELVIN)
#define Ds_Cp (- 1 * SPECIFICHEAT)
#define Ds_En (- 1)
#define ROENTGENIUMZ 111
#define ROENTGENIUM 282
#define RgZ 111
#define Rg_MASS (282 * MOLARMASS)
#define RgMASS (Rg_MASS / AVOGADRO)
#define Rg_DENSITY (- 1 * DENSITY)
#define Rg_MELT (- 1 * KELVIN)
#define Rg_BOIL (- 1 * KELVIN)
#define Rg_Cp (- 1 * SPECIFICHEAT)
#define Rg_En (- 1)
#define COPERNICIUMZ 112
#define COPERNICIUM 285
#define CnZ 112
#define Cn_MASS (285 * MOLARMASS)
#define CnMASS (Cn_MASS / AVOGADRO)
#define Cn_DENSITY (- 1 * DENSITY)
#define Cn_MELT (- 1 * KELVIN)
#define Cn_BOIL (357 * KELVIN)
#define Cn_Cp (- 1 * SPECIFICHEAT)
#define Cn_En (- 1)
#define NIHONIUMZ 113
#define NIHONIUM 286
#define NhZ 113
#define Nh_MASS (286 * MOLARMASS)
#define NhMASS (Nh_MASS / AVOGADRO)
#define Nh_DENSITY (- 1 * DENSITY)
#define Nh_MELT (- 1 * KELVIN)
#define Nh_BOIL (- 1 * KELVIN)
#define Nh_Cp (- 1 * SPECIFICHEAT)
#define Nh_En (- 1)
#define FLEROVIUMZ 114
#define FLEROVIUM 289
#define FlZ 114
#define Fl_MASS (289 * MOLARMASS)
#define FlMASS (Fl_MASS / AVOGADRO)
#define Fl_DENSITY (- 1 * DENSITY)
#define Fl_MELT (- 1 * KELVIN)
#define Fl_BOIL (210 * KELVIN)
#define Fl_Cp (- 1 * SPECIFICHEAT)
#define Fl_En (- 1)
#define MOSCOVIUMZ 115
#define MOSCOVIUM 290
#define McZ 115
#define Mc_MASS (290 * MOLARMASS)
#define McMASS (Mc_MASS / AVOGADRO)
#define Mc_DENSITY (- 1 * DENSITY)
#define Mc_MELT (- 1 * KELVIN)
#define Mc_BOIL (- 1 * KELVIN)
#define Mc_Cp (- 1 * SPECIFICHEAT)
#define Mc_En (- 1)
#define LIVERMORIUMZ 116
#define LIVERMORIUM 293
#define LvZ 116
#define Lv_MASS (293 * MOLARMASS)
#define LvMASS (Lv_MASS / AVOGADRO)
#define Lv_DENSITY (- 1 * DENSITY)
#define Lv_MELT (- 1 * KELVIN)
#define Lv_BOIL (- 1 * KELVIN)
#define Lv_Cp (- 1 * SPECIFICHEAT)
#define Lv_En (- 1)
#define TENNESSINEZ 117
#define TENNESSINE 294
#define TsZ 117
#define Ts_MASS (294 * MOLARMASS)
#define TsMASS (Ts_MASS / AVOGADRO)
#define Ts_DENSITY (- 1 * DENSITY)
#define Ts_MELT (- 1 * KELVIN)
#define Ts_BOIL (- 1 * KELVIN)
#define Ts_Cp (- 1 * SPECIFICHEAT)
#define Ts_En (- 1)
#define OGANESSONZ 118
#define OGANESSON 294
#define OgZ 118
#define Og_MASS (294 * MOLARMASS)
#define OgMASS (Og_MASS / AVOGADRO)
#define Og_DENSITY (- 1 * DENSITY)
#define Og_MELT (- 1 * KELVIN)
#define Og_BOIL (- 1 * KELVIN)
#define Og_Cp (- 1 * SPECIFICHEAT)
#define Og_En (- 1)
#define AIR_MASS \
      (PPM * (780781 * (2 * N_MASS) + 209444 * (2 * O_MASS) +\
            9339 * Ar_MASS + 410 * (C_MASS + 2 * O_MASS) +\
            18.18 * Ne_MASS + 5.24 * He_MASS + 1.79 * (C_MASS\
            + 4 * H_MASS) + 1.14 * Kr_MASS + 0.55 * (2 *\
            H_MASS)))
#define AIRMASS (AIR_MASS / AVOGADRO)
#define WATER_MASS (2.0 * H_MASS + O_MASS)
#define WATERMASS (2.0 * HMASS + OMASS)
#define WATER_Cp (4184 * SPECIFICHEAT)
#define ICE_Cp (2108 * SPECIFICHEAT)
#define STEAM_Cp (1996 * SPECIFICHEAT)
#define H1_MASS (1.007825032241 * MOLARMASS)
#define H1MASS (H1_MASS / AVOGADRO)
#define H2_MASS (2.01410177811 * MOLARMASS)
#define H2MASS (H2_MASS / AVOGADRO)
#define H3_MASS (3.01604928199 * MOLARMASS)
#define H3MASS (H3_MASS / AVOGADRO)
#define He3_MASS (3.01602932265 * MOLARMASS)
#define He3MASS (He3_MASS / AVOGADRO)
#define He4_MASS (4.002603254130 * MOLARMASS)
#define He4MASS (He4_MASS / AVOGADRO)
#define C12_MASS (12.0 * MOLARMASS)
#define C12MASS (C12_MASS / AVOGADRO)
#define C13_MASS (13.00335483521 * MOLARMASS)
#define C13MASS (C13_MASS / AVOGADRO)
#define C14_MASS (14.003241988 * MOLARMASS)
#define C14MASS (C14_MASS / AVOGADRO)
#define O16_MASS (15.99491461960 * MOLARMASS)
#define O16MASS (O16_MASS / AVOGADRO)
#define O17_MASS (16.9991317566 * MOLARMASS)
#define O17MASS (O17_MASS / AVOGADRO)
#define O18_MASS (17.9991596128 * MOLARMASS)
#define O18MASS (O18_MASS / AVOGADRO)
#define C13_RATIO (0.0107)
#define C14_RATIO (1E-12)
#define C12_RATIO (1.0 - C13_RATIO - C14_RATIO)
#define C_MEAN_MASS \
      (C12_MASS * C12_RATIO + C13_MASS * C13_RATIO + C14_MASS\
            * C14_RATIO)
#define VSMOW_H3_RATIO (1.85E-17)
#define VSMOW_H2_RATIO (1.5576E-4)
#define VSMOW_H1_RATIO (1.0 - VSMOW_H2_RATIO - VSMOW_H3_RATIO)
#define VSMOW_H_MASS \
      (H1_MASS * VSMOW_H1_RATIO + H2_MASS * VSMOW_H2_RATIO +\
            H3_MASS * VSMOW_H3_RATIO)
#define VSMOW_O18_RATIO (2.00520E-3)
#define VSMOW_O17_RATIO (3.799E-4)
#define VSMOW_O16_RATIO (1.0 - VSMOW_O17_RATIO - VSMOW_O18_RATIO)
#define VSMOW_O_MASS \
      (O16_MASS * VSMOW_O16_RATIO + O17_MASS *\
            VSMOW_O17_RATIO + O18_MASS * VSMOW_O18_RATIO)
#define VSMOW_MASS (2 * VSMOW_H_MASS + VSMOW_O_MASS)
#define WATER_FUSION_JPMOLE (6010 * JOULE / MOLE)
#define WATER_FUSION_JPKG (WATER_FUSION_JPMOLE / WATER_MASS)
#define WATER_VAPORIZATION_JPMOLE (40680 * JOULE / MOLE)
#define WATER_VAPORIZATION_JPKG \
      (WATER_VAPORIZATION_JPMOLE / WATER_MASS)
#define CH4_MASS \
      (4 * H_MASS + 1 * C_MASS + 0 * N_MASS + 0 * O_MASS)
#define CH4MASS (4 * HMASS + 1 * CMASS + 0 * NMASS + 0 * OMASS)
#define C2H6_MASS \
      (6 * H_MASS + 2 * C_MASS + 0 * N_MASS + 0 * O_MASS)
#define C2H6MASS (6 * HMASS + 2 * CMASS + 0 * NMASS + 0 * OMASS)
#define C3H8_MASS \
      (8 * H_MASS + 3 * C_MASS + 0 * N_MASS + 0 * O_MASS)
#define C3H8MASS (8 * HMASS + 3 * CMASS + 0 * NMASS + 0 * OMASS)
#define C4H10_MASS \
      (10 * H_MASS + 4 * C_MASS + 0 * N_MASS + 0 * O_MASS)
#define C4H10MASS \
      (10 * HMASS + 4 * CMASS + 0 * NMASS + 0 * OMASS)
#define C2H60_MASS \
      (6 * H_MASS + 2 * C_MASS + 0 * N_MASS + 1 * O_MASS)
#define C2H60MASS (6 * HMASS + 2 * CMASS + 0 * NMASS + 1 * OMASS)
#define CH3CH2OH_MASS \
      (6 * H_MASS + 2 * C_MASS + 0 * N_MASS + 1 * O_MASS)
#define CH3CH2OHMASS \
      (6 * HMASS + 2 * CMASS + 0 * NMASS + 1 * OMASS)
#define C12H22O11_MASS \
      (22 * H_MASS + 12 * C_MASS + 0 * N_MASS + 11 * O_MASS)
#define C12H22O11MASS \
      (22 * HMASS + 12 * CMASS + 0 * NMASS + 11 * OMASS)
#define SUGAR_MASS \
      (22 * H_MASS + 12 * C_MASS + 0 * N_MASS + 11 * O_MASS)
#define SUGARMASS \
      (22 * HMASS + 12 * CMASS + 0 * NMASS + 11 * OMASS)
#define SUGAR_JPMOLE \
      (1.619E+7 * SUGAR_MASS * (MOLE / KG) * JOULE / MOLE)
#define SUGAR_JPKG (SUGAR_JPMOLE / SUGAR_MASS)
#define SUGAR_JPKGTOTAL \
      (SUGAR_JPMOLE / (SUGAR_MASS + (22 / 4.0 + 12 - 11 /\
            2.0) * 2.0 * O_MASS))
#define SUGARDENSITY (845 * DENSITY)
#define SUGAR_JPL (SUGAR_JPKG * SUGARDENSITY / 1000)
#define COAL_MASS \
      (0 * H_MASS + 1 * C_MASS + 0 * N_MASS + 0 * O_MASS)
#define COALMASS (0 * HMASS + 1 * CMASS + 0 * NMASS + 0 * OMASS)
#define COAL_JPMOLE \
      (2.9307E+7 * COAL_MASS * (MOLE / KG) * JOULE / MOLE)
#define COAL_JPKG (COAL_JPMOLE / COAL_MASS)
#define COAL_JPKGTOTAL \
      (COAL_JPMOLE / (COAL_MASS + (0 / 4.0 + 1 - 0 / 2.0) *\
            2.0 * O_MASS))
#define COALDENSITY (1300 * DENSITY)
#define COAL_JPL (COAL_JPKG * COALDENSITY / 1000)
#define PARAFFIN_MASS \
      (62 * H_MASS + 30 * C_MASS + 0 * N_MASS + 0 * O_MASS)
#define PARAFFINMASS \
      (62 * HMASS + 30 * CMASS + 0 * NMASS + 0 * OMASS)
#define PARAFFIN_JPMOLE \
      (4.6E+7 * PARAFFIN_MASS * (MOLE / KG) * JOULE / MOLE)
#define PARAFFIN_JPKG (PARAFFIN_JPMOLE / PARAFFIN_MASS)
#define PARAFFIN_JPKGTOTAL \
      (PARAFFIN_JPMOLE / (PARAFFIN_MASS + (62 / 4.0 + 30 - 0\
            / 2.0) * 2.0 * O_MASS))
#define PARAFFINDENSITY (900 * DENSITY)
#define PARAFFIN_JPL (PARAFFIN_JPKG * PARAFFINDENSITY / 1000)
#define FAT_MASS \
      (100 * H_MASS + 60 * C_MASS + 0 * N_MASS + 6 * O_MASS)
#define FATMASS \
      (100 * HMASS + 60 * CMASS + 0 * NMASS + 6 * OMASS)
#define FAT_JPMOLE \
      (3.7E+7 * FAT_MASS * (MOLE / KG) * JOULE / MOLE)
#define FAT_JPKG (FAT_JPMOLE / FAT_MASS)
#define FAT_JPKGTOTAL \
      (FAT_JPMOLE / (FAT_MASS + (100 / 4.0 + 60 - 6 / 2.0) *\
            2.0 * O_MASS))
#define FATDENSITY (900 * DENSITY)
#define FAT_JPL (FAT_JPKG * FATDENSITY / 1000)
#define DIESEL_MASS \
      (26 * H_MASS + 12 * C_MASS + 0 * N_MASS + 0 * O_MASS)
#define DIESELMASS \
      (26 * HMASS + 12 * CMASS + 0 * NMASS + 0 * OMASS)
#define DIESEL_JPMOLE \
      (4.48E+7 * DIESEL_MASS * (MOLE / KG) * JOULE / MOLE)
#define DIESEL_JPKG (DIESEL_JPMOLE / DIESEL_MASS)
#define DIESEL_JPKGTOTAL \
      (DIESEL_JPMOLE / (DIESEL_MASS + (26 / 4.0 + 12 - 0 /\
            2.0) * 2.0 * O_MASS))
#define DIESELDENSITY (832 * DENSITY)
#define DIESEL_JPL (DIESEL_JPKG * DIESELDENSITY / 1000)
#define GASOLINE_MASS \
      (18 * H_MASS + 8 * C_MASS + 0 * N_MASS + 0 * O_MASS)
#define GASOLINEMASS \
      (18 * HMASS + 8 * CMASS + 0 * NMASS + 0 * OMASS)
#define GASOLINE_JPMOLE \
      (4.64E+7 * GASOLINE_MASS * (MOLE / KG) * JOULE / MOLE)
#define GASOLINE_JPKG (GASOLINE_JPMOLE / GASOLINE_MASS)
#define GASOLINE_JPKGTOTAL \
      (GASOLINE_JPMOLE / (GASOLINE_MASS + (18 / 4.0 + 8 - 0 /\
            2.0) * 2.0 * O_MASS))
#define GASOLINEDENSITY (748.9 * DENSITY)
#define GASOLINE_JPL (GASOLINE_JPKG * GASOLINEDENSITY / 1000)
#define KEROSENE_MASS \
      (28 * H_MASS + 13 * C_MASS + 0 * N_MASS + 0 * O_MASS)
#define KEROSENEMASS \
      (28 * HMASS + 13 * CMASS + 0 * NMASS + 0 * OMASS)
#define KEROSENE_JPMOLE \
      (4.62E+7 * KEROSENE_MASS * (MOLE / KG) * JOULE / MOLE)
#define KEROSENE_JPKG (KEROSENE_JPMOLE / KEROSENE_MASS)
#define KEROSENE_JPKGTOTAL \
      (KEROSENE_JPMOLE / (KEROSENE_MASS + (28 / 4.0 + 13 - 0\
            / 2.0) * 2.0 * O_MASS))
#define KEROSENEDENSITY (800 * DENSITY)
#define KEROSENE_JPL (KEROSENE_JPKG * KEROSENEDENSITY / 1000)
#define HYDROGEN_MASS \
      (2 * H_MASS + 0 * C_MASS + 0 * N_MASS + 0 * O_MASS)
#define HYDROGENMASS \
      (2 * HMASS + 0 * CMASS + 0 * NMASS + 0 * OMASS)
#define HYDROGEN_JPMOLE (2.86E+5 * JOULE / MOLE)
#define HYDROGEN_JPKG (HYDROGEN_JPMOLE / HYDROGEN_MASS)
#define HYDROGEN_JPKGTOTAL \
      (HYDROGEN_JPMOLE / (HYDROGEN_MASS + (2 / 4.0 + 0 - 0 /\
            2.0) * 2.0 * O_MASS))
#define METHANE_MASS \
      (4 * H_MASS + 1 * C_MASS + 0 * N_MASS + 0 * O_MASS)
#define METHANEMASS \
      (4 * HMASS + 1 * CMASS + 0 * NMASS + 0 * OMASS)
#define METHANE_JPMOLE (8.89E+5 * JOULE / MOLE)
#define METHANE_JPKG (METHANE_JPMOLE / METHANE_MASS)
#define METHANE_JPKGTOTAL \
      (METHANE_JPMOLE / (METHANE_MASS + (4 / 4.0 + 1 - 0 /\
            2.0) * 2.0 * O_MASS))
#define ETHANE_MASS \
      (6 * H_MASS + 2 * C_MASS + 0 * N_MASS + 0 * O_MASS)
#define ETHANEMASS \
      (6 * HMASS + 2 * CMASS + 0 * NMASS + 0 * OMASS)
#define ETHANE_JPMOLE (1.560E+6 * JOULE / MOLE)
#define ETHANE_JPKG (ETHANE_JPMOLE / ETHANE_MASS)
#define ETHANE_JPKGTOTAL \
      (ETHANE_JPMOLE / (ETHANE_MASS + (6 / 4.0 + 2 - 0 / 2.0)\
            * 2.0 * O_MASS))
#define PROPANE_MASS \
      (8 * H_MASS + 3 * C_MASS + 0 * N_MASS + 0 * O_MASS)
#define PROPANEMASS \
      (8 * HMASS + 3 * CMASS + 0 * NMASS + 0 * OMASS)
#define PROPANE_JPMOLE (2.220E+6 * JOULE / MOLE)
#define PROPANE_JPKG (PROPANE_JPMOLE / PROPANE_MASS)
#define PROPANE_JPKGTOTAL \
      (PROPANE_JPMOLE / (PROPANE_MASS + (8 / 4.0 + 3 - 0 /\
            2.0) * 2.0 * O_MASS))
#define BUTANE_MASS \
      (10 * H_MASS + 4 * C_MASS + 0 * N_MASS + 0 * O_MASS)
#define BUTANEMASS \
      (10 * HMASS + 4 * CMASS + 0 * NMASS + 0 * OMASS)
#define BUTANE_JPMOLE (2.877E+6 * JOULE / MOLE)
#define BUTANE_JPKG (BUTANE_JPMOLE / BUTANE_MASS)
#define BUTANE_JPKGTOTAL \
      (BUTANE_JPMOLE / (BUTANE_MASS + (10 / 4.0 + 4 - 0 /\
            2.0) * 2.0 * O_MASS))
#define PENTANE_MASS \
      (12 * H_MASS + 5 * C_MASS + 0 * N_MASS + 0 * O_MASS)
#define PENTANEMASS \
      (12 * HMASS + 5 * CMASS + 0 * NMASS + 0 * OMASS)
#define PENTANE_JPMOLE (3.507E+6 * JOULE / MOLE)
#define PENTANE_JPKG (PENTANE_JPMOLE / PENTANE_MASS)
#define PENTANE_JPKGTOTAL \
      (PENTANE_JPMOLE / (PENTANE_MASS + (12 / 4.0 + 5 - 0 /\
            2.0) * 2.0 * O_MASS))
#define HEXANE_MASS \
      (14 * H_MASS + 6 * C_MASS + 0 * N_MASS + 0 * O_MASS)
#define HEXANEMASS \
      (14 * HMASS + 6 * CMASS + 0 * NMASS + 0 * OMASS)
#define HEXANE_JPMOLE (4.160E+6 * JOULE / MOLE)
#define HEXANE_JPKG (HEXANE_JPMOLE / HEXANE_MASS)
#define HEXANE_JPKGTOTAL \
      (HEXANE_JPMOLE / (HEXANE_MASS + (14 / 4.0 + 6 - 0 /\
            2.0) * 2.0 * O_MASS))
#define ETHANOL_MASS \
      (6 * H_MASS + 2 * C_MASS + 0 * N_MASS + 1 * O_MASS)
#define ETHANOLMASS \
      (6 * HMASS + 2 * CMASS + 0 * NMASS + 1 * OMASS)
#define ETHANOL_JPMOLE (1.300E+6 * JOULE / MOLE)
#define ETHANOL_JPKG (ETHANOL_JPMOLE / ETHANOL_MASS)
#define ETHANOL_JPKGTOTAL \
      (ETHANOL_JPMOLE / (ETHANOL_MASS + (6 / 4.0 + 2 - 1 /\
            2.0) * 2.0 * O_MASS))
#define SUCROSE_MASS \
      (22 * H_MASS + 12 * C_MASS + 0 * N_MASS + 11 * O_MASS)
#define SUCROSEMASS \
      (22 * HMASS + 12 * CMASS + 0 * NMASS + 11 * OMASS)
#define SUCROSE_JPMOLE (5.6467E+6 * JOULE / MOLE)
#define SUCROSE_JPKG (SUCROSE_JPMOLE / SUCROSE_MASS)
#define SUCROSE_JPKGTOTAL \
      (SUCROSE_JPMOLE / (SUCROSE_MASS + (22 / 4.0 + 12 - 11 /\
            2.0) * 2.0 * O_MASS))
#define TNTJPKG (4.184E+6 * JOULE / KILOGRAM)
//  DDDDDDDDDDescription --------------- kwelements_description #
#define Kwelements_DESCRIPTION \
   "   Kwelements Constants: Ac_BOIL Ac_Cp Ac_DENSITY Ac_En Ac_"\
   "MASS Ac_MELT AcMASS ACTINIUM ACTINIUMZ AcZ Ag_BOIL Ag_Cp Ag"\
   "_DENSITY Ag_En Ag_MASS Ag_MELT AgMASS AgZ AIR_MASS AIRMASS "\
   "Al_BOIL Al_Cp Al_DENSITY Al_En Al_MASS Al_MELT AlMASS ALUMI"\
   "NIUM ALUMINIUMZ AlZ Am_BOIL Am_Cp Am_DENSITY Am_En Am_MASS "\
   "Am_MELT AMERICIUM AMERICIUMZ AmMASS AmZ ANTIMONY ANTIMONYZ "\
   "Ar_BOIL Ar_Cp Ar_DENSITY Ar_En Ar_MASS Ar_MELT ARGON ARGONZ"\
   " ArMASS ARSENIC ARSENICZ ArZ As_BOIL As_Cp As_DENSITY As_En"\
   " As_MASS As_MELT AsMASS ASTATINE ASTATINEZ AsZ At_BOIL At_C"\
   "p At_DENSITY At_En At_MASS At_MELT AtMASS AtZ Au_BOIL Au_Cp"\
   " Au_DENSITY Au_En Au_MASS Au_MELT AuMASS AuZ B_BOIL B_Cp B_"\
   "DENSITY B_En B_MASS B_MELT Ba_BOIL Ba_Cp Ba_DENSITY Ba_En B"\
   "a_MASS Ba_MELT BaMASS BARIUM BARIUMZ BaZ Be_BOIL Be_Cp Be_D"\
   "ENSITY Be_En Be_MASS Be_MELT BeMASS BERKELIUM BERKELIUMZ BE"\
   "RYLLIUM BERYLLIUMZ BeZ Bh_BOIL Bh_Cp Bh_DENSITY Bh_En Bh_MA"\
   "SS Bh_MELT BhMASS BhZ Bi_BOIL Bi_Cp Bi_DENSITY Bi_En Bi_MAS"\
   "S Bi_MELT BiMASS BISMUTH BISMUTHZ BiZ Bk_BOIL Bk_Cp Bk_DENS"\
   "ITY Bk_En Bk_MASS Bk_MELT BkMASS BkZ BMASS BOHRIUM BOHRIUMZ"\
   " BORON BORONZ Br_BOIL Br_Cp Br_DENSITY Br_En Br_MASS Br_MEL"\
   "T BrMASS BROMINE BROMINEZ BrZ BUTANE_JPKG BUTANE_JPKGTOTAL "\
   "BUTANE_JPMOLE BUTANE_MASS BUTANEMASS BZ C12_MASS C12_RATIO "\
   "C12H22O11_MASS C12H22O11MASS C12MASS C13_MASS C13_RATIO C13"\
   "MASS C14_MASS C14_RATIO C14MASS C2H60_MASS C2H60MASS C2H6_M"\
   "ASS C2H6MASS C3H8_MASS C3H8MASS C4H10_MASS C4H10MASS C_BOIL"\
   " C_Cp C_DENSITY C_En C_MASS C_MEAN_MASS C_MELT Ca_BOIL Ca_C"\
   "p Ca_DENSITY Ca_En Ca_MASS Ca_MELT CADMIUM CADMIUMZ CAESIUM"\
   " CAESIUMZ CALCIUM CALCIUMZ CALIFORNIUM CALIFORNIUMZ CaMASS "\
   "CARBON CARBONZ CaZ Cd_BOIL Cd_Cp Cd_DENSITY Cd_En Cd_MASS C"\
   "d_MELT CdMASS CdZ Ce_BOIL Ce_Cp Ce_DENSITY Ce_En Ce_MASS Ce"\
   "_MELT CeMASS CERIUM CERIUMZ CeZ Cf_BOIL Cf_Cp Cf_DENSITY Cf"\
   "_En Cf_MASS Cf_MELT CfMASS CfZ CH3CH2OH_MASS CH3CH2OHMASS C"\
   "H4_MASS CH4MASS CHLORINE CHLORINEZ CHROMIUM CHROMIUMZ Cl_BO"\
   "IL Cl_Cp Cl_DENSITY Cl_En Cl_MASS Cl_MELT ClMASS ClZ Cm_BOI"\
   "L Cm_Cp Cm_DENSITY Cm_En Cm_MASS Cm_MELT CMASS CmMASS CmZ C"\
   "n_BOIL Cn_Cp Cn_DENSITY Cn_En Cn_MASS Cn_MELT CnMASS CnZ Co"\
   "_BOIL Co_Cp Co_DENSITY Co_En Co_MASS Co_MELT COAL_JPKG COAL"\
   "_JPKGTOTAL COAL_JPL COAL_JPMOLE COAL_MASS COALDENSITY COALM"\
   "ASS COBALT COBALTZ CoMASS COPERNICIUM COPERNICIUMZ COPPER C"\
   "OPPERZ CoZ Cr_BOIL Cr_Cp Cr_DENSITY Cr_En Cr_MASS Cr_MELT C"\
   "rMASS CrZ Cs_BOIL Cs_Cp Cs_DENSITY Cs_En Cs_MASS Cs_MELT Cs"\
   "MASS CsZ Cu_BOIL Cu_Cp Cu_DENSITY Cu_En Cu_MASS Cu_MELT CuM"\
   "ASS CURIUM CURIUMZ CuZ CZ DARMSTADTIUM DARMSTADTIUMZ Db_BOI"\
   "L Db_Cp Db_DENSITY Db_En Db_MASS Db_MELT DbMASS DbZ DIESEL_"\
   "JPKG DIESEL_JPKGTOTAL DIESEL_JPL DIESEL_JPMOLE DIESEL_MASS "\
   "DIESELDENSITY DIESELMASS Ds_BOIL Ds_Cp Ds_DENSITY Ds_En Ds_"\
   "MASS Ds_MELT DsMASS DsZ DUBNIUM DUBNIUMZ Dy_BOIL Dy_Cp Dy_D"\
   "ENSITY Dy_En Dy_MASS Dy_MELT DyMASS DYSPROSIUM DYSPROSIUMZ "\
   "DyZ EINSTEINIUM EINSTEINIUMZ Er_BOIL Er_Cp Er_DENSITY Er_En"\
   " Er_MASS Er_MELT ERBIUM ERBIUMZ ErMASS ErZ Es_BOIL Es_Cp Es"\
   "_DENSITY Es_En Es_MASS Es_MELT EsMASS EsZ ETHANE_JPKG ETHAN"\
   "E_JPKGTOTAL ETHANE_JPMOLE ETHANE_MASS ETHANEMASS ETHANOL_JP"\
   "KG ETHANOL_JPKGTOTAL ETHANOL_JPMOLE ETHANOL_MASS ETHANOLMAS"\
   "S Eu_BOIL Eu_Cp Eu_DENSITY Eu_En Eu_MASS Eu_MELT EuMASS EUR"\
   "OPIUM EUROPIUMZ EuZ F_BOIL F_Cp F_DENSITY F_En F_MASS F_MEL"\
   "T FAT_JPKG FAT_JPKGTOTAL FAT_JPL FAT_JPMOLE FAT_MASS FATDEN"\
   "SITY FATMASS Fe_BOIL Fe_Cp Fe_DENSITY Fe_En Fe_MASS Fe_MELT"\
   " FeMASS FERMIUM FERMIUMZ FeZ Fl_BOIL Fl_Cp Fl_DENSITY Fl_En"\
   " Fl_MASS Fl_MELT FLEROVIUM FLEROVIUMZ FlMASS FLUORINE FLUOR"\
   "INEZ FlZ Fm_BOIL Fm_Cp Fm_DENSITY Fm_En Fm_MASS Fm_MELT FMA"\
   "SS FmMASS FmZ Fr_BOIL Fr_Cp Fr_DENSITY Fr_En Fr_MASS Fr_MEL"\
   "T FRANCIUM FRANCIUMZ FrMASS FrZ FZ Ga_BOIL Ga_Cp Ga_DENSITY"\
   " Ga_En Ga_MASS Ga_MELT GADOLINIUM GADOLINIUMZ GALLIUM GALLI"\
   "UMZ GaMASS GASOLINE_JPKG GASOLINE_JPKGTOTAL GASOLINE_JPL GA"\
   "SOLINE_JPMOLE GASOLINE_MASS GASOLINEDENSITY GASOLINEMASS Ga"\
   "Z Gd_BOIL Gd_Cp Gd_DENSITY Gd_En Gd_MASS Gd_MELT GdMASS GdZ"\
   " Ge_BOIL Ge_Cp Ge_DENSITY Ge_En Ge_MASS Ge_MELT GeMASS GERM"\
   "ANIUM GERMANIUMZ GeZ GOLD GOLDZ H1_MASS H1MASS H2_MASS H2MA"\
   "SS H3_MASS H3MASS H_BOIL H_Cp H_DENSITY H_En H_MASS H_MELT "\
   "HAFNIUM HAFNIUMZ HASSIUM HASSIUMZ He3_MASS He3MASS He4_MASS"\
   " He4MASS He_BOIL He_Cp He_DENSITY He_En He_MASS He_MELT HEL"\
   "IUM HELIUMZ HeMASS HEXANE_JPKG HEXANE_JPKGTOTAL HEXANE_JPMO"\
   "LE HEXANE_MASS HEXANEMASS HeZ Hf_BOIL Hf_Cp Hf_DENSITY Hf_E"\
   "n Hf_MASS Hf_MELT HfMASS HfZ Hg_BOIL Hg_Cp Hg_DENSITY Hg_En"\
   " Hg_MASS Hg_MELT HgMASS HgZ HMASS Ho_BOIL Ho_Cp Ho_DENSITY "\
   "Ho_En Ho_MASS Ho_MELT HOLMIUM HOLMIUMZ HoMASS HoZ Hs_BOIL H"\
   "s_Cp Hs_DENSITY Hs_En Hs_MASS Hs_MELT HsMASS HsZ HYDROGEN H"\
   "YDROGEN_JPKG HYDROGEN_JPKGTOTAL HYDROGEN_JPMOLE HYDROGEN_MA"\
   "SS HYDROGENMASS HYDROGENZ HZ I_BOIL I_Cp I_DENSITY I_En I_M"\
   "ASS I_MELT ICE_Cp IMASS In_BOIL In_Cp In_DENSITY In_En In_M"\
   "ASS In_MELT INDIUM INDIUMZ InMASS InZ IODINE IODINEZ Ir_BOI"\
   "L Ir_Cp Ir_DENSITY Ir_En Ir_MASS Ir_MELT IRIDIUM IRIDIUMZ I"\
   "rMASS IRON IRONZ IrZ IZ K_BOIL K_Cp K_DENSITY K_En K_MASS K"\
   "_MELT KEROSENE_JPKG KEROSENE_JPKGTOTAL KEROSENE_JPL KEROSEN"\
   "E_JPMOLE KEROSENE_MASS KEROSENEDENSITY KEROSENEMASS KMASS K"\
   "r_BOIL Kr_Cp Kr_DENSITY Kr_En Kr_MASS Kr_MELT KrMASS KRYPTO"\
   "N KRYPTONZ KrZ KZ La_BOIL La_Cp La_DENSITY La_En La_MASS La"\
   "_MELT LaMASS LANTHANUM LANTHANUMZ LAWRENCIUM LAWRENCIUMZ La"\
   "Z LEAD LEADZ Li_BOIL Li_Cp Li_DENSITY Li_En Li_MASS Li_MELT"\
   " LiMASS LITHIUM LITHIUMZ LIVERMORIUM LIVERMORIUMZ LiZ Lr_BO"\
   "IL Lr_Cp Lr_DENSITY Lr_En Lr_MASS Lr_MELT LrMASS LrZ Lu_BOI"\
   "L Lu_Cp Lu_DENSITY Lu_En Lu_MASS Lu_MELT LuMASS LUTETIUM LU"\
   "TETIUMZ LuZ Lv_BOIL Lv_Cp Lv_DENSITY Lv_En Lv_MASS Lv_MELT "\
   "LvMASS LvZ MAGNESIUM MAGNESIUMZ MANGANESE MANGANESEZ Mc_BOI"\
   "L Mc_Cp Mc_DENSITY Mc_En Mc_MASS Mc_MELT McMASS McZ Md_BOIL"\
   " Md_Cp Md_DENSITY Md_En Md_MASS Md_MELT MdMASS MdZ MEITNERI"\
   "UM MEITNERIUMZ MENDELEVIUM MENDELEVIUMZ MERCURY MERCURYZ ME"\
   "THANE_JPKG METHANE_JPKGTOTAL METHANE_JPMOLE METHANE_MASS ME"\
   "THANEMASS Mg_BOIL Mg_Cp Mg_DENSITY Mg_En Mg_MASS Mg_MELT Mg"\
   "MASS MgZ Mn_BOIL Mn_Cp Mn_DENSITY Mn_En Mn_MASS Mn_MELT MnM"\
   "ASS MnZ Mo_BOIL Mo_Cp Mo_DENSITY Mo_En Mo_MASS Mo_MELT MOLY"\
   "BDENUM MOLYBDENUMZ MoMASS MOSCOVIUM MOSCOVIUMZ MoZ Mt_BOIL "\
   "Mt_Cp Mt_DENSITY Mt_En Mt_MASS Mt_MELT MtMASS MtZ N_BOIL N_"\
   "Cp N_DENSITY N_En N_MASS N_MELT Na_BOIL Na_Cp Na_DENSITY Na"\
   "_En Na_MASS Na_MELT NaMASS NaZ Nb_BOIL Nb_Cp Nb_DENSITY Nb_"\
   "En Nb_MASS Nb_MELT NbMASS NbZ Nd_BOIL Nd_Cp Nd_DENSITY Nd_E"\
   "n Nd_MASS Nd_MELT NdMASS NdZ Ne_BOIL Ne_Cp Ne_DENSITY Ne_En"\
   " Ne_MASS Ne_MELT NeMASS NEODYMIUM NEODYMIUMZ NEON NEONZ NEP"\
   "TUNIUM NEPTUNIUMZ NeZ Nh_BOIL Nh_Cp Nh_DENSITY Nh_En Nh_MAS"\
   "S Nh_MELT NhMASS NhZ Ni_BOIL Ni_Cp Ni_DENSITY Ni_En Ni_MASS"\
   " Ni_MELT NICKEL NICKELZ NIHONIUM NIHONIUMZ NiMASS NIOBIUM N"\
   "IOBIUMZ NITROGEN NITROGENZ NiZ NMASS No_BOIL No_Cp No_DENSI"\
   "TY No_En No_MASS No_MELT NOBELIUM NOBELIUMZ NoMASS NoZ Np_B"\
   "OIL Np_Cp Np_DENSITY Np_En Np_MASS Np_MELT NpMASS NpZ NZ O1"\
   "6_MASS O16MASS O17_MASS O17MASS O18_MASS O18MASS O_BOIL O_C"\
   "p O_DENSITY O_En O_MASS O_MELT Og_BOIL Og_Cp Og_DENSITY Og_"\
   "En Og_MASS Og_MELT OGANESSON OGANESSONZ OgMASS OgZ OMASS Os"\
   "_BOIL Os_Cp Os_DENSITY Os_En Os_MASS Os_MELT OsMASS OSMIUM "\
   "OSMIUMZ OsZ OXYGEN OXYGENZ OZ P_BOIL P_Cp P_DENSITY P_En P_"\
   "MASS P_MELT Pa_BOIL Pa_Cp Pa_DENSITY Pa_En Pa_MASS Pa_MELT "\
   "PALLADIUM PALLADIUMZ PaMASS PARAFFIN_JPKG PARAFFIN_JPKGTOTA"\
   "L PARAFFIN_JPL PARAFFIN_JPMOLE PARAFFIN_MASS PARAFFINDENSIT"\
   "Y PARAFFINMASS PaZ Pb_BOIL Pb_Cp Pb_DENSITY Pb_En Pb_MASS P"\
   "b_MELT PbMASS PbZ Pd_BOIL Pd_Cp Pd_DENSITY Pd_En Pd_MASS Pd"\
   "_MELT PdMASS PdZ PENTANE_JPKG PENTANE_JPKGTOTAL PENTANE_JPM"\
   "OLE PENTANE_MASS PENTANEMASS PHOSPHORUS PHOSPHORUSZ PLATINU"\
   "M PLATINUMZ PLUTONIUM PLUTONIUMZ Pm_BOIL Pm_Cp Pm_DENSITY P"\
   "m_En Pm_MASS Pm_MELT PMASS PmMASS PmZ Po_BOIL Po_Cp Po_DENS"\
   "ITY Po_En Po_MASS Po_MELT POLONIUM POLONIUMZ PoMASS POTASSI"\
   "UM POTASSIUMZ PoZ Pr_BOIL Pr_Cp Pr_DENSITY Pr_En Pr_MASS Pr"\
   "_MELT PRASEODYMIUM PRASEODYMIUMZ PrMASS PROMETHIUM PROMETHI"\
   "UMZ PROPANE_JPKG PROPANE_JPKGTOTAL PROPANE_JPMOLE PROPANE_M"\
   "ASS PROPANEMASS PROTACTINIUM PROTACTINIUMZ PrZ Pt_BOIL Pt_C"\
   "p Pt_DENSITY Pt_En Pt_MASS Pt_MELT PtMASS PtZ Pu_BOIL Pu_Cp"\
   " Pu_DENSITY Pu_En Pu_MASS Pu_MELT PuMASS PuZ PZ Ra_BOIL Ra_"\
   "Cp Ra_DENSITY Ra_En Ra_MASS Ra_MELT RADIUM RADIUMZ RADON RA"\
   "DONZ RaMASS RaZ Rb_BOIL Rb_Cp Rb_DENSITY Rb_En Rb_MASS Rb_M"\
   "ELT RbMASS RbZ Re_BOIL Re_Cp Re_DENSITY Re_En Re_MASS Re_ME"\
   "LT ReMASS ReZ Rf_BOIL Rf_Cp Rf_DENSITY Rf_En Rf_MASS Rf_MEL"\
   "T RfMASS RfZ Rg_BOIL Rg_Cp Rg_DENSITY Rg_En Rg_MASS Rg_MELT"\
   " RgMASS RgZ Rh_BOIL Rh_Cp Rh_DENSITY Rh_En Rh_MASS Rh_MELT "\
   "RHENIUM RHENIUMZ RhMASS RHODIUM RHODIUMZ RhZ Rn_BOIL Rn_Cp "\
   "Rn_DENSITY Rn_En Rn_MASS Rn_MELT RnMASS RnZ ROENTGENIUM ROE"\
   "NTGENIUMZ Ru_BOIL Ru_Cp Ru_DENSITY Ru_En Ru_MASS Ru_MELT RU"\
   "BIDIUM RUBIDIUMZ RuMASS RUTHENIUM RUTHENIUMZ RUTHERFORDIUM "\
   "RUTHERFORDIUMZ RuZ S_BOIL S_Cp S_DENSITY S_En S_MASS S_MELT"\
   " SAMARIUM SAMARIUMZ Sb_BOIL Sb_Cp Sb_DENSITY Sb_En Sb_MASS "\
   "Sb_MELT SbMASS SbZ Sc_BOIL Sc_Cp Sc_DENSITY Sc_En Sc_MASS S"\
   "c_MELT SCANDIUM SCANDIUMZ ScMASS ScZ Se_BOIL Se_Cp Se_DENSI"\
   "TY Se_En Se_MASS Se_MELT SEABORGIUM SEABORGIUMZ SELENIUM SE"\
   "LENIUMZ SeMASS SeZ Sg_BOIL Sg_Cp Sg_DENSITY Sg_En Sg_MASS S"\
   "g_MELT SgMASS SgZ Si_BOIL Si_Cp Si_DENSITY Si_En Si_MASS Si"\
   "_MELT SILICON SILICONZ SILVER SILVERZ SiMASS SiZ Sm_BOIL Sm"\
   "_Cp Sm_DENSITY Sm_En Sm_MASS Sm_MELT SMASS SmMASS SmZ Sn_BO"\
   "IL Sn_Cp Sn_DENSITY Sn_En Sn_MASS Sn_MELT SnMASS SnZ SODIUM"\
   " SODIUMZ Sr_BOIL Sr_Cp Sr_DENSITY Sr_En Sr_MASS Sr_MELT SrM"\
   "ASS SrZ STEAM_Cp STRONTIUM STRONTIUMZ SUCROSE_JPKG SUCROSE_"\
   "JPKGTOTAL SUCROSE_JPMOLE SUCROSE_MASS SUCROSEMASS SUGAR_JPK"\
   "G SUGAR_JPKGTOTAL SUGAR_JPL SUGAR_JPMOLE SUGAR_MASS SUGARDE"\
   "NSITY SUGARMASS SULFUR SULFURZ SZ Ta_BOIL Ta_Cp Ta_DENSITY "\
   "Ta_En Ta_MASS Ta_MELT TaMASS TANTALUM TANTALUMZ TaZ Tb_BOIL"\
   " Tb_Cp Tb_DENSITY Tb_En Tb_MASS Tb_MELT TbMASS TbZ Tc_BOIL "\
   "Tc_Cp Tc_DENSITY Tc_En Tc_MASS Tc_MELT TcMASS TcZ Te_BOIL T"\
   "e_Cp Te_DENSITY Te_En Te_MASS Te_MELT TECHNETIUM TECHNETIUM"\
   "Z TELLURIUM TELLURIUMZ TeMASS TENNESSINE TENNESSINEZ TERBIU"\
   "M TERBIUMZ TeZ Th_BOIL Th_Cp Th_DENSITY Th_En Th_MASS Th_ME"\
   "LT THALLIUM THALLIUMZ ThMASS THORIUM THORIUMZ THULIUM THULI"\
   "UMZ ThZ Ti_BOIL Ti_Cp Ti_DENSITY Ti_En Ti_MASS Ti_MELT TiMA"\
   "SS TIN TINZ TITANIUM TITANIUMZ TiZ Tl_BOIL Tl_Cp Tl_DENSITY"\
   " Tl_En Tl_MASS Tl_MELT TlMASS TlZ Tm_BOIL Tm_Cp Tm_DENSITY "\
   "Tm_En Tm_MASS Tm_MELT TmMASS TmZ TNTJPKG Ts_BOIL Ts_Cp Ts_D"\
   "ENSITY Ts_En Ts_MASS Ts_MELT TsMASS TsZ TUNGSTEN TUNGSTENZ "\
   "U_BOIL U_Cp U_DENSITY U_En U_MASS U_MELT UMASS URANIUM URAN"\
   "IUMZ UZ V_BOIL V_Cp V_DENSITY V_En V_MASS V_MELT VANADIUM V"\
   "ANADIUMZ VMASS VSMOW_H1_RATIO VSMOW_H2_RATIO VSMOW_H3_RATIO"\
   " VSMOW_H_MASS VSMOW_MASS VSMOW_O16_RATIO VSMOW_O17_RATIO VS"\
   "MOW_O18_RATIO VSMOW_O_MASS VZ W_BOIL W_Cp W_DENSITY W_En W_"\
   "MASS W_MELT WATER_Cp WATER_FUSION_JPKG WATER_FUSION_JPMOLE "\
   "WATER_MASS WATER_VAPORIZATION_JPKG WATER_VAPORIZATION_JPMOL"\
   "E WATERMASS WMASS WZ Xe_BOIL Xe_Cp Xe_DENSITY Xe_En Xe_MASS"\
   " Xe_MELT XeMASS XENON XENONZ XeZ Y_BOIL Y_Cp Y_DENSITY Y_En"\
   " Y_MASS Y_MELT Yb_BOIL Yb_Cp Yb_DENSITY Yb_En Yb_MASS Yb_ME"\
   "LT YbMASS YbZ YMASS YTTERBIUM YTTERBIUMZ YTTRIUM YTTRIUMZ Y"\
   "Z ZINC ZINCZ ZIRCONIUM ZIRCONIUMZ Zn_BOIL Zn_Cp Zn_DENSITY "\
   "Zn_En Zn_MASS Zn_MELT ZnMASS ZnZ Zr_BOIL Zr_Cp Zr_DENSITY Z"\
   "r_En Zr_MASS Zr_MELT ZrMASS ZrZ"\
   "\n"
#define Kwelements_DESC \
   "   Kwelements Constants: Ac_(BOIL|Cp|DENSITY|En|M(ASS|ELT))"\
   " AcMASS ACTINIUMZ? AcZ Ag_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) A"\
   "gMASS AgZ AIR(_MASS|MASS) Al_(BOIL|Cp|DENSITY|En|M(ASS|ELT)"\
   ") AlMASS ALUMINIUMZ? AlZ Am_(BOIL|Cp|DENSITY|En|M(ASS|ELT))"\
   " AMERICIUMZ? AmMASS AmZ ANTIMONYZ? Ar_(BOIL|Cp|DENSITY|En|M"\
   "(ASS|ELT)) ARGONZ? ArMASS ARSENICZ? ArZ As_(BOIL|Cp|DENSITY"\
   "|En|M(ASS|ELT)) AsMASS ASTATINEZ? AsZ At_(BOIL|Cp|DENSITY|E"\
   "n|M(ASS|ELT)) AtMASS AtZ Au_(BOIL|Cp|DENSITY|En|M(ASS|ELT))"\
   " AuMASS AuZ B_BOIL B_Cp B_DENSITY B_En B_M(ASS|ELT) Ba_(BOI"\
   "L|Cp|DENSITY|En|M(ASS|ELT)) BaMASS BARIUMZ? BaZ Be_(BOIL|Cp"\
   "|DENSITY|En|M(ASS|ELT)) BeMASS BER(KELIUMZ?|YLLIUMZ?) BeZ B"\
   "h_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) BhMASS BhZ Bi_(BOIL|Cp|DE"\
   "NSITY|En|M(ASS|ELT)) BiMASS BISMUTHZ? BiZ Bk_(BOIL|Cp|DENSI"\
   "TY|En|M(ASS|ELT)) BkMASS BkZ BMASS BOHRIUMZ? BORONZ? Br_(BO"\
   "IL|Cp|DENSITY|En|M(ASS|ELT)) BrMASS BROMINEZ? BrZ BUTANE(_("\
   "JP(KG(TOTAL)?|MOLE)|MASS)|MASS) BZ C12(_(MASS|RATIO)|H22O11"\
   "(_MASS|MASS)|MASS) C13(_(MASS|RATIO)|MASS) C14(_(MASS|RATIO"\
   ")|MASS) C2H6(0(_MASS|MASS)|_MASS|MASS) C3H8(_MASS|MASS) C4H"\
   "10(_MASS|MASS) C_BOIL C_Cp C_DENSITY C_En C_M(ASS|E(AN_MASS"\
   "|LT)) Ca_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) CADMIUMZ? CAESIUMZ"\
   "? CAL(CIUMZ?|IFORNIUMZ?) CaMASS CARBONZ? CaZ Cd_(BOIL|Cp|DE"\
   "NSITY|En|M(ASS|ELT)) CdMASS CdZ Ce_(BOIL|Cp|DENSITY|En|M(AS"\
   "S|ELT)) CeMASS CERIUMZ? CeZ Cf_(BOIL|Cp|DENSITY|En|M(ASS|EL"\
   "T)) CfMASS CfZ CH3CH2OH(_MASS|MASS) CH4(_MASS|MASS) CHLORIN"\
   "EZ? CHROMIUMZ? Cl_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) ClMASS Cl"\
   "Z Cm_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) CMASS CmMASS CmZ Cn_(B"\
   "OIL|Cp|DENSITY|En|M(ASS|ELT)) CnMASS CnZ Co_(BOIL|Cp|DENSIT"\
   "Y|En|M(ASS|ELT)) COAL(_(JP(KG(TOTAL)?|L|MOLE)|MASS)|DENSITY"\
   "|MASS) COBALTZ? CoMASS COP(ERNICIUMZ?|PERZ?) CoZ Cr_(BOIL|C"\
   "p|DENSITY|En|M(ASS|ELT)) CrMASS CrZ Cs_(BOIL|Cp|DENSITY|En|"\
   "M(ASS|ELT)) CsMASS CsZ Cu_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) C"\
   "uMASS CURIUMZ? CuZ CZ DARMSTADTIUMZ? Db_(BOIL|Cp|DENSITY|En"\
   "|M(ASS|ELT)) DbMASS DbZ DIESEL(_(JP(KG(TOTAL)?|L|MOLE)|MASS"\
   ")|DENSITY|MASS) Ds_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) DsMASS D"\
   "sZ DUBNIUMZ? Dy_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) DyMASS DYSP"\
   "ROSIUMZ? DyZ EINSTEINIUMZ? Er_(BOIL|Cp|DENSITY|En|M(ASS|ELT"\
   ")) ERBIUMZ? ErMASS ErZ Es_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) E"\
   "sMASS EsZ ETHAN(E(_(JP(KG(TOTAL)?|MOLE)|MASS)|MASS)|OL(_(JP"\
   "(KG(TOTAL)?|MOLE)|MASS)|MASS)) Eu_(BOIL|Cp|DENSITY|En|M(ASS"\
   "|ELT)) EuMASS EUROPIUMZ? EuZ F_BOIL F_Cp F_DENSITY F_En F_M"\
   "(ASS|ELT) FAT(_(JP(KG(TOTAL)?|L|MOLE)|MASS)|DENSITY|MASS) F"\
   "e_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) FeMASS FERMIUMZ? FeZ Fl_("\
   "BOIL|Cp|DENSITY|En|M(ASS|ELT)) FLEROVIUMZ? FlMASS FLUORINEZ"\
   "? FlZ Fm_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) FMASS FmMASS FmZ F"\
   "r_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) FRANCIUMZ? FrMASS FrZ FZ "\
   "Ga_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) GADOLINIUMZ? GALLIUMZ? G"\
   "aMASS GASOLINE(_(JP(KG(TOTAL)?|L|MOLE)|MASS)|DENSITY|MASS) "\
   "GaZ Gd_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) GdMASS GdZ Ge_(BOIL|"\
   "Cp|DENSITY|En|M(ASS|ELT)) GeMASS GERMANIUMZ? GeZ GOLDZ? H1_"\
   "MASS H1MASS H2_MASS H2MASS H3_MASS H3MASS H_BOIL H_Cp H_DEN"\
   "SITY H_En H_M(ASS|ELT) HAFNIUMZ? HASSIUMZ? He3(_MASS|MASS) "\
   "He4(_MASS|MASS) He_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) HELIUMZ?"\
   " HeMASS HEXANE(_(JP(KG(TOTAL)?|MOLE)|MASS)|MASS) HeZ Hf_(BO"\
   "IL|Cp|DENSITY|En|M(ASS|ELT)) HfMASS HfZ Hg_(BOIL|Cp|DENSITY"\
   "|En|M(ASS|ELT)) HgMASS HgZ HMASS Ho_(BOIL|Cp|DENSITY|En|M(A"\
   "SS|ELT)) HOLMIUMZ? HoMASS HoZ Hs_(BOIL|Cp|DENSITY|En|M(ASS|"\
   "ELT)) HsMASS HsZ HYDROGEN(|_(JP(KG(TOTAL)?|MOLE)|MASS)|MASS"\
   "|Z) HZ I_BOIL I_Cp I_DENSITY I_En I_M(ASS|ELT) ICE_Cp IMASS"\
   " In_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) INDIUMZ? InMASS InZ IOD"\
   "INEZ? Ir_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) IRIDIUMZ? IrMASS I"\
   "RONZ? IrZ IZ K_BOIL K_Cp K_DENSITY K_En K_M(ASS|ELT) KEROSE"\
   "NE(_(JP(KG(TOTAL)?|L|MOLE)|MASS)|DENSITY|MASS) KMASS Kr_(BO"\
   "IL|Cp|DENSITY|En|M(ASS|ELT)) KrMASS KRYPTONZ? KrZ KZ La_(BO"\
   "IL|Cp|DENSITY|En|M(ASS|ELT)) LaMASS LANTHANUMZ? LAWRENCIUMZ"\
   "? LaZ LEADZ? Li_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) LiMASS LITH"\
   "IUMZ? LIVERMORIUMZ? LiZ Lr_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) "\
   "LrMASS LrZ Lu_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) LuMASS LUTETI"\
   "UMZ? LuZ Lv_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) LvMASS LvZ MAGN"\
   "ESIUMZ? MANGANESEZ? Mc_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) McMA"\
   "SS McZ Md_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) MdMASS MdZ MEITNE"\
   "RIUMZ? MENDELEVIUMZ? MERCURYZ? METHANE(_(JP(KG(TOTAL)?|MOLE"\
   ")|MASS)|MASS) Mg_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) MgMASS MgZ"\
   " Mn_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) MnMASS MnZ Mo_(BOIL|Cp|"\
   "DENSITY|En|M(ASS|ELT)) MOLYBDENUMZ? MoMASS MOSCOVIUMZ? MoZ "\
   "Mt_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) MtMASS MtZ N_BOIL N_Cp N"\
   "_DENSITY N_En N_M(ASS|ELT) Na_(BOIL|Cp|DENSITY|En|M(ASS|ELT"\
   ")) NaMASS NaZ Nb_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) NbMASS NbZ"\
   " Nd_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) NdMASS NdZ Ne_(BOIL|Cp|"\
   "DENSITY|En|M(ASS|ELT)) NeMASS NEO(DYMIUMZ?|NZ?) NEPTUNIUMZ?"\
   " NeZ Nh_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) NhMASS NhZ Ni_(BOIL"\
   "|Cp|DENSITY|En|M(ASS|ELT)) NICKELZ? NIHONIUMZ? NiMASS NIOBI"\
   "UMZ? NITROGENZ? NiZ NMASS No_(BOIL|Cp|DENSITY|En|M(ASS|ELT)"\
   ") NOBELIUMZ? NoMASS NoZ Np_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) "\
   "NpMASS NpZ NZ O16(_MASS|MASS) O17(_MASS|MASS) O18(_MASS|MAS"\
   "S) O_BOIL O_Cp O_DENSITY O_En O_M(ASS|ELT) Og_(BOIL|Cp|DENS"\
   "ITY|En|M(ASS|ELT)) OGANESSONZ? OgMASS OgZ OMASS Os_(BOIL|Cp"\
   "|DENSITY|En|M(ASS|ELT)) OsMASS OSMIUMZ? OsZ OXYGENZ? OZ P_B"\
   "OIL P_Cp P_DENSITY P_En P_M(ASS|ELT) Pa_(BOIL|Cp|DENSITY|En"\
   "|M(ASS|ELT)) PALLADIUMZ? PaMASS PARAFFIN(_(JP(KG(TOTAL)?|L|"\
   "MOLE)|MASS)|DENSITY|MASS) PaZ Pb_(BOIL|Cp|DENSITY|En|M(ASS|"\
   "ELT)) PbMASS PbZ Pd_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) PdMASS "\
   "PdZ PENTANE(_(JP(KG(TOTAL)?|MOLE)|MASS)|MASS) PHOSPHORUSZ? "\
   "PLATINUMZ? PLUTONIUMZ? Pm_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) P"\
   "MASS PmMASS PmZ Po_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) POLONIUM"\
   "Z? PoMASS POTASSIUMZ? PoZ Pr_(BOIL|Cp|DENSITY|En|M(ASS|ELT)"\
   ") PRASEODYMIUMZ? PrMASS PRO(METHIUMZ?|PANE(_(JP(KG(TOTAL)?|"\
   "MOLE)|MASS)|MASS)|TACTINIUMZ?) PrZ Pt_(BOIL|Cp|DENSITY|En|M"\
   "(ASS|ELT)) PtMASS PtZ Pu_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) Pu"\
   "MASS PuZ PZ Ra_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) RAD(IUMZ?|ON"\
   "Z?) RaMASS RaZ Rb_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) RbMASS Rb"\
   "Z Re_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) ReMASS ReZ Rf_(BOIL|Cp"\
   "|DENSITY|En|M(ASS|ELT)) RfMASS RfZ Rg_(BOIL|Cp|DENSITY|En|M"\
   "(ASS|ELT)) RgMASS RgZ Rh_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) RH"\
   "ENIUMZ? RhMASS RHODIUMZ? RhZ Rn_(BOIL|Cp|DENSITY|En|M(ASS|E"\
   "LT)) RnMASS RnZ ROENTGENIUMZ? Ru_(BOIL|Cp|DENSITY|En|M(ASS|"\
   "ELT)) RUBIDIUMZ? RuMASS RUTHE(NIUMZ?|RFORDIUMZ?) RuZ S_BOIL"\
   " S_Cp S_DENSITY S_En S_M(ASS|ELT) SAMARIUMZ? Sb_(BOIL|Cp|DE"\
   "NSITY|En|M(ASS|ELT)) SbMASS SbZ Sc_(BOIL|Cp|DENSITY|En|M(AS"\
   "S|ELT)) SCANDIUMZ? ScMASS ScZ Se_(BOIL|Cp|DENSITY|En|M(ASS|"\
   "ELT)) SEABORGIUMZ? SELENIUMZ? SeMASS SeZ Sg_(BOIL|Cp|DENSIT"\
   "Y|En|M(ASS|ELT)) SgMASS SgZ Si_(BOIL|Cp|DENSITY|En|M(ASS|EL"\
   "T)) SIL(ICONZ?|VERZ?) SiMASS SiZ Sm_(BOIL|Cp|DENSITY|En|M(A"\
   "SS|ELT)) SMASS SmMASS SmZ Sn_(BOIL|Cp|DENSITY|En|M(ASS|ELT)"\
   ") SnMASS SnZ SODIUMZ? Sr_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) Sr"\
   "MASS SrZ STEAM_Cp STRONTIUMZ? SUCROSE(_(JP(KG(TOTAL)?|MOLE)"\
   "|MASS)|MASS) SUGAR(_(JP(KG(TOTAL)?|L|MOLE)|MASS)|DENSITY|MA"\
   "SS) SULFURZ? SZ Ta_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) TaMASS T"\
   "ANTALUMZ? TaZ Tb_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) TbMASS TbZ"\
   " Tc_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) TcMASS TcZ Te_(BOIL|Cp|"\
   "DENSITY|En|M(ASS|ELT)) TECHNETIUMZ? TELLURIUMZ? TeMASS TENN"\
   "ESSINEZ? TERBIUMZ? TeZ Th_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) T"\
   "HALLIUMZ? ThMASS THORIUMZ? THULIUMZ? ThZ Ti_(BOIL|Cp|DENSIT"\
   "Y|En|M(ASS|ELT)) TiMASS TINZ? TITANIUMZ? TiZ Tl_(BOIL|Cp|DE"\
   "NSITY|En|M(ASS|ELT)) TlMASS TlZ Tm_(BOIL|Cp|DENSITY|En|M(AS"\
   "S|ELT)) TmMASS TmZ TNTJPKG Ts_(BOIL|Cp|DENSITY|En|M(ASS|ELT"\
   ")) TsMASS TsZ TUNGSTENZ? U_BOIL U_Cp U_DENSITY U_En U_M(ASS"\
   "|ELT) UMASS URANIUMZ? UZ V_BOIL V_Cp V_DENSITY V_En V_M(ASS"\
   "|ELT) VANADIUMZ? VMASS VSMOW_(H(1_RATIO|2_RATIO|3_RATIO|_MA"\
   "SS)|MASS|O(1[678]_RATIO|_MASS)) VZ W_BOIL W_Cp W_DENSITY W_"\
   "En W_M(ASS|ELT) WATER(_(Cp|FUSION_JP(KG|MOLE)|MASS|VAPORIZA"\
   "TION_JP(KG|MOLE))|MASS) WMASS WZ Xe_(BOIL|Cp|DENSITY|En|M(A"\
   "SS|ELT)) XeMASS XENONZ? XeZ Y_BOIL Y_Cp Y_DENSITY Y_En Y_M("\
   "ASS|ELT) Yb_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) YbMASS YbZ YMAS"\
   "S YTT(ERBIUMZ?|RIUMZ?) YZ ZINCZ? ZIRCONIUMZ? Zn_(BOIL|Cp|DE"\
   "NSITY|En|M(ASS|ELT)) ZnMASS ZnZ Zr_(BOIL|Cp|DENSITY|En|M(AS"\
   "S|ELT)) ZrMASS ZrZ"\
   "\n"
#endif // #ifndef INCLUDED_Kwelements_h
