#    Copyright (C) 2020 by Kevin D. Woerner
##-# =KDW= ########## DO NOT EDIT ######### DO NOT EDIT #########
##-# =KDW= ############ BUILDER $KWROOT/0lib/vkkcp.sh ###########
##-# =KDW= ##### SRC $KWROOT/codekdw/kw-lib/Kwelements.fwipp ####
# 2020-07-18 kdw  For Changelog, See File varylog
import sys
import math
import time
import Kw
HZ = 1
H_MASS = 1.008 * Kw.MOLARMASS
HMASS = H_MASS / Kw.AVOGADRO
H_DENSITY = 0.08988 * Kw.DENSITY
H_MELT = 14.01 * Kw.KELVIN
H_BOIL = 20.28 * Kw.KELVIN
H_Cp = 14304 * Kw.SPECIFICHEAT
H_En = 2.20
HeZ = 2
He_MASS = 4.002602 * Kw.MOLARMASS
HeMASS = He_MASS / Kw.AVOGADRO
He_DENSITY = 0.1785 * Kw.DENSITY
He_MELT = -1 * Kw.KELVIN
He_BOIL = 4.22 * Kw.KELVIN
He_Cp = 5193 * Kw.SPECIFICHEAT
He_En = -1
LiZ = 3
Li_MASS = 6.94 * Kw.MOLARMASS
LiMASS = Li_MASS / Kw.AVOGADRO
Li_DENSITY = 534 * Kw.DENSITY
Li_MELT = 453.69 * Kw.KELVIN
Li_BOIL = 1560 * Kw.KELVIN
Li_Cp = 3582 * Kw.SPECIFICHEAT
Li_En = 0.98
BeZ = 4
Be_MASS = 9.0121831 * Kw.MOLARMASS
BeMASS = Be_MASS / Kw.AVOGADRO
Be_DENSITY = 1850 * Kw.DENSITY
Be_MELT = 1560 * Kw.KELVIN
Be_BOIL = 2742 * Kw.KELVIN
Be_Cp = 1825 * Kw.SPECIFICHEAT
Be_En = 1.57
BZ = 5
B_MASS = 10.81 * Kw.MOLARMASS
BMASS = B_MASS / Kw.AVOGADRO
B_DENSITY = 2340 * Kw.DENSITY
B_MELT = 2349 * Kw.KELVIN
B_BOIL = 4200 * Kw.KELVIN
B_Cp = 1026 * Kw.SPECIFICHEAT
B_En = 2.04
CZ = 6
C_MASS = 12.011 * Kw.MOLARMASS
CMASS = C_MASS / Kw.AVOGADRO
C_DENSITY = 2267 * Kw.DENSITY
C_MELT = 3800 * Kw.KELVIN
C_BOIL = 4300 * Kw.KELVIN
C_Cp = 709 * Kw.SPECIFICHEAT
C_En = 2.55
NZ = 7
N_MASS = 14.007 * Kw.MOLARMASS
NMASS = N_MASS / Kw.AVOGADRO
N_DENSITY = 1.2506 * Kw.DENSITY
N_MELT = 63.15 * Kw.KELVIN
N_BOIL = 77.36 * Kw.KELVIN
N_Cp = 1040 * Kw.SPECIFICHEAT
N_En = 3.04
OZ = 8
O_MASS = 15.999 * Kw.MOLARMASS
OMASS = O_MASS / Kw.AVOGADRO
O_DENSITY = 1.429 * Kw.DENSITY
O_MELT = 54.36 * Kw.KELVIN
O_BOIL = 90.20 * Kw.KELVIN
O_Cp = 918 * Kw.SPECIFICHEAT
O_En = 3.44
FZ = 9
F_MASS = 18.998403163 * Kw.MOLARMASS
FMASS = F_MASS / Kw.AVOGADRO
F_DENSITY = 1.696 * Kw.DENSITY
F_MELT = 53.53 * Kw.KELVIN
F_BOIL = 85.03 * Kw.KELVIN
F_Cp = 824 * Kw.SPECIFICHEAT
F_En = 3.98
NeZ = 10
Ne_MASS = 20.1797 * Kw.MOLARMASS
NeMASS = Ne_MASS / Kw.AVOGADRO
Ne_DENSITY = 0.8999 * Kw.DENSITY
Ne_MELT = 24.56 * Kw.KELVIN
Ne_BOIL = 27.07 * Kw.KELVIN
Ne_Cp = 1030 * Kw.SPECIFICHEAT
Ne_En = -1
NaZ = 11
Na_MASS = 22.98976928 * Kw.MOLARMASS
NaMASS = Na_MASS / Kw.AVOGADRO
Na_DENSITY = 971 * Kw.DENSITY
Na_MELT = 370.87 * Kw.KELVIN
Na_BOIL = 1156 * Kw.KELVIN
Na_Cp = 1228 * Kw.SPECIFICHEAT
Na_En = 0.93
MgZ = 12
Mg_MASS = 24.305 * Kw.MOLARMASS
MgMASS = Mg_MASS / Kw.AVOGADRO
Mg_DENSITY = 1738 * Kw.DENSITY
Mg_MELT = 923 * Kw.KELVIN
Mg_BOIL = 1363 * Kw.KELVIN
Mg_Cp = 1023 * Kw.SPECIFICHEAT
Mg_En = 1.31
AlZ = 13
Al_MASS = 26.9815384 * Kw.MOLARMASS
AlMASS = Al_MASS / Kw.AVOGADRO
Al_DENSITY = 2698 * Kw.DENSITY
Al_MELT = 933.47 * Kw.KELVIN
Al_BOIL = 2792 * Kw.KELVIN
Al_Cp = 897 * Kw.SPECIFICHEAT
Al_En = 1.61
SiZ = 14
Si_MASS = 28.085 * Kw.MOLARMASS
SiMASS = Si_MASS / Kw.AVOGADRO
Si_DENSITY = 2329.6 * Kw.DENSITY
Si_MELT = 1687 * Kw.KELVIN
Si_BOIL = 3538 * Kw.KELVIN
Si_Cp = 705 * Kw.SPECIFICHEAT
Si_En = 1.9
PZ = 15
P_MASS = 30.973761998 * Kw.MOLARMASS
PMASS = P_MASS / Kw.AVOGADRO
P_DENSITY = 1820 * Kw.DENSITY
P_MELT = 317.30 * Kw.KELVIN
P_BOIL = 550 * Kw.KELVIN
P_Cp = 769 * Kw.SPECIFICHEAT
P_En = 2.19
SZ = 16
S_MASS = 32.06 * Kw.MOLARMASS
SMASS = S_MASS / Kw.AVOGADRO
S_DENSITY = 2067 * Kw.DENSITY
S_MELT = 388.36 * Kw.KELVIN
S_BOIL = 717.87 * Kw.KELVIN
S_Cp = 710 * Kw.SPECIFICHEAT
S_En = 2.58
ClZ = 17
Cl_MASS = 35.45 * Kw.MOLARMASS
ClMASS = Cl_MASS / Kw.AVOGADRO
Cl_DENSITY = 3.214 * Kw.DENSITY
Cl_MELT = 171.6 * Kw.KELVIN
Cl_BOIL = 239.11 * Kw.KELVIN
Cl_Cp = 479 * Kw.SPECIFICHEAT
Cl_En = 3.16
ArZ = 18
Ar_MASS = 39.948 * Kw.MOLARMASS
ArMASS = Ar_MASS / Kw.AVOGADRO
Ar_DENSITY = 1.7837 * Kw.DENSITY
Ar_MELT = 83.80 * Kw.KELVIN
Ar_BOIL = 87.30 * Kw.KELVIN
Ar_Cp = 520 * Kw.SPECIFICHEAT
Ar_En = -1
KZ = 19
K_MASS = 39.0983 * Kw.MOLARMASS
KMASS = K_MASS / Kw.AVOGADRO
K_DENSITY = 862 * Kw.DENSITY
K_MELT = 336.53 * Kw.KELVIN
K_BOIL = 1032 * Kw.KELVIN
K_Cp = 757 * Kw.SPECIFICHEAT
K_En = 0.82
CaZ = 20
Ca_MASS = 40.078 * Kw.MOLARMASS
CaMASS = Ca_MASS / Kw.AVOGADRO
Ca_DENSITY = 1540 * Kw.DENSITY
Ca_MELT = 1115 * Kw.KELVIN
Ca_BOIL = 1757 * Kw.KELVIN
Ca_Cp = 647 * Kw.SPECIFICHEAT
Ca_En = 1
ScZ = 21
Sc_MASS = 44.955908 * Kw.MOLARMASS
ScMASS = Sc_MASS / Kw.AVOGADRO
Sc_DENSITY = 2989 * Kw.DENSITY
Sc_MELT = 1814 * Kw.KELVIN
Sc_BOIL = 3109 * Kw.KELVIN
Sc_Cp = 568 * Kw.SPECIFICHEAT
Sc_En = 1.36
TiZ = 22
Ti_MASS = 47.867 * Kw.MOLARMASS
TiMASS = Ti_MASS / Kw.AVOGADRO
Ti_DENSITY = 4540 * Kw.DENSITY
Ti_MELT = 1941 * Kw.KELVIN
Ti_BOIL = 3560 * Kw.KELVIN
Ti_Cp = 523 * Kw.SPECIFICHEAT
Ti_En = 1.54
VZ = 23
V_MASS = 50.9415 * Kw.MOLARMASS
VMASS = V_MASS / Kw.AVOGADRO
V_DENSITY = 6110 * Kw.DENSITY
V_MELT = 2183 * Kw.KELVIN
V_BOIL = 3680 * Kw.KELVIN
V_Cp = 489 * Kw.SPECIFICHEAT
V_En = 1.63
CrZ = 24
Cr_MASS = 51.9961 * Kw.MOLARMASS
CrMASS = Cr_MASS / Kw.AVOGADRO
Cr_DENSITY = 7150 * Kw.DENSITY
Cr_MELT = 2180 * Kw.KELVIN
Cr_BOIL = 2944 * Kw.KELVIN
Cr_Cp = 449 * Kw.SPECIFICHEAT
Cr_En = 1.66
MnZ = 25
Mn_MASS = 54.938043 * Kw.MOLARMASS
MnMASS = Mn_MASS / Kw.AVOGADRO
Mn_DENSITY = 7440 * Kw.DENSITY
Mn_MELT = 1519 * Kw.KELVIN
Mn_BOIL = 2334 * Kw.KELVIN
Mn_Cp = 479 * Kw.SPECIFICHEAT
Mn_En = 1.55
FeZ = 26
Fe_MASS = 55.845 * Kw.MOLARMASS
FeMASS = Fe_MASS / Kw.AVOGADRO
Fe_DENSITY = 7874 * Kw.DENSITY
Fe_MELT = 1811 * Kw.KELVIN
Fe_BOIL = 3134 * Kw.KELVIN
Fe_Cp = 449 * Kw.SPECIFICHEAT
Fe_En = 1.83
CoZ = 27
Co_MASS = 58.933194 * Kw.MOLARMASS
CoMASS = Co_MASS / Kw.AVOGADRO
Co_DENSITY = 8860 * Kw.DENSITY
Co_MELT = 1768 * Kw.KELVIN
Co_BOIL = 3200 * Kw.KELVIN
Co_Cp = 421 * Kw.SPECIFICHEAT
Co_En = 1.88
NiZ = 28
Ni_MASS = 58.6934 * Kw.MOLARMASS
NiMASS = Ni_MASS / Kw.AVOGADRO
Ni_DENSITY = 8912 * Kw.DENSITY
Ni_MELT = 1728 * Kw.KELVIN
Ni_BOIL = 3186 * Kw.KELVIN
Ni_Cp = 444 * Kw.SPECIFICHEAT
Ni_En = 1.91
CuZ = 29
Cu_MASS = 63.546 * Kw.MOLARMASS
CuMASS = Cu_MASS / Kw.AVOGADRO
Cu_DENSITY = 8960 * Kw.DENSITY
Cu_MELT = 1357.77 * Kw.KELVIN
Cu_BOIL = 2835 * Kw.KELVIN
Cu_Cp = 385 * Kw.SPECIFICHEAT
Cu_En = 1.9
ZnZ = 30
Zn_MASS = 65.38 * Kw.MOLARMASS
ZnMASS = Zn_MASS / Kw.AVOGADRO
Zn_DENSITY = 7134 * Kw.DENSITY
Zn_MELT = 692.88 * Kw.KELVIN
Zn_BOIL = 1180 * Kw.KELVIN
Zn_Cp = 388 * Kw.SPECIFICHEAT
Zn_En = 1.65
GaZ = 31
Ga_MASS = 69.723 * Kw.MOLARMASS
GaMASS = Ga_MASS / Kw.AVOGADRO
Ga_DENSITY = 5907 * Kw.DENSITY
Ga_MELT = 302.9146 * Kw.KELVIN
Ga_BOIL = 2673 * Kw.KELVIN
Ga_Cp = 371 * Kw.SPECIFICHEAT
Ga_En = 1.81
GeZ = 32
Ge_MASS = 72.630 * Kw.MOLARMASS
GeMASS = Ge_MASS / Kw.AVOGADRO
Ge_DENSITY = 5323 * Kw.DENSITY
Ge_MELT = 1211.40 * Kw.KELVIN
Ge_BOIL = 3106 * Kw.KELVIN
Ge_Cp = 320 * Kw.SPECIFICHEAT
Ge_En = 2.01
AsZ = 33
As_MASS = 74.921595 * Kw.MOLARMASS
AsMASS = As_MASS / Kw.AVOGADRO
As_DENSITY = 5776 * Kw.DENSITY
As_MELT = 1090 * Kw.KELVIN
As_BOIL = 887 * Kw.KELVIN
As_Cp = 329 * Kw.SPECIFICHEAT
As_En = 2.18
SeZ = 34
Se_MASS = 78.971 * Kw.MOLARMASS
SeMASS = Se_MASS / Kw.AVOGADRO
Se_DENSITY = 4809 * Kw.DENSITY
Se_MELT = 453 * Kw.KELVIN
Se_BOIL = 958 * Kw.KELVIN
Se_Cp = 321 * Kw.SPECIFICHEAT
Se_En = 2.55
BrZ = 35
Br_MASS = 79.904 * Kw.MOLARMASS
BrMASS = Br_MASS / Kw.AVOGADRO
Br_DENSITY = 3122 * Kw.DENSITY
Br_MELT = 265.8 * Kw.KELVIN
Br_BOIL = 332.0 * Kw.KELVIN
Br_Cp = 474 * Kw.SPECIFICHEAT
Br_En = 2.96
KrZ = 36
Kr_MASS = 83.798 * Kw.MOLARMASS
KrMASS = Kr_MASS / Kw.AVOGADRO
Kr_DENSITY = 3.733 * Kw.DENSITY
Kr_MELT = 115.79 * Kw.KELVIN
Kr_BOIL = 119.93 * Kw.KELVIN
Kr_Cp = 248 * Kw.SPECIFICHEAT
Kr_En = 3
RbZ = 37
Rb_MASS = 85.4678 * Kw.MOLARMASS
RbMASS = Rb_MASS / Kw.AVOGADRO
Rb_DENSITY = 1532 * Kw.DENSITY
Rb_MELT = 312.46 * Kw.KELVIN
Rb_BOIL = 961 * Kw.KELVIN
Rb_Cp = 363 * Kw.SPECIFICHEAT
Rb_En = 0.82
SrZ = 38
Sr_MASS = 87.62 * Kw.MOLARMASS
SrMASS = Sr_MASS / Kw.AVOGADRO
Sr_DENSITY = 2640 * Kw.DENSITY
Sr_MELT = 1050 * Kw.KELVIN
Sr_BOIL = 1655 * Kw.KELVIN
Sr_Cp = 301 * Kw.SPECIFICHEAT
Sr_En = 0.95
YZ = 39
Y_MASS = 88.90584 * Kw.MOLARMASS
YMASS = Y_MASS / Kw.AVOGADRO
Y_DENSITY = 4469 * Kw.DENSITY
Y_MELT = 1799 * Kw.KELVIN
Y_BOIL = 3609 * Kw.KELVIN
Y_Cp = 298 * Kw.SPECIFICHEAT
Y_En = 1.22
ZrZ = 40
Zr_MASS = 91.224 * Kw.MOLARMASS
ZrMASS = Zr_MASS / Kw.AVOGADRO
Zr_DENSITY = 6506 * Kw.DENSITY
Zr_MELT = 2128 * Kw.KELVIN
Zr_BOIL = 4682 * Kw.KELVIN
Zr_Cp = 278 * Kw.SPECIFICHEAT
Zr_En = 1.33
NbZ = 41
Nb_MASS = 92.90637 * Kw.MOLARMASS
NbMASS = Nb_MASS / Kw.AVOGADRO
Nb_DENSITY = 8570 * Kw.DENSITY
Nb_MELT = 2750 * Kw.KELVIN
Nb_BOIL = 5017 * Kw.KELVIN
Nb_Cp = 265 * Kw.SPECIFICHEAT
Nb_En = 1.6
MoZ = 42
Mo_MASS = 95.95 * Kw.MOLARMASS
MoMASS = Mo_MASS / Kw.AVOGADRO
Mo_DENSITY = 10220 * Kw.DENSITY
Mo_MELT = 2896 * Kw.KELVIN
Mo_BOIL = 4912 * Kw.KELVIN
Mo_Cp = 251 * Kw.SPECIFICHEAT
Mo_En = 2.16
TcZ = 43
Tc_MASS = 98 * Kw.MOLARMASS
TcMASS = Tc_MASS / Kw.AVOGADRO
Tc_DENSITY = 11500 * Kw.DENSITY
Tc_MELT = 2430 * Kw.KELVIN
Tc_BOIL = 4538 * Kw.KELVIN
Tc_Cp = -1 * Kw.SPECIFICHEAT
Tc_En = 1.9
RuZ = 44
Ru_MASS = 101.07 * Kw.MOLARMASS
RuMASS = Ru_MASS / Kw.AVOGADRO
Ru_DENSITY = 12370 * Kw.DENSITY
Ru_MELT = 2607 * Kw.KELVIN
Ru_BOIL = 4423 * Kw.KELVIN
Ru_Cp = 238 * Kw.SPECIFICHEAT
Ru_En = 2.2
RhZ = 45
Rh_MASS = 102.90549 * Kw.MOLARMASS
RhMASS = Rh_MASS / Kw.AVOGADRO
Rh_DENSITY = 12410 * Kw.DENSITY
Rh_MELT = 2237 * Kw.KELVIN
Rh_BOIL = 3968 * Kw.KELVIN
Rh_Cp = 243 * Kw.SPECIFICHEAT
Rh_En = 2.28
PdZ = 46
Pd_MASS = 106.42 * Kw.MOLARMASS
PdMASS = Pd_MASS / Kw.AVOGADRO
Pd_DENSITY = 12020 * Kw.DENSITY
Pd_MELT = 1828.05 * Kw.KELVIN
Pd_BOIL = 3236 * Kw.KELVIN
Pd_Cp = 244 * Kw.SPECIFICHEAT
Pd_En = 2.2
AgZ = 47
Ag_MASS = 107.8682 * Kw.MOLARMASS
AgMASS = Ag_MASS / Kw.AVOGADRO
Ag_DENSITY = 10501 * Kw.DENSITY
Ag_MELT = 1234.93 * Kw.KELVIN
Ag_BOIL = 2435 * Kw.KELVIN
Ag_Cp = 235 * Kw.SPECIFICHEAT
Ag_En = 1.93
CdZ = 48
Cd_MASS = 112.414 * Kw.MOLARMASS
CdMASS = Cd_MASS / Kw.AVOGADRO
Cd_DENSITY = 8690 * Kw.DENSITY
Cd_MELT = 594.22 * Kw.KELVIN
Cd_BOIL = 1040 * Kw.KELVIN
Cd_Cp = 232 * Kw.SPECIFICHEAT
Cd_En = 1.69
InZ = 49
In_MASS = 114.818 * Kw.MOLARMASS
InMASS = In_MASS / Kw.AVOGADRO
In_DENSITY = 7310 * Kw.DENSITY
In_MELT = 429.75 * Kw.KELVIN
In_BOIL = 2345 * Kw.KELVIN
In_Cp = 233 * Kw.SPECIFICHEAT
In_En = 1.78
SnZ = 50
Sn_MASS = 118.710 * Kw.MOLARMASS
SnMASS = Sn_MASS / Kw.AVOGADRO
Sn_DENSITY = 7287 * Kw.DENSITY
Sn_MELT = 505.08 * Kw.KELVIN
Sn_BOIL = 2875 * Kw.KELVIN
Sn_Cp = 228 * Kw.SPECIFICHEAT
Sn_En = 1.96
SbZ = 51
Sb_MASS = 121.760 * Kw.MOLARMASS
SbMASS = Sb_MASS / Kw.AVOGADRO
Sb_DENSITY = 6685 * Kw.DENSITY
Sb_MELT = 903.78 * Kw.KELVIN
Sb_BOIL = 1860 * Kw.KELVIN
Sb_Cp = 207 * Kw.SPECIFICHEAT
Sb_En = 2.05
TeZ = 52
Te_MASS = 127.60 * Kw.MOLARMASS
TeMASS = Te_MASS / Kw.AVOGADRO
Te_DENSITY = 6232 * Kw.DENSITY
Te_MELT = 722.66 * Kw.KELVIN
Te_BOIL = 1261 * Kw.KELVIN
Te_Cp = 202 * Kw.SPECIFICHEAT
Te_En = 2.1
IZ = 53
I_MASS = 126.90447 * Kw.MOLARMASS
IMASS = I_MASS / Kw.AVOGADRO
I_DENSITY = 4930 * Kw.DENSITY
I_MELT = 386.85 * Kw.KELVIN
I_BOIL = 457.4 * Kw.KELVIN
I_Cp = 214 * Kw.SPECIFICHEAT
I_En = 2.66
XeZ = 54
Xe_MASS = 131.293 * Kw.MOLARMASS
XeMASS = Xe_MASS / Kw.AVOGADRO
Xe_DENSITY = 5.887 * Kw.DENSITY
Xe_MELT = 161.4 * Kw.KELVIN
Xe_BOIL = 165.03 * Kw.KELVIN
Xe_Cp = 158 * Kw.SPECIFICHEAT
Xe_En = 2.6
CsZ = 55
Cs_MASS = 132.90545196 * Kw.MOLARMASS
CsMASS = Cs_MASS / Kw.AVOGADRO
Cs_DENSITY = 1873 * Kw.DENSITY
Cs_MELT = 301.59 * Kw.KELVIN
Cs_BOIL = 944 * Kw.KELVIN
Cs_Cp = 242 * Kw.SPECIFICHEAT
Cs_En = 0.79
BaZ = 56
Ba_MASS = 137.327 * Kw.MOLARMASS
BaMASS = Ba_MASS / Kw.AVOGADRO
Ba_DENSITY = 3594 * Kw.DENSITY
Ba_MELT = 1000 * Kw.KELVIN
Ba_BOIL = 2170 * Kw.KELVIN
Ba_Cp = 204 * Kw.SPECIFICHEAT
Ba_En = 0.89
LaZ = 57
La_MASS = 138.90547 * Kw.MOLARMASS
LaMASS = La_MASS / Kw.AVOGADRO
La_DENSITY = 6145 * Kw.DENSITY
La_MELT = 1193 * Kw.KELVIN
La_BOIL = 3737 * Kw.KELVIN
La_Cp = 195 * Kw.SPECIFICHEAT
La_En = 1.1
CeZ = 58
Ce_MASS = 140.116 * Kw.MOLARMASS
CeMASS = Ce_MASS / Kw.AVOGADRO
Ce_DENSITY = 6770 * Kw.DENSITY
Ce_MELT = 1068 * Kw.KELVIN
Ce_BOIL = 3716 * Kw.KELVIN
Ce_Cp = 192 * Kw.SPECIFICHEAT
Ce_En = 1.12
PrZ = 59
Pr_MASS = 140.90766 * Kw.MOLARMASS
PrMASS = Pr_MASS / Kw.AVOGADRO
Pr_DENSITY = 6773 * Kw.DENSITY
Pr_MELT = 1208 * Kw.KELVIN
Pr_BOIL = 3793 * Kw.KELVIN
Pr_Cp = 193 * Kw.SPECIFICHEAT
Pr_En = 1.13
NdZ = 60
Nd_MASS = 144.242 * Kw.MOLARMASS
NdMASS = Nd_MASS / Kw.AVOGADRO
Nd_DENSITY = 7007 * Kw.DENSITY
Nd_MELT = 1297 * Kw.KELVIN
Nd_BOIL = 3347 * Kw.KELVIN
Nd_Cp = 190 * Kw.SPECIFICHEAT
Nd_En = 1.14
PmZ = 61
Pm_MASS = 145 * Kw.MOLARMASS
PmMASS = Pm_MASS / Kw.AVOGADRO
Pm_DENSITY = 7260 * Kw.DENSITY
Pm_MELT = 1315 * Kw.KELVIN
Pm_BOIL = 3273 * Kw.KELVIN
Pm_Cp = -1 * Kw.SPECIFICHEAT
Pm_En = 1.13
SmZ = 62
Sm_MASS = 150.36 * Kw.MOLARMASS
SmMASS = Sm_MASS / Kw.AVOGADRO
Sm_DENSITY = 7520 * Kw.DENSITY
Sm_MELT = 1345 * Kw.KELVIN
Sm_BOIL = 2067 * Kw.KELVIN
Sm_Cp = 197 * Kw.SPECIFICHEAT
Sm_En = 1.17
EuZ = 63
Eu_MASS = 151.964 * Kw.MOLARMASS
EuMASS = Eu_MASS / Kw.AVOGADRO
Eu_DENSITY = 5243 * Kw.DENSITY
Eu_MELT = 1099 * Kw.KELVIN
Eu_BOIL = 1802 * Kw.KELVIN
Eu_Cp = 182 * Kw.SPECIFICHEAT
Eu_En = 1.2
GdZ = 64
Gd_MASS = 157.25 * Kw.MOLARMASS
GdMASS = Gd_MASS / Kw.AVOGADRO
Gd_DENSITY = 7895 * Kw.DENSITY
Gd_MELT = 1585 * Kw.KELVIN
Gd_BOIL = 3546 * Kw.KELVIN
Gd_Cp = 236 * Kw.SPECIFICHEAT
Gd_En = 1.2
TbZ = 65
Tb_MASS = 158.925354 * Kw.MOLARMASS
TbMASS = Tb_MASS / Kw.AVOGADRO
Tb_DENSITY = 8229 * Kw.DENSITY
Tb_MELT = 1629 * Kw.KELVIN
Tb_BOIL = 3503 * Kw.KELVIN
Tb_Cp = 182 * Kw.SPECIFICHEAT
Tb_En = 1.2
DyZ = 66
Dy_MASS = 162.500 * Kw.MOLARMASS
DyMASS = Dy_MASS / Kw.AVOGADRO
Dy_DENSITY = 8550 * Kw.DENSITY
Dy_MELT = 1680 * Kw.KELVIN
Dy_BOIL = 2840 * Kw.KELVIN
Dy_Cp = 170 * Kw.SPECIFICHEAT
Dy_En = 1.22
HoZ = 67
Ho_MASS = 164.930328 * Kw.MOLARMASS
HoMASS = Ho_MASS / Kw.AVOGADRO
Ho_DENSITY = 8795 * Kw.DENSITY
Ho_MELT = 1734 * Kw.KELVIN
Ho_BOIL = 2993 * Kw.KELVIN
Ho_Cp = 165 * Kw.SPECIFICHEAT
Ho_En = 1.23
ErZ = 68
Er_MASS = 167.259 * Kw.MOLARMASS
ErMASS = Er_MASS / Kw.AVOGADRO
Er_DENSITY = 9066 * Kw.DENSITY
Er_MELT = 1802 * Kw.KELVIN
Er_BOIL = 3141 * Kw.KELVIN
Er_Cp = 168 * Kw.SPECIFICHEAT
Er_En = 1.24
TmZ = 69
Tm_MASS = 168.934218 * Kw.MOLARMASS
TmMASS = Tm_MASS / Kw.AVOGADRO
Tm_DENSITY = 9321 * Kw.DENSITY
Tm_MELT = 1818 * Kw.KELVIN
Tm_BOIL = 2223 * Kw.KELVIN
Tm_Cp = 160 * Kw.SPECIFICHEAT
Tm_En = 1.25
YbZ = 70
Yb_MASS = 173.045 * Kw.MOLARMASS
YbMASS = Yb_MASS / Kw.AVOGADRO
Yb_DENSITY = 6965 * Kw.DENSITY
Yb_MELT = 1097 * Kw.KELVIN
Yb_BOIL = 1469 * Kw.KELVIN
Yb_Cp = 155 * Kw.SPECIFICHEAT
Yb_En = 1.1
LuZ = 71
Lu_MASS = 174.9668 * Kw.MOLARMASS
LuMASS = Lu_MASS / Kw.AVOGADRO
Lu_DENSITY = 9840 * Kw.DENSITY
Lu_MELT = 1925 * Kw.KELVIN
Lu_BOIL = 3675 * Kw.KELVIN
Lu_Cp = 154 * Kw.SPECIFICHEAT
Lu_En = 1.27
HfZ = 72
Hf_MASS = 178.49 * Kw.MOLARMASS
HfMASS = Hf_MASS / Kw.AVOGADRO
Hf_DENSITY = 13310 * Kw.DENSITY
Hf_MELT = 2506 * Kw.KELVIN
Hf_BOIL = 4876 * Kw.KELVIN
Hf_Cp = 144 * Kw.SPECIFICHEAT
Hf_En = 1.3
TaZ = 73
Ta_MASS = 180.94788 * Kw.MOLARMASS
TaMASS = Ta_MASS / Kw.AVOGADRO
Ta_DENSITY = 16654 * Kw.DENSITY
Ta_MELT = 3290 * Kw.KELVIN
Ta_BOIL = 5731 * Kw.KELVIN
Ta_Cp = 140 * Kw.SPECIFICHEAT
Ta_En = 1.5
WZ = 74
W_MASS = 183.84 * Kw.MOLARMASS
WMASS = W_MASS / Kw.AVOGADRO
W_DENSITY = 19250 * Kw.DENSITY
W_MELT = 3695 * Kw.KELVIN
W_BOIL = 5828 * Kw.KELVIN
W_Cp = 132 * Kw.SPECIFICHEAT
W_En = 2.36
ReZ = 75
Re_MASS = 186.207 * Kw.MOLARMASS
ReMASS = Re_MASS / Kw.AVOGADRO
Re_DENSITY = 21020 * Kw.DENSITY
Re_MELT = 3459 * Kw.KELVIN
Re_BOIL = 5869 * Kw.KELVIN
Re_Cp = 137 * Kw.SPECIFICHEAT
Re_En = 1.9
OsZ = 76
Os_MASS = 190.23 * Kw.MOLARMASS
OsMASS = Os_MASS / Kw.AVOGADRO
Os_DENSITY = 22610 * Kw.DENSITY
Os_MELT = 3306 * Kw.KELVIN
Os_BOIL = 5285 * Kw.KELVIN
Os_Cp = 130 * Kw.SPECIFICHEAT
Os_En = 2.2
IrZ = 77
Ir_MASS = 192.217 * Kw.MOLARMASS
IrMASS = Ir_MASS / Kw.AVOGADRO
Ir_DENSITY = 22560 * Kw.DENSITY
Ir_MELT = 2719 * Kw.KELVIN
Ir_BOIL = 4701 * Kw.KELVIN
Ir_Cp = 131 * Kw.SPECIFICHEAT
Ir_En = 2.2
PtZ = 78
Pt_MASS = 195.084 * Kw.MOLARMASS
PtMASS = Pt_MASS / Kw.AVOGADRO
Pt_DENSITY = 21460 * Kw.DENSITY
Pt_MELT = 2041.4 * Kw.KELVIN
Pt_BOIL = 4098 * Kw.KELVIN
Pt_Cp = 133 * Kw.SPECIFICHEAT
Pt_En = 2.28
AuZ = 79
Au_MASS = 196.966570 * Kw.MOLARMASS
AuMASS = Au_MASS / Kw.AVOGADRO
Au_DENSITY = 19282 * Kw.DENSITY
Au_MELT = 1337.33 * Kw.KELVIN
Au_BOIL = 3129 * Kw.KELVIN
Au_Cp = 129 * Kw.SPECIFICHEAT
Au_En = 2.54
HgZ = 80
Hg_MASS = 200.592 * Kw.MOLARMASS
HgMASS = Hg_MASS / Kw.AVOGADRO
Hg_DENSITY = 13533.6 * Kw.DENSITY
Hg_MELT = 234.43 * Kw.KELVIN
Hg_BOIL = 629.88 * Kw.KELVIN
Hg_Cp = 140 * Kw.SPECIFICHEAT
Hg_En = 2
TlZ = 81
Tl_MASS = 204.38 * Kw.MOLARMASS
TlMASS = Tl_MASS / Kw.AVOGADRO
Tl_DENSITY = 11850 * Kw.DENSITY
Tl_MELT = 577 * Kw.KELVIN
Tl_BOIL = 1746 * Kw.KELVIN
Tl_Cp = 129 * Kw.SPECIFICHEAT
Tl_En = 1.62
PbZ = 82
Pb_MASS = 207.2 * Kw.MOLARMASS
PbMASS = Pb_MASS / Kw.AVOGADRO
Pb_DENSITY = 11342 * Kw.DENSITY
Pb_MELT = 600.61 * Kw.KELVIN
Pb_BOIL = 2022 * Kw.KELVIN
Pb_Cp = 129 * Kw.SPECIFICHEAT
Pb_En = 1.87
BiZ = 83
Bi_MASS = 208.98040 * Kw.MOLARMASS
BiMASS = Bi_MASS / Kw.AVOGADRO
Bi_DENSITY = 9807 * Kw.DENSITY
Bi_MELT = 544.7 * Kw.KELVIN
Bi_BOIL = 1837 * Kw.KELVIN
Bi_Cp = 122 * Kw.SPECIFICHEAT
Bi_En = 2.02
PoZ = 84
Po_MASS = 209 * Kw.MOLARMASS
PoMASS = Po_MASS / Kw.AVOGADRO
Po_DENSITY = 9320 * Kw.DENSITY
Po_MELT = 527 * Kw.KELVIN
Po_BOIL = 1235 * Kw.KELVIN
Po_Cp = -1 * Kw.SPECIFICHEAT
Po_En = 2.0
AtZ = 85
At_MASS = 210 * Kw.MOLARMASS
AtMASS = At_MASS / Kw.AVOGADRO
At_DENSITY = 7000 * Kw.DENSITY
At_MELT = 575 * Kw.KELVIN
At_BOIL = 610 * Kw.KELVIN
At_Cp = -1 * Kw.SPECIFICHEAT
At_En = 2.2
RnZ = 86
Rn_MASS = 222 * Kw.MOLARMASS
RnMASS = Rn_MASS / Kw.AVOGADRO
Rn_DENSITY = 9.73 * Kw.DENSITY
Rn_MELT = 202 * Kw.KELVIN
Rn_BOIL = 211.3 * Kw.KELVIN
Rn_Cp = 94 * Kw.SPECIFICHEAT
Rn_En = 2.2
FrZ = 87
Fr_MASS = 223 * Kw.MOLARMASS
FrMASS = Fr_MASS / Kw.AVOGADRO
Fr_DENSITY = 1870 * Kw.DENSITY
Fr_MELT = 300 * Kw.KELVIN
Fr_BOIL = 950 * Kw.KELVIN
Fr_Cp = -1 * Kw.SPECIFICHEAT
Fr_En = 0.7
RaZ = 88
Ra_MASS = 226 * Kw.MOLARMASS
RaMASS = Ra_MASS / Kw.AVOGADRO
Ra_DENSITY = 5500 * Kw.DENSITY
Ra_MELT = 973 * Kw.KELVIN
Ra_BOIL = 2010 * Kw.KELVIN
Ra_Cp = 94 * Kw.SPECIFICHEAT
Ra_En = 0.9
AcZ = 89
Ac_MASS = 227 * Kw.MOLARMASS
AcMASS = Ac_MASS / Kw.AVOGADRO
Ac_DENSITY = 10070 * Kw.DENSITY
Ac_MELT = 1323 * Kw.KELVIN
Ac_BOIL = 3471 * Kw.KELVIN
Ac_Cp = 120 * Kw.SPECIFICHEAT
Ac_En = 1.1
ThZ = 90
Th_MASS = 232.0377 * Kw.MOLARMASS
ThMASS = Th_MASS / Kw.AVOGADRO
Th_DENSITY = 11720 * Kw.DENSITY
Th_MELT = 2115 * Kw.KELVIN
Th_BOIL = 5061 * Kw.KELVIN
Th_Cp = 113 * Kw.SPECIFICHEAT
Th_En = 1.3
PaZ = 91
Pa_MASS = 231.03588 * Kw.MOLARMASS
PaMASS = Pa_MASS / Kw.AVOGADRO
Pa_DENSITY = 15370 * Kw.DENSITY
Pa_MELT = 1841 * Kw.KELVIN
Pa_BOIL = 4300 * Kw.KELVIN
Pa_Cp = -1 * Kw.SPECIFICHEAT
Pa_En = 1.5
UZ = 92
U_MASS = 238.02891 * Kw.MOLARMASS
UMASS = U_MASS / Kw.AVOGADRO
U_DENSITY = 18950 * Kw.DENSITY
U_MELT = 1405.3 * Kw.KELVIN
U_BOIL = 4404 * Kw.KELVIN
U_Cp = 116 * Kw.SPECIFICHEAT
U_En = 1.38
NpZ = 93
Np_MASS = 237 * Kw.MOLARMASS
NpMASS = Np_MASS / Kw.AVOGADRO
Np_DENSITY = 20450 * Kw.DENSITY
Np_MELT = 917 * Kw.KELVIN
Np_BOIL = 4273 * Kw.KELVIN
Np_Cp = -1 * Kw.SPECIFICHEAT
Np_En = 1.36
PuZ = 94
Pu_MASS = 244 * Kw.MOLARMASS
PuMASS = Pu_MASS / Kw.AVOGADRO
Pu_DENSITY = 19840 * Kw.DENSITY
Pu_MELT = 912.5 * Kw.KELVIN
Pu_BOIL = 3501 * Kw.KELVIN
Pu_Cp = -1 * Kw.SPECIFICHEAT
Pu_En = 1.28
AmZ = 95
Am_MASS = 243 * Kw.MOLARMASS
AmMASS = Am_MASS / Kw.AVOGADRO
Am_DENSITY = 13690 * Kw.DENSITY
Am_MELT = 1449 * Kw.KELVIN
Am_BOIL = 2880 * Kw.KELVIN
Am_Cp = -1 * Kw.SPECIFICHEAT
Am_En = 1.13
CmZ = 96
Cm_MASS = 247 * Kw.MOLARMASS
CmMASS = Cm_MASS / Kw.AVOGADRO
Cm_DENSITY = 13510 * Kw.DENSITY
Cm_MELT = 1613 * Kw.KELVIN
Cm_BOIL = 3383 * Kw.KELVIN
Cm_Cp = -1 * Kw.SPECIFICHEAT
Cm_En = 1.28
BkZ = 97
Bk_MASS = 247 * Kw.MOLARMASS
BkMASS = Bk_MASS / Kw.AVOGADRO
Bk_DENSITY = 14790 * Kw.DENSITY
Bk_MELT = 1259 * Kw.KELVIN
Bk_BOIL = 2900 * Kw.KELVIN
Bk_Cp = -1 * Kw.SPECIFICHEAT
Bk_En = 1.3
CfZ = 98
Cf_MASS = 251 * Kw.MOLARMASS
CfMASS = Cf_MASS / Kw.AVOGADRO
Cf_DENSITY = 15100 * Kw.DENSITY
Cf_MELT = 1173 * Kw.KELVIN
Cf_BOIL = -1 * Kw.KELVIN
Cf_Cp = -1 * Kw.SPECIFICHEAT
Cf_En = 1.3
EsZ = 99
Es_MASS = 252 * Kw.MOLARMASS
EsMASS = Es_MASS / Kw.AVOGADRO
Es_DENSITY = 8840 * Kw.DENSITY
Es_MELT = 1133 * Kw.KELVIN
Es_BOIL = -1 * Kw.KELVIN
Es_Cp = -1 * Kw.SPECIFICHEAT
Es_En = 1.3
FmZ = 100
Fm_MASS = 257 * Kw.MOLARMASS
FmMASS = Fm_MASS / Kw.AVOGADRO
Fm_DENSITY = -1 * Kw.DENSITY
Fm_MELT = -1 * Kw.KELVIN
Fm_BOIL = -1 * Kw.KELVIN
Fm_Cp = -1 * Kw.SPECIFICHEAT
Fm_En = 1.3
MdZ = 101
Md_MASS = 258 * Kw.MOLARMASS
MdMASS = Md_MASS / Kw.AVOGADRO
Md_DENSITY = -1 * Kw.DENSITY
Md_MELT = -1 * Kw.KELVIN
Md_BOIL = -1 * Kw.KELVIN
Md_Cp = -1 * Kw.SPECIFICHEAT
Md_En = 1.3
NoZ = 102
No_MASS = 259 * Kw.MOLARMASS
NoMASS = No_MASS / Kw.AVOGADRO
No_DENSITY = -1 * Kw.DENSITY
No_MELT = -1 * Kw.KELVIN
No_BOIL = -1 * Kw.KELVIN
No_Cp = -1 * Kw.SPECIFICHEAT
No_En = 1.3
LrZ = 103
Lr_MASS = 266 * Kw.MOLARMASS
LrMASS = Lr_MASS / Kw.AVOGADRO
Lr_DENSITY = -1 * Kw.DENSITY
Lr_MELT = -1 * Kw.KELVIN
Lr_BOIL = -1 * Kw.KELVIN
Lr_Cp = -1 * Kw.SPECIFICHEAT
Lr_En = 1.3
RfZ = 104
Rf_MASS = 267 * Kw.MOLARMASS
RfMASS = Rf_MASS / Kw.AVOGADRO
Rf_DENSITY = -1 * Kw.DENSITY
Rf_MELT = -1 * Kw.KELVIN
Rf_BOIL = -1 * Kw.KELVIN
Rf_Cp = -1 * Kw.SPECIFICHEAT
Rf_En = -1
DbZ = 105
Db_MASS = 268 * Kw.MOLARMASS
DbMASS = Db_MASS / Kw.AVOGADRO
Db_DENSITY = -1 * Kw.DENSITY
Db_MELT = -1 * Kw.KELVIN
Db_BOIL = -1 * Kw.KELVIN
Db_Cp = -1 * Kw.SPECIFICHEAT
Db_En = -1
SgZ = 106
Sg_MASS = 269 * Kw.MOLARMASS
SgMASS = Sg_MASS / Kw.AVOGADRO
Sg_DENSITY = -1 * Kw.DENSITY
Sg_MELT = -1 * Kw.KELVIN
Sg_BOIL = -1 * Kw.KELVIN
Sg_Cp = -1 * Kw.SPECIFICHEAT
Sg_En = -1
BhZ = 107
Bh_MASS = 270 * Kw.MOLARMASS
BhMASS = Bh_MASS / Kw.AVOGADRO
Bh_DENSITY = -1 * Kw.DENSITY
Bh_MELT = -1 * Kw.KELVIN
Bh_BOIL = -1 * Kw.KELVIN
Bh_Cp = -1 * Kw.SPECIFICHEAT
Bh_En = -1
HsZ = 108
Hs_MASS = 270 * Kw.MOLARMASS
HsMASS = Hs_MASS / Kw.AVOGADRO
Hs_DENSITY = -1 * Kw.DENSITY
Hs_MELT = -1 * Kw.KELVIN
Hs_BOIL = -1 * Kw.KELVIN
Hs_Cp = -1 * Kw.SPECIFICHEAT
Hs_En = -1
MtZ = 109
Mt_MASS = 278 * Kw.MOLARMASS
MtMASS = Mt_MASS / Kw.AVOGADRO
Mt_DENSITY = -1 * Kw.DENSITY
Mt_MELT = -1 * Kw.KELVIN
Mt_BOIL = -1 * Kw.KELVIN
Mt_Cp = -1 * Kw.SPECIFICHEAT
Mt_En = -1
DsZ = 110
Ds_MASS = 281 * Kw.MOLARMASS
DsMASS = Ds_MASS / Kw.AVOGADRO
Ds_DENSITY = -1 * Kw.DENSITY
Ds_MELT = -1 * Kw.KELVIN
Ds_BOIL = -1 * Kw.KELVIN
Ds_Cp = -1 * Kw.SPECIFICHEAT
Ds_En = -1
RgZ = 111
Rg_MASS = 282 * Kw.MOLARMASS
RgMASS = Rg_MASS / Kw.AVOGADRO
Rg_DENSITY = -1 * Kw.DENSITY
Rg_MELT = -1 * Kw.KELVIN
Rg_BOIL = -1 * Kw.KELVIN
Rg_Cp = -1 * Kw.SPECIFICHEAT
Rg_En = -1
CnZ = 112
Cn_MASS = 285 * Kw.MOLARMASS
CnMASS = Cn_MASS / Kw.AVOGADRO
Cn_DENSITY = -1 * Kw.DENSITY
Cn_MELT = -1 * Kw.KELVIN
Cn_BOIL = 357 * Kw.KELVIN
Cn_Cp = -1 * Kw.SPECIFICHEAT
Cn_En = -1
NhZ = 113
Nh_MASS = 286 * Kw.MOLARMASS
NhMASS = Nh_MASS / Kw.AVOGADRO
Nh_DENSITY = -1 * Kw.DENSITY
Nh_MELT = -1 * Kw.KELVIN
Nh_BOIL = -1 * Kw.KELVIN
Nh_Cp = -1 * Kw.SPECIFICHEAT
Nh_En = -1
FlZ = 114
Fl_MASS = 289 * Kw.MOLARMASS
FlMASS = Fl_MASS / Kw.AVOGADRO
Fl_DENSITY = -1 * Kw.DENSITY
Fl_MELT = -1 * Kw.KELVIN
Fl_BOIL = 210 * Kw.KELVIN
Fl_Cp = -1 * Kw.SPECIFICHEAT
Fl_En = -1
McZ = 115
Mc_MASS = 290 * Kw.MOLARMASS
McMASS = Mc_MASS / Kw.AVOGADRO
Mc_DENSITY = -1 * Kw.DENSITY
Mc_MELT = -1 * Kw.KELVIN
Mc_BOIL = -1 * Kw.KELVIN
Mc_Cp = -1 * Kw.SPECIFICHEAT
Mc_En = -1
LvZ = 116
Lv_MASS = 293 * Kw.MOLARMASS
LvMASS = Lv_MASS / Kw.AVOGADRO
Lv_DENSITY = -1 * Kw.DENSITY
Lv_MELT = -1 * Kw.KELVIN
Lv_BOIL = -1 * Kw.KELVIN
Lv_Cp = -1 * Kw.SPECIFICHEAT
Lv_En = -1
TsZ = 117
Ts_MASS = 294 * Kw.MOLARMASS
TsMASS = Ts_MASS / Kw.AVOGADRO
Ts_DENSITY = -1 * Kw.DENSITY
Ts_MELT = -1 * Kw.KELVIN
Ts_BOIL = -1 * Kw.KELVIN
Ts_Cp = -1 * Kw.SPECIFICHEAT
Ts_En = -1
OgZ = 118
Og_MASS = 294 * Kw.MOLARMASS
OgMASS = Og_MASS / Kw.AVOGADRO
Og_DENSITY = -1 * Kw.DENSITY
Og_MELT = -1 * Kw.KELVIN
Og_BOIL = -1 * Kw.KELVIN
Og_Cp = -1 * Kw.SPECIFICHEAT
Og_En = -1
AIR_MASS = Kw.PPM * (780781 * (2 * N_MASS) + 209444 * (2 *\
      O_MASS) + 9339 * Ar_MASS + 410 * (C_MASS + 2 * O_MASS)\
      + 18.18 * Ne_MASS + 5.24 * He_MASS + 1.79 * (C_MASS + 4\
      * H_MASS) + 1.14 * Kr_MASS + 0.55 * (2 * H_MASS))
WATER_MASS = 2.0 * H_MASS + O_MASS
WATERMASS = 2.0 * HMASS + OMASS
WATER_Cp = 4184 * Kw.SPECIFICHEAT
ICE_Cp = 2108 * Kw.SPECIFICHEAT
STEAM_Cp = 1996 * Kw.SPECIFICHEAT
WATER_FUSION = 3.3355E+5 * Kw.JOULE / Kw.KILOGRAM
WATER_VAPORIZATION = 2.257E+6 * Kw.JOULE / Kw.KILOGRAM
H1_MASS = 1.007825032241 * Kw.MOLARMASS
H1MASS = H1_MASS / Kw.AVOGADRO
H2_MASS = 2.01410177811 * Kw.MOLARMASS
H2MASS = H2_MASS / Kw.AVOGADRO
H3_MASS = 3.01604928199 * Kw.MOLARMASS
H3MASS = H3_MASS / Kw.AVOGADRO
He3_MASS = 3.01602932265 * Kw.MOLARMASS
He3MASS = He3_MASS / Kw.AVOGADRO
He4_MASS = 4.002603254130 * Kw.MOLARMASS
He4MASS = He4_MASS / Kw.AVOGADRO
C12_MASS = 12.0 * Kw.MOLARMASS
C12MASS = C12_MASS / Kw.AVOGADRO
C13_MASS = 13.00335483521 * Kw.MOLARMASS
C13MASS = C13_MASS / Kw.AVOGADRO
C14_MASS = 14.003241988 * Kw.MOLARMASS
C14MASS = C14_MASS / Kw.AVOGADRO
O16_MASS = 15.99491461960 * Kw.MOLARMASS
O16MASS = O16_MASS / Kw.AVOGADRO
O17_MASS = 16.9991317566 * Kw.MOLARMASS
O17MASS = O17_MASS / Kw.AVOGADRO
O18_MASS = 17.9991596128 * Kw.MOLARMASS
O18MASS = O18_MASS / Kw.AVOGADRO
C13_RATIO = 0.0107
C14_RATIO = 1E-12
C12_RATIO = 1.0 - C13_RATIO - C14_RATIO
C_M_MASS = C12_MASS * C12_RATIO + C13_MASS * C13_RATIO +\
      C14_MASS * C14_RATIO
VSMOW_H3_RATIO = 1.85E-17
VSMOW_H2_RATIO = 1.5576E-4
VSMOW_H1_RATIO = 1.0 - VSMOW_H2_RATIO - VSMOW_H3_RATIO
VSMOW_H_MASS = (H1_MASS * VSMOW_H1_RATIO + H2_MASS *\
      VSMOW_H2_RATIO + H3_MASS * VSMOW_H3_RATIO)
VSMOW_O18_RATIO = 2.00520E-3
VSMOW_O17_RATIO = 3.799E-4
VSMOW_O16_RATIO = 1.0 - VSMOW_O17_RATIO - VSMOW_O18_RATIO
VSMOW_O_MASS = O16_MASS * VSMOW_O16_RATIO + O17_MASS *\
      VSMOW_O17_RATIO + O18_MASS * VSMOW_O18_RATIO
VSMOW_MASS = 2 * VSMOW_H_MASS + VSMOW_O_MASS
CH4_MASS = 4 * H_MASS + 1 * C_MASS + 0 * O_MASS
CH4MASS = 4 * HMASS + 1 * CMASS + 0 * OMASS
C2H6_MASS = 6 * H_MASS + 2 * C_MASS + 0 * O_MASS
C2H6MASS = 6 * HMASS + 2 * CMASS + 0 * OMASS
C3H8_MASS = 8 * H_MASS + 3 * C_MASS + 0 * O_MASS
C3H8MASS = 8 * HMASS + 3 * CMASS + 0 * OMASS
C4H10_MASS = 10 * H_MASS + 4 * C_MASS + 0 * O_MASS
C4H10MASS = 10 * HMASS + 4 * CMASS + 0 * OMASS
C2H60_MASS = 6 * H_MASS + 2 * C_MASS + 1 * O_MASS
C2H60MASS = 6 * HMASS + 2 * CMASS + 1 * OMASS
CH3CH2OH_MASS = 6 * H_MASS + 2 * C_MASS + 1 * O_MASS
CH3CH2OHMASS = 6 * HMASS + 2 * CMASS + 1 * OMASS
C12H22O11_MASS = 22 * H_MASS + 12 * C_MASS + 11 * O_MASS
C12H22O11MASS = 22 * HMASS + 12 * CMASS + 11 * OMASS
HYDROGEN_MASS = 2 * H_MASS + 0 * C_MASS + 0 * O_MASS
HYDROGENMASS = 2 * HMASS + 0 * CMASS + 0 * OMASS
HYDROGENJPMOLE = 1.418E+8 * Kw.JOULE / Kw.KILOGRAM *\
      HYDROGEN_MASS
HYDROGENJPKG = HYDROGENJPMOLE / HYDROGEN_MASS
HYDROGENJPKGTOTAL = HYDROGENJPMOLE / (HYDROGEN_MASS + (0.5 *\
      2 + 2.0 * 0 - 1.0 * 0) * O_MASS)
METHANE_MASS = 4 * H_MASS + 1 * C_MASS + 0 * O_MASS
METHANEMASS = 4 * HMASS + 1 * CMASS + 0 * OMASS
METHANEJPMOLE = 5.550E+7 * Kw.JOULE / Kw.KILOGRAM * METHANE_MASS
METHANEJPKG = METHANEJPMOLE / METHANE_MASS
METHANEJPKGTOTAL = METHANEJPMOLE / (METHANE_MASS + (0.5 * 4 +\
      2.0 * 1 - 1.0 * 0) * O_MASS)
ETHANE_MASS = 6 * H_MASS + 2 * C_MASS + 0 * O_MASS
ETHANEMASS = 6 * HMASS + 2 * CMASS + 0 * OMASS
ETHANEJPMOLE = 5.190E+7 * Kw.JOULE / Kw.KILOGRAM * ETHANE_MASS
ETHANEJPKG = ETHANEJPMOLE / ETHANE_MASS
ETHANEJPKGTOTAL = ETHANEJPMOLE / (ETHANE_MASS + (0.5 * 6 +\
      2.0 * 2 - 1.0 * 0) * O_MASS)
PROPANE_MASS = 8 * H_MASS + 3 * C_MASS + 0 * O_MASS
PROPANEMASS = 8 * HMASS + 3 * CMASS + 0 * OMASS
PROPANEJPMOLE = 5.035E+7 * Kw.JOULE / Kw.KILOGRAM * PROPANE_MASS
PROPANEJPKG = PROPANEJPMOLE / PROPANE_MASS
PROPANEJPKGTOTAL = PROPANEJPMOLE / (PROPANE_MASS + (0.5 * 8 +\
      2.0 * 3 - 1.0 * 0) * O_MASS)
BUTANE_MASS = 10 * H_MASS + 4 * C_MASS + 0 * O_MASS
BUTANEMASS = 10 * HMASS + 4 * CMASS + 0 * OMASS
BUTANEJPMOLE = 4.950E+7 * Kw.JOULE / Kw.KILOGRAM * BUTANE_MASS
BUTANEJPKG = BUTANEJPMOLE / BUTANE_MASS
BUTANEJPKGTOTAL = BUTANEJPMOLE / (BUTANE_MASS + (0.5 * 10 +\
      2.0 * 4 - 1.0 * 0) * O_MASS)
ETHANOL_MASS = 6 * H_MASS + 2 * C_MASS + 1 * O_MASS
ETHANOLMASS = 6 * HMASS + 2 * CMASS + 1 * OMASS
ETHANOLJPMOLE = 2.97E+7 * Kw.JOULE / Kw.KILOGRAM * ETHANOL_MASS
ETHANOLJPKG = ETHANOLJPMOLE / ETHANOL_MASS
ETHANOLJPKGTOTAL = ETHANOLJPMOLE / (ETHANOL_MASS + (0.5 * 6 +\
      2.0 * 2 - 1.0 * 1) * O_MASS)
SUGAR_MASS = 22 * H_MASS + 12 * C_MASS + 11 * O_MASS
SUGARMASS = 22 * HMASS + 12 * CMASS + 11 * OMASS
SUGARJPMOLE = 1.619E+7 * Kw.JOULE / Kw.KILOGRAM * SUGAR_MASS
SUGARJPKG = SUGARJPMOLE / SUGAR_MASS
SUGARJPKGTOTAL = SUGARJPMOLE / (SUGAR_MASS + (0.5 * 22 + 2.0\
      * 12 - 1.0 * 11) * O_MASS)
COAL_MASS = 0 * H_MASS + 1 * C_MASS + 0 * O_MASS
COALMASS = 0 * HMASS + 1 * CMASS + 0 * OMASS
COALJPMOLE = 3.0E+7 * Kw.JOULE / Kw.KILOGRAM * COAL_MASS
COALJPKG = COALJPMOLE / COAL_MASS
COALJPKGTOTAL = COALJPMOLE / (COAL_MASS + (0.5 * 0 + 2.0 * 1\
      - 1.0 * 0) * O_MASS)
PARAFFIN_MASS = 62 * H_MASS + 30 * C_MASS + 0 * O_MASS
PARAFFINMASS = 62 * HMASS + 30 * CMASS + 0 * OMASS
PARAFFINJPMOLE = 4.6E+7 * Kw.JOULE / Kw.KILOGRAM * PARAFFIN_MASS
PARAFFINJPKG = PARAFFINJPMOLE / PARAFFIN_MASS
PARAFFINJPKGTOTAL = PARAFFINJPMOLE / (PARAFFIN_MASS + (0.5 *\
      62 + 2.0 * 30 - 1.0 * 0) * O_MASS)
FAT_MASS = 100 * H_MASS + 60 * C_MASS + 6 * O_MASS
FATMASS = 100 * HMASS + 60 * CMASS + 6 * OMASS
FATJPMOLE = 3.7E+7 * Kw.JOULE / Kw.KILOGRAM * FAT_MASS
FATJPKG = FATJPMOLE / FAT_MASS
FATJPKGTOTAL = FATJPMOLE / (FAT_MASS + (0.5 * 100 + 2.0 * 60\
      - 1.0 * 6) * O_MASS)
DIESEL_MASS = 26 * H_MASS + 12 * C_MASS + 0 * O_MASS
DIESELMASS = 26 * HMASS + 12 * CMASS + 0 * OMASS
DIESELJPMOLE = 4.48E+7 * Kw.JOULE / Kw.KILOGRAM * DIESEL_MASS
DIESELJPKG = DIESELJPMOLE / DIESEL_MASS
DIESELJPKGTOTAL = DIESELJPMOLE / (DIESEL_MASS + (0.5 * 26 +\
      2.0 * 12 - 1.0 * 0) * O_MASS)
GASOLINE_MASS = 18 * H_MASS + 8 * C_MASS + 0 * O_MASS
GASOLINEMASS = 18 * HMASS + 8 * CMASS + 0 * OMASS
GASOLINEJPMOLE = 4.64E+7 * Kw.JOULE / Kw.KILOGRAM * GASOLINE_MASS
GASOLINEJPKG = GASOLINEJPMOLE / GASOLINE_MASS
GASOLINEJPKGTOTAL = GASOLINEJPMOLE / (GASOLINE_MASS + (0.5 *\
      18 + 2.0 * 8 - 1.0 * 0) * O_MASS)
SUCROSE_MASS = C12H22O11_MASS
TNTJPKG = 4.184E+6 * Kw.JOULE / Kw.KILOGRAM
SUGARDENSITY = 845 * Kw.DENSITY
DIESELDENSITY = 832 * Kw.DENSITY
GASOLINEDENSITY = 748.9 * Kw.DENSITY
ETHANOLDENSITY = 789 * Kw.DENSITY
PARAFFINDENSITY = 900 * Kw.DENSITY
FATDENSITY = 900 * Kw.DENSITY
#   DDDDDDDDDDescription --------------- kwelements_description #
def kwelements_description():
   return( \
   "   Kwelements Constants: Ac_BOIL Ac_Cp Ac_DENSITY Ac_En " + \
   "Ac_MASS Ac_MELT AcMASS AcZ Ag_BOIL Ag_Cp Ag_DENSITY Ag_E" + \
   "n Ag_MASS Ag_MELT AgMASS AgZ AIR_MASS Al_BOIL Al_Cp Al_D" + \
   "ENSITY Al_En Al_MASS Al_MELT AlMASS AlZ Am_BOIL Am_Cp Am" + \
   "_DENSITY Am_En Am_MASS Am_MELT AmMASS AmZ Ar_BOIL Ar_Cp " + \
   "Ar_DENSITY Ar_En Ar_MASS Ar_MELT ArMASS ArZ As_BOIL As_C" + \
   "p As_DENSITY As_En As_MASS As_MELT AsMASS AsZ At_BOIL At" + \
   "_Cp At_DENSITY At_En At_MASS At_MELT AtMASS AtZ Au_BOIL " + \
   "Au_Cp Au_DENSITY Au_En Au_MASS Au_MELT AuMASS AuZ B_BOIL" + \
   " B_Cp B_DENSITY B_En B_MASS B_MELT Ba_BOIL Ba_Cp Ba_DENS" + \
   "ITY Ba_En Ba_MASS Ba_MELT BaMASS BaZ Be_BOIL Be_Cp Be_DE" + \
   "NSITY Be_En Be_MASS Be_MELT BeMASS BeZ Bh_BOIL Bh_Cp Bh_" + \
   "DENSITY Bh_En Bh_MASS Bh_MELT BhMASS BhZ Bi_BOIL Bi_Cp B" + \
   "i_DENSITY Bi_En Bi_MASS Bi_MELT BiMASS BiZ Bk_BOIL Bk_Cp" + \
   " Bk_DENSITY Bk_En Bk_MASS Bk_MELT BkMASS BkZ BMASS Br_BO" + \
   "IL Br_Cp Br_DENSITY Br_En Br_MASS Br_MELT BrMASS BrZ BUT" + \
   "ANE_MASS BUTANEJPKG BUTANEJPKGTOTAL BUTANEJPMOLE BUTANEM" + \
   "ASS BZ C12_MASS C12_RATIO C12H22O11_MASS C12H22O11MASS C" + \
   "12MASS C13_MASS C13_RATIO C13MASS C14_MASS C14_RATIO C14" + \
   "MASS C2H60_MASS C2H60MASS C2H6_MASS C2H6MASS C3H8_MASS C" + \
   "3H8MASS C4H10_MASS C4H10MASS C_BOIL C_Cp C_DENSITY C_En " + \
   "C_M_MASS C_MASS C_MELT Ca_BOIL Ca_Cp Ca_DENSITY Ca_En Ca" + \
   "_MASS Ca_MELT CaMASS CaZ Cd_BOIL Cd_Cp Cd_DENSITY Cd_En " + \
   "Cd_MASS Cd_MELT CdMASS CdZ Ce_BOIL Ce_Cp Ce_DENSITY Ce_E" + \
   "n Ce_MASS Ce_MELT CeMASS CeZ Cf_BOIL Cf_Cp Cf_DENSITY Cf" + \
   "_En Cf_MASS Cf_MELT CfMASS CfZ CH3CH2OH_MASS CH3CH2OHMAS" + \
   "S CH4_MASS CH4MASS Cl_BOIL Cl_Cp Cl_DENSITY Cl_En Cl_MAS" + \
   "S Cl_MELT ClMASS ClZ Cm_BOIL Cm_Cp Cm_DENSITY Cm_En Cm_M" + \
   "ASS Cm_MELT CMASS CmMASS CmZ Cn_BOIL Cn_Cp Cn_DENSITY Cn" + \
   "_En Cn_MASS Cn_MELT CnMASS CnZ Co_BOIL Co_Cp Co_DENSITY " + \
   "Co_En Co_MASS Co_MELT COAL_MASS COALJPKG COALJPKGTOTAL C" + \
   "OALJPMOLE COALMASS CoMASS CoZ Cr_BOIL Cr_Cp Cr_DENSITY C" + \
   "r_En Cr_MASS Cr_MELT CrMASS CrZ Cs_BOIL Cs_Cp Cs_DENSITY" + \
   " Cs_En Cs_MASS Cs_MELT CsMASS CsZ Cu_BOIL Cu_Cp Cu_DENSI" + \
   "TY Cu_En Cu_MASS Cu_MELT CuMASS CuZ CZ Db_BOIL Db_Cp Db_" + \
   "DENSITY Db_En Db_MASS Db_MELT DbMASS DbZ DIESEL_MASS DIE" + \
   "SELDENSITY DIESELJPKG DIESELJPKGTOTAL DIESELJPMOLE DIESE" + \
   "LMASS Ds_BOIL Ds_Cp Ds_DENSITY Ds_En Ds_MASS Ds_MELT DsM" + \
   "ASS DsZ Dy_BOIL Dy_Cp Dy_DENSITY Dy_En Dy_MASS Dy_MELT D" + \
   "yMASS DyZ Er_BOIL Er_Cp Er_DENSITY Er_En Er_MASS Er_MELT" + \
   " ErMASS ErZ Es_BOIL Es_Cp Es_DENSITY Es_En Es_MASS Es_ME" + \
   "LT EsMASS EsZ ETHANE_MASS ETHANEJPKG ETHANEJPKGTOTAL ETH" + \
   "ANEJPMOLE ETHANEMASS ETHANOL_MASS ETHANOLDENSITY ETHANOL" + \
   "JPKG ETHANOLJPKGTOTAL ETHANOLJPMOLE ETHANOLMASS Eu_BOIL " + \
   "Eu_Cp Eu_DENSITY Eu_En Eu_MASS Eu_MELT EuMASS EuZ F_BOIL" + \
   " F_Cp F_DENSITY F_En F_MASS F_MELT FAT_MASS FATDENSITY F" + \
   "ATJPKG FATJPKGTOTAL FATJPMOLE FATMASS Fe_BOIL Fe_Cp Fe_D" + \
   "ENSITY Fe_En Fe_MASS Fe_MELT FeMASS FeZ Fl_BOIL Fl_Cp Fl" + \
   "_DENSITY Fl_En Fl_MASS Fl_MELT FlMASS FlZ Fm_BOIL Fm_Cp " + \
   "Fm_DENSITY Fm_En Fm_MASS Fm_MELT FMASS FmMASS FmZ Fr_BOI" + \
   "L Fr_Cp Fr_DENSITY Fr_En Fr_MASS Fr_MELT FrMASS FrZ FZ G" + \
   "a_BOIL Ga_Cp Ga_DENSITY Ga_En Ga_MASS Ga_MELT GaMASS GAS" + \
   "OLINE_MASS GASOLINEDENSITY GASOLINEJPKG GASOLINEJPKGTOTA" + \
   "L GASOLINEJPMOLE GASOLINEMASS GaZ Gd_BOIL Gd_Cp Gd_DENSI" + \
   "TY Gd_En Gd_MASS Gd_MELT GdMASS GdZ Ge_BOIL Ge_Cp Ge_DEN" + \
   "SITY Ge_En Ge_MASS Ge_MELT GeMASS GeZ H1_MASS H1MASS H2_" + \
   "MASS H2MASS H3_MASS H3MASS H_BOIL H_Cp H_DENSITY H_En H_" + \
   "MASS H_MELT He3_MASS He3MASS He4_MASS He4MASS He_BOIL He" + \
   "_Cp He_DENSITY He_En He_MASS He_MELT HeMASS HeZ Hf_BOIL " + \
   "Hf_Cp Hf_DENSITY Hf_En Hf_MASS Hf_MELT HfMASS HfZ Hg_BOI" + \
   "L Hg_Cp Hg_DENSITY Hg_En Hg_MASS Hg_MELT HgMASS HgZ HMAS" + \
   "S Ho_BOIL Ho_Cp Ho_DENSITY Ho_En Ho_MASS Ho_MELT HoMASS " + \
   "HoZ Hs_BOIL Hs_Cp Hs_DENSITY Hs_En Hs_MASS Hs_MELT HsMAS" + \
   "S HsZ HYDROGEN_MASS HYDROGENJPKG HYDROGENJPKGTOTAL HYDRO" + \
   "GENJPMOLE HYDROGENMASS HZ I_BOIL I_Cp I_DENSITY I_En I_M" + \
   "ASS I_MELT ICE_Cp IMASS In_BOIL In_Cp In_DENSITY In_En I" + \
   "n_MASS In_MELT InMASS InZ Ir_BOIL Ir_Cp Ir_DENSITY Ir_En" + \
   " Ir_MASS Ir_MELT IrMASS IrZ IZ K_BOIL K_Cp K_DENSITY K_E" + \
   "n K_MASS K_MELT KMASS Kr_BOIL Kr_Cp Kr_DENSITY Kr_En Kr_" + \
   "MASS Kr_MELT KrMASS KrZ KZ La_BOIL La_Cp La_DENSITY La_E" + \
   "n La_MASS La_MELT LaMASS LaZ Li_BOIL Li_Cp Li_DENSITY Li" + \
   "_En Li_MASS Li_MELT LiMASS LiZ Lr_BOIL Lr_Cp Lr_DENSITY " + \
   "Lr_En Lr_MASS Lr_MELT LrMASS LrZ Lu_BOIL Lu_Cp Lu_DENSIT" + \
   "Y Lu_En Lu_MASS Lu_MELT LuMASS LuZ Lv_BOIL Lv_Cp Lv_DENS" + \
   "ITY Lv_En Lv_MASS Lv_MELT LvMASS LvZ Mc_BOIL Mc_Cp Mc_DE" + \
   "NSITY Mc_En Mc_MASS Mc_MELT McMASS McZ Md_BOIL Md_Cp Md_" + \
   "DENSITY Md_En Md_MASS Md_MELT MdMASS MdZ METHANE_MASS ME" + \
   "THANEJPKG METHANEJPKGTOTAL METHANEJPMOLE METHANEMASS Mg_" + \
   "BOIL Mg_Cp Mg_DENSITY Mg_En Mg_MASS Mg_MELT MgMASS MgZ M" + \
   "n_BOIL Mn_Cp Mn_DENSITY Mn_En Mn_MASS Mn_MELT MnMASS MnZ" + \
   " Mo_BOIL Mo_Cp Mo_DENSITY Mo_En Mo_MASS Mo_MELT MoMASS M" + \
   "oZ Mt_BOIL Mt_Cp Mt_DENSITY Mt_En Mt_MASS Mt_MELT MtMASS" + \
   " MtZ N_BOIL N_Cp N_DENSITY N_En N_MASS N_MELT Na_BOIL Na" + \
   "_Cp Na_DENSITY Na_En Na_MASS Na_MELT NaMASS NaZ Nb_BOIL " + \
   "Nb_Cp Nb_DENSITY Nb_En Nb_MASS Nb_MELT NbMASS NbZ Nd_BOI" + \
   "L Nd_Cp Nd_DENSITY Nd_En Nd_MASS Nd_MELT NdMASS NdZ Ne_B" + \
   "OIL Ne_Cp Ne_DENSITY Ne_En Ne_MASS Ne_MELT NeMASS NeZ Nh" + \
   "_BOIL Nh_Cp Nh_DENSITY Nh_En Nh_MASS Nh_MELT NhMASS NhZ " + \
   "Ni_BOIL Ni_Cp Ni_DENSITY Ni_En Ni_MASS Ni_MELT NiMASS Ni" + \
   "Z NMASS No_BOIL No_Cp No_DENSITY No_En No_MASS No_MELT N" + \
   "oMASS NoZ Np_BOIL Np_Cp Np_DENSITY Np_En Np_MASS Np_MELT" + \
   " NpMASS NpZ NZ O16_MASS O16MASS O17_MASS O17MASS O18_MAS" + \
   "S O18MASS O_BOIL O_Cp O_DENSITY O_En O_MASS O_MELT Og_BO" + \
   "IL Og_Cp Og_DENSITY Og_En Og_MASS Og_MELT OgMASS OgZ OMA" + \
   "SS Os_BOIL Os_Cp Os_DENSITY Os_En Os_MASS Os_MELT OsMASS" + \
   " OsZ OZ P_BOIL P_Cp P_DENSITY P_En P_MASS P_MELT Pa_BOIL" + \
   " Pa_Cp Pa_DENSITY Pa_En Pa_MASS Pa_MELT PaMASS PARAFFIN_" + \
   "MASS PARAFFINDENSITY PARAFFINJPKG PARAFFINJPKGTOTAL PARA" + \
   "FFINJPMOLE PARAFFINMASS PaZ Pb_BOIL Pb_Cp Pb_DENSITY Pb_" + \
   "En Pb_MASS Pb_MELT PbMASS PbZ Pd_BOIL Pd_Cp Pd_DENSITY P" + \
   "d_En Pd_MASS Pd_MELT PdMASS PdZ Pm_BOIL Pm_Cp Pm_DENSITY" + \
   " Pm_En Pm_MASS Pm_MELT PMASS PmMASS PmZ Po_BOIL Po_Cp Po" + \
   "_DENSITY Po_En Po_MASS Po_MELT PoMASS PoZ Pr_BOIL Pr_Cp " + \
   "Pr_DENSITY Pr_En Pr_MASS Pr_MELT PrMASS PROPANE_MASS PRO" + \
   "PANEJPKG PROPANEJPKGTOTAL PROPANEJPMOLE PROPANEMASS PrZ " + \
   "Pt_BOIL Pt_Cp Pt_DENSITY Pt_En Pt_MASS Pt_MELT PtMASS Pt" + \
   "Z Pu_BOIL Pu_Cp Pu_DENSITY Pu_En Pu_MASS Pu_MELT PuMASS " + \
   "PuZ PZ Ra_BOIL Ra_Cp Ra_DENSITY Ra_En Ra_MASS Ra_MELT Ra" + \
   "MASS RaZ Rb_BOIL Rb_Cp Rb_DENSITY Rb_En Rb_MASS Rb_MELT " + \
   "RbMASS RbZ Re_BOIL Re_Cp Re_DENSITY Re_En Re_MASS Re_MEL" + \
   "T ReMASS ReZ Rf_BOIL Rf_Cp Rf_DENSITY Rf_En Rf_MASS Rf_M" + \
   "ELT RfMASS RfZ Rg_BOIL Rg_Cp Rg_DENSITY Rg_En Rg_MASS Rg" + \
   "_MELT RgMASS RgZ Rh_BOIL Rh_Cp Rh_DENSITY Rh_En Rh_MASS " + \
   "Rh_MELT RhMASS RhZ Rn_BOIL Rn_Cp Rn_DENSITY Rn_En Rn_MAS" + \
   "S Rn_MELT RnMASS RnZ Ru_BOIL Ru_Cp Ru_DENSITY Ru_En Ru_M" + \
   "ASS Ru_MELT RuMASS RuZ S_BOIL S_Cp S_DENSITY S_En S_MASS" + \
   " S_MELT Sb_BOIL Sb_Cp Sb_DENSITY Sb_En Sb_MASS Sb_MELT S" + \
   "bMASS SbZ Sc_BOIL Sc_Cp Sc_DENSITY Sc_En Sc_MASS Sc_MELT" + \
   " ScMASS ScZ Se_BOIL Se_Cp Se_DENSITY Se_En Se_MASS Se_ME" + \
   "LT SeMASS SeZ Sg_BOIL Sg_Cp Sg_DENSITY Sg_En Sg_MASS Sg_" + \
   "MELT SgMASS SgZ Si_BOIL Si_Cp Si_DENSITY Si_En Si_MASS S" + \
   "i_MELT SiMASS SiZ Sm_BOIL Sm_Cp Sm_DENSITY Sm_En Sm_MASS" + \
   " Sm_MELT SMASS SmMASS SmZ Sn_BOIL Sn_Cp Sn_DENSITY Sn_En" + \
   " Sn_MASS Sn_MELT SnMASS SnZ Sr_BOIL Sr_Cp Sr_DENSITY Sr_" + \
   "En Sr_MASS Sr_MELT SrMASS SrZ STEAM_Cp SUCROSE_MASS SUGA" + \
   "R_MASS SUGARDENSITY SUGARJPKG SUGARJPKGTOTAL SUGARJPMOLE" + \
   " SUGARMASS SZ Ta_BOIL Ta_Cp Ta_DENSITY Ta_En Ta_MASS Ta_" + \
   "MELT TaMASS TaZ Tb_BOIL Tb_Cp Tb_DENSITY Tb_En Tb_MASS T" + \
   "b_MELT TbMASS TbZ Tc_BOIL Tc_Cp Tc_DENSITY Tc_En Tc_MASS" + \
   " Tc_MELT TcMASS TcZ Te_BOIL Te_Cp Te_DENSITY Te_En Te_MA" + \
   "SS Te_MELT TeMASS TeZ Th_BOIL Th_Cp Th_DENSITY Th_En Th_" + \
   "MASS Th_MELT ThMASS ThZ Ti_BOIL Ti_Cp Ti_DENSITY Ti_En T" + \
   "i_MASS Ti_MELT TiMASS TiZ Tl_BOIL Tl_Cp Tl_DENSITY Tl_En" + \
   " Tl_MASS Tl_MELT TlMASS TlZ Tm_BOIL Tm_Cp Tm_DENSITY Tm_" + \
   "En Tm_MASS Tm_MELT TmMASS TmZ TNTJPKG Ts_BOIL Ts_Cp Ts_D" + \
   "ENSITY Ts_En Ts_MASS Ts_MELT TsMASS TsZ U_BOIL U_Cp U_DE" + \
   "NSITY U_En U_MASS U_MELT UMASS UZ V_BOIL V_Cp V_DENSITY " + \
   "V_En V_MASS V_MELT VMASS VSMOW_H1_RATIO VSMOW_H2_RATIO V" + \
   "SMOW_H3_RATIO VSMOW_H_MASS VSMOW_MASS VSMOW_O16_RATIO VS" + \
   "MOW_O17_RATIO VSMOW_O18_RATIO VSMOW_O_MASS VZ W_BOIL W_C" + \
   "p W_DENSITY W_En W_MASS W_MELT WATER_Cp WATER_FUSION WAT" + \
   "ER_MASS WATER_VAPORIZATION WATERMASS WMASS WZ Xe_BOIL Xe" + \
   "_Cp Xe_DENSITY Xe_En Xe_MASS Xe_MELT XeMASS XeZ Y_BOIL Y" + \
   "_Cp Y_DENSITY Y_En Y_MASS Y_MELT Yb_BOIL Yb_Cp Yb_DENSIT" + \
   "Y Yb_En Yb_MASS Yb_MELT YbMASS YbZ YMASS YZ Zn_BOIL Zn_C" + \
   "p Zn_DENSITY Zn_En Zn_MASS Zn_MELT ZnMASS ZnZ Zr_BOIL Zr" + \
   "_Cp Zr_DENSITY Zr_En Zr_MASS Zr_MELT ZrMASS ZrZ" + \
   "\n"
)
def kwelements_desc():
   return( \
   "   Kwelements Constants: Ac_(BOIL|Cp|DENSITY|En|M(ASS|EL" + \
   "T)) AcMASS AcZ Ag_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) AgMASS" + \
   " AgZ AIR_MASS Al_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) AlMASS " + \
   "AlZ Am_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) AmMASS AmZ Ar_(BO" + \
   "IL|Cp|DENSITY|En|M(ASS|ELT)) ArMASS ArZ As_(BOIL|Cp|DENS" + \
   "ITY|En|M(ASS|ELT)) AsMASS AsZ At_(BOIL|Cp|DENSITY|En|M(A" + \
   "SS|ELT)) AtMASS AtZ Au_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) A" + \
   "uMASS AuZ B_BOIL B_Cp B_DENSITY B_En B_M(ASS|ELT) Ba_(BO" + \
   "IL|Cp|DENSITY|En|M(ASS|ELT)) BaMASS BaZ Be_(BOIL|Cp|DENS" + \
   "ITY|En|M(ASS|ELT)) BeMASS BeZ Bh_(BOIL|Cp|DENSITY|En|M(A" + \
   "SS|ELT)) BhMASS BhZ Bi_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) B" + \
   "iMASS BiZ Bk_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) BkMASS BkZ " + \
   "BMASS Br_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) BrMASS BrZ BUTA" + \
   "NE(_MASS|JP(KG(TOTAL)?|MOLE)|MASS) BZ C12(_(MASS|RATIO)|" + \
   "H22O11(_MASS|MASS)|MASS) C13(_(MASS|RATIO)|MASS) C14(_(M" + \
   "ASS|RATIO)|MASS) C2H6(0(_MASS|MASS)|_MASS|MASS) C3H8(_MA" + \
   "SS|MASS) C4H10(_MASS|MASS) C_BOIL C_Cp C_DENSITY C_En C_" + \
   "M(_MASS|ASS|ELT) Ca_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) CaMA" + \
   "SS CaZ Cd_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) CdMASS CdZ Ce_" + \
   "(BOIL|Cp|DENSITY|En|M(ASS|ELT)) CeMASS CeZ Cf_(BOIL|Cp|D" + \
   "ENSITY|En|M(ASS|ELT)) CfMASS CfZ CH3CH2OH(_MASS|MASS) CH" + \
   "4(_MASS|MASS) Cl_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) ClMASS " + \
   "ClZ Cm_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) CMASS CmMASS CmZ " + \
   "Cn_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) CnMASS CnZ Co_(BOIL|C" + \
   "p|DENSITY|En|M(ASS|ELT)) COAL(_MASS|JP(KG(TOTAL)?|MOLE)|" + \
   "MASS) CoMASS CoZ Cr_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) CrMA" + \
   "SS CrZ Cs_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) CsMASS CsZ Cu_" + \
   "(BOIL|Cp|DENSITY|En|M(ASS|ELT)) CuMASS CuZ CZ Db_(BOIL|C" + \
   "p|DENSITY|En|M(ASS|ELT)) DbMASS DbZ DIESEL(_MASS|DENSITY" + \
   "|JP(KG(TOTAL)?|MOLE)|MASS) Ds_(BOIL|Cp|DENSITY|En|M(ASS|" + \
   "ELT)) DsMASS DsZ Dy_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) DyMA" + \
   "SS DyZ Er_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) ErMASS ErZ Es_" + \
   "(BOIL|Cp|DENSITY|En|M(ASS|ELT)) EsMASS EsZ ETHAN(E(_MASS" + \
   "|JP(KG(TOTAL)?|MOLE)|MASS)|OL(_MASS|DENSITY|JP(KG(TOTAL)" + \
   "?|MOLE)|MASS)) Eu_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) EuMASS" + \
   " EuZ F_BOIL F_Cp F_DENSITY F_En F_M(ASS|ELT) FAT(_MASS|D" + \
   "ENSITY|JP(KG(TOTAL)?|MOLE)|MASS) Fe_(BOIL|Cp|DENSITY|En|" + \
   "M(ASS|ELT)) FeMASS FeZ Fl_(BOIL|Cp|DENSITY|En|M(ASS|ELT)" + \
   ") FlMASS FlZ Fm_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) FMASS Fm" + \
   "MASS FmZ Fr_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) FrMASS FrZ F" + \
   "Z Ga_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) GaMASS GASOLINE(_MA" + \
   "SS|DENSITY|JP(KG(TOTAL)?|MOLE)|MASS) GaZ Gd_(BOIL|Cp|DEN" + \
   "SITY|En|M(ASS|ELT)) GdMASS GdZ Ge_(BOIL|Cp|DENSITY|En|M(" + \
   "ASS|ELT)) GeMASS GeZ H1_MASS H1MASS H2_MASS H2MASS H3_MA" + \
   "SS H3MASS H_BOIL H_Cp H_DENSITY H_En H_M(ASS|ELT) He3(_M" + \
   "ASS|MASS) He4(_MASS|MASS) He_(BOIL|Cp|DENSITY|En|M(ASS|E" + \
   "LT)) HeMASS HeZ Hf_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) HfMAS" + \
   "S HfZ Hg_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) HgMASS HgZ HMAS" + \
   "S Ho_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) HoMASS HoZ Hs_(BOIL" + \
   "|Cp|DENSITY|En|M(ASS|ELT)) HsMASS HsZ HYDROGEN(_MASS|JP(" + \
   "KG(TOTAL)?|MOLE)|MASS) HZ I_BOIL I_Cp I_DENSITY I_En I_M" + \
   "(ASS|ELT) ICE_Cp IMASS In_(BOIL|Cp|DENSITY|En|M(ASS|ELT)" + \
   ") InMASS InZ Ir_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) IrMASS I" + \
   "rZ IZ K_BOIL K_Cp K_DENSITY K_En K_M(ASS|ELT) KMASS Kr_(" + \
   "BOIL|Cp|DENSITY|En|M(ASS|ELT)) KrMASS KrZ KZ La_(BOIL|Cp" + \
   "|DENSITY|En|M(ASS|ELT)) LaMASS LaZ Li_(BOIL|Cp|DENSITY|E" + \
   "n|M(ASS|ELT)) LiMASS LiZ Lr_(BOIL|Cp|DENSITY|En|M(ASS|EL" + \
   "T)) LrMASS LrZ Lu_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) LuMASS" + \
   " LuZ Lv_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) LvMASS LvZ Mc_(B" + \
   "OIL|Cp|DENSITY|En|M(ASS|ELT)) McMASS McZ Md_(BOIL|Cp|DEN" + \
   "SITY|En|M(ASS|ELT)) MdMASS MdZ METHANE(_MASS|JP(KG(TOTAL" + \
   ")?|MOLE)|MASS) Mg_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) MgMASS" + \
   " MgZ Mn_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) MnMASS MnZ Mo_(B" + \
   "OIL|Cp|DENSITY|En|M(ASS|ELT)) MoMASS MoZ Mt_(BOIL|Cp|DEN" + \
   "SITY|En|M(ASS|ELT)) MtMASS MtZ N_BOIL N_Cp N_DENSITY N_E" + \
   "n N_M(ASS|ELT) Na_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) NaMASS" + \
   " NaZ Nb_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) NbMASS NbZ Nd_(B" + \
   "OIL|Cp|DENSITY|En|M(ASS|ELT)) NdMASS NdZ Ne_(BOIL|Cp|DEN" + \
   "SITY|En|M(ASS|ELT)) NeMASS NeZ Nh_(BOIL|Cp|DENSITY|En|M(" + \
   "ASS|ELT)) NhMASS NhZ Ni_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) " + \
   "NiMASS NiZ NMASS No_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) NoMA" + \
   "SS NoZ Np_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) NpMASS NpZ NZ " + \
   "O16(_MASS|MASS) O17(_MASS|MASS) O18(_MASS|MASS) O_BOIL O" + \
   "_Cp O_DENSITY O_En O_M(ASS|ELT) Og_(BOIL|Cp|DENSITY|En|M" + \
   "(ASS|ELT)) OgMASS OgZ OMASS Os_(BOIL|Cp|DENSITY|En|M(ASS" + \
   "|ELT)) OsMASS OsZ OZ P_BOIL P_Cp P_DENSITY P_En P_M(ASS|" + \
   "ELT) Pa_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) PaMASS PARAFFIN(" + \
   "_MASS|DENSITY|JP(KG(TOTAL)?|MOLE)|MASS) PaZ Pb_(BOIL|Cp|" + \
   "DENSITY|En|M(ASS|ELT)) PbMASS PbZ Pd_(BOIL|Cp|DENSITY|En" + \
   "|M(ASS|ELT)) PdMASS PdZ Pm_(BOIL|Cp|DENSITY|En|M(ASS|ELT" + \
   ")) PMASS PmMASS PmZ Po_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) P" + \
   "oMASS PoZ Pr_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) PrMASS PROP" + \
   "ANE(_MASS|JP(KG(TOTAL)?|MOLE)|MASS) PrZ Pt_(BOIL|Cp|DENS" + \
   "ITY|En|M(ASS|ELT)) PtMASS PtZ Pu_(BOIL|Cp|DENSITY|En|M(A" + \
   "SS|ELT)) PuMASS PuZ PZ Ra_(BOIL|Cp|DENSITY|En|M(ASS|ELT)" + \
   ") RaMASS RaZ Rb_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) RbMASS R" + \
   "bZ Re_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) ReMASS ReZ Rf_(BOI" + \
   "L|Cp|DENSITY|En|M(ASS|ELT)) RfMASS RfZ Rg_(BOIL|Cp|DENSI" + \
   "TY|En|M(ASS|ELT)) RgMASS RgZ Rh_(BOIL|Cp|DENSITY|En|M(AS" + \
   "S|ELT)) RhMASS RhZ Rn_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) Rn" + \
   "MASS RnZ Ru_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) RuMASS RuZ S" + \
   "_BOIL S_Cp S_DENSITY S_En S_M(ASS|ELT) Sb_(BOIL|Cp|DENSI" + \
   "TY|En|M(ASS|ELT)) SbMASS SbZ Sc_(BOIL|Cp|DENSITY|En|M(AS" + \
   "S|ELT)) ScMASS ScZ Se_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) Se" + \
   "MASS SeZ Sg_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) SgMASS SgZ S" + \
   "i_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) SiMASS SiZ Sm_(BOIL|Cp" + \
   "|DENSITY|En|M(ASS|ELT)) SMASS SmMASS SmZ Sn_(BOIL|Cp|DEN" + \
   "SITY|En|M(ASS|ELT)) SnMASS SnZ Sr_(BOIL|Cp|DENSITY|En|M(" + \
   "ASS|ELT)) SrMASS SrZ STEAM_Cp SUCROSE_MASS SUGAR(_MASS|D" + \
   "ENSITY|JP(KG(TOTAL)?|MOLE)|MASS) SZ Ta_(BOIL|Cp|DENSITY|" + \
   "En|M(ASS|ELT)) TaMASS TaZ Tb_(BOIL|Cp|DENSITY|En|M(ASS|E" + \
   "LT)) TbMASS TbZ Tc_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) TcMAS" + \
   "S TcZ Te_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) TeMASS TeZ Th_(" + \
   "BOIL|Cp|DENSITY|En|M(ASS|ELT)) ThMASS ThZ Ti_(BOIL|Cp|DE" + \
   "NSITY|En|M(ASS|ELT)) TiMASS TiZ Tl_(BOIL|Cp|DENSITY|En|M" + \
   "(ASS|ELT)) TlMASS TlZ Tm_(BOIL|Cp|DENSITY|En|M(ASS|ELT))" + \
   " TmMASS TmZ TNTJPKG Ts_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) T" + \
   "sMASS TsZ U_BOIL U_Cp U_DENSITY U_En U_M(ASS|ELT) UMASS " + \
   "UZ V_BOIL V_Cp V_DENSITY V_En V_M(ASS|ELT) VMASS VSMOW_(" + \
   "H(1_RATIO|2_RATIO|3_RATIO|_MASS)|MASS|O(1[678]_RATIO|_MA" + \
   "SS)) VZ W_BOIL W_Cp W_DENSITY W_En W_M(ASS|ELT) WATER(_(" + \
   "Cp|FUSION|MASS|VAPORIZATION)|MASS) WMASS WZ Xe_(BOIL|Cp|" + \
   "DENSITY|En|M(ASS|ELT)) XeMASS XeZ Y_BOIL Y_Cp Y_DENSITY " + \
   "Y_En Y_M(ASS|ELT) Yb_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) YbM" + \
   "ASS YbZ YMASS YZ Zn_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) ZnMA" + \
   "SS ZnZ Zr_(BOIL|Cp|DENSITY|En|M(ASS|ELT)) ZrMASS ZrZ" + \
   "\n"
)
