//   Copyright (C) 2021 by Kevin D. Woerner
//-/ =KDW= ################# BUILDER $KWROOT/0lib/vkkcp.sh ##################
//-/ =KDW= ######### SOURCE $KWROOT/codekdw/kw-lib/Kwelements.fwipp #########
//-/ =KDW= #### THIS FILE CAN BE OVERWRITTEN BY KEVIN D. WOERNER OR HIS #####
//-/ =KDW= ############ MINIONS AT *ANY* TIME. Caveat utilitor. #############
// 2021-05-14 kdw  For Changelog, See File Kwelements.varylog
#include "Kwelements.h"
//  CCCCCCCCCConstant ############################################## LANG_C #
double cxHYDROGEN_Z(void) { return (HYDROGEN_Z); }
double cxHYDROGEN(void) { return (HYDROGEN); }
double cxH_Z(void) { return (H_Z); }
double cxH_WEIGHT(void) { return (H_WEIGHT); }
double cxH_MASS(void) { return (H_MASS); }
double cxHMASS(void) { return (HMASS); }
double cxH_DENSITY(void) { return (H_DENSITY); }
double cxH_MELT(void) { return (H_MELT); }
double cxH_BOIL(void) { return (H_BOIL); }
double cxH_Cp(void) { return (H_Cp); }
double cxH_En(void) { return (H_En); }
double cxHELIUM_Z(void) { return (HELIUM_Z); }
double cxHELIUM(void) { return (HELIUM); }
double cxHe_Z(void) { return (He_Z); }
double cxHe_WEIGHT(void) { return (He_WEIGHT); }
double cxHe_MASS(void) { return (He_MASS); }
double cxHeMASS(void) { return (HeMASS); }
double cxHe_DENSITY(void) { return (He_DENSITY); }
double cxHe_MELT(void) { return (He_MELT); }
double cxHe_BOIL(void) { return (He_BOIL); }
double cxHe_Cp(void) { return (He_Cp); }
double cxHe_En(void) { return (He_En); }
double cxLITHIUM_Z(void) { return (LITHIUM_Z); }
double cxLITHIUM(void) { return (LITHIUM); }
double cxLi_Z(void) { return (Li_Z); }
double cxLi_WEIGHT(void) { return (Li_WEIGHT); }
double cxLi_MASS(void) { return (Li_MASS); }
double cxLiMASS(void) { return (LiMASS); }
double cxLi_DENSITY(void) { return (Li_DENSITY); }
double cxLi_MELT(void) { return (Li_MELT); }
double cxLi_BOIL(void) { return (Li_BOIL); }
double cxLi_Cp(void) { return (Li_Cp); }
double cxLi_En(void) { return (Li_En); }
double cxBERYLLIUM_Z(void) { return (BERYLLIUM_Z); }
double cxBERYLLIUM(void) { return (BERYLLIUM); }
double cxBe_Z(void) { return (Be_Z); }
double cxBe_WEIGHT(void) { return (Be_WEIGHT); }
double cxBe_MASS(void) { return (Be_MASS); }
double cxBeMASS(void) { return (BeMASS); }
double cxBe_DENSITY(void) { return (Be_DENSITY); }
double cxBe_MELT(void) { return (Be_MELT); }
double cxBe_BOIL(void) { return (Be_BOIL); }
double cxBe_Cp(void) { return (Be_Cp); }
double cxBe_En(void) { return (Be_En); }
double cxBORON_Z(void) { return (BORON_Z); }
double cxBORON(void) { return (BORON); }
double cxB_Z(void) { return (B_Z); }
double cxB_WEIGHT(void) { return (B_WEIGHT); }
double cxB_MASS(void) { return (B_MASS); }
double cxBMASS(void) { return (BMASS); }
double cxB_DENSITY(void) { return (B_DENSITY); }
double cxB_MELT(void) { return (B_MELT); }
double cxB_BOIL(void) { return (B_BOIL); }
double cxB_Cp(void) { return (B_Cp); }
double cxB_En(void) { return (B_En); }
double cxCARBON_Z(void) { return (CARBON_Z); }
double cxCARBON(void) { return (CARBON); }
double cxC_Z(void) { return (C_Z); }
double cxC_WEIGHT(void) { return (C_WEIGHT); }
double cxC_MASS(void) { return (C_MASS); }
double cxCMASS(void) { return (CMASS); }
double cxC_DENSITY(void) { return (C_DENSITY); }
double cxC_MELT(void) { return (C_MELT); }
double cxC_BOIL(void) { return (C_BOIL); }
double cxC_Cp(void) { return (C_Cp); }
double cxC_En(void) { return (C_En); }
double cxNITROGEN_Z(void) { return (NITROGEN_Z); }
double cxNITROGEN(void) { return (NITROGEN); }
double cxN_Z(void) { return (N_Z); }
double cxN_WEIGHT(void) { return (N_WEIGHT); }
double cxN_MASS(void) { return (N_MASS); }
double cxNMASS(void) { return (NMASS); }
double cxN_DENSITY(void) { return (N_DENSITY); }
double cxN_MELT(void) { return (N_MELT); }
double cxN_BOIL(void) { return (N_BOIL); }
double cxN_Cp(void) { return (N_Cp); }
double cxN_En(void) { return (N_En); }
double cxOXYGEN_Z(void) { return (OXYGEN_Z); }
double cxOXYGEN(void) { return (OXYGEN); }
double cxO_Z(void) { return (O_Z); }
double cxO_WEIGHT(void) { return (O_WEIGHT); }
double cxO_MASS(void) { return (O_MASS); }
double cxOMASS(void) { return (OMASS); }
double cxO_DENSITY(void) { return (O_DENSITY); }
double cxO_MELT(void) { return (O_MELT); }
double cxO_BOIL(void) { return (O_BOIL); }
double cxO_Cp(void) { return (O_Cp); }
double cxO_En(void) { return (O_En); }
double cxFLUORINE_Z(void) { return (FLUORINE_Z); }
double cxFLUORINE(void) { return (FLUORINE); }
double cxF_Z(void) { return (F_Z); }
double cxF_WEIGHT(void) { return (F_WEIGHT); }
double cxF_MASS(void) { return (F_MASS); }
double cxFMASS(void) { return (FMASS); }
double cxF_DENSITY(void) { return (F_DENSITY); }
double cxF_MELT(void) { return (F_MELT); }
double cxF_BOIL(void) { return (F_BOIL); }
double cxF_Cp(void) { return (F_Cp); }
double cxF_En(void) { return (F_En); }
double cxNEON_Z(void) { return (NEON_Z); }
double cxNEON(void) { return (NEON); }
double cxNe_Z(void) { return (Ne_Z); }
double cxNe_WEIGHT(void) { return (Ne_WEIGHT); }
double cxNe_MASS(void) { return (Ne_MASS); }
double cxNeMASS(void) { return (NeMASS); }
double cxNe_DENSITY(void) { return (Ne_DENSITY); }
double cxNe_MELT(void) { return (Ne_MELT); }
double cxNe_BOIL(void) { return (Ne_BOIL); }
double cxNe_Cp(void) { return (Ne_Cp); }
double cxNe_En(void) { return (Ne_En); }
double cxSODIUM_Z(void) { return (SODIUM_Z); }
double cxSODIUM(void) { return (SODIUM); }
double cxNa_Z(void) { return (Na_Z); }
double cxNa_WEIGHT(void) { return (Na_WEIGHT); }
double cxNa_MASS(void) { return (Na_MASS); }
double cxNaMASS(void) { return (NaMASS); }
double cxNa_DENSITY(void) { return (Na_DENSITY); }
double cxNa_MELT(void) { return (Na_MELT); }
double cxNa_BOIL(void) { return (Na_BOIL); }
double cxNa_Cp(void) { return (Na_Cp); }
double cxNa_En(void) { return (Na_En); }
double cxMAGNESIUM_Z(void) { return (MAGNESIUM_Z); }
double cxMAGNESIUM(void) { return (MAGNESIUM); }
double cxMg_Z(void) { return (Mg_Z); }
double cxMg_WEIGHT(void) { return (Mg_WEIGHT); }
double cxMg_MASS(void) { return (Mg_MASS); }
double cxMgMASS(void) { return (MgMASS); }
double cxMg_DENSITY(void) { return (Mg_DENSITY); }
double cxMg_MELT(void) { return (Mg_MELT); }
double cxMg_BOIL(void) { return (Mg_BOIL); }
double cxMg_Cp(void) { return (Mg_Cp); }
double cxMg_En(void) { return (Mg_En); }
double cxALUMINIUM_Z(void) { return (ALUMINIUM_Z); }
double cxALUMINIUM(void) { return (ALUMINIUM); }
double cxAl_Z(void) { return (Al_Z); }
double cxAl_WEIGHT(void) { return (Al_WEIGHT); }
double cxAl_MASS(void) { return (Al_MASS); }
double cxAlMASS(void) { return (AlMASS); }
double cxAl_DENSITY(void) { return (Al_DENSITY); }
double cxAl_MELT(void) { return (Al_MELT); }
double cxAl_BOIL(void) { return (Al_BOIL); }
double cxAl_Cp(void) { return (Al_Cp); }
double cxAl_En(void) { return (Al_En); }
double cxSILICON_Z(void) { return (SILICON_Z); }
double cxSILICON(void) { return (SILICON); }
double cxSi_Z(void) { return (Si_Z); }
double cxSi_WEIGHT(void) { return (Si_WEIGHT); }
double cxSi_MASS(void) { return (Si_MASS); }
double cxSiMASS(void) { return (SiMASS); }
double cxSi_DENSITY(void) { return (Si_DENSITY); }
double cxSi_MELT(void) { return (Si_MELT); }
double cxSi_BOIL(void) { return (Si_BOIL); }
double cxSi_Cp(void) { return (Si_Cp); }
double cxSi_En(void) { return (Si_En); }
double cxPHOSPHORUS_Z(void) { return (PHOSPHORUS_Z); }
double cxPHOSPHORUS(void) { return (PHOSPHORUS); }
double cxP_Z(void) { return (P_Z); }
double cxP_WEIGHT(void) { return (P_WEIGHT); }
double cxP_MASS(void) { return (P_MASS); }
double cxPMASS(void) { return (PMASS); }
double cxP_DENSITY(void) { return (P_DENSITY); }
double cxP_MELT(void) { return (P_MELT); }
double cxP_BOIL(void) { return (P_BOIL); }
double cxP_Cp(void) { return (P_Cp); }
double cxP_En(void) { return (P_En); }
double cxSULFUR_Z(void) { return (SULFUR_Z); }
double cxSULFUR(void) { return (SULFUR); }
double cxS_Z(void) { return (S_Z); }
double cxS_WEIGHT(void) { return (S_WEIGHT); }
double cxS_MASS(void) { return (S_MASS); }
double cxSMASS(void) { return (SMASS); }
double cxS_DENSITY(void) { return (S_DENSITY); }
double cxS_MELT(void) { return (S_MELT); }
double cxS_BOIL(void) { return (S_BOIL); }
double cxS_Cp(void) { return (S_Cp); }
double cxS_En(void) { return (S_En); }
double cxCHLORINE_Z(void) { return (CHLORINE_Z); }
double cxCHLORINE(void) { return (CHLORINE); }
double cxCl_Z(void) { return (Cl_Z); }
double cxCl_WEIGHT(void) { return (Cl_WEIGHT); }
double cxCl_MASS(void) { return (Cl_MASS); }
double cxClMASS(void) { return (ClMASS); }
double cxCl_DENSITY(void) { return (Cl_DENSITY); }
double cxCl_MELT(void) { return (Cl_MELT); }
double cxCl_BOIL(void) { return (Cl_BOIL); }
double cxCl_Cp(void) { return (Cl_Cp); }
double cxCl_En(void) { return (Cl_En); }
double cxARGON_Z(void) { return (ARGON_Z); }
double cxARGON(void) { return (ARGON); }
double cxAr_Z(void) { return (Ar_Z); }
double cxAr_WEIGHT(void) { return (Ar_WEIGHT); }
double cxAr_MASS(void) { return (Ar_MASS); }
double cxArMASS(void) { return (ArMASS); }
double cxAr_DENSITY(void) { return (Ar_DENSITY); }
double cxAr_MELT(void) { return (Ar_MELT); }
double cxAr_BOIL(void) { return (Ar_BOIL); }
double cxAr_Cp(void) { return (Ar_Cp); }
double cxAr_En(void) { return (Ar_En); }
double cxPOTASSIUM_Z(void) { return (POTASSIUM_Z); }
double cxPOTASSIUM(void) { return (POTASSIUM); }
double cxK_Z(void) { return (K_Z); }
double cxK_WEIGHT(void) { return (K_WEIGHT); }
double cxK_MASS(void) { return (K_MASS); }
double cxKMASS(void) { return (KMASS); }
double cxK_DENSITY(void) { return (K_DENSITY); }
double cxK_MELT(void) { return (K_MELT); }
double cxK_BOIL(void) { return (K_BOIL); }
double cxK_Cp(void) { return (K_Cp); }
double cxK_En(void) { return (K_En); }
double cxCALCIUM_Z(void) { return (CALCIUM_Z); }
double cxCALCIUM(void) { return (CALCIUM); }
double cxCa_Z(void) { return (Ca_Z); }
double cxCa_WEIGHT(void) { return (Ca_WEIGHT); }
double cxCa_MASS(void) { return (Ca_MASS); }
double cxCaMASS(void) { return (CaMASS); }
double cxCa_DENSITY(void) { return (Ca_DENSITY); }
double cxCa_MELT(void) { return (Ca_MELT); }
double cxCa_BOIL(void) { return (Ca_BOIL); }
double cxCa_Cp(void) { return (Ca_Cp); }
double cxCa_En(void) { return (Ca_En); }
double cxSCANDIUM_Z(void) { return (SCANDIUM_Z); }
double cxSCANDIUM(void) { return (SCANDIUM); }
double cxSc_Z(void) { return (Sc_Z); }
double cxSc_WEIGHT(void) { return (Sc_WEIGHT); }
double cxSc_MASS(void) { return (Sc_MASS); }
double cxScMASS(void) { return (ScMASS); }
double cxSc_DENSITY(void) { return (Sc_DENSITY); }
double cxSc_MELT(void) { return (Sc_MELT); }
double cxSc_BOIL(void) { return (Sc_BOIL); }
double cxSc_Cp(void) { return (Sc_Cp); }
double cxSc_En(void) { return (Sc_En); }
double cxTITANIUM_Z(void) { return (TITANIUM_Z); }
double cxTITANIUM(void) { return (TITANIUM); }
double cxTi_Z(void) { return (Ti_Z); }
double cxTi_WEIGHT(void) { return (Ti_WEIGHT); }
double cxTi_MASS(void) { return (Ti_MASS); }
double cxTiMASS(void) { return (TiMASS); }
double cxTi_DENSITY(void) { return (Ti_DENSITY); }
double cxTi_MELT(void) { return (Ti_MELT); }
double cxTi_BOIL(void) { return (Ti_BOIL); }
double cxTi_Cp(void) { return (Ti_Cp); }
double cxTi_En(void) { return (Ti_En); }
double cxVANADIUM_Z(void) { return (VANADIUM_Z); }
double cxVANADIUM(void) { return (VANADIUM); }
double cxV_Z(void) { return (V_Z); }
double cxV_WEIGHT(void) { return (V_WEIGHT); }
double cxV_MASS(void) { return (V_MASS); }
double cxVMASS(void) { return (VMASS); }
double cxV_DENSITY(void) { return (V_DENSITY); }
double cxV_MELT(void) { return (V_MELT); }
double cxV_BOIL(void) { return (V_BOIL); }
double cxV_Cp(void) { return (V_Cp); }
double cxV_En(void) { return (V_En); }
double cxCHROMIUM_Z(void) { return (CHROMIUM_Z); }
double cxCHROMIUM(void) { return (CHROMIUM); }
double cxCr_Z(void) { return (Cr_Z); }
double cxCr_WEIGHT(void) { return (Cr_WEIGHT); }
double cxCr_MASS(void) { return (Cr_MASS); }
double cxCrMASS(void) { return (CrMASS); }
double cxCr_DENSITY(void) { return (Cr_DENSITY); }
double cxCr_MELT(void) { return (Cr_MELT); }
double cxCr_BOIL(void) { return (Cr_BOIL); }
double cxCr_Cp(void) { return (Cr_Cp); }
double cxCr_En(void) { return (Cr_En); }
double cxMANGANESE_Z(void) { return (MANGANESE_Z); }
double cxMANGANESE(void) { return (MANGANESE); }
double cxMn_Z(void) { return (Mn_Z); }
double cxMn_WEIGHT(void) { return (Mn_WEIGHT); }
double cxMn_MASS(void) { return (Mn_MASS); }
double cxMnMASS(void) { return (MnMASS); }
double cxMn_DENSITY(void) { return (Mn_DENSITY); }
double cxMn_MELT(void) { return (Mn_MELT); }
double cxMn_BOIL(void) { return (Mn_BOIL); }
double cxMn_Cp(void) { return (Mn_Cp); }
double cxMn_En(void) { return (Mn_En); }
double cxIRON_Z(void) { return (IRON_Z); }
double cxIRON(void) { return (IRON); }
double cxFe_Z(void) { return (Fe_Z); }
double cxFe_WEIGHT(void) { return (Fe_WEIGHT); }
double cxFe_MASS(void) { return (Fe_MASS); }
double cxFeMASS(void) { return (FeMASS); }
double cxFe_DENSITY(void) { return (Fe_DENSITY); }
double cxFe_MELT(void) { return (Fe_MELT); }
double cxFe_BOIL(void) { return (Fe_BOIL); }
double cxFe_Cp(void) { return (Fe_Cp); }
double cxFe_En(void) { return (Fe_En); }
double cxCOBALT_Z(void) { return (COBALT_Z); }
double cxCOBALT(void) { return (COBALT); }
double cxCo_Z(void) { return (Co_Z); }
double cxCo_WEIGHT(void) { return (Co_WEIGHT); }
double cxCo_MASS(void) { return (Co_MASS); }
double cxCoMASS(void) { return (CoMASS); }
double cxCo_DENSITY(void) { return (Co_DENSITY); }
double cxCo_MELT(void) { return (Co_MELT); }
double cxCo_BOIL(void) { return (Co_BOIL); }
double cxCo_Cp(void) { return (Co_Cp); }
double cxCo_En(void) { return (Co_En); }
double cxNICKEL_Z(void) { return (NICKEL_Z); }
double cxNICKEL(void) { return (NICKEL); }
double cxNi_Z(void) { return (Ni_Z); }
double cxNi_WEIGHT(void) { return (Ni_WEIGHT); }
double cxNi_MASS(void) { return (Ni_MASS); }
double cxNiMASS(void) { return (NiMASS); }
double cxNi_DENSITY(void) { return (Ni_DENSITY); }
double cxNi_MELT(void) { return (Ni_MELT); }
double cxNi_BOIL(void) { return (Ni_BOIL); }
double cxNi_Cp(void) { return (Ni_Cp); }
double cxNi_En(void) { return (Ni_En); }
double cxCOPPER_Z(void) { return (COPPER_Z); }
double cxCOPPER(void) { return (COPPER); }
double cxCu_Z(void) { return (Cu_Z); }
double cxCu_WEIGHT(void) { return (Cu_WEIGHT); }
double cxCu_MASS(void) { return (Cu_MASS); }
double cxCuMASS(void) { return (CuMASS); }
double cxCu_DENSITY(void) { return (Cu_DENSITY); }
double cxCu_MELT(void) { return (Cu_MELT); }
double cxCu_BOIL(void) { return (Cu_BOIL); }
double cxCu_Cp(void) { return (Cu_Cp); }
double cxCu_En(void) { return (Cu_En); }
double cxZINC_Z(void) { return (ZINC_Z); }
double cxZINC(void) { return (ZINC); }
double cxZn_Z(void) { return (Zn_Z); }
double cxZn_WEIGHT(void) { return (Zn_WEIGHT); }
double cxZn_MASS(void) { return (Zn_MASS); }
double cxZnMASS(void) { return (ZnMASS); }
double cxZn_DENSITY(void) { return (Zn_DENSITY); }
double cxZn_MELT(void) { return (Zn_MELT); }
double cxZn_BOIL(void) { return (Zn_BOIL); }
double cxZn_Cp(void) { return (Zn_Cp); }
double cxZn_En(void) { return (Zn_En); }
double cxGALLIUM_Z(void) { return (GALLIUM_Z); }
double cxGALLIUM(void) { return (GALLIUM); }
double cxGa_Z(void) { return (Ga_Z); }
double cxGa_WEIGHT(void) { return (Ga_WEIGHT); }
double cxGa_MASS(void) { return (Ga_MASS); }
double cxGaMASS(void) { return (GaMASS); }
double cxGa_DENSITY(void) { return (Ga_DENSITY); }
double cxGa_MELT(void) { return (Ga_MELT); }
double cxGa_BOIL(void) { return (Ga_BOIL); }
double cxGa_Cp(void) { return (Ga_Cp); }
double cxGa_En(void) { return (Ga_En); }
double cxGERMANIUM_Z(void) { return (GERMANIUM_Z); }
double cxGERMANIUM(void) { return (GERMANIUM); }
double cxGe_Z(void) { return (Ge_Z); }
double cxGe_WEIGHT(void) { return (Ge_WEIGHT); }
double cxGe_MASS(void) { return (Ge_MASS); }
double cxGeMASS(void) { return (GeMASS); }
double cxGe_DENSITY(void) { return (Ge_DENSITY); }
double cxGe_MELT(void) { return (Ge_MELT); }
double cxGe_BOIL(void) { return (Ge_BOIL); }
double cxGe_Cp(void) { return (Ge_Cp); }
double cxGe_En(void) { return (Ge_En); }
double cxARSENIC_Z(void) { return (ARSENIC_Z); }
double cxARSENIC(void) { return (ARSENIC); }
double cxAs_Z(void) { return (As_Z); }
double cxAs_WEIGHT(void) { return (As_WEIGHT); }
double cxAs_MASS(void) { return (As_MASS); }
double cxAsMASS(void) { return (AsMASS); }
double cxAs_DENSITY(void) { return (As_DENSITY); }
double cxAs_MELT(void) { return (As_MELT); }
double cxAs_BOIL(void) { return (As_BOIL); }
double cxAs_Cp(void) { return (As_Cp); }
double cxAs_En(void) { return (As_En); }
double cxSELENIUM_Z(void) { return (SELENIUM_Z); }
double cxSELENIUM(void) { return (SELENIUM); }
double cxSe_Z(void) { return (Se_Z); }
double cxSe_WEIGHT(void) { return (Se_WEIGHT); }
double cxSe_MASS(void) { return (Se_MASS); }
double cxSeMASS(void) { return (SeMASS); }
double cxSe_DENSITY(void) { return (Se_DENSITY); }
double cxSe_MELT(void) { return (Se_MELT); }
double cxSe_BOIL(void) { return (Se_BOIL); }
double cxSe_Cp(void) { return (Se_Cp); }
double cxSe_En(void) { return (Se_En); }
double cxBROMINE_Z(void) { return (BROMINE_Z); }
double cxBROMINE(void) { return (BROMINE); }
double cxBr_Z(void) { return (Br_Z); }
double cxBr_WEIGHT(void) { return (Br_WEIGHT); }
double cxBr_MASS(void) { return (Br_MASS); }
double cxBrMASS(void) { return (BrMASS); }
double cxBr_DENSITY(void) { return (Br_DENSITY); }
double cxBr_MELT(void) { return (Br_MELT); }
double cxBr_BOIL(void) { return (Br_BOIL); }
double cxBr_Cp(void) { return (Br_Cp); }
double cxBr_En(void) { return (Br_En); }
double cxKRYPTON_Z(void) { return (KRYPTON_Z); }
double cxKRYPTON(void) { return (KRYPTON); }
double cxKr_Z(void) { return (Kr_Z); }
double cxKr_WEIGHT(void) { return (Kr_WEIGHT); }
double cxKr_MASS(void) { return (Kr_MASS); }
double cxKrMASS(void) { return (KrMASS); }
double cxKr_DENSITY(void) { return (Kr_DENSITY); }
double cxKr_MELT(void) { return (Kr_MELT); }
double cxKr_BOIL(void) { return (Kr_BOIL); }
double cxKr_Cp(void) { return (Kr_Cp); }
double cxKr_En(void) { return (Kr_En); }
double cxRUBIDIUM_Z(void) { return (RUBIDIUM_Z); }
double cxRUBIDIUM(void) { return (RUBIDIUM); }
double cxRb_Z(void) { return (Rb_Z); }
double cxRb_WEIGHT(void) { return (Rb_WEIGHT); }
double cxRb_MASS(void) { return (Rb_MASS); }
double cxRbMASS(void) { return (RbMASS); }
double cxRb_DENSITY(void) { return (Rb_DENSITY); }
double cxRb_MELT(void) { return (Rb_MELT); }
double cxRb_BOIL(void) { return (Rb_BOIL); }
double cxRb_Cp(void) { return (Rb_Cp); }
double cxRb_En(void) { return (Rb_En); }
double cxSTRONTIUM_Z(void) { return (STRONTIUM_Z); }
double cxSTRONTIUM(void) { return (STRONTIUM); }
double cxSr_Z(void) { return (Sr_Z); }
double cxSr_WEIGHT(void) { return (Sr_WEIGHT); }
double cxSr_MASS(void) { return (Sr_MASS); }
double cxSrMASS(void) { return (SrMASS); }
double cxSr_DENSITY(void) { return (Sr_DENSITY); }
double cxSr_MELT(void) { return (Sr_MELT); }
double cxSr_BOIL(void) { return (Sr_BOIL); }
double cxSr_Cp(void) { return (Sr_Cp); }
double cxSr_En(void) { return (Sr_En); }
double cxYTTRIUM_Z(void) { return (YTTRIUM_Z); }
double cxYTTRIUM(void) { return (YTTRIUM); }
double cxY_Z(void) { return (Y_Z); }
double cxY_WEIGHT(void) { return (Y_WEIGHT); }
double cxY_MASS(void) { return (Y_MASS); }
double cxYMASS(void) { return (YMASS); }
double cxY_DENSITY(void) { return (Y_DENSITY); }
double cxY_MELT(void) { return (Y_MELT); }
double cxY_BOIL(void) { return (Y_BOIL); }
double cxY_Cp(void) { return (Y_Cp); }
double cxY_En(void) { return (Y_En); }
double cxZIRCONIUM_Z(void) { return (ZIRCONIUM_Z); }
double cxZIRCONIUM(void) { return (ZIRCONIUM); }
double cxZr_Z(void) { return (Zr_Z); }
double cxZr_WEIGHT(void) { return (Zr_WEIGHT); }
double cxZr_MASS(void) { return (Zr_MASS); }
double cxZrMASS(void) { return (ZrMASS); }
double cxZr_DENSITY(void) { return (Zr_DENSITY); }
double cxZr_MELT(void) { return (Zr_MELT); }
double cxZr_BOIL(void) { return (Zr_BOIL); }
double cxZr_Cp(void) { return (Zr_Cp); }
double cxZr_En(void) { return (Zr_En); }
double cxNIOBIUM_Z(void) { return (NIOBIUM_Z); }
double cxNIOBIUM(void) { return (NIOBIUM); }
double cxNb_Z(void) { return (Nb_Z); }
double cxNb_WEIGHT(void) { return (Nb_WEIGHT); }
double cxNb_MASS(void) { return (Nb_MASS); }
double cxNbMASS(void) { return (NbMASS); }
double cxNb_DENSITY(void) { return (Nb_DENSITY); }
double cxNb_MELT(void) { return (Nb_MELT); }
double cxNb_BOIL(void) { return (Nb_BOIL); }
double cxNb_Cp(void) { return (Nb_Cp); }
double cxNb_En(void) { return (Nb_En); }
double cxMOLYBDENUM_Z(void) { return (MOLYBDENUM_Z); }
double cxMOLYBDENUM(void) { return (MOLYBDENUM); }
double cxMo_Z(void) { return (Mo_Z); }
double cxMo_WEIGHT(void) { return (Mo_WEIGHT); }
double cxMo_MASS(void) { return (Mo_MASS); }
double cxMoMASS(void) { return (MoMASS); }
double cxMo_DENSITY(void) { return (Mo_DENSITY); }
double cxMo_MELT(void) { return (Mo_MELT); }
double cxMo_BOIL(void) { return (Mo_BOIL); }
double cxMo_Cp(void) { return (Mo_Cp); }
double cxMo_En(void) { return (Mo_En); }
double cxTECHNETIUM_Z(void) { return (TECHNETIUM_Z); }
double cxTECHNETIUM(void) { return (TECHNETIUM); }
double cxTc_Z(void) { return (Tc_Z); }
double cxTc_WEIGHT(void) { return (Tc_WEIGHT); }
double cxTc_MASS(void) { return (Tc_MASS); }
double cxTcMASS(void) { return (TcMASS); }
double cxTc_DENSITY(void) { return (Tc_DENSITY); }
double cxTc_MELT(void) { return (Tc_MELT); }
double cxTc_BOIL(void) { return (Tc_BOIL); }
double cxTc_Cp(void) { return (Tc_Cp); }
double cxTc_En(void) { return (Tc_En); }
double cxRUTHENIUM_Z(void) { return (RUTHENIUM_Z); }
double cxRUTHENIUM(void) { return (RUTHENIUM); }
double cxRu_Z(void) { return (Ru_Z); }
double cxRu_WEIGHT(void) { return (Ru_WEIGHT); }
double cxRu_MASS(void) { return (Ru_MASS); }
double cxRuMASS(void) { return (RuMASS); }
double cxRu_DENSITY(void) { return (Ru_DENSITY); }
double cxRu_MELT(void) { return (Ru_MELT); }
double cxRu_BOIL(void) { return (Ru_BOIL); }
double cxRu_Cp(void) { return (Ru_Cp); }
double cxRu_En(void) { return (Ru_En); }
double cxRHODIUM_Z(void) { return (RHODIUM_Z); }
double cxRHODIUM(void) { return (RHODIUM); }
double cxRh_Z(void) { return (Rh_Z); }
double cxRh_WEIGHT(void) { return (Rh_WEIGHT); }
double cxRh_MASS(void) { return (Rh_MASS); }
double cxRhMASS(void) { return (RhMASS); }
double cxRh_DENSITY(void) { return (Rh_DENSITY); }
double cxRh_MELT(void) { return (Rh_MELT); }
double cxRh_BOIL(void) { return (Rh_BOIL); }
double cxRh_Cp(void) { return (Rh_Cp); }
double cxRh_En(void) { return (Rh_En); }
double cxPALLADIUM_Z(void) { return (PALLADIUM_Z); }
double cxPALLADIUM(void) { return (PALLADIUM); }
double cxPd_Z(void) { return (Pd_Z); }
double cxPd_WEIGHT(void) { return (Pd_WEIGHT); }
double cxPd_MASS(void) { return (Pd_MASS); }
double cxPdMASS(void) { return (PdMASS); }
double cxPd_DENSITY(void) { return (Pd_DENSITY); }
double cxPd_MELT(void) { return (Pd_MELT); }
double cxPd_BOIL(void) { return (Pd_BOIL); }
double cxPd_Cp(void) { return (Pd_Cp); }
double cxPd_En(void) { return (Pd_En); }
double cxSILVER_Z(void) { return (SILVER_Z); }
double cxSILVER(void) { return (SILVER); }
double cxAg_Z(void) { return (Ag_Z); }
double cxAg_WEIGHT(void) { return (Ag_WEIGHT); }
double cxAg_MASS(void) { return (Ag_MASS); }
double cxAgMASS(void) { return (AgMASS); }
double cxAg_DENSITY(void) { return (Ag_DENSITY); }
double cxAg_MELT(void) { return (Ag_MELT); }
double cxAg_BOIL(void) { return (Ag_BOIL); }
double cxAg_Cp(void) { return (Ag_Cp); }
double cxAg_En(void) { return (Ag_En); }
double cxCADMIUM_Z(void) { return (CADMIUM_Z); }
double cxCADMIUM(void) { return (CADMIUM); }
double cxCd_Z(void) { return (Cd_Z); }
double cxCd_WEIGHT(void) { return (Cd_WEIGHT); }
double cxCd_MASS(void) { return (Cd_MASS); }
double cxCdMASS(void) { return (CdMASS); }
double cxCd_DENSITY(void) { return (Cd_DENSITY); }
double cxCd_MELT(void) { return (Cd_MELT); }
double cxCd_BOIL(void) { return (Cd_BOIL); }
double cxCd_Cp(void) { return (Cd_Cp); }
double cxCd_En(void) { return (Cd_En); }
double cxINDIUM_Z(void) { return (INDIUM_Z); }
double cxINDIUM(void) { return (INDIUM); }
double cxIn_Z(void) { return (In_Z); }
double cxIn_WEIGHT(void) { return (In_WEIGHT); }
double cxIn_MASS(void) { return (In_MASS); }
double cxInMASS(void) { return (InMASS); }
double cxIn_DENSITY(void) { return (In_DENSITY); }
double cxIn_MELT(void) { return (In_MELT); }
double cxIn_BOIL(void) { return (In_BOIL); }
double cxIn_Cp(void) { return (In_Cp); }
double cxIn_En(void) { return (In_En); }
double cxTIN_Z(void) { return (TIN_Z); }
double cxTIN(void) { return (TIN); }
double cxSn_Z(void) { return (Sn_Z); }
double cxSn_WEIGHT(void) { return (Sn_WEIGHT); }
double cxSn_MASS(void) { return (Sn_MASS); }
double cxSnMASS(void) { return (SnMASS); }
double cxSn_DENSITY(void) { return (Sn_DENSITY); }
double cxSn_MELT(void) { return (Sn_MELT); }
double cxSn_BOIL(void) { return (Sn_BOIL); }
double cxSn_Cp(void) { return (Sn_Cp); }
double cxSn_En(void) { return (Sn_En); }
double cxANTIMONY_Z(void) { return (ANTIMONY_Z); }
double cxANTIMONY(void) { return (ANTIMONY); }
double cxSb_Z(void) { return (Sb_Z); }
double cxSb_WEIGHT(void) { return (Sb_WEIGHT); }
double cxSb_MASS(void) { return (Sb_MASS); }
double cxSbMASS(void) { return (SbMASS); }
double cxSb_DENSITY(void) { return (Sb_DENSITY); }
double cxSb_MELT(void) { return (Sb_MELT); }
double cxSb_BOIL(void) { return (Sb_BOIL); }
double cxSb_Cp(void) { return (Sb_Cp); }
double cxSb_En(void) { return (Sb_En); }
double cxTELLURIUM_Z(void) { return (TELLURIUM_Z); }
double cxTELLURIUM(void) { return (TELLURIUM); }
double cxTe_Z(void) { return (Te_Z); }
double cxTe_WEIGHT(void) { return (Te_WEIGHT); }
double cxTe_MASS(void) { return (Te_MASS); }
double cxTeMASS(void) { return (TeMASS); }
double cxTe_DENSITY(void) { return (Te_DENSITY); }
double cxTe_MELT(void) { return (Te_MELT); }
double cxTe_BOIL(void) { return (Te_BOIL); }
double cxTe_Cp(void) { return (Te_Cp); }
double cxTe_En(void) { return (Te_En); }
double cxIODINE_Z(void) { return (IODINE_Z); }
double cxIODINE(void) { return (IODINE); }
double cxI_Z(void) { return (I_Z); }
double cxI_WEIGHT(void) { return (I_WEIGHT); }
double cxI_MASS(void) { return (I_MASS); }
double cxIMASS(void) { return (IMASS); }
double cxI_DENSITY(void) { return (I_DENSITY); }
double cxI_MELT(void) { return (I_MELT); }
double cxI_BOIL(void) { return (I_BOIL); }
double cxI_Cp(void) { return (I_Cp); }
double cxI_En(void) { return (I_En); }
double cxXENON_Z(void) { return (XENON_Z); }
double cxXENON(void) { return (XENON); }
double cxXe_Z(void) { return (Xe_Z); }
double cxXe_WEIGHT(void) { return (Xe_WEIGHT); }
double cxXe_MASS(void) { return (Xe_MASS); }
double cxXeMASS(void) { return (XeMASS); }
double cxXe_DENSITY(void) { return (Xe_DENSITY); }
double cxXe_MELT(void) { return (Xe_MELT); }
double cxXe_BOIL(void) { return (Xe_BOIL); }
double cxXe_Cp(void) { return (Xe_Cp); }
double cxXe_En(void) { return (Xe_En); }
double cxCAESIUM_Z(void) { return (CAESIUM_Z); }
double cxCAESIUM(void) { return (CAESIUM); }
double cxCs_Z(void) { return (Cs_Z); }
double cxCs_WEIGHT(void) { return (Cs_WEIGHT); }
double cxCs_MASS(void) { return (Cs_MASS); }
double cxCsMASS(void) { return (CsMASS); }
double cxCs_DENSITY(void) { return (Cs_DENSITY); }
double cxCs_MELT(void) { return (Cs_MELT); }
double cxCs_BOIL(void) { return (Cs_BOIL); }
double cxCs_Cp(void) { return (Cs_Cp); }
double cxCs_En(void) { return (Cs_En); }
double cxBARIUM_Z(void) { return (BARIUM_Z); }
double cxBARIUM(void) { return (BARIUM); }
double cxBa_Z(void) { return (Ba_Z); }
double cxBa_WEIGHT(void) { return (Ba_WEIGHT); }
double cxBa_MASS(void) { return (Ba_MASS); }
double cxBaMASS(void) { return (BaMASS); }
double cxBa_DENSITY(void) { return (Ba_DENSITY); }
double cxBa_MELT(void) { return (Ba_MELT); }
double cxBa_BOIL(void) { return (Ba_BOIL); }
double cxBa_Cp(void) { return (Ba_Cp); }
double cxBa_En(void) { return (Ba_En); }
double cxLANTHANUM_Z(void) { return (LANTHANUM_Z); }
double cxLANTHANUM(void) { return (LANTHANUM); }
double cxLa_Z(void) { return (La_Z); }
double cxLa_WEIGHT(void) { return (La_WEIGHT); }
double cxLa_MASS(void) { return (La_MASS); }
double cxLaMASS(void) { return (LaMASS); }
double cxLa_DENSITY(void) { return (La_DENSITY); }
double cxLa_MELT(void) { return (La_MELT); }
double cxLa_BOIL(void) { return (La_BOIL); }
double cxLa_Cp(void) { return (La_Cp); }
double cxLa_En(void) { return (La_En); }
double cxCERIUM_Z(void) { return (CERIUM_Z); }
double cxCERIUM(void) { return (CERIUM); }
double cxCe_Z(void) { return (Ce_Z); }
double cxCe_WEIGHT(void) { return (Ce_WEIGHT); }
double cxCe_MASS(void) { return (Ce_MASS); }
double cxCeMASS(void) { return (CeMASS); }
double cxCe_DENSITY(void) { return (Ce_DENSITY); }
double cxCe_MELT(void) { return (Ce_MELT); }
double cxCe_BOIL(void) { return (Ce_BOIL); }
double cxCe_Cp(void) { return (Ce_Cp); }
double cxCe_En(void) { return (Ce_En); }
double cxPRASEODYMIUM_Z(void) { return (PRASEODYMIUM_Z); }
double cxPRASEODYMIUM(void) { return (PRASEODYMIUM); }
double cxPr_Z(void) { return (Pr_Z); }
double cxPr_WEIGHT(void) { return (Pr_WEIGHT); }
double cxPr_MASS(void) { return (Pr_MASS); }
double cxPrMASS(void) { return (PrMASS); }
double cxPr_DENSITY(void) { return (Pr_DENSITY); }
double cxPr_MELT(void) { return (Pr_MELT); }
double cxPr_BOIL(void) { return (Pr_BOIL); }
double cxPr_Cp(void) { return (Pr_Cp); }
double cxPr_En(void) { return (Pr_En); }
double cxNEODYMIUM_Z(void) { return (NEODYMIUM_Z); }
double cxNEODYMIUM(void) { return (NEODYMIUM); }
double cxNd_Z(void) { return (Nd_Z); }
double cxNd_WEIGHT(void) { return (Nd_WEIGHT); }
double cxNd_MASS(void) { return (Nd_MASS); }
double cxNdMASS(void) { return (NdMASS); }
double cxNd_DENSITY(void) { return (Nd_DENSITY); }
double cxNd_MELT(void) { return (Nd_MELT); }
double cxNd_BOIL(void) { return (Nd_BOIL); }
double cxNd_Cp(void) { return (Nd_Cp); }
double cxNd_En(void) { return (Nd_En); }
double cxPROMETHIUM_Z(void) { return (PROMETHIUM_Z); }
double cxPROMETHIUM(void) { return (PROMETHIUM); }
double cxPm_Z(void) { return (Pm_Z); }
double cxPm_WEIGHT(void) { return (Pm_WEIGHT); }
double cxPm_MASS(void) { return (Pm_MASS); }
double cxPmMASS(void) { return (PmMASS); }
double cxPm_DENSITY(void) { return (Pm_DENSITY); }
double cxPm_MELT(void) { return (Pm_MELT); }
double cxPm_BOIL(void) { return (Pm_BOIL); }
double cxPm_Cp(void) { return (Pm_Cp); }
double cxPm_En(void) { return (Pm_En); }
double cxSAMARIUM_Z(void) { return (SAMARIUM_Z); }
double cxSAMARIUM(void) { return (SAMARIUM); }
double cxSm_Z(void) { return (Sm_Z); }
double cxSm_WEIGHT(void) { return (Sm_WEIGHT); }
double cxSm_MASS(void) { return (Sm_MASS); }
double cxSmMASS(void) { return (SmMASS); }
double cxSm_DENSITY(void) { return (Sm_DENSITY); }
double cxSm_MELT(void) { return (Sm_MELT); }
double cxSm_BOIL(void) { return (Sm_BOIL); }
double cxSm_Cp(void) { return (Sm_Cp); }
double cxSm_En(void) { return (Sm_En); }
double cxEUROPIUM_Z(void) { return (EUROPIUM_Z); }
double cxEUROPIUM(void) { return (EUROPIUM); }
double cxEu_Z(void) { return (Eu_Z); }
double cxEu_WEIGHT(void) { return (Eu_WEIGHT); }
double cxEu_MASS(void) { return (Eu_MASS); }
double cxEuMASS(void) { return (EuMASS); }
double cxEu_DENSITY(void) { return (Eu_DENSITY); }
double cxEu_MELT(void) { return (Eu_MELT); }
double cxEu_BOIL(void) { return (Eu_BOIL); }
double cxEu_Cp(void) { return (Eu_Cp); }
double cxEu_En(void) { return (Eu_En); }
double cxGADOLINIUM_Z(void) { return (GADOLINIUM_Z); }
double cxGADOLINIUM(void) { return (GADOLINIUM); }
double cxGd_Z(void) { return (Gd_Z); }
double cxGd_WEIGHT(void) { return (Gd_WEIGHT); }
double cxGd_MASS(void) { return (Gd_MASS); }
double cxGdMASS(void) { return (GdMASS); }
double cxGd_DENSITY(void) { return (Gd_DENSITY); }
double cxGd_MELT(void) { return (Gd_MELT); }
double cxGd_BOIL(void) { return (Gd_BOIL); }
double cxGd_Cp(void) { return (Gd_Cp); }
double cxGd_En(void) { return (Gd_En); }
double cxTERBIUM_Z(void) { return (TERBIUM_Z); }
double cxTERBIUM(void) { return (TERBIUM); }
double cxTb_Z(void) { return (Tb_Z); }
double cxTb_WEIGHT(void) { return (Tb_WEIGHT); }
double cxTb_MASS(void) { return (Tb_MASS); }
double cxTbMASS(void) { return (TbMASS); }
double cxTb_DENSITY(void) { return (Tb_DENSITY); }
double cxTb_MELT(void) { return (Tb_MELT); }
double cxTb_BOIL(void) { return (Tb_BOIL); }
double cxTb_Cp(void) { return (Tb_Cp); }
double cxTb_En(void) { return (Tb_En); }
double cxDYSPROSIUM_Z(void) { return (DYSPROSIUM_Z); }
double cxDYSPROSIUM(void) { return (DYSPROSIUM); }
double cxDy_Z(void) { return (Dy_Z); }
double cxDy_WEIGHT(void) { return (Dy_WEIGHT); }
double cxDy_MASS(void) { return (Dy_MASS); }
double cxDyMASS(void) { return (DyMASS); }
double cxDy_DENSITY(void) { return (Dy_DENSITY); }
double cxDy_MELT(void) { return (Dy_MELT); }
double cxDy_BOIL(void) { return (Dy_BOIL); }
double cxDy_Cp(void) { return (Dy_Cp); }
double cxDy_En(void) { return (Dy_En); }
double cxHOLMIUM_Z(void) { return (HOLMIUM_Z); }
double cxHOLMIUM(void) { return (HOLMIUM); }
double cxHo_Z(void) { return (Ho_Z); }
double cxHo_WEIGHT(void) { return (Ho_WEIGHT); }
double cxHo_MASS(void) { return (Ho_MASS); }
double cxHoMASS(void) { return (HoMASS); }
double cxHo_DENSITY(void) { return (Ho_DENSITY); }
double cxHo_MELT(void) { return (Ho_MELT); }
double cxHo_BOIL(void) { return (Ho_BOIL); }
double cxHo_Cp(void) { return (Ho_Cp); }
double cxHo_En(void) { return (Ho_En); }
double cxERBIUM_Z(void) { return (ERBIUM_Z); }
double cxERBIUM(void) { return (ERBIUM); }
double cxEr_Z(void) { return (Er_Z); }
double cxEr_WEIGHT(void) { return (Er_WEIGHT); }
double cxEr_MASS(void) { return (Er_MASS); }
double cxErMASS(void) { return (ErMASS); }
double cxEr_DENSITY(void) { return (Er_DENSITY); }
double cxEr_MELT(void) { return (Er_MELT); }
double cxEr_BOIL(void) { return (Er_BOIL); }
double cxEr_Cp(void) { return (Er_Cp); }
double cxEr_En(void) { return (Er_En); }
double cxTHULIUM_Z(void) { return (THULIUM_Z); }
double cxTHULIUM(void) { return (THULIUM); }
double cxTm_Z(void) { return (Tm_Z); }
double cxTm_WEIGHT(void) { return (Tm_WEIGHT); }
double cxTm_MASS(void) { return (Tm_MASS); }
double cxTmMASS(void) { return (TmMASS); }
double cxTm_DENSITY(void) { return (Tm_DENSITY); }
double cxTm_MELT(void) { return (Tm_MELT); }
double cxTm_BOIL(void) { return (Tm_BOIL); }
double cxTm_Cp(void) { return (Tm_Cp); }
double cxTm_En(void) { return (Tm_En); }
double cxYTTERBIUM_Z(void) { return (YTTERBIUM_Z); }
double cxYTTERBIUM(void) { return (YTTERBIUM); }
double cxYb_Z(void) { return (Yb_Z); }
double cxYb_WEIGHT(void) { return (Yb_WEIGHT); }
double cxYb_MASS(void) { return (Yb_MASS); }
double cxYbMASS(void) { return (YbMASS); }
double cxYb_DENSITY(void) { return (Yb_DENSITY); }
double cxYb_MELT(void) { return (Yb_MELT); }
double cxYb_BOIL(void) { return (Yb_BOIL); }
double cxYb_Cp(void) { return (Yb_Cp); }
double cxYb_En(void) { return (Yb_En); }
double cxLUTETIUM_Z(void) { return (LUTETIUM_Z); }
double cxLUTETIUM(void) { return (LUTETIUM); }
double cxLu_Z(void) { return (Lu_Z); }
double cxLu_WEIGHT(void) { return (Lu_WEIGHT); }
double cxLu_MASS(void) { return (Lu_MASS); }
double cxLuMASS(void) { return (LuMASS); }
double cxLu_DENSITY(void) { return (Lu_DENSITY); }
double cxLu_MELT(void) { return (Lu_MELT); }
double cxLu_BOIL(void) { return (Lu_BOIL); }
double cxLu_Cp(void) { return (Lu_Cp); }
double cxLu_En(void) { return (Lu_En); }
double cxHAFNIUM_Z(void) { return (HAFNIUM_Z); }
double cxHAFNIUM(void) { return (HAFNIUM); }
double cxHf_Z(void) { return (Hf_Z); }
double cxHf_WEIGHT(void) { return (Hf_WEIGHT); }
double cxHf_MASS(void) { return (Hf_MASS); }
double cxHfMASS(void) { return (HfMASS); }
double cxHf_DENSITY(void) { return (Hf_DENSITY); }
double cxHf_MELT(void) { return (Hf_MELT); }
double cxHf_BOIL(void) { return (Hf_BOIL); }
double cxHf_Cp(void) { return (Hf_Cp); }
double cxHf_En(void) { return (Hf_En); }
double cxTANTALUM_Z(void) { return (TANTALUM_Z); }
double cxTANTALUM(void) { return (TANTALUM); }
double cxTa_Z(void) { return (Ta_Z); }
double cxTa_WEIGHT(void) { return (Ta_WEIGHT); }
double cxTa_MASS(void) { return (Ta_MASS); }
double cxTaMASS(void) { return (TaMASS); }
double cxTa_DENSITY(void) { return (Ta_DENSITY); }
double cxTa_MELT(void) { return (Ta_MELT); }
double cxTa_BOIL(void) { return (Ta_BOIL); }
double cxTa_Cp(void) { return (Ta_Cp); }
double cxTa_En(void) { return (Ta_En); }
double cxTUNGSTEN_Z(void) { return (TUNGSTEN_Z); }
double cxTUNGSTEN(void) { return (TUNGSTEN); }
double cxW_Z(void) { return (W_Z); }
double cxW_WEIGHT(void) { return (W_WEIGHT); }
double cxW_MASS(void) { return (W_MASS); }
double cxWMASS(void) { return (WMASS); }
double cxW_DENSITY(void) { return (W_DENSITY); }
double cxW_MELT(void) { return (W_MELT); }
double cxW_BOIL(void) { return (W_BOIL); }
double cxW_Cp(void) { return (W_Cp); }
double cxW_En(void) { return (W_En); }
double cxRHENIUM_Z(void) { return (RHENIUM_Z); }
double cxRHENIUM(void) { return (RHENIUM); }
double cxRe_Z(void) { return (Re_Z); }
double cxRe_WEIGHT(void) { return (Re_WEIGHT); }
double cxRe_MASS(void) { return (Re_MASS); }
double cxReMASS(void) { return (ReMASS); }
double cxRe_DENSITY(void) { return (Re_DENSITY); }
double cxRe_MELT(void) { return (Re_MELT); }
double cxRe_BOIL(void) { return (Re_BOIL); }
double cxRe_Cp(void) { return (Re_Cp); }
double cxRe_En(void) { return (Re_En); }
double cxOSMIUM_Z(void) { return (OSMIUM_Z); }
double cxOSMIUM(void) { return (OSMIUM); }
double cxOs_Z(void) { return (Os_Z); }
double cxOs_WEIGHT(void) { return (Os_WEIGHT); }
double cxOs_MASS(void) { return (Os_MASS); }
double cxOsMASS(void) { return (OsMASS); }
double cxOs_DENSITY(void) { return (Os_DENSITY); }
double cxOs_MELT(void) { return (Os_MELT); }
double cxOs_BOIL(void) { return (Os_BOIL); }
double cxOs_Cp(void) { return (Os_Cp); }
double cxOs_En(void) { return (Os_En); }
double cxIRIDIUM_Z(void) { return (IRIDIUM_Z); }
double cxIRIDIUM(void) { return (IRIDIUM); }
double cxIr_Z(void) { return (Ir_Z); }
double cxIr_WEIGHT(void) { return (Ir_WEIGHT); }
double cxIr_MASS(void) { return (Ir_MASS); }
double cxIrMASS(void) { return (IrMASS); }
double cxIr_DENSITY(void) { return (Ir_DENSITY); }
double cxIr_MELT(void) { return (Ir_MELT); }
double cxIr_BOIL(void) { return (Ir_BOIL); }
double cxIr_Cp(void) { return (Ir_Cp); }
double cxIr_En(void) { return (Ir_En); }
double cxPLATINUM_Z(void) { return (PLATINUM_Z); }
double cxPLATINUM(void) { return (PLATINUM); }
double cxPt_Z(void) { return (Pt_Z); }
double cxPt_WEIGHT(void) { return (Pt_WEIGHT); }
double cxPt_MASS(void) { return (Pt_MASS); }
double cxPtMASS(void) { return (PtMASS); }
double cxPt_DENSITY(void) { return (Pt_DENSITY); }
double cxPt_MELT(void) { return (Pt_MELT); }
double cxPt_BOIL(void) { return (Pt_BOIL); }
double cxPt_Cp(void) { return (Pt_Cp); }
double cxPt_En(void) { return (Pt_En); }
double cxGOLD_Z(void) { return (GOLD_Z); }
double cxGOLD(void) { return (GOLD); }
double cxAu_Z(void) { return (Au_Z); }
double cxAu_WEIGHT(void) { return (Au_WEIGHT); }
double cxAu_MASS(void) { return (Au_MASS); }
double cxAuMASS(void) { return (AuMASS); }
double cxAu_DENSITY(void) { return (Au_DENSITY); }
double cxAu_MELT(void) { return (Au_MELT); }
double cxAu_BOIL(void) { return (Au_BOIL); }
double cxAu_Cp(void) { return (Au_Cp); }
double cxAu_En(void) { return (Au_En); }
double cxMERCURY_Z(void) { return (MERCURY_Z); }
double cxMERCURY(void) { return (MERCURY); }
double cxHg_Z(void) { return (Hg_Z); }
double cxHg_WEIGHT(void) { return (Hg_WEIGHT); }
double cxHg_MASS(void) { return (Hg_MASS); }
double cxHgMASS(void) { return (HgMASS); }
double cxHg_DENSITY(void) { return (Hg_DENSITY); }
double cxHg_MELT(void) { return (Hg_MELT); }
double cxHg_BOIL(void) { return (Hg_BOIL); }
double cxHg_Cp(void) { return (Hg_Cp); }
double cxHg_En(void) { return (Hg_En); }
double cxTHALLIUM_Z(void) { return (THALLIUM_Z); }
double cxTHALLIUM(void) { return (THALLIUM); }
double cxTl_Z(void) { return (Tl_Z); }
double cxTl_WEIGHT(void) { return (Tl_WEIGHT); }
double cxTl_MASS(void) { return (Tl_MASS); }
double cxTlMASS(void) { return (TlMASS); }
double cxTl_DENSITY(void) { return (Tl_DENSITY); }
double cxTl_MELT(void) { return (Tl_MELT); }
double cxTl_BOIL(void) { return (Tl_BOIL); }
double cxTl_Cp(void) { return (Tl_Cp); }
double cxTl_En(void) { return (Tl_En); }
double cxLEAD_Z(void) { return (LEAD_Z); }
double cxLEAD(void) { return (LEAD); }
double cxPb_Z(void) { return (Pb_Z); }
double cxPb_WEIGHT(void) { return (Pb_WEIGHT); }
double cxPb_MASS(void) { return (Pb_MASS); }
double cxPbMASS(void) { return (PbMASS); }
double cxPb_DENSITY(void) { return (Pb_DENSITY); }
double cxPb_MELT(void) { return (Pb_MELT); }
double cxPb_BOIL(void) { return (Pb_BOIL); }
double cxPb_Cp(void) { return (Pb_Cp); }
double cxPb_En(void) { return (Pb_En); }
double cxBISMUTH_Z(void) { return (BISMUTH_Z); }
double cxBISMUTH(void) { return (BISMUTH); }
double cxBi_Z(void) { return (Bi_Z); }
double cxBi_WEIGHT(void) { return (Bi_WEIGHT); }
double cxBi_MASS(void) { return (Bi_MASS); }
double cxBiMASS(void) { return (BiMASS); }
double cxBi_DENSITY(void) { return (Bi_DENSITY); }
double cxBi_MELT(void) { return (Bi_MELT); }
double cxBi_BOIL(void) { return (Bi_BOIL); }
double cxBi_Cp(void) { return (Bi_Cp); }
double cxBi_En(void) { return (Bi_En); }
double cxPOLONIUM_Z(void) { return (POLONIUM_Z); }
double cxPOLONIUM(void) { return (POLONIUM); }
double cxPo_Z(void) { return (Po_Z); }
double cxPo_WEIGHT(void) { return (Po_WEIGHT); }
double cxPo_MASS(void) { return (Po_MASS); }
double cxPoMASS(void) { return (PoMASS); }
double cxPo_DENSITY(void) { return (Po_DENSITY); }
double cxPo_MELT(void) { return (Po_MELT); }
double cxPo_BOIL(void) { return (Po_BOIL); }
double cxPo_Cp(void) { return (Po_Cp); }
double cxPo_En(void) { return (Po_En); }
double cxASTATINE_Z(void) { return (ASTATINE_Z); }
double cxASTATINE(void) { return (ASTATINE); }
double cxAt_Z(void) { return (At_Z); }
double cxAt_WEIGHT(void) { return (At_WEIGHT); }
double cxAt_MASS(void) { return (At_MASS); }
double cxAtMASS(void) { return (AtMASS); }
double cxAt_DENSITY(void) { return (At_DENSITY); }
double cxAt_MELT(void) { return (At_MELT); }
double cxAt_BOIL(void) { return (At_BOIL); }
double cxAt_Cp(void) { return (At_Cp); }
double cxAt_En(void) { return (At_En); }
double cxRADON_Z(void) { return (RADON_Z); }
double cxRADON(void) { return (RADON); }
double cxRn_Z(void) { return (Rn_Z); }
double cxRn_WEIGHT(void) { return (Rn_WEIGHT); }
double cxRn_MASS(void) { return (Rn_MASS); }
double cxRnMASS(void) { return (RnMASS); }
double cxRn_DENSITY(void) { return (Rn_DENSITY); }
double cxRn_MELT(void) { return (Rn_MELT); }
double cxRn_BOIL(void) { return (Rn_BOIL); }
double cxRn_Cp(void) { return (Rn_Cp); }
double cxRn_En(void) { return (Rn_En); }
double cxFRANCIUM_Z(void) { return (FRANCIUM_Z); }
double cxFRANCIUM(void) { return (FRANCIUM); }
double cxFr_Z(void) { return (Fr_Z); }
double cxFr_WEIGHT(void) { return (Fr_WEIGHT); }
double cxFr_MASS(void) { return (Fr_MASS); }
double cxFrMASS(void) { return (FrMASS); }
double cxFr_DENSITY(void) { return (Fr_DENSITY); }
double cxFr_MELT(void) { return (Fr_MELT); }
double cxFr_BOIL(void) { return (Fr_BOIL); }
double cxFr_Cp(void) { return (Fr_Cp); }
double cxFr_En(void) { return (Fr_En); }
double cxRADIUM_Z(void) { return (RADIUM_Z); }
double cxRADIUM(void) { return (RADIUM); }
double cxRa_Z(void) { return (Ra_Z); }
double cxRa_WEIGHT(void) { return (Ra_WEIGHT); }
double cxRa_MASS(void) { return (Ra_MASS); }
double cxRaMASS(void) { return (RaMASS); }
double cxRa_DENSITY(void) { return (Ra_DENSITY); }
double cxRa_MELT(void) { return (Ra_MELT); }
double cxRa_BOIL(void) { return (Ra_BOIL); }
double cxRa_Cp(void) { return (Ra_Cp); }
double cxRa_En(void) { return (Ra_En); }
double cxACTINIUM_Z(void) { return (ACTINIUM_Z); }
double cxACTINIUM(void) { return (ACTINIUM); }
double cxAc_Z(void) { return (Ac_Z); }
double cxAc_WEIGHT(void) { return (Ac_WEIGHT); }
double cxAc_MASS(void) { return (Ac_MASS); }
double cxAcMASS(void) { return (AcMASS); }
double cxAc_DENSITY(void) { return (Ac_DENSITY); }
double cxAc_MELT(void) { return (Ac_MELT); }
double cxAc_BOIL(void) { return (Ac_BOIL); }
double cxAc_Cp(void) { return (Ac_Cp); }
double cxAc_En(void) { return (Ac_En); }
double cxTHORIUM_Z(void) { return (THORIUM_Z); }
double cxTHORIUM(void) { return (THORIUM); }
double cxTh_Z(void) { return (Th_Z); }
double cxTh_WEIGHT(void) { return (Th_WEIGHT); }
double cxTh_MASS(void) { return (Th_MASS); }
double cxThMASS(void) { return (ThMASS); }
double cxTh_DENSITY(void) { return (Th_DENSITY); }
double cxTh_MELT(void) { return (Th_MELT); }
double cxTh_BOIL(void) { return (Th_BOIL); }
double cxTh_Cp(void) { return (Th_Cp); }
double cxTh_En(void) { return (Th_En); }
double cxPROTACTINIUM_Z(void) { return (PROTACTINIUM_Z); }
double cxPROTACTINIUM(void) { return (PROTACTINIUM); }
double cxPa_Z(void) { return (Pa_Z); }
double cxPa_WEIGHT(void) { return (Pa_WEIGHT); }
double cxPa_MASS(void) { return (Pa_MASS); }
double cxPaMASS(void) { return (PaMASS); }
double cxPa_DENSITY(void) { return (Pa_DENSITY); }
double cxPa_MELT(void) { return (Pa_MELT); }
double cxPa_BOIL(void) { return (Pa_BOIL); }
double cxPa_Cp(void) { return (Pa_Cp); }
double cxPa_En(void) { return (Pa_En); }
double cxURANIUM_Z(void) { return (URANIUM_Z); }
double cxURANIUM(void) { return (URANIUM); }
double cxU_Z(void) { return (U_Z); }
double cxU_WEIGHT(void) { return (U_WEIGHT); }
double cxU_MASS(void) { return (U_MASS); }
double cxUMASS(void) { return (UMASS); }
double cxU_DENSITY(void) { return (U_DENSITY); }
double cxU_MELT(void) { return (U_MELT); }
double cxU_BOIL(void) { return (U_BOIL); }
double cxU_Cp(void) { return (U_Cp); }
double cxU_En(void) { return (U_En); }
double cxNEPTUNIUM_Z(void) { return (NEPTUNIUM_Z); }
double cxNEPTUNIUM(void) { return (NEPTUNIUM); }
double cxNp_Z(void) { return (Np_Z); }
double cxNp_WEIGHT(void) { return (Np_WEIGHT); }
double cxNp_MASS(void) { return (Np_MASS); }
double cxNpMASS(void) { return (NpMASS); }
double cxNp_DENSITY(void) { return (Np_DENSITY); }
double cxNp_MELT(void) { return (Np_MELT); }
double cxNp_BOIL(void) { return (Np_BOIL); }
double cxNp_Cp(void) { return (Np_Cp); }
double cxNp_En(void) { return (Np_En); }
double cxPLUTONIUM_Z(void) { return (PLUTONIUM_Z); }
double cxPLUTONIUM(void) { return (PLUTONIUM); }
double cxPu_Z(void) { return (Pu_Z); }
double cxPu_WEIGHT(void) { return (Pu_WEIGHT); }
double cxPu_MASS(void) { return (Pu_MASS); }
double cxPuMASS(void) { return (PuMASS); }
double cxPu_DENSITY(void) { return (Pu_DENSITY); }
double cxPu_MELT(void) { return (Pu_MELT); }
double cxPu_BOIL(void) { return (Pu_BOIL); }
double cxPu_Cp(void) { return (Pu_Cp); }
double cxPu_En(void) { return (Pu_En); }
double cxAMERICIUM_Z(void) { return (AMERICIUM_Z); }
double cxAMERICIUM(void) { return (AMERICIUM); }
double cxAm_Z(void) { return (Am_Z); }
double cxAm_WEIGHT(void) { return (Am_WEIGHT); }
double cxAm_MASS(void) { return (Am_MASS); }
double cxAmMASS(void) { return (AmMASS); }
double cxAm_DENSITY(void) { return (Am_DENSITY); }
double cxAm_MELT(void) { return (Am_MELT); }
double cxAm_BOIL(void) { return (Am_BOIL); }
double cxAm_Cp(void) { return (Am_Cp); }
double cxAm_En(void) { return (Am_En); }
double cxCURIUM_Z(void) { return (CURIUM_Z); }
double cxCURIUM(void) { return (CURIUM); }
double cxCm_Z(void) { return (Cm_Z); }
double cxCm_WEIGHT(void) { return (Cm_WEIGHT); }
double cxCm_MASS(void) { return (Cm_MASS); }
double cxCmMASS(void) { return (CmMASS); }
double cxCm_DENSITY(void) { return (Cm_DENSITY); }
double cxCm_MELT(void) { return (Cm_MELT); }
double cxCm_BOIL(void) { return (Cm_BOIL); }
double cxCm_Cp(void) { return (Cm_Cp); }
double cxCm_En(void) { return (Cm_En); }
double cxBERKELIUM_Z(void) { return (BERKELIUM_Z); }
double cxBERKELIUM(void) { return (BERKELIUM); }
double cxBk_Z(void) { return (Bk_Z); }
double cxBk_WEIGHT(void) { return (Bk_WEIGHT); }
double cxBk_MASS(void) { return (Bk_MASS); }
double cxBkMASS(void) { return (BkMASS); }
double cxBk_DENSITY(void) { return (Bk_DENSITY); }
double cxBk_MELT(void) { return (Bk_MELT); }
double cxBk_BOIL(void) { return (Bk_BOIL); }
double cxBk_Cp(void) { return (Bk_Cp); }
double cxBk_En(void) { return (Bk_En); }
double cxCALIFORNIUM_Z(void) { return (CALIFORNIUM_Z); }
double cxCALIFORNIUM(void) { return (CALIFORNIUM); }
double cxCf_Z(void) { return (Cf_Z); }
double cxCf_WEIGHT(void) { return (Cf_WEIGHT); }
double cxCf_MASS(void) { return (Cf_MASS); }
double cxCfMASS(void) { return (CfMASS); }
double cxCf_DENSITY(void) { return (Cf_DENSITY); }
double cxCf_MELT(void) { return (Cf_MELT); }
double cxCf_BOIL(void) { return (Cf_BOIL); }
double cxCf_Cp(void) { return (Cf_Cp); }
double cxCf_En(void) { return (Cf_En); }
double cxEINSTEINIUM_Z(void) { return (EINSTEINIUM_Z); }
double cxEINSTEINIUM(void) { return (EINSTEINIUM); }
double cxEs_Z(void) { return (Es_Z); }
double cxEs_WEIGHT(void) { return (Es_WEIGHT); }
double cxEs_MASS(void) { return (Es_MASS); }
double cxEsMASS(void) { return (EsMASS); }
double cxEs_DENSITY(void) { return (Es_DENSITY); }
double cxEs_MELT(void) { return (Es_MELT); }
double cxEs_BOIL(void) { return (Es_BOIL); }
double cxEs_Cp(void) { return (Es_Cp); }
double cxEs_En(void) { return (Es_En); }
double cxFERMIUM_Z(void) { return (FERMIUM_Z); }
double cxFERMIUM(void) { return (FERMIUM); }
double cxFm_Z(void) { return (Fm_Z); }
double cxFm_WEIGHT(void) { return (Fm_WEIGHT); }
double cxFm_MASS(void) { return (Fm_MASS); }
double cxFmMASS(void) { return (FmMASS); }
double cxFm_DENSITY(void) { return (Fm_DENSITY); }
double cxFm_MELT(void) { return (Fm_MELT); }
double cxFm_BOIL(void) { return (Fm_BOIL); }
double cxFm_Cp(void) { return (Fm_Cp); }
double cxFm_En(void) { return (Fm_En); }
double cxMENDELEVIUM_Z(void) { return (MENDELEVIUM_Z); }
double cxMENDELEVIUM(void) { return (MENDELEVIUM); }
double cxMd_Z(void) { return (Md_Z); }
double cxMd_WEIGHT(void) { return (Md_WEIGHT); }
double cxMd_MASS(void) { return (Md_MASS); }
double cxMdMASS(void) { return (MdMASS); }
double cxMd_DENSITY(void) { return (Md_DENSITY); }
double cxMd_MELT(void) { return (Md_MELT); }
double cxMd_BOIL(void) { return (Md_BOIL); }
double cxMd_Cp(void) { return (Md_Cp); }
double cxMd_En(void) { return (Md_En); }
double cxNOBELIUM_Z(void) { return (NOBELIUM_Z); }
double cxNOBELIUM(void) { return (NOBELIUM); }
double cxNo_Z(void) { return (No_Z); }
double cxNo_WEIGHT(void) { return (No_WEIGHT); }
double cxNo_MASS(void) { return (No_MASS); }
double cxNoMASS(void) { return (NoMASS); }
double cxNo_DENSITY(void) { return (No_DENSITY); }
double cxNo_MELT(void) { return (No_MELT); }
double cxNo_BOIL(void) { return (No_BOIL); }
double cxNo_Cp(void) { return (No_Cp); }
double cxNo_En(void) { return (No_En); }
double cxLAWRENCIUM_Z(void) { return (LAWRENCIUM_Z); }
double cxLAWRENCIUM(void) { return (LAWRENCIUM); }
double cxLr_Z(void) { return (Lr_Z); }
double cxLr_WEIGHT(void) { return (Lr_WEIGHT); }
double cxLr_MASS(void) { return (Lr_MASS); }
double cxLrMASS(void) { return (LrMASS); }
double cxLr_DENSITY(void) { return (Lr_DENSITY); }
double cxLr_MELT(void) { return (Lr_MELT); }
double cxLr_BOIL(void) { return (Lr_BOIL); }
double cxLr_Cp(void) { return (Lr_Cp); }
double cxLr_En(void) { return (Lr_En); }
double cxRUTHERFORDIUM_Z(void) { return (RUTHERFORDIUM_Z); }
double cxRUTHERFORDIUM(void) { return (RUTHERFORDIUM); }
double cxRf_Z(void) { return (Rf_Z); }
double cxRf_WEIGHT(void) { return (Rf_WEIGHT); }
double cxRf_MASS(void) { return (Rf_MASS); }
double cxRfMASS(void) { return (RfMASS); }
double cxRf_DENSITY(void) { return (Rf_DENSITY); }
double cxRf_MELT(void) { return (Rf_MELT); }
double cxRf_BOIL(void) { return (Rf_BOIL); }
double cxRf_Cp(void) { return (Rf_Cp); }
double cxRf_En(void) { return (Rf_En); }
double cxDUBNIUM_Z(void) { return (DUBNIUM_Z); }
double cxDUBNIUM(void) { return (DUBNIUM); }
double cxDb_Z(void) { return (Db_Z); }
double cxDb_WEIGHT(void) { return (Db_WEIGHT); }
double cxDb_MASS(void) { return (Db_MASS); }
double cxDbMASS(void) { return (DbMASS); }
double cxDb_DENSITY(void) { return (Db_DENSITY); }
double cxDb_MELT(void) { return (Db_MELT); }
double cxDb_BOIL(void) { return (Db_BOIL); }
double cxDb_Cp(void) { return (Db_Cp); }
double cxDb_En(void) { return (Db_En); }
double cxSEABORGIUM_Z(void) { return (SEABORGIUM_Z); }
double cxSEABORGIUM(void) { return (SEABORGIUM); }
double cxSg_Z(void) { return (Sg_Z); }
double cxSg_WEIGHT(void) { return (Sg_WEIGHT); }
double cxSg_MASS(void) { return (Sg_MASS); }
double cxSgMASS(void) { return (SgMASS); }
double cxSg_DENSITY(void) { return (Sg_DENSITY); }
double cxSg_MELT(void) { return (Sg_MELT); }
double cxSg_BOIL(void) { return (Sg_BOIL); }
double cxSg_Cp(void) { return (Sg_Cp); }
double cxSg_En(void) { return (Sg_En); }
double cxBOHRIUM_Z(void) { return (BOHRIUM_Z); }
double cxBOHRIUM(void) { return (BOHRIUM); }
double cxBh_Z(void) { return (Bh_Z); }
double cxBh_WEIGHT(void) { return (Bh_WEIGHT); }
double cxBh_MASS(void) { return (Bh_MASS); }
double cxBhMASS(void) { return (BhMASS); }
double cxBh_DENSITY(void) { return (Bh_DENSITY); }
double cxBh_MELT(void) { return (Bh_MELT); }
double cxBh_BOIL(void) { return (Bh_BOIL); }
double cxBh_Cp(void) { return (Bh_Cp); }
double cxBh_En(void) { return (Bh_En); }
double cxHASSIUM_Z(void) { return (HASSIUM_Z); }
double cxHASSIUM(void) { return (HASSIUM); }
double cxHs_Z(void) { return (Hs_Z); }
double cxHs_WEIGHT(void) { return (Hs_WEIGHT); }
double cxHs_MASS(void) { return (Hs_MASS); }
double cxHsMASS(void) { return (HsMASS); }
double cxHs_DENSITY(void) { return (Hs_DENSITY); }
double cxHs_MELT(void) { return (Hs_MELT); }
double cxHs_BOIL(void) { return (Hs_BOIL); }
double cxHs_Cp(void) { return (Hs_Cp); }
double cxHs_En(void) { return (Hs_En); }
double cxMEITNERIUM_Z(void) { return (MEITNERIUM_Z); }
double cxMEITNERIUM(void) { return (MEITNERIUM); }
double cxMt_Z(void) { return (Mt_Z); }
double cxMt_WEIGHT(void) { return (Mt_WEIGHT); }
double cxMt_MASS(void) { return (Mt_MASS); }
double cxMtMASS(void) { return (MtMASS); }
double cxMt_DENSITY(void) { return (Mt_DENSITY); }
double cxMt_MELT(void) { return (Mt_MELT); }
double cxMt_BOIL(void) { return (Mt_BOIL); }
double cxMt_Cp(void) { return (Mt_Cp); }
double cxMt_En(void) { return (Mt_En); }
double cxDARMSTADTIUM_Z(void) { return (DARMSTADTIUM_Z); }
double cxDARMSTADTIUM(void) { return (DARMSTADTIUM); }
double cxDs_Z(void) { return (Ds_Z); }
double cxDs_WEIGHT(void) { return (Ds_WEIGHT); }
double cxDs_MASS(void) { return (Ds_MASS); }
double cxDsMASS(void) { return (DsMASS); }
double cxDs_DENSITY(void) { return (Ds_DENSITY); }
double cxDs_MELT(void) { return (Ds_MELT); }
double cxDs_BOIL(void) { return (Ds_BOIL); }
double cxDs_Cp(void) { return (Ds_Cp); }
double cxDs_En(void) { return (Ds_En); }
double cxROENTGENIUM_Z(void) { return (ROENTGENIUM_Z); }
double cxROENTGENIUM(void) { return (ROENTGENIUM); }
double cxRg_Z(void) { return (Rg_Z); }
double cxRg_WEIGHT(void) { return (Rg_WEIGHT); }
double cxRg_MASS(void) { return (Rg_MASS); }
double cxRgMASS(void) { return (RgMASS); }
double cxRg_DENSITY(void) { return (Rg_DENSITY); }
double cxRg_MELT(void) { return (Rg_MELT); }
double cxRg_BOIL(void) { return (Rg_BOIL); }
double cxRg_Cp(void) { return (Rg_Cp); }
double cxRg_En(void) { return (Rg_En); }
double cxCOPERNICIUM_Z(void) { return (COPERNICIUM_Z); }
double cxCOPERNICIUM(void) { return (COPERNICIUM); }
double cxCn_Z(void) { return (Cn_Z); }
double cxCn_WEIGHT(void) { return (Cn_WEIGHT); }
double cxCn_MASS(void) { return (Cn_MASS); }
double cxCnMASS(void) { return (CnMASS); }
double cxCn_DENSITY(void) { return (Cn_DENSITY); }
double cxCn_MELT(void) { return (Cn_MELT); }
double cxCn_BOIL(void) { return (Cn_BOIL); }
double cxCn_Cp(void) { return (Cn_Cp); }
double cxCn_En(void) { return (Cn_En); }
double cxNIHONIUM_Z(void) { return (NIHONIUM_Z); }
double cxNIHONIUM(void) { return (NIHONIUM); }
double cxNh_Z(void) { return (Nh_Z); }
double cxNh_WEIGHT(void) { return (Nh_WEIGHT); }
double cxNh_MASS(void) { return (Nh_MASS); }
double cxNhMASS(void) { return (NhMASS); }
double cxNh_DENSITY(void) { return (Nh_DENSITY); }
double cxNh_MELT(void) { return (Nh_MELT); }
double cxNh_BOIL(void) { return (Nh_BOIL); }
double cxNh_Cp(void) { return (Nh_Cp); }
double cxNh_En(void) { return (Nh_En); }
double cxFLEROVIUM_Z(void) { return (FLEROVIUM_Z); }
double cxFLEROVIUM(void) { return (FLEROVIUM); }
double cxFl_Z(void) { return (Fl_Z); }
double cxFl_WEIGHT(void) { return (Fl_WEIGHT); }
double cxFl_MASS(void) { return (Fl_MASS); }
double cxFlMASS(void) { return (FlMASS); }
double cxFl_DENSITY(void) { return (Fl_DENSITY); }
double cxFl_MELT(void) { return (Fl_MELT); }
double cxFl_BOIL(void) { return (Fl_BOIL); }
double cxFl_Cp(void) { return (Fl_Cp); }
double cxFl_En(void) { return (Fl_En); }
double cxMOSCOVIUM_Z(void) { return (MOSCOVIUM_Z); }
double cxMOSCOVIUM(void) { return (MOSCOVIUM); }
double cxMc_Z(void) { return (Mc_Z); }
double cxMc_WEIGHT(void) { return (Mc_WEIGHT); }
double cxMc_MASS(void) { return (Mc_MASS); }
double cxMcMASS(void) { return (McMASS); }
double cxMc_DENSITY(void) { return (Mc_DENSITY); }
double cxMc_MELT(void) { return (Mc_MELT); }
double cxMc_BOIL(void) { return (Mc_BOIL); }
double cxMc_Cp(void) { return (Mc_Cp); }
double cxMc_En(void) { return (Mc_En); }
double cxLIVERMORIUM_Z(void) { return (LIVERMORIUM_Z); }
double cxLIVERMORIUM(void) { return (LIVERMORIUM); }
double cxLv_Z(void) { return (Lv_Z); }
double cxLv_WEIGHT(void) { return (Lv_WEIGHT); }
double cxLv_MASS(void) { return (Lv_MASS); }
double cxLvMASS(void) { return (LvMASS); }
double cxLv_DENSITY(void) { return (Lv_DENSITY); }
double cxLv_MELT(void) { return (Lv_MELT); }
double cxLv_BOIL(void) { return (Lv_BOIL); }
double cxLv_Cp(void) { return (Lv_Cp); }
double cxLv_En(void) { return (Lv_En); }
double cxTENNESSINE_Z(void) { return (TENNESSINE_Z); }
double cxTENNESSINE(void) { return (TENNESSINE); }
double cxTs_Z(void) { return (Ts_Z); }
double cxTs_WEIGHT(void) { return (Ts_WEIGHT); }
double cxTs_MASS(void) { return (Ts_MASS); }
double cxTsMASS(void) { return (TsMASS); }
double cxTs_DENSITY(void) { return (Ts_DENSITY); }
double cxTs_MELT(void) { return (Ts_MELT); }
double cxTs_BOIL(void) { return (Ts_BOIL); }
double cxTs_Cp(void) { return (Ts_Cp); }
double cxTs_En(void) { return (Ts_En); }
double cxOGANESSON_Z(void) { return (OGANESSON_Z); }
double cxOGANESSON(void) { return (OGANESSON); }
double cxOg_Z(void) { return (Og_Z); }
double cxOg_WEIGHT(void) { return (Og_WEIGHT); }
double cxOg_MASS(void) { return (Og_MASS); }
double cxOgMASS(void) { return (OgMASS); }
double cxOg_DENSITY(void) { return (Og_DENSITY); }
double cxOg_MELT(void) { return (Og_MELT); }
double cxOg_BOIL(void) { return (Og_BOIL); }
double cxOg_Cp(void) { return (Og_Cp); }
double cxOg_En(void) { return (Og_En); }
double cxH1_WEIGHT(void) { return (H1_WEIGHT); }
double cxH1_MASS(void) { return (H1_MASS); }
double cxH1MASS(void) { return (H1MASS); }
double cxDEUTERIUM_Z(void) { return (DEUTERIUM_Z); }
double cxDEUTERIUM(void) { return (DEUTERIUM); }
double cxD_Z(void) { return (D_Z); }
double cxD_WEIGHT(void) { return (D_WEIGHT); }
double cxD_MASS(void) { return (D_MASS); }
double cxDMASS(void) { return (DMASS); }
double cxTRITIUM_Z(void) { return (TRITIUM_Z); }
double cxTRITIUM(void) { return (TRITIUM); }
double cxT_Z(void) { return (T_Z); }
double cxT_WEIGHT(void) { return (T_WEIGHT); }
double cxT_MASS(void) { return (T_MASS); }
double cxTMASS(void) { return (TMASS); }
double cxH2_WEIGHT(void) { return (H2_WEIGHT); }
double cxH2_MASS(void) { return (H2_MASS); }
double cxH2MASS(void) { return (H2MASS); }
double cxH3_WEIGHT(void) { return (H3_WEIGHT); }
double cxH3_MASS(void) { return (H3_MASS); }
double cxH3MASS(void) { return (H3MASS); }
double cxHe3_WEIGHT(void) { return (He3_WEIGHT); }
double cxHe3_MASS(void) { return (He3_MASS); }
double cxHe3MASS(void) { return (He3MASS); }
double cxHe4_WEIGHT(void) { return (He4_WEIGHT); }
double cxHe4_MASS(void) { return (He4_MASS); }
double cxHe4MASS(void) { return (He4MASS); }
double cxC12_WEIGHT(void) { return (C12_WEIGHT); }
double cxC12_MASS(void) { return (C12_MASS); }
double cxC12MASS(void) { return (C12MASS); }
double cxC13_WEIGHT(void) { return (C13_WEIGHT); }
double cxC13_MASS(void) { return (C13_MASS); }
double cxC13MASS(void) { return (C13MASS); }
double cxC14_WEIGHT(void) { return (C14_WEIGHT); }
double cxC14_MASS(void) { return (C14_MASS); }
double cxC14MASS(void) { return (C14MASS); }
double cxO16_WEIGHT(void) { return (O16_WEIGHT); }
double cxO16_MASS(void) { return (O16_MASS); }
double cxO16MASS(void) { return (O16MASS); }
double cxO17_WEIGHT(void) { return (O17_WEIGHT); }
double cxO17_MASS(void) { return (O17_MASS); }
double cxO17MASS(void) { return (O17MASS); }
double cxO18_WEIGHT(void) { return (O18_WEIGHT); }
double cxO18_MASS(void) { return (O18_MASS); }
double cxO18MASS(void) { return (O18MASS); }
double cxDEUTERON_WEIGHT(void) { return (DEUTERON_WEIGHT); }
double cxDEUTERON_MASS(void) { return (DEUTERON_MASS); }
double cxDEUTERONMASS(void) { return (DEUTERONMASS); }
double cxDEUTERONMASS_ERR(void) { return (DEUTERONMASS_ERR); }
double cxDEUTERONENERGY(void) { return (DEUTERONENERGY); }
double cxHELION_WEIGHT(void) { return (HELION_WEIGHT); }
double cxHELION_MASS(void) { return (HELION_MASS); }
double cxHELIONMASS(void) { return (HELIONMASS); }
double cxHELIONMASS_ERR(void) { return (HELIONMASS_ERR); }
double cxHELIONENERGY(void) { return (HELIONENERGY); }
double cxTRITON_WEIGHT(void) { return (TRITON_WEIGHT); }
double cxTRITON_MASS(void) { return (TRITON_MASS); }
double cxTRITONMASS(void) { return (TRITONMASS); }
double cxTRITONMASS_ERR(void) { return (TRITONMASS_ERR); }
double cxTRITONENERGY(void) { return (TRITONENERGY); }
double cxALPHA_WEIGHT(void) { return (ALPHA_WEIGHT); }
double cxALPHA_MASS(void) { return (ALPHA_MASS); }
double cxALPHAMASS(void) { return (ALPHAMASS); }
double cxALPHAMASS_ERR(void) { return (ALPHAMASS_ERR); }
double cxALPHAENERGY(void) { return (ALPHAENERGY); }
double cxUPQUARK_ENERGY(void) { return (UPQUARK_ENERGY); }
double cxUPQUARKMASS(void) { return (UPQUARKMASS); }
double cxUPQUARK_MASS(void) { return (UPQUARK_MASS); }
double cxUPQUARKMASS_ERR(void) { return (UPQUARKMASS_ERR); }
double cxUPQUARK_Hz(void) { return (UPQUARK_Hz); }
double cxUPQUARK_WAVELENGTH(void) { return (UPQUARK_WAVELENGTH); }
double cxUPQUARK_CHARGE(void) { return (UPQUARK_CHARGE); }
double cxDOWNQUARK_ENERGY(void) { return (DOWNQUARK_ENERGY); }
double cxDOWNQUARKMASS(void) { return (DOWNQUARKMASS); }
double cxDOWNQUARK_MASS(void) { return (DOWNQUARK_MASS); }
double cxDOWNQUARKMASS_ERR(void) { return (DOWNQUARKMASS_ERR); }
double cxDOWNQUARK_Hz(void) { return (DOWNQUARK_Hz); }
double cxDOWNQUARK_WAVELENGTH(void) { return (DOWNQUARK_WAVELENGTH); }
double cxDOWNQUARK_CHARGE(void) { return (DOWNQUARK_CHARGE); }
double cxCHARMQUARK_ENERGY(void) { return (CHARMQUARK_ENERGY); }
double cxCHARMQUARKMASS(void) { return (CHARMQUARKMASS); }
double cxCHARMQUARK_MASS(void) { return (CHARMQUARK_MASS); }
double cxCHARMQUARKMASS_ERR(void) { return (CHARMQUARKMASS_ERR); }
double cxCHARMQUARK_Hz(void) { return (CHARMQUARK_Hz); }
double cxCHARMQUARK_WAVELENGTH(void) { return (CHARMQUARK_WAVELENGTH); }
double cxCHARMQUARK_CHARGE(void) { return (CHARMQUARK_CHARGE); }
double cxSTRANGEQUARK_ENERGY(void) { return (STRANGEQUARK_ENERGY); }
double cxSTRANGEQUARKMASS(void) { return (STRANGEQUARKMASS); }
double cxSTRANGEQUARK_MASS(void) { return (STRANGEQUARK_MASS); }
double cxSTRANGEQUARKMASS_ERR(void) { return (STRANGEQUARKMASS_ERR); }
double cxSTRANGEQUARK_Hz(void) { return (STRANGEQUARK_Hz); }
double cxSTRANGEQUARK_WAVELENGTH(void) { return (STRANGEQUARK_WAVELENGTH); }
double cxSTRANGEQUARK_CHARGE(void) { return (STRANGEQUARK_CHARGE); }
double cxTOPQUARK_ENERGY(void) { return (TOPQUARK_ENERGY); }
double cxTOPQUARKMASS(void) { return (TOPQUARKMASS); }
double cxTOPQUARK_MASS(void) { return (TOPQUARK_MASS); }
double cxTOPQUARKMASS_ERR(void) { return (TOPQUARKMASS_ERR); }
double cxTOPQUARK_Hz(void) { return (TOPQUARK_Hz); }
double cxTOPQUARK_WAVELENGTH(void) { return (TOPQUARK_WAVELENGTH); }
double cxTOPQUARK_CHARGE(void) { return (TOPQUARK_CHARGE); }
double cxBOTTOMQUARK_ENERGY(void) { return (BOTTOMQUARK_ENERGY); }
double cxBOTTOMQUARKMASS(void) { return (BOTTOMQUARKMASS); }
double cxBOTTOMQUARK_MASS(void) { return (BOTTOMQUARK_MASS); }
double cxBOTTOMQUARKMASS_ERR(void) { return (BOTTOMQUARKMASS_ERR); }
double cxBOTTOMQUARK_Hz(void) { return (BOTTOMQUARK_Hz); }
double cxBOTTOMQUARK_WAVELENGTH(void) { return (BOTTOMQUARK_WAVELENGTH); }
double cxBOTTOMQUARK_CHARGE(void) { return (BOTTOMQUARK_CHARGE); }
double cxHIGGSBOSON_ENERGY(void) { return (HIGGSBOSON_ENERGY); }
double cxHIGGSBOSONMASS(void) { return (HIGGSBOSONMASS); }
double cxHIGGSBOSON_MASS(void) { return (HIGGSBOSON_MASS); }
double cxHIGGSBOSONMASS_ERR(void) { return (HIGGSBOSONMASS_ERR); }
double cxHIGGSBOSON_Hz(void) { return (HIGGSBOSON_Hz); }
double cxHIGGSBOSON_WAVELENGTH(void) { return (HIGGSBOSON_WAVELENGTH); }
double cxWBOSON_ENERGY(void) { return (WBOSON_ENERGY); }
double cxWBOSONMASS(void) { return (WBOSONMASS); }
double cxWBOSON_MASS(void) { return (WBOSON_MASS); }
double cxWBOSONMASS_ERR(void) { return (WBOSONMASS_ERR); }
double cxWBOSON_Hz(void) { return (WBOSON_Hz); }
double cxWBOSON_WAVELENGTH(void) { return (WBOSON_WAVELENGTH); }
double cxZBOSON_ENERGY(void) { return (ZBOSON_ENERGY); }
double cxZBOSONMASS(void) { return (ZBOSONMASS); }
double cxZBOSON_MASS(void) { return (ZBOSON_MASS); }
double cxZBOSONMASS_ERR(void) { return (ZBOSONMASS_ERR); }
double cxZBOSON_Hz(void) { return (ZBOSON_Hz); }
double cxZBOSON_WAVELENGTH(void) { return (ZBOSON_WAVELENGTH); }
double cxTAU_ENERGY(void) { return (TAU_ENERGY); }
double cxTAUMASS(void) { return (TAUMASS); }
double cxTAU_MASS(void) { return (TAU_MASS); }
double cxTAUMASS_ERR(void) { return (TAUMASS_ERR); }
double cxTAU_Hz(void) { return (TAU_Hz); }
double cxTAU_WAVELENGTH(void) { return (TAU_WAVELENGTH); }
double cxMUON_ENERGY(void) { return (MUON_ENERGY); }
double cxMUONMASS(void) { return (MUONMASS); }
double cxMUON_MASS(void) { return (MUON_MASS); }
double cxMUONMASS_ERR(void) { return (MUONMASS_ERR); }
double cxMUON_Hz(void) { return (MUON_Hz); }
double cxMUON_WAVELENGTH(void) { return (MUON_WAVELENGTH); }
double cxELECTRON_ENERGY(void) { return (ELECTRON_ENERGY); }
double cxELECTRONMASS(void) { return (ELECTRONMASS); }
double cxELECTRON_MASS(void) { return (ELECTRON_MASS); }
double cxELECTRONMASS_ERR(void) { return (ELECTRONMASS_ERR); }
double cxELECTRON_Hz(void) { return (ELECTRON_Hz); }
double cxELECTRON_WAVELENGTH(void) { return (ELECTRON_WAVELENGTH); }
double cxPROTON_ENERGY(void) { return (PROTON_ENERGY); }
double cxPROTONMASS(void) { return (PROTONMASS); }
double cxPROTON_MASS(void) { return (PROTON_MASS); }
double cxPROTONMASS_ERR(void) { return (PROTONMASS_ERR); }
double cxPROTON_Hz(void) { return (PROTON_Hz); }
double cxPROTON_WAVELENGTH(void) { return (PROTON_WAVELENGTH); }
double cxNEUTRON_ENERGY(void) { return (NEUTRON_ENERGY); }
double cxNEUTRONMASS(void) { return (NEUTRONMASS); }
double cxNEUTRON_MASS(void) { return (NEUTRON_MASS); }
double cxNEUTRONMASS_ERR(void) { return (NEUTRONMASS_ERR); }
double cxNEUTRON_Hz(void) { return (NEUTRON_Hz); }
double cxNEUTRON_WAVELENGTH(void) { return (NEUTRON_WAVELENGTH); }
double cxHYDROGEN_RADIUS(void) { return (HYDROGEN_RADIUS); }
double cxHYDROGEN_RADIUS_ERR(void) { return (HYDROGEN_RADIUS_ERR); }
double cxBOHRRADIUS(void) { return (BOHRRADIUS); }
double cxBOHRRADIUS_ERR(void) { return (BOHRRADIUS_ERR); }
double cxAIR_MASS(void) { return (AIR_MASS); }
double cxAIRMASS(void) { return (AIRMASS); }
double cxSTEAM_MASS(void) { return (STEAM_MASS); }
double cxSTEAMMASS(void) { return (STEAMMASS); }
double cxSTEAM_HF(void) { return (STEAM_HF); }
double cxSTEAM_HC(void) { return (STEAM_HC); }
double cxSTEAM_JPKG(void) { return (STEAM_JPKG); }
double cxSTEAM_DENSITY(void) { return (STEAM_DENSITY); }
double cxSTEAM_JPL(void) { return (STEAM_JPL); }
double cxH2O_MASS(void) { return (H2O_MASS); }
double cxH2OMASS(void) { return (H2OMASS); }
double cxH2O_HF(void) { return (H2O_HF); }
double cxH2O_HC(void) { return (H2O_HC); }
double cxH2O_JPKG(void) { return (H2O_JPKG); }
double cxH2O_DENSITY(void) { return (H2O_DENSITY); }
double cxH2O_JPL(void) { return (H2O_JPL); }
double cxWATER_MASS(void) { return (WATER_MASS); }
double cxWATERMASS(void) { return (WATERMASS); }
double cxWATER_HF(void) { return (WATER_HF); }
double cxWATER_HC(void) { return (WATER_HC); }
double cxWATER_JPKG(void) { return (WATER_JPKG); }
double cxWATER_DENSITY(void) { return (WATER_DENSITY); }
double cxWATER_JPL(void) { return (WATER_JPL); }
double cxCO2_MASS(void) { return (CO2_MASS); }
double cxCO2MASS(void) { return (CO2MASS); }
double cxCO2_HF(void) { return (CO2_HF); }
double cxCO2_HC(void) { return (CO2_HC); }
double cxCO2_JPKG(void) { return (CO2_JPKG); }
double cxCO2_DENSITY(void) { return (CO2_DENSITY); }
double cxCO2_JPL(void) { return (CO2_JPL); }
double cxCARBONDIOXIDE_MASS(void) { return (CARBONDIOXIDE_MASS); }
double cxCARBONDIOXIDEMASS(void) { return (CARBONDIOXIDEMASS); }
double cxCARBONDIOXIDE_HF(void) { return (CARBONDIOXIDE_HF); }
double cxCARBONDIOXIDE_HC(void) { return (CARBONDIOXIDE_HC); }
double cxCARBONDIOXIDE_JPKG(void) { return (CARBONDIOXIDE_JPKG); }
double cxCARBONDIOXIDE_DENSITY(void) { return (CARBONDIOXIDE_DENSITY); }
double cxCARBONDIOXIDE_JPL(void) { return (CARBONDIOXIDE_JPL); }
double cxO2_MASS(void) { return (O2_MASS); }
double cxO2MASS(void) { return (O2MASS); }
double cxO2_HF(void) { return (O2_HF); }
double cxO2_HC(void) { return (O2_HC); }
double cxO2_JPKG(void) { return (O2_JPKG); }
double cxO2_DENSITY(void) { return (O2_DENSITY); }
double cxO2_JPL(void) { return (O2_JPL); }
double cxHYDROGEN_MASS(void) { return (HYDROGEN_MASS); }
double cxHYDROGENMASS(void) { return (HYDROGENMASS); }
double cxHYDROGEN_HF(void) { return (HYDROGEN_HF); }
double cxHYDROGEN_HC(void) { return (HYDROGEN_HC); }
double cxHYDROGEN_HCC(void) { return (HYDROGEN_HCC); }
double cxHYDROGEN_JPKG(void) { return (HYDROGEN_JPKG); }
double cxHYDROGEN_DENSITY(void) { return (HYDROGEN_DENSITY); }
double cxHYDROGEN_JPL(void) { return (HYDROGEN_JPL); }
double cxMETHANE_MASS(void) { return (METHANE_MASS); }
double cxMETHANEMASS(void) { return (METHANEMASS); }
double cxMETHANE_HF(void) { return (METHANE_HF); }
double cxMETHANE_HC(void) { return (METHANE_HC); }
double cxMETHANE_HCC(void) { return (METHANE_HCC); }
double cxMETHANE_JPKG(void) { return (METHANE_JPKG); }
double cxMETHANE_DENSITY(void) { return (METHANE_DENSITY); }
double cxMETHANE_JPL(void) { return (METHANE_JPL); }
double cxETHANE_MASS(void) { return (ETHANE_MASS); }
double cxETHANEMASS(void) { return (ETHANEMASS); }
double cxETHANE_HF(void) { return (ETHANE_HF); }
double cxETHANE_HC(void) { return (ETHANE_HC); }
double cxETHANE_HCC(void) { return (ETHANE_HCC); }
double cxETHANE_JPKG(void) { return (ETHANE_JPKG); }
double cxETHANE_DENSITY(void) { return (ETHANE_DENSITY); }
double cxETHANE_JPL(void) { return (ETHANE_JPL); }
double cxPROPANE_MASS(void) { return (PROPANE_MASS); }
double cxPROPANEMASS(void) { return (PROPANEMASS); }
double cxPROPANE_HF(void) { return (PROPANE_HF); }
double cxPROPANE_HC(void) { return (PROPANE_HC); }
double cxPROPANE_HCC(void) { return (PROPANE_HCC); }
double cxPROPANE_JPKG(void) { return (PROPANE_JPKG); }
double cxPROPANE_DENSITY(void) { return (PROPANE_DENSITY); }
double cxPROPANE_JPL(void) { return (PROPANE_JPL); }
double cxBUTANE_MASS(void) { return (BUTANE_MASS); }
double cxBUTANEMASS(void) { return (BUTANEMASS); }
double cxBUTANE_HF(void) { return (BUTANE_HF); }
double cxBUTANE_HC(void) { return (BUTANE_HC); }
double cxBUTANE_HCC(void) { return (BUTANE_HCC); }
double cxBUTANE_JPKG(void) { return (BUTANE_JPKG); }
double cxBUTANE_DENSITY(void) { return (BUTANE_DENSITY); }
double cxBUTANE_JPL(void) { return (BUTANE_JPL); }
double cxPENTANE_MASS(void) { return (PENTANE_MASS); }
double cxPENTANEMASS(void) { return (PENTANEMASS); }
double cxPENTANE_HF(void) { return (PENTANE_HF); }
double cxPENTANE_HC(void) { return (PENTANE_HC); }
double cxPENTANE_HCC(void) { return (PENTANE_HCC); }
double cxPENTANE_JPKG(void) { return (PENTANE_JPKG); }
double cxPENTANE_DENSITY(void) { return (PENTANE_DENSITY); }
double cxPENTANE_JPL(void) { return (PENTANE_JPL); }
double cxHEXANE_MASS(void) { return (HEXANE_MASS); }
double cxHEXANEMASS(void) { return (HEXANEMASS); }
double cxHEXANE_HF(void) { return (HEXANE_HF); }
double cxHEXANE_HC(void) { return (HEXANE_HC); }
double cxHEXANE_HCC(void) { return (HEXANE_HCC); }
double cxHEXANE_JPKG(void) { return (HEXANE_JPKG); }
double cxHEXANE_DENSITY(void) { return (HEXANE_DENSITY); }
double cxHEXANE_JPL(void) { return (HEXANE_JPL); }
double cxETHANOL_MASS(void) { return (ETHANOL_MASS); }
double cxETHANOLMASS(void) { return (ETHANOLMASS); }
double cxETHANOL_HF(void) { return (ETHANOL_HF); }
double cxETHANOL_HC(void) { return (ETHANOL_HC); }
double cxETHANOL_HCC(void) { return (ETHANOL_HCC); }
double cxETHANOL_JPKG(void) { return (ETHANOL_JPKG); }
double cxETHANOL_DENSITY(void) { return (ETHANOL_DENSITY); }
double cxETHANOL_JPL(void) { return (ETHANOL_JPL); }
double cxETHANOL_G_MASS(void) { return (ETHANOL_G_MASS); }
double cxETHANOL_GMASS(void) { return (ETHANOL_GMASS); }
double cxETHANOL_G_HF(void) { return (ETHANOL_G_HF); }
double cxETHANOL_G_HC(void) { return (ETHANOL_G_HC); }
double cxETHANOL_G_HCC(void) { return (ETHANOL_G_HCC); }
double cxETHANOL_G_JPKG(void) { return (ETHANOL_G_JPKG); }
double cxETHANOL_G_DENSITY(void) { return (ETHANOL_G_DENSITY); }
double cxETHANOL_G_JPL(void) { return (ETHANOL_G_JPL); }
double cxSUCROSE_MASS(void) { return (SUCROSE_MASS); }
double cxSUCROSEMASS(void) { return (SUCROSEMASS); }
double cxSUCROSE_HF(void) { return (SUCROSE_HF); }
double cxSUCROSE_HC(void) { return (SUCROSE_HC); }
double cxSUCROSE_HCC(void) { return (SUCROSE_HCC); }
double cxSUCROSE_JPKG(void) { return (SUCROSE_JPKG); }
double cxSUCROSE_DENSITY(void) { return (SUCROSE_DENSITY); }
double cxSUCROSE_JPL(void) { return (SUCROSE_JPL); }
double cxSUGAR_MASS(void) { return (SUGAR_MASS); }
double cxSUGARMASS(void) { return (SUGARMASS); }
double cxSUGAR_HF(void) { return (SUGAR_HF); }
double cxSUGAR_HC(void) { return (SUGAR_HC); }
double cxSUGAR_HCC(void) { return (SUGAR_HCC); }
double cxSUGAR_JPKG(void) { return (SUGAR_JPKG); }
double cxSUGAR_DENSITY(void) { return (SUGAR_DENSITY); }
double cxSUGAR_JPL(void) { return (SUGAR_JPL); }
double cxCOAL_MASS(void) { return (COAL_MASS); }
double cxCOALMASS(void) { return (COALMASS); }
double cxCOAL_JPKG(void) { return (COAL_JPKG); }
double cxCOAL_DENSITY(void) { return (COAL_DENSITY); }
double cxCOAL_JPL(void) { return (COAL_JPL); }
double cxPARAFFIN_MASS(void) { return (PARAFFIN_MASS); }
double cxPARAFFINMASS(void) { return (PARAFFINMASS); }
double cxPARAFFIN_JPKG(void) { return (PARAFFIN_JPKG); }
double cxPARAFFIN_DENSITY(void) { return (PARAFFIN_DENSITY); }
double cxPARAFFIN_JPL(void) { return (PARAFFIN_JPL); }
double cxFAT_MASS(void) { return (FAT_MASS); }
double cxFATMASS(void) { return (FATMASS); }
double cxFAT_JPKG(void) { return (FAT_JPKG); }
double cxFAT_DENSITY(void) { return (FAT_DENSITY); }
double cxFAT_JPL(void) { return (FAT_JPL); }
double cxDIESEL_MASS(void) { return (DIESEL_MASS); }
double cxDIESELMASS(void) { return (DIESELMASS); }
double cxDIESEL_JPKG(void) { return (DIESEL_JPKG); }
double cxDIESEL_DENSITY(void) { return (DIESEL_DENSITY); }
double cxDIESEL_JPL(void) { return (DIESEL_JPL); }
double cxGASOLINE_MASS(void) { return (GASOLINE_MASS); }
double cxGASOLINEMASS(void) { return (GASOLINEMASS); }
double cxGASOLINE_JPKG(void) { return (GASOLINE_JPKG); }
double cxGASOLINE_DENSITY(void) { return (GASOLINE_DENSITY); }
double cxGASOLINE_JPL(void) { return (GASOLINE_JPL); }
double cxKEROSENE_MASS(void) { return (KEROSENE_MASS); }
double cxKEROSENEMASS(void) { return (KEROSENEMASS); }
double cxKEROSENE_JPKG(void) { return (KEROSENE_JPKG); }
double cxKEROSENE_DENSITY(void) { return (KEROSENE_DENSITY); }
double cxKEROSENE_JPL(void) { return (KEROSENE_JPL); }
double cxC13_RATIO(void) { return (C13_RATIO); }
double cxC14_RATIO(void) { return (C14_RATIO); }
double cxC12_RATIO(void) { return (C12_RATIO); }
double cxC_MEAN_MASS(void) { return (C_MEAN_MASS); }
double cxWATER_Cp(void) { return (WATER_Cp); }
double cxICE_Cp(void) { return (ICE_Cp); }
double cxSTEAM_Cp(void) { return (STEAM_Cp); }
double cxWATER_FUSION_JPMOLE(void) { return (WATER_FUSION_JPMOLE); }
double cxWATER_FUSION_JPKG(void) { return (WATER_FUSION_JPKG); }
double cxWATER_VAPORIZATION_JPMOLE(void) {
   return (WATER_VAPORIZATION_JPMOLE); }
double cxWATER_VAPORIZATION_JPKG(void) { return (WATER_VAPORIZATION_JPKG); }
double cxWATER_CRITICAL(void) { return (WATER_CRITICAL); }
double cxVSMOW_H3_RATIO(void) { return (VSMOW_H3_RATIO); }
double cxVSMOW_H2_RATIO(void) { return (VSMOW_H2_RATIO); }
double cxVSMOW_H1_RATIO(void) { return (VSMOW_H1_RATIO); }
double cxVSMOW_H_MASS(void) { return (VSMOW_H_MASS); }
double cxVSMOW_O18_RATIO(void) { return (VSMOW_O18_RATIO); }
double cxVSMOW_O17_RATIO(void) { return (VSMOW_O17_RATIO); }
double cxVSMOW_O16_RATIO(void) { return (VSMOW_O16_RATIO); }
double cxVSMOW_O_MASS(void) { return (VSMOW_O_MASS); }
double cxVSMOW_MASS(void) { return (VSMOW_MASS); }
double cxTNTJPKG(void) { return (TNTJPKG); }
//  IIIIIIIIIINCLUDE ############################################### LANG_C #
#include "Kw.h"
double watervapor_pressure(double temp_k)
{
   double retvalu;
   double temp_c;
   if (temp_k <= 16.1 || WATER_CRITICAL <= temp_k) {
      retvalu = 0.0;
   } else {
      temp_c = k2tempc(temp_k);
      if (0.0 <= temp_c) {
         retvalu = 611.21 * exp((18.678 - temp_c / 234.5) * (temp_c /\
                  (257.14 + temp_c)));
      } else {
         retvalu = 611.15 * exp((23.036 - temp_c / 333.7) * (temp_c /\
                  (279.82 + temp_c)));
      }
   }
   return (retvalu);
}
double watervaporization(double temp_k)
{
   double retvalu;
   if (WATER_CRITICAL <= temp_k) {
      retvalu = 0.0;
   } else {
      retvalu = pow((WATER_CRITICAL - temp_k) / (WATER_CRITICAL - 373.15)\
               , 0.37) * WATER_VAPORIZATION_JPMOLE;
   }
   return (retvalu);
}
double waterboiling(double pressure_pa)
{
   double retvalu;
   if (pressure_pa <= 0.0) {
      retvalu = 0.0;
   } else {
      retvalu = 1.0 / (1.0 / 373.15 - log(pressure_pa / ATM) * GAS /\
               WATER_VAPORIZATION_JPMOLE);
   }
   return (retvalu);
}
double waterdensity_airfree(double temp_k)
{
   double temp_c;
   double retvalu;
   temp_c = k2tempc(temp_k);
   if (temp_c < 5.0 || 40.0 < temp_c) {
      retvalu = ((((((-2.8054253E-10) * temp_c + 1.0556302E-7) * temp_c -\
               4.6170461E-5) * temp_c - 7.9870401E-3) * temp_c +\
               1.6945176E+1) * temp_c + 9.9983952E+2);
      retvalu /= (1.6897850E-2 * temp_c + 1.0);
   } else {
      retvalu = (((((-3.821216E-7) * temp_c + 6.943248E-5) * temp_c -\
               8.523829E-3) * temp_c + 6.32693E-2) * temp_c + 9.9985308E+2);
   }
   return (retvalu);
}
double waterdensity(double temp_k)
{
   double temp_c;
   double retvalu;
   temp_c = k2tempc(temp_k);
   if (temp_c < 0.0) {
      retvalu = 917 - 0.13 * temp_c;
   } else if (temp_c <= 5.0) {
      retvalu = (((8.7191684845109E-5) * temp_c - 9.0329747829960E-3) *\
               temp_c + 6.7771627919989E-2) * temp_c + 9.9984281840963E+2;
   } else if (temp_c <= 40.0) {
      retvalu = ((((-3.821216E-7) * temp_c + 6.943248E-5) * temp_c -\
               8.523829E-3) * temp_c + 6.337563E-2) * temp_c +\
               9.9984847E+2 + 0.0059;
   } else {
      retvalu = ((((-6.5202248732325E-8) * temp_c + 2.5745673934090E-5) *\
               temp_c - 6.1868849581972E-3) * temp_c +\
               6.0164627537211E-3) * temp_c + 1.0003918667215E+3;
   }
   return (retvalu);
}
double waterdensity_airfree__1(double temp_k)
{
   double temp_c;
   double retvalu;
   temp_c = k2tempc(temp_k);
   if (temp_c <= 5.0) {
      retvalu = ((((9.6308327803439E-5) * temp_c - 9.0973473048107E-3) *\
               temp_c + 6.7877518213033E-2) * temp_c + 9.9984280358288E+2);
   } else if (temp_c <= 40.0) {
      retvalu = (((((((-4.6205682267935E-11) * temp_c +\
               1.0474115539454E-8) * temp_c - 1.1933226216922E-6) *\
               temp_c + 9.8476793645150E-5) * temp_c -\
               9.0387372512241E-3) * temp_c + 6.7575261493264E-2) *\
               temp_c + 9.9984328159055E+2);
   } else if (temp_c <= 100) {
      retvalu = (((((-6.5202248732325E-8) * temp_c + 2.5745673934090E-5)\
               * temp_c - 6.1868849581972E-3) * temp_c +\
               6.0164627537211E-3) * temp_c + 1.0003918667215E+3);
   } else {
      retvalu = ((((((((((-5.4752717629528E-17) * temp_c +\
               1.1052954300641E-13) * temp_c - 9.7190466446857E-11) *\
               temp_c + 4.8801821861028E-8) * temp_c -\
               1.5403658215495E-5) * temp_c + 3.1660515368531E-3) *\
               temp_c - 4.2335200290825E-1) * temp_c +\
               3.5482000718216E+1) * temp_c - 1.6909944548890E+3) *\
               temp_c + 3.5888296998420E+4);
   }
   return (retvalu);
}
