//   Copyright (C) 2020 by Kevin D. Woerner
//-/ =KDW= ########## DO NOT EDIT -- AUTOGENERATED CODE #########
//-/ =KDW= ############ BUILDER $KWROOT/0lib/vkkcp.sh ###########
//-/ =KDW= ##### SRC $KWROOT/codekdw/kw-lib/Kwplanets.fwipp #####
// 2020-07-20 kdw  For Changelog, See File Kwplanets.varylog
#ifndef INCLUDED_Kwplanets_h
#define INCLUDED_Kwplanets_h
double cxearthsiderealday(void);
double cxearthstellarday(void);
double cxearthtropicalyear(void);
double cxearthsiderealyear(void);
double cxearthanomalisticyear(void);
double cxsiderealyear(void);
double cxanomalisticyear(void);
double cxtropicalyear(void);
double cxstellarday(void);
double cxsiderealday(void);
double cxsungmnasa(void);
double cxsungmiers(void);
double cxsungm(void);
double cxsunyear(void);
double cxsunday(void);
double cxsunflatness(void);
double cxsun_a(void);
double cxsun_c(void);
double cxsun_b(void);
double cxsunradius(void);
double cxsunescape(void);
double cxsunoblateness(void);
double cxsungravity(void);
double cxsunmass(void);
double cxsunvolume(void);
double cxsundensity(void);
double cxmercurygm(void);
double cxmercuryyear(void);
double cxmercuryday(void);
double cxmercuryflatness(void);
double cxmercury_a(void);
double cxmercury_c(void);
double cxmercury_b(void);
double cxmercuryradius(void);
double cxmercuryescape(void);
double cxmercuryoblateness(void);
double cxmercurygravity(void);
double cxmercurymass(void);
double cxmercuryvolume(void);
double cxmercurydensity(void);
double cxvenusgm(void);
double cxvenusyear(void);
double cxvenusday(void);
double cxvenusflatness(void);
double cxvenus_a(void);
double cxvenus_c(void);
double cxvenus_b(void);
double cxvenusradius(void);
double cxvenusescape(void);
double cxvenusoblateness(void);
double cxvenusgravity(void);
double cxvenusmass(void);
double cxvenusvolume(void);
double cxvenusdensity(void);
double cxearthgm(void);
double cxearthyear(void);
double cxearthday(void);
double cxearthflatness(void);
double cxearth_a(void);
double cxearth_c(void);
double cxearth_b(void);
double cxearthradius(void);
double cxearthescape(void);
double cxearthoblateness(void);
double cxearthgravity(void);
double cxearthmass(void);
double cxearthvolume(void);
double cxearthdensity(void);
double cxearthprecession(void);
double cxearththeta_0(void);
double cxmarsgm(void);
double cxmarsyear(void);
double cxmarsday(void);
double cxmarsflatness(void);
double cxmars_a(void);
double cxmars_c(void);
double cxmars_b(void);
double cxmarsradius(void);
double cxmarsescape(void);
double cxmarsoblateness(void);
double cxmarsgravity(void);
double cxmarsmass(void);
double cxmarsvolume(void);
double cxmarsdensity(void);
double cxjupitergm(void);
double cxjupiteryear(void);
double cxjupiterday(void);
double cxjupiterflatness(void);
double cxjupiter_a(void);
double cxjupiter_c(void);
double cxjupiter_b(void);
double cxjupiterradius(void);
double cxjupiterescape(void);
double cxjupiteroblateness(void);
double cxjupitergravity(void);
double cxjupitermass(void);
double cxjupitervolume(void);
double cxjupiterdensity(void);
double cxsaturngm(void);
double cxsaturnyear(void);
double cxsaturnday(void);
double cxsaturnflatness(void);
double cxsaturn_a(void);
double cxsaturn_c(void);
double cxsaturn_b(void);
double cxsaturnradius(void);
double cxsaturnescape(void);
double cxsaturnoblateness(void);
double cxsaturngravity(void);
double cxsaturnmass(void);
double cxsaturnvolume(void);
double cxsaturndensity(void);
double cxuranusgm(void);
double cxuranusyear(void);
double cxuranusday(void);
double cxuranusflatness(void);
double cxuranus_a(void);
double cxuranus_c(void);
double cxuranus_b(void);
double cxuranusradius(void);
double cxuranusescape(void);
double cxuranusoblateness(void);
double cxuranusgravity(void);
double cxuranusmass(void);
double cxuranusvolume(void);
double cxuranusdensity(void);
double cxneptunegm(void);
double cxneptuneyear(void);
double cxneptuneday(void);
double cxneptuneflatness(void);
double cxneptune_a(void);
double cxneptune_c(void);
double cxneptune_b(void);
double cxneptuneradius(void);
double cxneptuneescape(void);
double cxneptuneoblateness(void);
double cxneptunegravity(void);
double cxneptunemass(void);
double cxneptunevolume(void);
double cxneptunedensity(void);
double cxplutogm(void);
double cxplutoyear(void);
double cxplutoday(void);
double cxplutoflatness(void);
double cxpluto_a(void);
double cxpluto_c(void);
double cxpluto_b(void);
double cxplutoradius(void);
double cxplutoescape(void);
double cxplutooblateness(void);
double cxplutogravity(void);
double cxplutomass(void);
double cxplutovolume(void);
double cxplutodensity(void);
double cxmoongm(void);
double cxmoonyear(void);
double cxmoonday(void);
double cxmoonflatness(void);
double cxmoon_a(void);
double cxmoon_c(void);
double cxmoon_b(void);
double cxmoonradius(void);
double cxmoonescape(void);
double cxmoonoblateness(void);
double cxmoongravity(void);
double cxmoonmass(void);
double cxmoonvolume(void);
double cxmoondensity(void);
double cxmoonorbit(void);
double cxmooneccentricity(void);
double cxmooninclination(void);
double cxceresgm(void);
double cxceresyear(void);
double cxceresday(void);
double cxceresflatness(void);
double cxceres_a(void);
double cxceres_c(void);
double cxceres_b(void);
double cxceresradius(void);
double cxceresescape(void);
double cxceresoblateness(void);
double cxceresgravity(void);
double cxceresmass(void);
double cxceresvolume(void);
double cxceresdensity(void);
double cxerisgm(void);
double cxerisyear(void);
double cxerisday(void);
double cxerisflatness(void);
double cxeris_a(void);
double cxeris_c(void);
double cxeris_b(void);
double cxerisradius(void);
double cxerisescape(void);
double cxerisoblateness(void);
double cxerisgravity(void);
double cxerismass(void);
double cxerisvolume(void);
double cxerisdensity(void);
double cxmakemakegm(void);
double cxmakemakeyear(void);
double cxmakemakeday(void);
double cxmakemakeflatness(void);
double cxmakemake_a(void);
double cxmakemake_c(void);
double cxmakemake_b(void);
double cxmakemakeradius(void);
double cxmakemakeescape(void);
double cxmakemakeoblateness(void);
double cxmakemakegravity(void);
double cxmakemakemass(void);
double cxmakemakevolume(void);
double cxmakemakedensity(void);
double cxhaumeagm(void);
double cxhaumeayear(void);
double cxhaumeaday(void);
double cxhaumeaflatness(void);
double cxhaumea_a(void);
double cxhaumea_c(void);
double cxhaumea_b(void);
double cxhaumearadius(void);
double cxhaumeaescape(void);
double cxhaumeaoblateness(void);
double cxhaumeagravity(void);
double cxhaumeamass(void);
double cxhaumeavolume(void);
double cxhaumeadensity(void);
double cxsunorbit(void);
double cxsuneccentricity(void);
double cxsuninclination(void);
double cxsunlongitude(void);
double cxsunperiapsis(void);
double cxsunascending(void);
double cxsunorbit_dt(void);
double cxsuneccentricity_dt(void);
double cxsuninclination_dt(void);
double cxsunlongitude_dt(void);
double cxsunperiapsis_dt(void);
double cxsunascending_dt(void);
double cxearthorbit(void);
double cxeartheccentricity(void);
double cxearthinclination(void);
double cxearthlongitude(void);
double cxearthperiapsis(void);
double cxearthascending(void);
double cxearthorbit_dt(void);
double cxeartheccentricity_dt(void);
double cxearthinclination_dt(void);
double cxearthlongitude_dt(void);
double cxearthperiapsis_dt(void);
double cxearthascending_dt(void);
double cxmercuryorbit(void);
double cxmercuryeccentricity(void);
double cxmercuryinclination(void);
double cxmercurylongitude(void);
double cxmercuryperiapsis(void);
double cxmercuryascending(void);
double cxmercuryorbit_dt(void);
double cxmercuryeccentricity_dt(void);
double cxmercuryinclination_dt(void);
double cxmercurylongitude_dt(void);
double cxmercuryperiapsis_dt(void);
double cxmercuryascending_dt(void);
double cxvenusorbit(void);
double cxvenuseccentricity(void);
double cxvenusinclination(void);
double cxvenuslongitude(void);
double cxvenusperiapsis(void);
double cxvenusascending(void);
double cxvenusorbit_dt(void);
double cxvenuseccentricity_dt(void);
double cxvenusinclination_dt(void);
double cxvenuslongitude_dt(void);
double cxvenusperiapsis_dt(void);
double cxvenusascending_dt(void);
double cxmarsorbit(void);
double cxmarseccentricity(void);
double cxmarsinclination(void);
double cxmarslongitude(void);
double cxmarsperiapsis(void);
double cxmarsascending(void);
double cxmarsorbit_dt(void);
double cxmarseccentricity_dt(void);
double cxmarsinclination_dt(void);
double cxmarslongitude_dt(void);
double cxmarsperiapsis_dt(void);
double cxmarsascending_dt(void);
double cxjupiterorbit(void);
double cxjupitereccentricity(void);
double cxjupiterinclination(void);
double cxjupiterlongitude(void);
double cxjupiterperiapsis(void);
double cxjupiterascending(void);
double cxjupiterorbit_dt(void);
double cxjupitereccentricity_dt(void);
double cxjupiterinclination_dt(void);
double cxjupiterlongitude_dt(void);
double cxjupiterperiapsis_dt(void);
double cxjupiterascending_dt(void);
double cxsaturnorbit(void);
double cxsaturneccentricity(void);
double cxsaturninclination(void);
double cxsaturnlongitude(void);
double cxsaturnperiapsis(void);
double cxsaturnascending(void);
double cxsaturnorbit_dt(void);
double cxsaturneccentricity_dt(void);
double cxsaturninclination_dt(void);
double cxsaturnlongitude_dt(void);
double cxsaturnperiapsis_dt(void);
double cxsaturnascending_dt(void);
double cxuranusorbit(void);
double cxuranuseccentricity(void);
double cxuranusinclination(void);
double cxuranuslongitude(void);
double cxuranusperiapsis(void);
double cxuranusascending(void);
double cxuranusorbit_dt(void);
double cxuranuseccentricity_dt(void);
double cxuranusinclination_dt(void);
double cxuranuslongitude_dt(void);
double cxuranusperiapsis_dt(void);
double cxuranusascending_dt(void);
double cxneptuneorbit(void);
double cxneptuneeccentricity(void);
double cxneptuneinclination(void);
double cxneptunelongitude(void);
double cxneptuneperiapsis(void);
double cxneptuneascending(void);
double cxneptuneorbit_dt(void);
double cxneptuneeccentricity_dt(void);
double cxneptuneinclination_dt(void);
double cxneptunelongitude_dt(void);
double cxneptuneperiapsis_dt(void);
double cxneptuneascending_dt(void);
double cxplutoorbit(void);
double cxplutoeccentricity(void);
double cxplutoinclination(void);
double cxplutolongitude(void);
double cxplutoperiapsis(void);
double cxplutoascending(void);
double cxplutoorbit_dt(void);
double cxplutoeccentricity_dt(void);
double cxplutoinclination_dt(void);
double cxplutolongitude_dt(void);
double cxplutoperiapsis_dt(void);
double cxplutoascending_dt(void);
double cxceresorbit(void);
double cxcereseccentricity(void);
double cxceresinclination(void);
double cxcereslongitude(void);
double cxceresperiapsis(void);
double cxceresascending(void);
double cxceresorbit_dt(void);
double cxcereseccentricity_dt(void);
double cxceresinclination_dt(void);
double cxcereslongitude_dt(void);
double cxceresperiapsis_dt(void);
double cxceresascending_dt(void);
double cxerisorbit(void);
double cxeriseccentricity(void);
double cxerisinclination(void);
double cxerislongitude(void);
double cxerisperiapsis(void);
double cxerisascending(void);
double cxerisorbit_dt(void);
double cxeriseccentricity_dt(void);
double cxerisinclination_dt(void);
double cxerislongitude_dt(void);
double cxerisperiapsis_dt(void);
double cxerisascending_dt(void);
double cxmakemakeorbit(void);
double cxmakemakeeccentricity(void);
double cxmakemakeinclination(void);
double cxmakemakelongitude(void);
double cxmakemakeperiapsis(void);
double cxmakemakeascending(void);
double cxmakemakeorbit_dt(void);
double cxmakemakeeccentricity_dt(void);
double cxmakemakeinclination_dt(void);
double cxmakemakelongitude_dt(void);
double cxmakemakeperiapsis_dt(void);
double cxmakemakeascending_dt(void);
double cxhaumeaorbit(void);
double cxhaumeaeccentricity(void);
double cxhaumeainclination(void);
double cxhaumealongitude(void);
double cxhaumeaperiapsis(void);
double cxhaumeaascending(void);
double cxhaumeaorbit_dt(void);
double cxhaumeaeccentricity_dt(void);
double cxhaumeainclination_dt(void);
double cxhaumealongitude_dt(void);
double cxhaumeaperiapsis_dt(void);
double cxhaumeaascending_dt(void);
#include <stdbool.h>
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <time.h>
#include <sys/time.h>
double timee(void);
#include "Kw.h"
#include "Kwelements.h"
#define EARTHSIDEREALDAY (DAY / 1.002737909350795)
#define EARTHSTELLARDAY (DAY / 1.00273781191135448)
#define EARTHTROPICALYEAR (365.242190402 * DAY)
#define EARTHSIDEREALYEAR (365.256363004 * DAY)
#define EARTHANOMALISTICYEAR (365.259636 * DAY)
#define SIDEREALYEAR (EARTHSIDEREALYEAR)
#define ANOMALISTICYEAR (EARTHANOMALISTICYEAR)
#define TROPICALYEAR (EARTHTROPICALYEAR)
#define STELLARDAY (EARTHSTELLARDAY)
#define SIDEREALDAY (EARTHSIDEREALDAY)
#define SUNGMNASA (1.32712440018E+20 * UNITGM)
#define SUNGMIERS (1.32712442099E+20 * UNITGM)
#define SUNGM (SUNGMNASA)
#define SUNYEAR (0.0 * DAY)
#define SUNDAY (24.47 * DAY)
#define SUNFLATNESS (9.0E-6)
#define SUN_A (6.957E+8 * METER)
#define SUN_C (SUN_A)
#define SUN_B (SUN_A * (1.0 - SUNFLATNESS))
#define SUNRADIUS (0.333333333333333 * (SUN_A + SUN_B + SUN_C))
#define SUNESCAPE (sqrt(2 * SUNGM / SUNRADIUS))
#define SUNOBLATENESS (sqrt(SUNFLATNESS * (2.0 - SUNFLATNESS)))
#define SUNGRAVITY (SUNGM / (SUNRADIUS * SUNRADIUS))
#define SUNMASS (SUNGM / GRAVITATION)
#define SUNVOLUME \
      (2.0 * TAU / 3.0 * SUNRADIUS * SUNRADIUS * SUNRADIUS)
#define SUNDENSITY (SUNMASS / SUNVOLUME)
#define MERCURYGM (2.2032E+13 * UNITGM)
#define MERCURYYEAR (87.9691 * DAY)
#define MERCURYDAY (58.6462 * DAY)
#define MERCURYFLATNESS (0.0)
#define MERCURY_A (2.4397E+6 * METER)
#define MERCURY_C (MERCURY_A)
#define MERCURY_B (MERCURY_A * (1.0 - MERCURYFLATNESS))
#define MERCURYRADIUS \
      (0.333333333333333 * (MERCURY_A + MERCURY_B + MERCURY_C))
#define MERCURYESCAPE (sqrt(2 * MERCURYGM / MERCURYRADIUS))
#define MERCURYOBLATENESS \
      (sqrt(MERCURYFLATNESS * (2.0 - MERCURYFLATNESS)))
#define MERCURYGRAVITY \
      (MERCURYGM / (MERCURYRADIUS * MERCURYRADIUS))
#define MERCURYMASS (MERCURYGM / GRAVITATION)
#define MERCURYVOLUME \
      (2.0 * TAU / 3.0 * MERCURYRADIUS * MERCURYRADIUS *\
            MERCURYRADIUS)
#define MERCURYDENSITY (MERCURYMASS / MERCURYVOLUME)
#define VENUSGM (3.24859E+14 * UNITGM)
#define VENUSYEAR (224.701 * DAY)
#define VENUSDAY (- 243.018 * DAY)
#define VENUSFLATNESS (0.0)
#define VENUS_A (6.0518E+6 * METER)
#define VENUS_C (VENUS_A)
#define VENUS_B (VENUS_A * (1.0 - VENUSFLATNESS))
#define VENUSRADIUS \
      (0.333333333333333 * (VENUS_A + VENUS_B + VENUS_C))
#define VENUSESCAPE (sqrt(2 * VENUSGM / VENUSRADIUS))
#define VENUSOBLATENESS \
      (sqrt(VENUSFLATNESS * (2.0 - VENUSFLATNESS)))
#define VENUSGRAVITY (VENUSGM / (VENUSRADIUS * VENUSRADIUS))
#define VENUSMASS (VENUSGM / GRAVITATION)
#define VENUSVOLUME \
      (2.0 * TAU / 3.0 * VENUSRADIUS * VENUSRADIUS * VENUSRADIUS)
#define VENUSDENSITY (VENUSMASS / VENUSVOLUME)
#define EARTHGM (3.986004418E+14 * UNITGM)
#define EARTHYEAR (EARTHSIDEREALYEAR)
#define EARTHDAY (EARTHSTELLARDAY)
#define EARTHFLATNESS (1.0 / 298.257223563)
#define EARTH_A (6.378137E+6 * METER)
#define EARTH_C (EARTH_A)
#define EARTH_B (EARTH_A * (1.0 - EARTHFLATNESS))
#define EARTHRADIUS \
      (0.333333333333333 * (EARTH_A + EARTH_B + EARTH_C))
#define EARTHESCAPE (sqrt(2 * EARTHGM / EARTHRADIUS))
#define EARTHOBLATENESS \
      (sqrt(EARTHFLATNESS * (2.0 - EARTHFLATNESS)))
#define EARTHGRAVITY (EARTHGM / (EARTHRADIUS * EARTHRADIUS))
#define EARTHMASS (EARTHGM / GRAVITATION)
#define EARTHVOLUME \
      (2.0 * TAU / 3.0 * EARTHRADIUS * EARTHRADIUS * EARTHRADIUS)
#define EARTHDENSITY (EARTHMASS / EARTHVOLUME)
#define EARTHPRECESSION (50.28792 * ARCSEC / JYEAR)
#define EARTHTHETA_0 (0.7790572732640 * TURN)
#define MARSGM (4.282837E+13 * UNITGM)
#define MARSYEAR (686.971 * DAY)
#define MARSDAY (1.02595676 * DAY)
#define MARSFLATNESS (1.0 / 169.81)
#define MARS_A (3.3962E+6 * METER)
#define MARS_C (MARS_A)
#define MARS_B (MARS_A * (1.0 - MARSFLATNESS))
#define MARSRADIUS \
      (0.333333333333333 * (MARS_A + MARS_B + MARS_C))
#define MARSESCAPE (sqrt(2 * MARSGM / MARSRADIUS))
#define MARSOBLATENESS \
      (sqrt(MARSFLATNESS * (2.0 - MARSFLATNESS)))
#define MARSGRAVITY (MARSGM / (MARSRADIUS * MARSRADIUS))
#define MARSMASS (MARSGM / GRAVITATION)
#define MARSVOLUME \
      (2.0 * TAU / 3.0 * MARSRADIUS * MARSRADIUS * MARSRADIUS)
#define MARSDENSITY (MARSMASS / MARSVOLUME)
#define JUPITERGM (1.26686534E+17 * UNITGM)
#define JUPITERYEAR (4332.59 * DAY)
#define JUPITERDAY (0.41354 * DAY)
#define JUPITERFLATNESS (1.0 / 15.4144028)
#define JUPITER_A (7.1492E+7 * METER)
#define JUPITER_C (JUPITER_A)
#define JUPITER_B (JUPITER_A * (1.0 - JUPITERFLATNESS))
#define JUPITERRADIUS \
      (0.333333333333333 * (JUPITER_A + JUPITER_B + JUPITER_C))
#define JUPITERESCAPE (sqrt(2 * JUPITERGM / JUPITERRADIUS))
#define JUPITEROBLATENESS \
      (sqrt(JUPITERFLATNESS * (2.0 - JUPITERFLATNESS)))
#define JUPITERGRAVITY \
      (JUPITERGM / (JUPITERRADIUS * JUPITERRADIUS))
#define JUPITERMASS (JUPITERGM / GRAVITATION)
#define JUPITERVOLUME \
      (2.0 * TAU / 3.0 * JUPITERRADIUS * JUPITERRADIUS *\
            JUPITERRADIUS)
#define JUPITERDENSITY (JUPITERMASS / JUPITERVOLUME)
#define SATURNGM (3.7931187E+16 * UNITGM)
#define SATURNYEAR (10759.22 * DAY)
#define SATURNDAY (0.44401 * DAY)
#define SATURNFLATNESS (1.0 / 10.208)
#define SATURN_A (6.0268E+7 * METER)
#define SATURN_C (SATURN_A)
#define SATURN_B (SATURN_A * (1.0 - SATURNFLATNESS))
#define SATURNRADIUS \
      (0.333333333333333 * (SATURN_A + SATURN_B + SATURN_C))
#define SATURNESCAPE (sqrt(2 * SATURNGM / SATURNRADIUS))
#define SATURNOBLATENESS \
      (sqrt(SATURNFLATNESS * (2.0 - SATURNFLATNESS)))
#define SATURNGRAVITY (SATURNGM / (SATURNRADIUS * SATURNRADIUS))
#define SATURNMASS (SATURNGM / GRAVITATION)
#define SATURNVOLUME \
      (2.0 * TAU / 3.0 * SATURNRADIUS * SATURNRADIUS *\
            SATURNRADIUS)
#define SATURNDENSITY (SATURNMASS / SATURNVOLUME)
#define URANUSGM (5.793939E+15 * UNITGM)
#define URANUSYEAR (30688.5 * DAY)
#define URANUSDAY (- 0.71833 * DAY)
#define URANUSFLATNESS (1.0 / 43.61604)
#define URANUS_A (2.5559E+7 * METER)
#define URANUS_C (URANUS_A)
#define URANUS_B (URANUS_A * (1.0 - URANUSFLATNESS))
#define URANUSRADIUS \
      (0.333333333333333 * (URANUS_A + URANUS_B + URANUS_C))
#define URANUSESCAPE (sqrt(2 * URANUSGM / URANUSRADIUS))
#define URANUSOBLATENESS \
      (sqrt(URANUSFLATNESS * (2.0 - URANUSFLATNESS)))
#define URANUSGRAVITY (URANUSGM / (URANUSRADIUS * URANUSRADIUS))
#define URANUSMASS (URANUSGM / GRAVITATION)
#define URANUSVOLUME \
      (2.0 * TAU / 3.0 * URANUSRADIUS * URANUSRADIUS *\
            URANUSRADIUS)
#define URANUSDENSITY (URANUSMASS / URANUSVOLUME)
#define NEPTUNEGM (6.836529E+15 * UNITGM)
#define NEPTUNEYEAR (6.0182E+4 * DAY)
#define NEPTUNEDAY (0.67125 * DAY)
#define NEPTUNEFLATNESS (1.0 / 58.54373)
#define NEPTUNE_A (2.4764E+7 * METER)
#define NEPTUNE_C (NEPTUNE_A)
#define NEPTUNE_B (NEPTUNE_A * (1.0 - NEPTUNEFLATNESS))
#define NEPTUNERADIUS \
      (0.333333333333333 * (NEPTUNE_A + NEPTUNE_B + NEPTUNE_C))
#define NEPTUNEESCAPE (sqrt(2 * NEPTUNEGM / NEPTUNERADIUS))
#define NEPTUNEOBLATENESS \
      (sqrt(NEPTUNEFLATNESS * (2.0 - NEPTUNEFLATNESS)))
#define NEPTUNEGRAVITY \
      (NEPTUNEGM / (NEPTUNERADIUS * NEPTUNERADIUS))
#define NEPTUNEMASS (NEPTUNEGM / GRAVITATION)
#define NEPTUNEVOLUME \
      (2.0 * TAU / 3.0 * NEPTUNERADIUS * NEPTUNERADIUS *\
            NEPTUNERADIUS)
#define NEPTUNEDENSITY (NEPTUNEMASS / NEPTUNEVOLUME)
#define PLUTOGM (8.71E+11 * UNITGM)
#define PLUTOYEAR (9.056E+4 * DAY)
#define PLUTODAY (6.38723 * DAY)
#define PLUTOFLATNESS (0.0)
#define PLUTO_A (1.1899E+6 * METER)
#define PLUTO_C (PLUTO_A)
#define PLUTO_B (PLUTO_A * (1.0 - PLUTOFLATNESS))
#define PLUTORADIUS \
      (0.333333333333333 * (PLUTO_A + PLUTO_B + PLUTO_C))
#define PLUTOESCAPE (sqrt(2 * PLUTOGM / PLUTORADIUS))
#define PLUTOOBLATENESS \
      (sqrt(PLUTOFLATNESS * (2.0 - PLUTOFLATNESS)))
#define PLUTOGRAVITY (PLUTOGM / (PLUTORADIUS * PLUTORADIUS))
#define PLUTOMASS (PLUTOGM / GRAVITATION)
#define PLUTOVOLUME \
      (2.0 * TAU / 3.0 * PLUTORADIUS * PLUTORADIUS * PLUTORADIUS)
#define PLUTODENSITY (PLUTOMASS / PLUTOVOLUME)
#define MOONGM (4.9048695E+12 * UNITGM)
#define MOONYEAR (27.32166155 * DAY)
#define MOONDAY (27.321661 * DAY)
#define MOONFLATNESS (1.0 / 827.667)
#define MOON_A (1.7381E+6 * METER)
#define MOON_C (MOON_A)
#define MOON_B (MOON_A * (1.0 - MOONFLATNESS))
#define MOONRADIUS \
      (0.333333333333333 * (MOON_A + MOON_B + MOON_C))
#define MOONESCAPE (sqrt(2 * MOONGM / MOONRADIUS))
#define MOONOBLATENESS \
      (sqrt(MOONFLATNESS * (2.0 - MOONFLATNESS)))
#define MOONGRAVITY (MOONGM / (MOONRADIUS * MOONRADIUS))
#define MOONMASS (MOONGM / GRAVITATION)
#define MOONVOLUME \
      (2.0 * TAU / 3.0 * MOONRADIUS * MOONRADIUS * MOONRADIUS)
#define MOONDENSITY (MOONMASS / MOONVOLUME)
#define MOONORBIT (3.843999E+8 * METER)
#define MOONECCENTRICITY (0.0549)
#define MOONINCLINATION (5.415 * ARCDEG)
#define CERESGM (6.26325E+10 * UNITGM)
#define CERESYEAR (1681.63 * DAY)
#define CERESDAY (9.074170 * HOUR)
#define CERESFLATNESS (1.0 / 13.0432)
#define CERES_A (4.826E+5 * METER)
#define CERES_C (4.806E+5 * METER)
#define CERES_B (CERES_A * (1.0 - CERESFLATNESS))
#define CERESRADIUS \
      (0.333333333333333 * (CERES_A + CERES_B + CERES_C))
#define CERESESCAPE (sqrt(2 * CERESGM / CERESRADIUS))
#define CERESOBLATENESS \
      (sqrt(CERESFLATNESS * (2.0 - CERESFLATNESS)))
#define CERESGRAVITY (CERESGM / (CERESRADIUS * CERESRADIUS))
#define CERESMASS (CERESGM / GRAVITATION)
#define CERESVOLUME \
      (2.0 * TAU / 3.0 * CERESRADIUS * CERESRADIUS * CERESRADIUS)
#define CERESDENSITY (CERESMASS / CERESVOLUME)
#define ERISGM (1.108E+12 * UNITGM)
#define ERISYEAR (2.0383E+5 * DAY)
#define ERISDAY (25.9 * HOUR)
#define ERISFLATNESS (0.0)
#define ERIS_A (1.163E+6 * METER)
#define ERIS_C (ERIS_A)
#define ERIS_B (ERIS_A * (1.0 - ERISFLATNESS))
#define ERISRADIUS \
      (0.333333333333333 * (ERIS_A + ERIS_B + ERIS_C))
#define ERISESCAPE (sqrt(2 * ERISGM / ERISRADIUS))
#define ERISOBLATENESS \
      (sqrt(ERISFLATNESS * (2.0 - ERISFLATNESS)))
#define ERISGRAVITY (ERISGM / (ERISRADIUS * ERISRADIUS))
#define ERISMASS (ERISGM / GRAVITATION)
#define ERISVOLUME \
      (2.0 * TAU / 3.0 * ERISRADIUS * ERISRADIUS * ERISRADIUS)
#define ERISDENSITY (ERISMASS / ERISVOLUME)
#define MAKEMAKEGM (2.9366E+11 * UNITGM)
#define MAKEMAKEYEAR (1.12897E+5 * DAY)
#define MAKEMAKEDAY (7.771 * HOUR)
#define MAKEMAKEFLATNESS (1.0 / 30.7917)
#define MAKEMAKE_A (7.39E+5 * METER)
#define MAKEMAKE_C (MAKEMAKE_A)
#define MAKEMAKE_B (MAKEMAKE_A * (1.0 - MAKEMAKEFLATNESS))
#define MAKEMAKERADIUS \
      (0.333333333333333 * (MAKEMAKE_A + MAKEMAKE_B +\
            MAKEMAKE_C))
#define MAKEMAKEESCAPE (sqrt(2 * MAKEMAKEGM / MAKEMAKERADIUS))
#define MAKEMAKEOBLATENESS \
      (sqrt(MAKEMAKEFLATNESS * (2.0 - MAKEMAKEFLATNESS)))
#define MAKEMAKEGRAVITY \
      (MAKEMAKEGM / (MAKEMAKERADIUS * MAKEMAKERADIUS))
#define MAKEMAKEMASS (MAKEMAKEGM / GRAVITATION)
#define MAKEMAKEVOLUME \
      (2.0 * TAU / 3.0 * MAKEMAKERADIUS * MAKEMAKERADIUS *\
            MAKEMAKERADIUS)
#define MAKEMAKEDENSITY (MAKEMAKEMASS / MAKEMAKEVOLUME)
#define HAUMEAGM (2.674E+11 * UNITGM)
#define HAUMEAYEAR (1.03774E+5 * DAY)
#define HAUMEADAY (3.9155 * HOUR)
#define HAUMEAFLATNESS (1.0 / 1.96115)
#define HAUMEA_A (1.161E+6 * METER)
#define HAUMEA_C (8.52E+5 * METER)
#define HAUMEA_B (HAUMEA_A * (1.0 - HAUMEAFLATNESS))
#define HAUMEARADIUS \
      (0.333333333333333 * (HAUMEA_A + HAUMEA_B + HAUMEA_C))
#define HAUMEAESCAPE (sqrt(2 * HAUMEAGM / HAUMEARADIUS))
#define HAUMEAOBLATENESS \
      (sqrt(HAUMEAFLATNESS * (2.0 - HAUMEAFLATNESS)))
#define HAUMEAGRAVITY (HAUMEAGM / (HAUMEARADIUS * HAUMEARADIUS))
#define HAUMEAMASS (HAUMEAGM / GRAVITATION)
#define HAUMEAVOLUME \
      (2.0 * TAU / 3.0 * HAUMEARADIUS * HAUMEARADIUS *\
            HAUMEARADIUS)
#define HAUMEADENSITY (HAUMEAMASS / HAUMEAVOLUME)
#define SUNORBIT (0.0 * AU)
#define SUNECCENTRICITY (0.0)
#define SUNINCLINATION (0.0 * ARCDEG)
#define SUNLONGITUDE (0.0 * ARCDEG)
#define SUNPERIAPSIS (0.0 * ARCDEG)
#define SUNASCENDING (0.0 * ARCDEG)
#define SUNORBIT_DT (0.0 * AU / JC)
#define SUNECCENTRICITY_DT (0.0 / JC)
#define SUNINCLINATION_DT (0.0 * ARCDEG / JC)
#define SUNLONGITUDE_DT (0.0 * ARCDEG / JC)
#define SUNPERIAPSIS_DT (0.0 * ARCDEG / JC)
#define SUNASCENDING_DT (0.0 * ARCDEG / JC)
#define EARTHORBIT (1.00000261 * AU)
#define EARTHECCENTRICITY (0.01671123)
#define EARTHINCLINATION (359.99998469 * ARCDEG)
#define EARTHLONGITUDE (100.46457166 * ARCDEG)
#define EARTHPERIAPSIS (102.93768193 * ARCDEG)
#define EARTHASCENDING (0.0 * ARCDEG)
#define EARTHORBIT_DT (0.00000562 * AU / JC)
#define EARTHECCENTRICITY_DT (- 0.00004392 / JC)
#define EARTHINCLINATION_DT (- 0.01294668 * ARCDEG / JC)
#define EARTHLONGITUDE_DT (35999.37244981 * ARCDEG / JC)
#define EARTHPERIAPSIS_DT (0.32327364 * ARCDEG / JC)
#define EARTHASCENDING_DT (0.0 * ARCDEG / JC)
#define MERCURYORBIT (0.38709927 * AU)
#define MERCURYECCENTRICITY (0.20563593)
#define MERCURYINCLINATION (7.00497902 * ARCDEG)
#define MERCURYLONGITUDE (252.25032350 * ARCDEG)
#define MERCURYPERIAPSIS (77.45779628 * ARCDEG)
#define MERCURYASCENDING (48.33076593 * ARCDEG)
#define MERCURYORBIT_DT (0.00000037 * AU / JC)
#define MERCURYECCENTRICITY_DT (0.00001906 / JC)
#define MERCURYINCLINATION_DT (- 0.00594749 * ARCDEG / JC)
#define MERCURYLONGITUDE_DT (149472.67411175 * ARCDEG / JC)
#define MERCURYPERIAPSIS_DT (0.16047689 * ARCDEG / JC)
#define MERCURYASCENDING_DT (- 0.12534081 * ARCDEG / JC)
#define VENUSORBIT (0.72333566 * AU)
#define VENUSECCENTRICITY (0.00677672)
#define VENUSINCLINATION (3.39467605 * ARCDEG)
#define VENUSLONGITUDE (181.97909950 * ARCDEG)
#define VENUSPERIAPSIS (131.60246718 * ARCDEG)
#define VENUSASCENDING (76.67984255 * ARCDEG)
#define VENUSORBIT_DT (0.00000390 * AU / JC)
#define VENUSECCENTRICITY_DT (- 0.00004107 / JC)
#define VENUSINCLINATION_DT (- 0.00078890 * ARCDEG / JC)
#define VENUSLONGITUDE_DT (58517.81538729 * ARCDEG / JC)
#define VENUSPERIAPSIS_DT (0.00268329 * ARCDEG / JC)
#define VENUSASCENDING_DT (- 0.27769418 * ARCDEG / JC)
#define MARSORBIT (1.52371034 * AU)
#define MARSECCENTRICITY (0.09339410)
#define MARSINCLINATION (1.84969142 * ARCDEG)
#define MARSLONGITUDE (355.44656795 * ARCDEG)
#define MARSPERIAPSIS (336.05637041 * ARCDEG)
#define MARSASCENDING (49.55953891 * ARCDEG)
#define MARSORBIT_DT (0.00001847 * AU / JC)
#define MARSECCENTRICITY_DT (0.00007882 / JC)
#define MARSINCLINATION_DT (- 0.00813131 * ARCDEG / JC)
#define MARSLONGITUDE_DT (19140.30268499 * ARCDEG / JC)
#define MARSPERIAPSIS_DT (0.44441088 * ARCDEG / JC)
#define MARSASCENDING_DT (- 0.29257343 * ARCDEG / JC)
#define JUPITERORBIT (5.20288700 * AU)
#define JUPITERECCENTRICITY (0.04838624)
#define JUPITERINCLINATION (1.30439695 * ARCDEG)
#define JUPITERLONGITUDE (34.39644051 * ARCDEG)
#define JUPITERPERIAPSIS (14.72847983 * ARCDEG)
#define JUPITERASCENDING (100.47390909 * ARCDEG)
#define JUPITERORBIT_DT (- 0.00011607 * AU / JC)
#define JUPITERECCENTRICITY_DT (- 0.00013253 / JC)
#define JUPITERINCLINATION_DT (- 0.00183714 * ARCDEG / JC)
#define JUPITERLONGITUDE_DT (3034.74612775 * ARCDEG / JC)
#define JUPITERPERIAPSIS_DT (0.21252668 * ARCDEG / JC)
#define JUPITERASCENDING_DT (0.20469106 * ARCDEG / JC)
#define SATURNORBIT (9.53667594 * AU)
#define SATURNECCENTRICITY (0.05386179)
#define SATURNINCLINATION (2.48599187 * ARCDEG)
#define SATURNLONGITUDE (49.95424423 * ARCDEG)
#define SATURNPERIAPSIS (92.59887831 * ARCDEG)
#define SATURNASCENDING (113.66242448 * ARCDEG)
#define SATURNORBIT_DT (- 0.00125060 * AU / JC)
#define SATURNECCENTRICITY_DT (- 0.00050991 / JC)
#define SATURNINCLINATION_DT (0.00193609 * ARCDEG / JC)
#define SATURNLONGITUDE_DT (1222.49362201 * ARCDEG / JC)
#define SATURNPERIAPSIS_DT (- 0.41897216 * ARCDEG / JC)
#define SATURNASCENDING_DT (- 0.28867794 * ARCDEG / JC)
#define URANUSORBIT (19.18916464 * AU)
#define URANUSECCENTRICITY (0.04725744)
#define URANUSINCLINATION (0.77263783 * ARCDEG)
#define URANUSLONGITUDE (313.23810451 * ARCDEG)
#define URANUSPERIAPSIS (170.95427630 * ARCDEG)
#define URANUSASCENDING (74.01692503 * ARCDEG)
#define URANUSORBIT_DT (- 0.00196176 * AU / JC)
#define URANUSECCENTRICITY_DT (- 0.00004397 / JC)
#define URANUSINCLINATION_DT (- 0.00242939 * ARCDEG / JC)
#define URANUSLONGITUDE_DT (428.48202785 * ARCDEG / JC)
#define URANUSPERIAPSIS_DT (0.40805281 * ARCDEG / JC)
#define URANUSASCENDING_DT (0.04240589 * ARCDEG / JC)
#define NEPTUNEORBIT (30.06992276 * AU)
#define NEPTUNEECCENTRICITY (0.00859048)
#define NEPTUNEINCLINATION (1.77004347 * ARCDEG)
#define NEPTUNELONGITUDE (304.87997031 * ARCDEG)
#define NEPTUNEPERIAPSIS (44.96476227 * ARCDEG)
#define NEPTUNEASCENDING (131.78422574 * ARCDEG)
#define NEPTUNEORBIT_DT (0.00026291 * AU / JC)
#define NEPTUNEECCENTRICITY_DT (0.00005105 / JC)
#define NEPTUNEINCLINATION_DT (0.00035372 * ARCDEG / JC)
#define NEPTUNELONGITUDE_DT (218.45945325 * ARCDEG / JC)
#define NEPTUNEPERIAPSIS_DT (- 0.32241464 * ARCDEG / JC)
#define NEPTUNEASCENDING_DT (- 0.00508664 * ARCDEG / JC)
#define PLUTOORBIT (39.48211675 * AU)
#define PLUTOECCENTRICITY (0.24882730)
#define PLUTOINCLINATION (17.14001206 * ARCDEG)
#define PLUTOLONGITUDE (238.92903833 * ARCDEG)
#define PLUTOPERIAPSIS (224.06891629 * ARCDEG)
#define PLUTOASCENDING (110.30393684 * ARCDEG)
#define PLUTOORBIT_DT (- 0.00031596 * AU / JC)
#define PLUTOECCENTRICITY_DT (0.00005170 / JC)
#define PLUTOINCLINATION_DT (0.00004818 * ARCDEG / JC)
#define PLUTOLONGITUDE_DT (145.20780515 * ARCDEG / JC)
#define PLUTOPERIAPSIS_DT (- 0.04062942 * ARCDEG / JC)
#define PLUTOASCENDING_DT (- 0.01183482 * ARCDEG / JC)
#define CERESORBIT (2.76740933 * AU)
#define CERESECCENTRICITY (0.07560729)
#define CERESINCLINATION (10.59321706 * ARCDEG)
#define CERESLONGITUDE (102.82668 * ARCDEG)
#define CERESPERIAPSIS (73.023742647 * ARCDEG)
#define CERESASCENDING (80.308882612359 * ARCDEG)
#define CERESORBIT_DT (0.0 * AU / JC)
#define CERESECCENTRICITY_DT (0.0 / JC)
#define CERESINCLINATION_DT (0.0 * ARCDEG / JC)
#define CERESLONGITUDE_DT (0.0 * ARCDEG / JC)
#define CERESPERIAPSIS_DT (0.0 * ARCDEG / JC)
#define CERESASCENDING_DT (0.0 * ARCDEG / JC)
#define ERISORBIT (67.781 * AU)
#define ERISECCENTRICITY (0.44068)
#define ERISINCLINATION (44.0445 * ARCDEG)
#define ERISLONGITUDE (32.4926663 * ARCDEG)
#define ERISPERIAPSIS (151.60371236817 * ARCDEG)
#define ERISASCENDING (35.87992471211 * ARCDEG)
#define ERISORBIT_DT (0.0 * AU / JC)
#define ERISECCENTRICITY_DT (0.0 / JC)
#define ERISINCLINATION_DT (0.0 * ARCDEG / JC)
#define ERISLONGITUDE_DT (0.0 * ARCDEG / JC)
#define ERISPERIAPSIS_DT (0.0 * ARCDEG / JC)
#define ERISASCENDING_DT (0.0 * ARCDEG / JC)
#define MAKEMAKEORBIT (45.715 * AU)
#define MAKEMAKEECCENTRICITY (0.15586)
#define MAKEMAKEINCLINATION (29.00685 * ARCDEG)
#define MAKEMAKELONGITUDE (177.2966805 * ARCDEG)
#define MAKEMAKEPERIAPSIS (295.642772002 * ARCDEG)
#define MAKEMAKEASCENDING (79.616805978978 * ARCDEG)
#define MAKEMAKEORBIT_DT (0.0 * AU / JC)
#define MAKEMAKEECCENTRICITY_DT (0.0 / JC)
#define MAKEMAKEINCLINATION_DT (0.0 * ARCDEG / JC)
#define MAKEMAKELONGITUDE_DT (0.0 * ARCDEG / JC)
#define MAKEMAKEPERIAPSIS_DT (0.0 * ARCDEG / JC)
#define MAKEMAKEASCENDING_DT (0.0 * ARCDEG / JC)
#define HAUMEAORBIT (43.218 * AU)
#define HAUMEAECCENTRICITY (0.19126)
#define HAUMEAINCLINATION (28.19 * ARCDEG)
#define HAUMEALONGITUDE (215.687315 * ARCDEG)
#define HAUMEAPERIAPSIS (238.69440821915 * ARCDEG)
#define HAUMEAASCENDING (122.01840302632 * ARCDEG)
#define HAUMEAORBIT_DT (0.0 * AU / JC)
#define HAUMEAECCENTRICITY_DT (0.0 / JC)
#define HAUMEAINCLINATION_DT (0.0 * ARCDEG / JC)
#define HAUMEALONGITUDE_DT (0.0 * ARCDEG / JC)
#define HAUMEAPERIAPSIS_DT (0.0 * ARCDEG / JC)
#define HAUMEAASCENDING_DT (0.0 * ARCDEG / JC)
double margot(double pmass
      , double porbit);
double sternlevison(double pmass
      , double porbit);
long pl(long plnt);
double plsettime(double jtwokdate);
double pl_gm(long plnt);
double plgm(void);
double pl_year(long plnt);
double plyear(void);
double pl_day(long plnt);
double plday(void);
double pl_flatness(long plnt);
double plflatness(void);
double pl_a(long plnt);
double pla(void);
double pl_c(long plnt);
double plc(void);
double pl_orbit(long plnt);
double plorbit(void);
double pl_eccentricity(long plnt);
double pleccentricity(void);
double pl_inclination(long plnt);
double plinclination(void);
double pl_longitude(long plnt);
double pllongitude(void);
double pl_periapsis(long plnt);
double plperiapsis(void);
double pl_ascending(long plnt);
double plascending(void);
double pl_mass(long plnt);
double plmass(void);
double pl_b(long plnt);
double plb(void);
double pl_radius(long plnt);
double plradius(void);
double pl_gravity(long plnt);
double plgravity(void);
double pl_meananomaly(long plnt);
double plmeananomaly(void);
double pl_escape(long plnt);
double plescape(void);
double pl_synodic(long plnt);
double plsynodic(void);
double pl_volume(long plnt);
double plvolume(void);
double pl_density(long plnt);
double pldensity(void);
double pl_argument(long plnt);
double plargument(void);
double pl_margot(long plnt);
double plmargot(void);
double pl_sternlevison(long plnt);
double plsternlevison(void);
double pl_perihelion(long plnt);
double plperihelion(void);
double pl_aphelion(long plnt);
double plaphelion(void);
double eccentric_anomaly(double mean_ano_rad
      , double eccen);
double pl_eccentricanomaly(long plnt);
double pleccentricanomaly(void);
double pl_heliocentric(long plnt
      , double jtwok);
double plhelio(long indd);
double plgeo(long indd);
long pl_name(long plnt);
double plname(void);
double earth_radius(double lat_deg);
double earth_tropicalyear(double jtwokdate);
double earth_distance(double lata_deg
      , double lona_deg
      , double latb_deg
      , double lonb_deg);
double plaradius(double lat_deg);
double pl_aradius(long plnt
      , double lat_deg);
double earth_obliquity(double jtwok);
double earth_gravity(double lat_deg);
double earth_gravity_height(double lat_deg
      , double height_m);
double isa_temp(double height_m);
double isa_pres(double height_m);
double isa_dens(double height_m);
double vin_distance(double lata_deg
      , double lona_deg
      , double latb_deg
      , double lonb_deg
      , double *ret_bearings_arr_p);
double vin_destination(double lata_deg
      , double lona_deg
      , double heading_deg
      , double dist_m
      , double *ret_dest_arr_p);
//  DDDDDDDDDDescription ---------------- kwplanets_description #
#define Kwplanets_DESCRIPTION \
   "   Kwplanets Constants: ANOMALISTICYEAR CERES_A CERES_B CER"\
   "ES_C CERESASCENDING CERESASCENDING_DT CERESDAY CERESDENSITY"\
   " CERESECCENTRICITY CERESECCENTRICITY_DT CERESESCAPE CERESFL"\
   "ATNESS CERESGM CERESGRAVITY CERESINCLINATION CERESINCLINATI"\
   "ON_DT CERESLONGITUDE CERESLONGITUDE_DT CERESMASS CERESOBLAT"\
   "ENESS CERESORBIT CERESORBIT_DT CERESPERIAPSIS CERESPERIAPSI"\
   "S_DT CERESRADIUS CERESVOLUME CERESYEAR EARTH_A EARTH_B EART"\
   "H_C EARTHANOMALISTICYEAR EARTHASCENDING EARTHASCENDING_DT E"\
   "ARTHDAY EARTHDENSITY EARTHECCENTRICITY EARTHECCENTRICITY_DT"\
   " EARTHESCAPE EARTHFLATNESS EARTHGM EARTHGRAVITY EARTHINCLIN"\
   "ATION EARTHINCLINATION_DT EARTHLONGITUDE EARTHLONGITUDE_DT "\
   "EARTHMASS EARTHOBLATENESS EARTHORBIT EARTHORBIT_DT EARTHPER"\
   "IAPSIS EARTHPERIAPSIS_DT EARTHPRECESSION EARTHRADIUS EARTHS"\
   "IDEREALDAY EARTHSIDEREALYEAR EARTHSTELLARDAY EARTHTHETA_0 E"\
   "ARTHTROPICALYEAR EARTHVOLUME EARTHYEAR ERIS_A ERIS_B ERIS_C"\
   " ERISASCENDING ERISASCENDING_DT ERISDAY ERISDENSITY ERISECC"\
   "ENTRICITY ERISECCENTRICITY_DT ERISESCAPE ERISFLATNESS ERISG"\
   "M ERISGRAVITY ERISINCLINATION ERISINCLINATION_DT ERISLONGIT"\
   "UDE ERISLONGITUDE_DT ERISMASS ERISOBLATENESS ERISORBIT ERIS"\
   "ORBIT_DT ERISPERIAPSIS ERISPERIAPSIS_DT ERISRADIUS ERISVOLU"\
   "ME ERISYEAR HAUMEA_A HAUMEA_B HAUMEA_C HAUMEAASCENDING HAUM"\
   "EAASCENDING_DT HAUMEADAY HAUMEADENSITY HAUMEAECCENTRICITY H"\
   "AUMEAECCENTRICITY_DT HAUMEAESCAPE HAUMEAFLATNESS HAUMEAGM H"\
   "AUMEAGRAVITY HAUMEAINCLINATION HAUMEAINCLINATION_DT HAUMEAL"\
   "ONGITUDE HAUMEALONGITUDE_DT HAUMEAMASS HAUMEAOBLATENESS HAU"\
   "MEAORBIT HAUMEAORBIT_DT HAUMEAPERIAPSIS HAUMEAPERIAPSIS_DT "\
   "HAUMEARADIUS HAUMEAVOLUME HAUMEAYEAR JUPITER_A JUPITER_B JU"\
   "PITER_C JUPITERASCENDING JUPITERASCENDING_DT JUPITERDAY JUP"\
   "ITERDENSITY JUPITERECCENTRICITY JUPITERECCENTRICITY_DT JUPI"\
   "TERESCAPE JUPITERFLATNESS JUPITERGM JUPITERGRAVITY JUPITERI"\
   "NCLINATION JUPITERINCLINATION_DT JUPITERLONGITUDE JUPITERLO"\
   "NGITUDE_DT JUPITERMASS JUPITEROBLATENESS JUPITERORBIT JUPIT"\
   "ERORBIT_DT JUPITERPERIAPSIS JUPITERPERIAPSIS_DT JUPITERRADI"\
   "US JUPITERVOLUME JUPITERYEAR MAKEMAKE_A MAKEMAKE_B MAKEMAKE"\
   "_C MAKEMAKEASCENDING MAKEMAKEASCENDING_DT MAKEMAKEDAY MAKEM"\
   "AKEDENSITY MAKEMAKEECCENTRICITY MAKEMAKEECCENTRICITY_DT MAK"\
   "EMAKEESCAPE MAKEMAKEFLATNESS MAKEMAKEGM MAKEMAKEGRAVITY MAK"\
   "EMAKEINCLINATION MAKEMAKEINCLINATION_DT MAKEMAKELONGITUDE M"\
   "AKEMAKELONGITUDE_DT MAKEMAKEMASS MAKEMAKEOBLATENESS MAKEMAK"\
   "EORBIT MAKEMAKEORBIT_DT MAKEMAKEPERIAPSIS MAKEMAKEPERIAPSIS"\
   "_DT MAKEMAKERADIUS MAKEMAKEVOLUME MAKEMAKEYEAR MARS_A MARS_"\
   "B MARS_C MARSASCENDING MARSASCENDING_DT MARSDAY MARSDENSITY"\
   " MARSECCENTRICITY MARSECCENTRICITY_DT MARSESCAPE MARSFLATNE"\
   "SS MARSGM MARSGRAVITY MARSINCLINATION MARSINCLINATION_DT MA"\
   "RSLONGITUDE MARSLONGITUDE_DT MARSMASS MARSOBLATENESS MARSOR"\
   "BIT MARSORBIT_DT MARSPERIAPSIS MARSPERIAPSIS_DT MARSRADIUS "\
   "MARSVOLUME MARSYEAR MERCURY_A MERCURY_B MERCURY_C MERCURYAS"\
   "CENDING MERCURYASCENDING_DT MERCURYDAY MERCURYDENSITY MERCU"\
   "RYECCENTRICITY MERCURYECCENTRICITY_DT MERCURYESCAPE MERCURY"\
   "FLATNESS MERCURYGM MERCURYGRAVITY MERCURYINCLINATION MERCUR"\
   "YINCLINATION_DT MERCURYLONGITUDE MERCURYLONGITUDE_DT MERCUR"\
   "YMASS MERCURYOBLATENESS MERCURYORBIT MERCURYORBIT_DT MERCUR"\
   "YPERIAPSIS MERCURYPERIAPSIS_DT MERCURYRADIUS MERCURYVOLUME "\
   "MERCURYYEAR MOON_A MOON_B MOON_C MOONDAY MOONDENSITY MOONEC"\
   "CENTRICITY MOONESCAPE MOONFLATNESS MOONGM MOONGRAVITY MOONI"\
   "NCLINATION MOONMASS MOONOBLATENESS MOONORBIT MOONRADIUS MOO"\
   "NVOLUME MOONYEAR NEPTUNE_A NEPTUNE_B NEPTUNE_C NEPTUNEASCEN"\
   "DING NEPTUNEASCENDING_DT NEPTUNEDAY NEPTUNEDENSITY NEPTUNEE"\
   "CCENTRICITY NEPTUNEECCENTRICITY_DT NEPTUNEESCAPE NEPTUNEFLA"\
   "TNESS NEPTUNEGM NEPTUNEGRAVITY NEPTUNEINCLINATION NEPTUNEIN"\
   "CLINATION_DT NEPTUNELONGITUDE NEPTUNELONGITUDE_DT NEPTUNEMA"\
   "SS NEPTUNEOBLATENESS NEPTUNEORBIT NEPTUNEORBIT_DT NEPTUNEPE"\
   "RIAPSIS NEPTUNEPERIAPSIS_DT NEPTUNERADIUS NEPTUNEVOLUME NEP"\
   "TUNEYEAR PLUTO_A PLUTO_B PLUTO_C PLUTOASCENDING PLUTOASCEND"\
   "ING_DT PLUTODAY PLUTODENSITY PLUTOECCENTRICITY PLUTOECCENTR"\
   "ICITY_DT PLUTOESCAPE PLUTOFLATNESS PLUTOGM PLUTOGRAVITY PLU"\
   "TOINCLINATION PLUTOINCLINATION_DT PLUTOLONGITUDE PLUTOLONGI"\
   "TUDE_DT PLUTOMASS PLUTOOBLATENESS PLUTOORBIT PLUTOORBIT_DT "\
   "PLUTOPERIAPSIS PLUTOPERIAPSIS_DT PLUTORADIUS PLUTOVOLUME PL"\
   "UTOYEAR SATURN_A SATURN_B SATURN_C SATURNASCENDING SATURNAS"\
   "CENDING_DT SATURNDAY SATURNDENSITY SATURNECCENTRICITY SATUR"\
   "NECCENTRICITY_DT SATURNESCAPE SATURNFLATNESS SATURNGM SATUR"\
   "NGRAVITY SATURNINCLINATION SATURNINCLINATION_DT SATURNLONGI"\
   "TUDE SATURNLONGITUDE_DT SATURNMASS SATURNOBLATENESS SATURNO"\
   "RBIT SATURNORBIT_DT SATURNPERIAPSIS SATURNPERIAPSIS_DT SATU"\
   "RNRADIUS SATURNVOLUME SATURNYEAR SIDEREALDAY SIDEREALYEAR S"\
   "TELLARDAY SUN_A SUN_B SUN_C SUNASCENDING SUNASCENDING_DT SU"\
   "NDAY SUNDENSITY SUNECCENTRICITY SUNECCENTRICITY_DT SUNESCAP"\
   "E SUNFLATNESS SUNGM SUNGMIERS SUNGMNASA SUNGRAVITY SUNINCLI"\
   "NATION SUNINCLINATION_DT SUNLONGITUDE SUNLONGITUDE_DT SUNMA"\
   "SS SUNOBLATENESS SUNORBIT SUNORBIT_DT SUNPERIAPSIS SUNPERIA"\
   "PSIS_DT SUNRADIUS SUNVOLUME SUNYEAR TROPICALYEAR URANUS_A U"\
   "RANUS_B URANUS_C URANUSASCENDING URANUSASCENDING_DT URANUSD"\
   "AY URANUSDENSITY URANUSECCENTRICITY URANUSECCENTRICITY_DT U"\
   "RANUSESCAPE URANUSFLATNESS URANUSGM URANUSGRAVITY URANUSINC"\
   "LINATION URANUSINCLINATION_DT URANUSLONGITUDE URANUSLONGITU"\
   "DE_DT URANUSMASS URANUSOBLATENESS URANUSORBIT URANUSORBIT_D"\
   "T URANUSPERIAPSIS URANUSPERIAPSIS_DT URANUSRADIUS URANUSVOL"\
   "UME URANUSYEAR VENUS_A VENUS_B VENUS_C VENUSASCENDING VENUS"\
   "ASCENDING_DT VENUSDAY VENUSDENSITY VENUSECCENTRICITY VENUSE"\
   "CCENTRICITY_DT VENUSESCAPE VENUSFLATNESS VENUSGM VENUSGRAVI"\
   "TY VENUSINCLINATION VENUSINCLINATION_DT VENUSLONGITUDE VENU"\
   "SLONGITUDE_DT VENUSMASS VENUSOBLATENESS VENUSORBIT VENUSORB"\
   "IT_DT VENUSPERIAPSIS VENUSPERIAPSIS_DT VENUSRADIUS VENUSVOL"\
   "UME VENUSYEAR"\
   "\n"\
   "   Kwplanets 0-ary Functions: pla plaphelion plargument pla"\
   "scending plb plc plday pldensity pleccentricanomaly pleccen"\
   "tricity plescape plflatness plgm plgravity plinclination pl"\
   "longitude plmargot plmass plmeananomaly plname plorbit plpe"\
   "riapsis plperihelion plradius plsternlevison plsynodic plvo"\
   "lume plyear"\
   "\n"\
   "   Kwplanets 1-ary Functions: earth_gravity earth_obliquity"\
   " earth_radius earth_tropicalyear isa_dens isa_pres isa_temp"\
   " pl pl_a pl_aphelion pl_argument pl_ascending pl_b pl_c pl_"\
   "day pl_density pl_eccentricanomaly pl_eccentricity pl_escap"\
   "e pl_flatness pl_gm pl_gravity pl_inclination pl_longitude "\
   "pl_margot pl_mass pl_meananomaly pl_name pl_orbit pl_periap"\
   "sis pl_perihelion pl_radius pl_sternlevison pl_synodic pl_v"\
   "olume pl_year plaradius plgeo plhelio plsettime"\
   "\n"\
   "   Kwplanets 2-ary Functions: earth_gravity_height eccentri"\
   "c_anomaly margot pl_aradius pl_heliocentric sternlevison"\
   "\n"\
   "   Kwplanets 4-ary Functions: earth_distance"\
   "\n"\
   "   Kwplanets 5-ary Functions: vin_destination vin_distance"\
   "\n"
#define Kwplanets_DESC \
   "   Kwplanets Constants: ANOMALISTICYEAR CERES(_[ABC]|ASCEND"\
   "ING(_DT)?|D(AY|ENSITY)|E(CCENTRICITY(_DT)?|SCAPE)|FLATNESS|"\
   "G(M|RAVITY)|INCLINATION(_DT)?|LONGITUDE(_DT)?|MASS|O(BLATEN"\
   "ESS|RBIT(_DT)?)|PERIAPSIS(_DT)?|RADIUS|VOLUME|YEAR) EARTH(_"\
   "[ABC]|A(NOMALISTICYEAR|SCENDING(_DT)?)|D(AY|ENSITY)|E(CCENT"\
   "RICITY(_DT)?|SCAPE)|FLATNESS|G(M|RAVITY)|INCLINATION(_DT)?|"\
   "LONGITUDE(_DT)?|MASS|O(BLATENESS|RBIT(_DT)?)|P(ERIAPSIS(_DT"\
   ")?|RECESSION)|RADIUS|S(IDEREAL(DAY|YEAR)|TELLARDAY)|T(HETA_"\
   "0|ROPICALYEAR)|VOLUME|YEAR) ERIS(_[ABC]|ASCENDING(_DT)?|D(A"\
   "Y|ENSITY)|E(CCENTRICITY(_DT)?|SCAPE)|FLATNESS|G(M|RAVITY)|I"\
   "NCLINATION(_DT)?|LONGITUDE(_DT)?|MASS|O(BLATENESS|RBIT(_DT)"\
   "?)|PERIAPSIS(_DT)?|RADIUS|VOLUME|YEAR) HAUMEA(_[ABC]|ASCEND"\
   "ING(_DT)?|D(AY|ENSITY)|E(CCENTRICITY(_DT)?|SCAPE)|FLATNESS|"\
   "G(M|RAVITY)|INCLINATION(_DT)?|LONGITUDE(_DT)?|MASS|O(BLATEN"\
   "ESS|RBIT(_DT)?)|PERIAPSIS(_DT)?|RADIUS|VOLUME|YEAR) JUPITER"\
   "(_[ABC]|ASCENDING(_DT)?|D(AY|ENSITY)|E(CCENTRICITY(_DT)?|SC"\
   "APE)|FLATNESS|G(M|RAVITY)|INCLINATION(_DT)?|LONGITUDE(_DT)?"\
   "|MASS|O(BLATENESS|RBIT(_DT)?)|PERIAPSIS(_DT)?|RADIUS|VOLUME"\
   "|YEAR) MAKEMAKE(_[ABC]|ASCENDING(_DT)?|D(AY|ENSITY)|E(CCENT"\
   "RICITY(_DT)?|SCAPE)|FLATNESS|G(M|RAVITY)|INCLINATION(_DT)?|"\
   "LONGITUDE(_DT)?|MASS|O(BLATENESS|RBIT(_DT)?)|PERIAPSIS(_DT)"\
   "?|RADIUS|VOLUME|YEAR) MARS(_[ABC]|ASCENDING(_DT)?|D(AY|ENSI"\
   "TY)|E(CCENTRICITY(_DT)?|SCAPE)|FLATNESS|G(M|RAVITY)|INCLINA"\
   "TION(_DT)?|LONGITUDE(_DT)?|MASS|O(BLATENESS|RBIT(_DT)?)|PER"\
   "IAPSIS(_DT)?|RADIUS|VOLUME|YEAR) MERCURY(_[ABC]|ASCENDING(_"\
   "DT)?|D(AY|ENSITY)|E(CCENTRICITY(_DT)?|SCAPE)|FLATNESS|G(M|R"\
   "AVITY)|INCLINATION(_DT)?|LONGITUDE(_DT)?|MASS|O(BLATENESS|R"\
   "BIT(_DT)?)|PERIAPSIS(_DT)?|RADIUS|VOLUME|YEAR) MOON(_[ABC]|"\
   "D(AY|ENSITY)|E(CCENTRICITY|SCAPE)|FLATNESS|G(M|RAVITY)|INCL"\
   "INATION|MASS|O(BLATENESS|RBIT)|RADIUS|VOLUME|YEAR) NEPTUNE("\
   "_[ABC]|ASCENDING(_DT)?|D(AY|ENSITY)|E(CCENTRICITY(_DT)?|SCA"\
   "PE)|FLATNESS|G(M|RAVITY)|INCLINATION(_DT)?|LONGITUDE(_DT)?|"\
   "MASS|O(BLATENESS|RBIT(_DT)?)|PERIAPSIS(_DT)?|RADIUS|VOLUME|"\
   "YEAR) PLUTO(_[ABC]|ASCENDING(_DT)?|D(AY|ENSITY)|E(CCENTRICI"\
   "TY(_DT)?|SCAPE)|FLATNESS|G(M|RAVITY)|INCLINATION(_DT)?|LONG"\
   "ITUDE(_DT)?|MASS|O(BLATENESS|RBIT(_DT)?)|PERIAPSIS(_DT)?|RA"\
   "DIUS|VOLUME|YEAR) SATURN(_[ABC]|ASCENDING(_DT)?|D(AY|ENSITY"\
   ")|E(CCENTRICITY(_DT)?|SCAPE)|FLATNESS|G(M|RAVITY)|INCLINATI"\
   "ON(_DT)?|LONGITUDE(_DT)?|MASS|O(BLATENESS|RBIT(_DT)?)|PERIA"\
   "PSIS(_DT)?|RADIUS|VOLUME|YEAR) SIDEREAL(DAY|YEAR) STELLARDA"\
   "Y SUN(_[ABC]|ASCENDING(_DT)?|D(AY|ENSITY)|E(CCENTRICITY(_DT"\
   ")?|SCAPE)|FLATNESS|G(M(IERS|NASA)?|RAVITY)|INCLINATION(_DT)"\
   "?|LONGITUDE(_DT)?|MASS|O(BLATENESS|RBIT(_DT)?)|PERIAPSIS(_D"\
   "T)?|RADIUS|VOLUME|YEAR) TROPICALYEAR URANUS(_[ABC]|ASCENDIN"\
   "G(_DT)?|D(AY|ENSITY)|E(CCENTRICITY(_DT)?|SCAPE)|FLATNESS|G("\
   "M|RAVITY)|INCLINATION(_DT)?|LONGITUDE(_DT)?|MASS|O(BLATENES"\
   "S|RBIT(_DT)?)|PERIAPSIS(_DT)?|RADIUS|VOLUME|YEAR) VENUS(_[A"\
   "BC]|ASCENDING(_DT)?|D(AY|ENSITY)|E(CCENTRICITY(_DT)?|SCAPE)"\
   "|FLATNESS|G(M|RAVITY)|INCLINATION(_DT)?|LONGITUDE(_DT)?|MAS"\
   "S|O(BLATENESS|RBIT(_DT)?)|PERIAPSIS(_DT)?|RADIUS|VOLUME|YEA"\
   "R)"\
   "\n"\
   "   Kwplanets 0-ary Functions: pla(phelion|rgument|scending)"\
   "? plb plc pld(ay|ensity) ple(ccentric(anomaly|ity)|scape) p"\
   "lflatness plg(m|ravity) plinclination pllongitude plm(a(rgo"\
   "t|ss)|eananomaly) plname plorbit plperi(apsis|helion) plrad"\
   "ius pls(ternlevison|ynodic) plvolume plyear"\
   "\n"\
   "   Kwplanets 1-ary Functions: earth_(gravity|obliquity|radi"\
   "us|tropicalyear) isa_(dens|pres|temp) pl pl_(a(phelion|rgum"\
   "ent|scending)?|b|c|d(ay|ensity)|e(ccentric(anomaly|ity)|sca"\
   "pe)|flatness|g(m|ravity)|inclination|longitude|m(a(rgot|ss)"\
   "|eananomaly)|name|orbit|peri(apsis|helion)|radius|s(ternlev"\
   "ison|ynodic)|volume|year) plaradius plgeo plhelio plsettime"\
   "\n"\
   "   Kwplanets 2-ary Functions: earth_gravity_height eccentri"\
   "c_anomaly margot pl_(aradius|heliocentric) sternlevison"\
   "\n"\
   "   Kwplanets 4-ary Functions: earth_distance"\
   "\n"\
   "   Kwplanets 5-ary Functions: vin_d(estination|istance)"\
   "\n"
#endif // #ifndef INCLUDED_Kwplanets_h
